(do
  (clojure.core/in-ns 'datomic.garbage.pod)
  (clojure.core/with-loading-context
    (do
      (clojure.core/refer 'clojure.core)
      (clojure.core/require
        ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
        ['datomic.cluster :as 'cluster]
        ['datomic.config :as 'config]
        ['datomic.future :as 'future]
        ['datomic.monitor :as 'monitor]
        ['datomic.process :as 'process]
        ['datomic.slf4j :as 'logger])))
  (when-not (.equals 'datomic.garbage.pod 'clojure.core)
    (dosync (commute (deref #'clojure.core/*loaded-libs*) conj 'datomic.garbage.pod))
    (clojure.core/with-loading-context
      (do
        (clojure.core/refer 'clojure.core)
        (clojure.core/require
          ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
          ['datomic.cluster :as 'cluster]
          ['datomic.config :as 'config]
          ['datomic.future :as 'future]
          ['datomic.monitor :as 'monitor]
          ['datomic.process :as 'process]
          ['datomic.slf4j :as 'logger]))))
  (set! *warn-on-reflection* true)
  (def pod-gc-delay-msec (delay (config/property "datomic.podGcDelayMsec")))
  (reset-meta!
    #'pod-gc-delay-msec
    (assoc {:private true, :column 1} :name 'pod-gc-delay-msec :ns *ns*))
  (defn warn
    ([msg ex]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod") ex ex]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg) ex)
          (logger/caused-by logger ex))
        nil))
    ([msg]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod")]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg)))
        nil)))
  (reset-meta!
    #'warn
    (assoc
      {:private true, :arglists (clojure.core/list ['msg] ['msg 'ex]), :column 1}
      :name
      'warn
      :ns
      *ns*))
  (defn schedule-gc
    ([cluster garbage_ids_ref]
      (let [c__6079__auto__ (a/chan 1)
            captured_bindings__6080__auto__ (clojure.lang.Var/getThreadBindingFrame)]
        (clojure.core.async.impl.dispatch/run
          (fn fn__26925
            ([]
              (let [G__26832 (fn G__26832 ([] cluster))
                    G__26833 (fn G__26833 ([] garbage_ids_ref))
                    f__6081__auto__ (fn state_machine__5842__auto__
                                      ([]
                                        (let [statearr_26931 (java.util.concurrent.atomic.AtomicReferenceArray.
                                                               (int 30))]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_26931
                                            0
                                            state_machine__5842__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_26931
                                            1
                                            1)
                                          statearr_26931))
                                      ([state_26924]
                                        (let [old_frame__5843__auto__ (clojure.lang.Var/getThreadBindingFrame)
                                              ret_value__5844__auto__ (try
                                                                        (try
                                                                          (do
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              (clojure.core.async.impl.ioc-macros/aget-object
                                                                                state_26924
                                                                                3))
                                                                            (loop 
                                                                              []
                                                                              (let 
                                                                                [result__5845__auto__
                                                                                 (let 
                                                                                   [G__26933
                                                                                    (int
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_26924
                                                                                        1))]
                                                                                   (case
                                                                                     G__26933
                                                                                     4
                                                                                     (let 
                                                                                       [inst_26922
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)]
                                                                                       (clojure.core.async.impl.ioc-macros/return-chan
                                                                                         state_26924
                                                                                         inst_26922))
                                                                                     6
                                                                                     (let 
                                                                                       [inst_26884
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          8)
                                                                                        inst_26882
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          9)
                                                                                        inst_26864
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          10)
                                                                                        inst_26852
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          6)
                                                                                        inst_26876
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          11)
                                                                                        inst_26862
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          12)
                                                                                        inst_26861
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          13)
                                                                                        inst_26887
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          14)
                                                                                        inst_26871
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          15)
                                                                                        inst_26869
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          16)
                                                                                        inst_26853
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          7)
                                                                                        inst_26886
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          17)
                                                                                        inst_26872
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          18)
                                                                                        inst_26885
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          19)
                                                                                        inst_26888
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          20)
                                                                                        first__26846
                                                                                        inst_26884
                                                                                        vec__26844
                                                                                        inst_26882
                                                                                        to_ch
                                                                                        inst_26864
                                                                                        cluster
                                                                                        inst_26852
                                                                                        G__26839
                                                                                        inst_26876
                                                                                        _
                                                                                        inst_26862
                                                                                        garbage_ids
                                                                                        inst_26861
                                                                                        result_chs
                                                                                        inst_26887
                                                                                        first__26842
                                                                                        inst_26871
                                                                                        vec__26840
                                                                                        inst_26869
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        ch
                                                                                        inst_26886
                                                                                        seq__26841
                                                                                        inst_26872
                                                                                        seq__26845
                                                                                        inst_26885
                                                                                        count
                                                                                        inst_26888
                                                                                        inst_26918
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageDeletedCount
                                                                                          count)]
                                                                                       (let 
                                                                                         [statearr_26942
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26942
                                                                                           2
                                                                                           inst_26918)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26942
                                                                                           1
                                                                                           7))
                                                                                       :recur)
                                                                                     1
                                                                                     (let 
                                                                                       [inst_26852
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          6)
                                                                                        inst_26853
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          7)
                                                                                        inst_26850
                                                                                        (^clojure.lang.IFn G__26832)
                                                                                        cluster
                                                                                        inst_26850
                                                                                        inst_26851
                                                                                        (^clojure.lang.IFn G__26833)
                                                                                        inst_26852
                                                                                        inst_26850
                                                                                        inst_26853
                                                                                        inst_26851
                                                                                        cluster
                                                                                        inst_26852
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        inst_26854
                                                                                        (a/timeout
                                                                                          (long
                                                                                            (deref
                                                                                              pod-gc-delay-msec)))
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26934
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26934
                                                                                            6
                                                                                            inst_26852)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26934
                                                                                            7
                                                                                            inst_26853)
                                                                                          statearr_26934)]
                                                                                       (clojure.core.async.impl.ioc-macros/take!
                                                                                         state_26924
                                                                                         2
                                                                                         inst_26854))
                                                                                     7
                                                                                     (let 
                                                                                       [inst_26920
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)]
                                                                                       (let 
                                                                                         [statearr_26943
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26943
                                                                                           2
                                                                                           inst_26920)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26943
                                                                                           1
                                                                                           4))
                                                                                       :recur)
                                                                                     14
                                                                                     (let 
                                                                                       [inst_26907
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)]
                                                                                       (let 
                                                                                         [statearr_26955
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26955
                                                                                           2
                                                                                           inst_26907)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26955
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     17
                                                                                     (let 
                                                                                       [inst_26888
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          20)
                                                                                        inst_26887
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          14)
                                                                                        inst_26914
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)
                                                                                        inst_26915
                                                                                        (+
                                                                                          inst_26888
                                                                                          inst_26914)
                                                                                        inst_26876
                                                                                        inst_26887
                                                                                        inst_26877
                                                                                        inst_26915
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26958
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26958
                                                                                            11
                                                                                            inst_26876)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26958
                                                                                            21
                                                                                            inst_26877)
                                                                                          statearr_26958)]
                                                                                       (let 
                                                                                         [statearr_26959
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26959
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26959
                                                                                           1
                                                                                           3))
                                                                                       :recur)
                                                                                     12
                                                                                     (let 
                                                                                       [inst_26896
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          23)
                                                                                        inst_26904
                                                                                        (process/fail
                                                                                          process/instance
                                                                                          "Cluster pod gc failed"
                                                                                          inst_26896)]
                                                                                       (let 
                                                                                         [statearr_26953
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26953
                                                                                           2
                                                                                           inst_26904)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26953
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     2
                                                                                     (let 
                                                                                       [inst_26852
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          6)
                                                                                        inst_26853
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          7)
                                                                                        inst_26864
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          10)
                                                                                        inst_26862
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          12)
                                                                                        inst_26861
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          13)
                                                                                        inst_26856
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)
                                                                                        cluster
                                                                                        inst_26852
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        inst_26857
                                                                                        (deref
                                                                                          garbage_ids_ref)
                                                                                        cluster
                                                                                        inst_26852
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        garbage_ids
                                                                                        inst_26857
                                                                                        inst_26858
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageItems
                                                                                          (java.lang.Integer/valueOf
                                                                                            (int
                                                                                              (count
                                                                                                garbage_ids))))
                                                                                        cluster
                                                                                        inst_26852
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        garbage_ids
                                                                                        inst_26857
                                                                                        _
                                                                                        inst_26858
                                                                                        inst_26859
                                                                                        (mapv
                                                                                          (comp
                                                                                            future/get-channel
                                                                                            (fn 
                                                                                              fn__26935
                                                                                              ([p1__26831#]
                                                                                                (cluster/delete
                                                                                                  cluster
                                                                                                  p1__26831#))))
                                                                                          garbage_ids)
                                                                                        cluster
                                                                                        inst_26852
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        garbage_ids
                                                                                        inst_26857
                                                                                        _
                                                                                        inst_26858
                                                                                        result_chs
                                                                                        inst_26859
                                                                                        inst_26860
                                                                                        (a/timeout
                                                                                          (long
                                                                                            cluster/BOUNDING_TIMEOUT_MSEC))
                                                                                        inst_26861
                                                                                        inst_26857
                                                                                        inst_26862
                                                                                        inst_26858
                                                                                        inst_26863
                                                                                        inst_26859
                                                                                        inst_26864
                                                                                        inst_26860
                                                                                        to_ch
                                                                                        inst_26864
                                                                                        cluster
                                                                                        inst_26852
                                                                                        G__26839
                                                                                        inst_26863
                                                                                        _
                                                                                        inst_26862
                                                                                        garbage_ids
                                                                                        inst_26861
                                                                                        result_chs
                                                                                        inst_26863
                                                                                        vec__26840
                                                                                        inst_26863
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        inst_26865
                                                                                        (seq
                                                                                          vec__26840)
                                                                                        to_ch
                                                                                        inst_26864
                                                                                        cluster
                                                                                        inst_26852
                                                                                        G__26839
                                                                                        inst_26863
                                                                                        _
                                                                                        inst_26862
                                                                                        garbage_ids
                                                                                        inst_26861
                                                                                        result_chs
                                                                                        inst_26863
                                                                                        vec__26840
                                                                                        inst_26863
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        seq__26841
                                                                                        inst_26865
                                                                                        inst_26866
                                                                                        (first
                                                                                          seq__26841)
                                                                                        to_ch
                                                                                        inst_26864
                                                                                        cluster
                                                                                        inst_26852
                                                                                        G__26839
                                                                                        inst_26863
                                                                                        _
                                                                                        inst_26862
                                                                                        garbage_ids
                                                                                        inst_26861
                                                                                        result_chs
                                                                                        inst_26863
                                                                                        first__26842
                                                                                        inst_26866
                                                                                        vec__26840
                                                                                        inst_26863
                                                                                        garbage_ids_ref
                                                                                        inst_26853
                                                                                        seq__26841
                                                                                        inst_26865
                                                                                        inst_26867
                                                                                        (next
                                                                                          seq__26841)
                                                                                        inst_26868
                                                                                        inst_26863
                                                                                        inst_26869
                                                                                        inst_26863
                                                                                        inst_26870
                                                                                        inst_26865
                                                                                        inst_26871
                                                                                        inst_26866
                                                                                        inst_26872
                                                                                        inst_26867
                                                                                        inst_26873
                                                                                        inst_26866
                                                                                        inst_26874
                                                                                        inst_26867
                                                                                        inst_26875
                                                                                        0
                                                                                        inst_26876
                                                                                        inst_26868
                                                                                        inst_26877
                                                                                        inst_26875
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26937
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            24
                                                                                            inst_26856)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            13
                                                                                            inst_26861)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            12
                                                                                            inst_26862)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            10
                                                                                            inst_26864)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            16
                                                                                            inst_26869)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            25
                                                                                            inst_26870)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            15
                                                                                            inst_26871)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            18
                                                                                            inst_26872)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            26
                                                                                            inst_26873)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            27
                                                                                            inst_26874)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            11
                                                                                            inst_26876)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26937
                                                                                            21
                                                                                            (long
                                                                                              inst_26877))
                                                                                          statearr_26937)]
                                                                                       (let 
                                                                                         [statearr_26938
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26938
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26938
                                                                                           1
                                                                                           3))
                                                                                       :recur)
                                                                                     16
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_26957
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26957
                                                                                           2
                                                                                           0)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26957
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     15
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_26956
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26956
                                                                                           2
                                                                                           1)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26956
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     9
                                                                                     (let 
                                                                                       [inst_26900
                                                                                        (warn
                                                                                          "Cluster pod gc timed out")]
                                                                                       (let 
                                                                                         [statearr_26947
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26947
                                                                                           2
                                                                                           inst_26900)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26947
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     10
                                                                                     (let 
                                                                                       [inst_26896
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          23)
                                                                                        inst_26902
                                                                                        (instance?
                                                                                          java.lang.Throwable
                                                                                          inst_26896)]
                                                                                       (if
                                                                                         inst_26902
                                                                                         (let 
                                                                                           [statearr_26948
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26948
                                                                                             1
                                                                                             12))
                                                                                         (let 
                                                                                           [statearr_26949
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26949
                                                                                             1
                                                                                             13)))
                                                                                       :recur)
                                                                                     5
                                                                                     (let 
                                                                                       [inst_26886
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          17)
                                                                                        inst_26864
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          10)
                                                                                        inst_26890
                                                                                        (vector
                                                                                          inst_26886
                                                                                          inst_26864)]
                                                                                       (a/ioc-alts!
                                                                                         state_26924
                                                                                         8
                                                                                         inst_26890))
                                                                                     13
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_26954
                                                                                          state_26924]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26954
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_26954
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     8
                                                                                     (let 
                                                                                       [inst_26864
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          10)
                                                                                        inst_26892
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)
                                                                                        inst_26893
                                                                                        (nth
                                                                                          inst_26892
                                                                                          (int 0)
                                                                                          nil)
                                                                                        inst_26894
                                                                                        (nth
                                                                                          inst_26892
                                                                                          (int 1)
                                                                                          nil)
                                                                                        inst_26895
                                                                                        inst_26892
                                                                                        inst_26896
                                                                                        inst_26893
                                                                                        inst_26897
                                                                                        inst_26894
                                                                                        inst_26898
                                                                                        (=
                                                                                          inst_26897
                                                                                          inst_26864)
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26944
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26944
                                                                                            29
                                                                                            inst_26895)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26944
                                                                                            23
                                                                                            inst_26896)
                                                                                          statearr_26944)]
                                                                                       (if
                                                                                         inst_26898
                                                                                         (let 
                                                                                           [statearr_26945
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26945
                                                                                             1
                                                                                             9))
                                                                                         (let 
                                                                                           [statearr_26946
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26946
                                                                                             1
                                                                                             10)))
                                                                                       :recur)
                                                                                     11
                                                                                     (let 
                                                                                       [inst_26896
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          23)
                                                                                        inst_26909
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          2)
                                                                                        inst_26910
                                                                                        (=
                                                                                          :ok
                                                                                          inst_26896)
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26950
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26950
                                                                                            28
                                                                                            inst_26909)
                                                                                          statearr_26950)]
                                                                                       (if
                                                                                         inst_26910
                                                                                         (let 
                                                                                           [statearr_26951
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26951
                                                                                             1
                                                                                             15))
                                                                                         (let 
                                                                                           [statearr_26952
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26952
                                                                                             1
                                                                                             16)))
                                                                                       :recur)
                                                                                     3
                                                                                     (let 
                                                                                       [inst_26876
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          11)
                                                                                        inst_26877
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          21)
                                                                                        inst_26886
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_26924
                                                                                          17)
                                                                                        inst_26879
                                                                                        (seq
                                                                                          inst_26876)
                                                                                        inst_26880
                                                                                        (first
                                                                                          inst_26879)
                                                                                        inst_26881
                                                                                        (next
                                                                                          inst_26879)
                                                                                        inst_26882
                                                                                        inst_26876
                                                                                        inst_26883
                                                                                        inst_26879
                                                                                        inst_26884
                                                                                        inst_26880
                                                                                        inst_26885
                                                                                        inst_26881
                                                                                        inst_26886
                                                                                        inst_26880
                                                                                        inst_26887
                                                                                        inst_26881
                                                                                        inst_26888
                                                                                        inst_26877
                                                                                        state_26924
                                                                                        (let 
                                                                                          [statearr_26939
                                                                                           state_26924]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            9
                                                                                            inst_26882)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            22
                                                                                            inst_26883)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            8
                                                                                            inst_26884)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            19
                                                                                            inst_26885)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            17
                                                                                            inst_26886)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            14
                                                                                            inst_26887)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_26939
                                                                                            20
                                                                                            inst_26888)
                                                                                          statearr_26939)]
                                                                                       (if
                                                                                         inst_26886
                                                                                         (let 
                                                                                           [statearr_26940
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26940
                                                                                             1
                                                                                             5))
                                                                                         (let 
                                                                                           [statearr_26941
                                                                                            state_26924]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_26941
                                                                                             1
                                                                                             6)))
                                                                                       :recur)))]
                                                                                (if
                                                                                  (identical?
                                                                                    result__5845__auto__
                                                                                    :recur)
                                                                                  (recur)
                                                                                  result__5845__auto__))))
                                                                          (catch
                                                                            java.lang.Throwable
                                                                            ex__5846__auto__
                                                                            (do
                                                                              (let 
                                                                                [statearr_26960
                                                                                 state_26924]
                                                                                (clojure.core.async.impl.ioc-macros/aset-object
                                                                                  statearr_26960
                                                                                  2
                                                                                  ex__5846__auto__))
                                                                              (if
                                                                                (seq
                                                                                  (clojure.core.async.impl.ioc-macros/aget-object
                                                                                    state_26924
                                                                                    4))
                                                                                (let 
                                                                                  [statearr_26961
                                                                                   state_26924]
                                                                                  (clojure.core.async.impl.ioc-macros/aset-object
                                                                                    statearr_26961
                                                                                    1
                                                                                    (first
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_26924
                                                                                        4))))
                                                                                (throw
                                                                                  ^java.lang.Throwable ex__5846__auto__))
                                                                              :recur)))
                                                                        (finally
                                                                          (do
                                                                            (clojure.core.async.impl.ioc-macros/aset-object
                                                                              state_26924
                                                                              3
                                                                              (clojure.lang.Var/getThreadBindingFrame))
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              old_frame__5843__auto__))))]
                                          (if (identical? ret_value__5844__auto__ :recur)
                                            (recur state_26924)
                                            ret_value__5844__auto__))))
                    state__6082__auto__ (let [statearr_26967 (^clojure.lang.IFn f__6081__auto__)]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_26967
                                            5
                                            c__6079__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_26967
                                            3
                                            captured_bindings__6080__auto__)
                                          statearr_26967)]
                (clojure.core.async.impl.ioc-macros/run-state-machine-wrapped
                  state__6082__auto__)))))
        c__6079__auto__))))