[package]
name = "edb-transactor"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.30", features = ["bundled", "hooks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
edb-encoding = { path = "../edb-encoding" }
edb-schema = { path = "../edb-schema" }
edb-tx = { path = "../edb-tx" }
edb-store-sqlite = { path = "../edb-store-sqlite" }
edb-index = { path = "../edb-index" }
edb-envelope = { path = "../edb-envelope" }
serde_cbor = "0.11"

[dev-dependencies]
ed25519-dalek = { version = "2", features = ["rand_core"] }
