(do
  (clojure.core/in-ns 'datomic.garbage.pod)
  (clojure.core/with-loading-context
    (do
      (clojure.core/refer 'clojure.core)
      (clojure.core/require
        ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
        ['datomic.cluster :as 'cluster]
        ['datomic.config :as 'config]
        ['datomic.future :as 'future]
        ['datomic.monitor :as 'monitor]
        ['datomic.process :as 'process]
        ['datomic.slf4j :as 'logger])))
  (when-not (.equals 'datomic.garbage.pod 'clojure.core)
    (dosync (commute (deref #'clojure.core/*loaded-libs*) conj 'datomic.garbage.pod))
    (clojure.core/with-loading-context
      (do
        (clojure.core/refer 'clojure.core)
        (clojure.core/require
          ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
          ['datomic.cluster :as 'cluster]
          ['datomic.config :as 'config]
          ['datomic.future :as 'future]
          ['datomic.monitor :as 'monitor]
          ['datomic.process :as 'process]
          ['datomic.slf4j :as 'logger]))))
  (set! *warn-on-reflection* true)
  (def pod-gc-delay-msec (delay (config/property "datomic.podGcDelayMsec")))
  (reset-meta!
    #'pod-gc-delay-msec
    (assoc {:private true, :column 1} :name 'pod-gc-delay-msec :ns *ns*))
  (defn warn
    ([msg ex]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod") ex ex]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg) ex)
          (logger/caused-by logger ex))
        nil))
    ([msg]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod")]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg))
          nil)
        nil)))
  (reset-meta!
    #'warn
    (assoc
      {:private true, :arglists (clojure.core/list ['msg] ['msg 'ex]), :column 1}
      :name
      'warn
      :ns
      *ns*))
  (defn schedule-gc
    ([cluster garbage_ids_ref]
      (let [c__6597__auto__ (a/chan 1)
            captured_bindings__6598__auto__ (clojure.lang.Var/getThreadBindingFrame)]
        (clojure.core.async.impl.dispatch/run
          (fn fn__22693
            ([]
              (let [G__22600 (fn G__22600 ([] cluster))
                    G__22601 (fn G__22601 ([] garbage_ids_ref))
                    f__6599__auto__ (fn state_machine__6360__auto__
                                      ([]
                                        (let [statearr_22699 (java.util.concurrent.atomic.AtomicReferenceArray.
                                                               (int 30))]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22699
                                            0
                                            state_machine__6360__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22699
                                            1
                                            1)
                                          statearr_22699))
                                      ([state_22692]
                                        (let [old_frame__6361__auto__ (clojure.lang.Var/getThreadBindingFrame)
                                              ret_value__6362__auto__ (try
                                                                        (do
                                                                          (clojure.lang.Var/resetThreadBindingFrame
                                                                            (clojure.core.async.impl.ioc-macros/aget-object
                                                                              state_22692
                                                                              3))
                                                                          (loop 
                                                                            []
                                                                            (let 
                                                                              [result__6363__auto__
                                                                               (let 
                                                                                 [G__22701
                                                                                  (int
                                                                                    (clojure.core.async.impl.ioc-macros/aget-object
                                                                                      state_22692
                                                                                      1))]
                                                                                 (case
                                                                                   G__22701
                                                                                   6
                                                                                   (let 
                                                                                     [inst_22637
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        8)
                                                                                      inst_22652
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        9)
                                                                                      inst_22632
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        10)
                                                                                      inst_22640
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        11)
                                                                                      inst_22650
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        12)
                                                                                      inst_22653
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        13)
                                                                                      inst_22620
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        6)
                                                                                      inst_22630
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        14)
                                                                                      inst_22629
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        15)
                                                                                      inst_22655
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        16)
                                                                                      inst_22621
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        7)
                                                                                      inst_22654
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        17)
                                                                                      inst_22639
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        18)
                                                                                      inst_22644
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        19)
                                                                                      inst_22656
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        20)
                                                                                      vec__22608
                                                                                      inst_22637
                                                                                      first__22614
                                                                                      inst_22652
                                                                                      to_ch
                                                                                      inst_22632
                                                                                      seq__22609
                                                                                      inst_22640
                                                                                      vec__22612
                                                                                      inst_22650
                                                                                      seq__22613
                                                                                      inst_22653
                                                                                      cluster
                                                                                      inst_22620
                                                                                      _ inst_22630
                                                                                      garbage_ids
                                                                                      inst_22629
                                                                                      result_chs
                                                                                      inst_22655
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      ch inst_22654
                                                                                      first__22610
                                                                                      inst_22639
                                                                                      G__22607
                                                                                      inst_22644
                                                                                      count
                                                                                      inst_22656
                                                                                      inst_22686
                                                                                      (monitor/add-stat
                                                                                        :PodGarbageDeletedCount
                                                                                        count)]
                                                                                     (let 
                                                                                       [statearr_22710
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22710
                                                                                         2
                                                                                         inst_22686)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22710
                                                                                         1
                                                                                         7))
                                                                                     :recur)
                                                                                   8
                                                                                   (let 
                                                                                     [inst_22632
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        10)
                                                                                      inst_22660
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)
                                                                                      inst_22661
                                                                                      (nth
                                                                                        inst_22660
                                                                                        (int 0)
                                                                                        nil)
                                                                                      inst_22662
                                                                                      (nth
                                                                                        inst_22660
                                                                                        (int 1)
                                                                                        nil)
                                                                                      inst_22663
                                                                                      inst_22660
                                                                                      inst_22664
                                                                                      inst_22661
                                                                                      inst_22665
                                                                                      inst_22662
                                                                                      inst_22666
                                                                                      (=
                                                                                        inst_22665
                                                                                        inst_22632)
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22712
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22712
                                                                                          29
                                                                                          inst_22663)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22712
                                                                                          23
                                                                                          inst_22664)
                                                                                        statearr_22712)]
                                                                                     (if
                                                                                       inst_22666
                                                                                       (let 
                                                                                         [statearr_22713
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22713
                                                                                           1
                                                                                           9))
                                                                                       (let 
                                                                                         [statearr_22714
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22714
                                                                                           1
                                                                                           10)))
                                                                                     :recur)
                                                                                   5
                                                                                   (let 
                                                                                     [inst_22654
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        17)
                                                                                      inst_22632
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        10)
                                                                                      inst_22658
                                                                                      (vector
                                                                                        inst_22654
                                                                                        inst_22632)]
                                                                                     (a/ioc-alts!
                                                                                       state_22692
                                                                                       8
                                                                                       inst_22658))
                                                                                   15
                                                                                   (do
                                                                                     (let 
                                                                                       [statearr_22724
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22724
                                                                                         2
                                                                                         1)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22724
                                                                                         1
                                                                                         17))
                                                                                     :recur)
                                                                                   12
                                                                                   (let 
                                                                                     [inst_22664
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        23)
                                                                                      inst_22672
                                                                                      (process/fail
                                                                                        process/instance
                                                                                        "Cluster pod gc failed"
                                                                                        inst_22664)]
                                                                                     (let 
                                                                                       [statearr_22721
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22721
                                                                                         2
                                                                                         inst_22672)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22721
                                                                                         1
                                                                                         14))
                                                                                     :recur)
                                                                                   9
                                                                                   (let 
                                                                                     [inst_22668
                                                                                      (warn
                                                                                        "Cluster pod gc timed out")]
                                                                                     (let 
                                                                                       [statearr_22715
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22715
                                                                                         2
                                                                                         inst_22668)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22715
                                                                                         1
                                                                                         11))
                                                                                     :recur)
                                                                                   2
                                                                                   (let 
                                                                                     [inst_22620
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        6)
                                                                                      inst_22621
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        7)
                                                                                      inst_22632
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        10)
                                                                                      inst_22630
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        14)
                                                                                      inst_22629
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        15)
                                                                                      inst_22624
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)
                                                                                      cluster
                                                                                      inst_22620
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      inst_22625
                                                                                      (deref
                                                                                        garbage_ids_ref)
                                                                                      cluster
                                                                                      inst_22620
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      garbage_ids
                                                                                      inst_22625
                                                                                      inst_22626
                                                                                      (monitor/add-stat
                                                                                        :PodGarbageItems
                                                                                        (java.lang.Integer/valueOf
                                                                                          (int
                                                                                            (count
                                                                                              garbage_ids))))
                                                                                      cluster
                                                                                      inst_22620
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      garbage_ids
                                                                                      inst_22625
                                                                                      _ inst_22626
                                                                                      inst_22627
                                                                                      (mapv
                                                                                        (comp
                                                                                          future/get-channel
                                                                                          (fn 
                                                                                            fn__22703
                                                                                            ([p1__22599#]
                                                                                              (cluster/delete
                                                                                                cluster
                                                                                                p1__22599#))))
                                                                                        garbage_ids)
                                                                                      cluster
                                                                                      inst_22620
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      garbage_ids
                                                                                      inst_22625
                                                                                      _ inst_22626
                                                                                      result_chs
                                                                                      inst_22627
                                                                                      inst_22628
                                                                                      (a/timeout
                                                                                        (long
                                                                                          cluster/BOUNDING_TIMEOUT_MSEC))
                                                                                      inst_22629
                                                                                      inst_22625
                                                                                      inst_22630
                                                                                      inst_22626
                                                                                      inst_22631
                                                                                      inst_22627
                                                                                      inst_22632
                                                                                      inst_22628
                                                                                      vec__22608
                                                                                      inst_22631
                                                                                      to_ch
                                                                                      inst_22632
                                                                                      cluster
                                                                                      inst_22620
                                                                                      _ inst_22630
                                                                                      garbage_ids
                                                                                      inst_22629
                                                                                      result_chs
                                                                                      inst_22631
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      G__22607
                                                                                      inst_22631
                                                                                      inst_22633
                                                                                      (seq
                                                                                        vec__22608)
                                                                                      vec__22608
                                                                                      inst_22631
                                                                                      to_ch
                                                                                      inst_22632
                                                                                      seq__22609
                                                                                      inst_22633
                                                                                      cluster
                                                                                      inst_22620
                                                                                      _ inst_22630
                                                                                      garbage_ids
                                                                                      inst_22629
                                                                                      result_chs
                                                                                      inst_22631
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      G__22607
                                                                                      inst_22631
                                                                                      inst_22634
                                                                                      (first
                                                                                        seq__22609)
                                                                                      vec__22608
                                                                                      inst_22631
                                                                                      to_ch
                                                                                      inst_22632
                                                                                      seq__22609
                                                                                      inst_22633
                                                                                      cluster
                                                                                      inst_22620
                                                                                      _ inst_22630
                                                                                      garbage_ids
                                                                                      inst_22629
                                                                                      result_chs
                                                                                      inst_22631
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      first__22610
                                                                                      inst_22634
                                                                                      G__22607
                                                                                      inst_22631
                                                                                      inst_22635
                                                                                      (next
                                                                                        seq__22609)
                                                                                      inst_22636
                                                                                      inst_22631
                                                                                      inst_22637
                                                                                      inst_22631
                                                                                      inst_22638
                                                                                      inst_22633
                                                                                      inst_22639
                                                                                      inst_22634
                                                                                      inst_22640
                                                                                      inst_22635
                                                                                      inst_22641
                                                                                      inst_22634
                                                                                      inst_22642
                                                                                      inst_22635
                                                                                      inst_22643 0
                                                                                      inst_22644
                                                                                      inst_22636
                                                                                      inst_22645
                                                                                      inst_22643
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22705
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          24
                                                                                          inst_22624)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          15
                                                                                          inst_22629)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          14
                                                                                          inst_22630)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          10
                                                                                          inst_22632)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          8
                                                                                          inst_22637)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          25
                                                                                          inst_22638)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          18
                                                                                          inst_22639)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          11
                                                                                          inst_22640)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          26
                                                                                          inst_22641)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          27
                                                                                          inst_22642)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          19
                                                                                          inst_22644)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22705
                                                                                          21
                                                                                          (long
                                                                                            inst_22645))
                                                                                        statearr_22705)]
                                                                                     (let 
                                                                                       [statearr_22706
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22706
                                                                                         2
                                                                                         nil)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22706
                                                                                         1
                                                                                         3))
                                                                                     :recur)
                                                                                   14
                                                                                   (let 
                                                                                     [inst_22675
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)]
                                                                                     (let 
                                                                                       [statearr_22723
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22723
                                                                                         2
                                                                                         inst_22675)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22723
                                                                                         1
                                                                                         11))
                                                                                     :recur)
                                                                                   3
                                                                                   (let 
                                                                                     [inst_22644
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        19)
                                                                                      inst_22645
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        21)
                                                                                      inst_22654
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        17)
                                                                                      inst_22647
                                                                                      (seq
                                                                                        inst_22644)
                                                                                      inst_22648
                                                                                      (first
                                                                                        inst_22647)
                                                                                      inst_22649
                                                                                      (next
                                                                                        inst_22647)
                                                                                      inst_22650
                                                                                      inst_22644
                                                                                      inst_22651
                                                                                      inst_22647
                                                                                      inst_22652
                                                                                      inst_22648
                                                                                      inst_22653
                                                                                      inst_22649
                                                                                      inst_22654
                                                                                      inst_22648
                                                                                      inst_22655
                                                                                      inst_22649
                                                                                      inst_22656
                                                                                      inst_22645
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22707
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          12
                                                                                          inst_22650)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          22
                                                                                          inst_22651)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          9
                                                                                          inst_22652)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          13
                                                                                          inst_22653)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          17
                                                                                          inst_22654)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          16
                                                                                          inst_22655)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22707
                                                                                          20
                                                                                          inst_22656)
                                                                                        statearr_22707)]
                                                                                     (if
                                                                                       inst_22654
                                                                                       (let 
                                                                                         [statearr_22708
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22708
                                                                                           1
                                                                                           5))
                                                                                       (let 
                                                                                         [statearr_22709
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22709
                                                                                           1
                                                                                           6)))
                                                                                     :recur)
                                                                                   7
                                                                                   (let 
                                                                                     [inst_22688
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)]
                                                                                     (let 
                                                                                       [statearr_22711
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22711
                                                                                         2
                                                                                         inst_22688)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22711
                                                                                         1
                                                                                         4))
                                                                                     :recur)
                                                                                   17
                                                                                   (let 
                                                                                     [inst_22656
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        20)
                                                                                      inst_22655
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        16)
                                                                                      inst_22682
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)
                                                                                      inst_22683
                                                                                      (+
                                                                                        inst_22656
                                                                                        inst_22682)
                                                                                      inst_22644
                                                                                      inst_22655
                                                                                      inst_22645
                                                                                      inst_22683
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22726
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22726
                                                                                          19
                                                                                          inst_22644)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22726
                                                                                          21
                                                                                          inst_22645)
                                                                                        statearr_22726)]
                                                                                     (let 
                                                                                       [statearr_22727
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22727
                                                                                         2
                                                                                         nil)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22727
                                                                                         1
                                                                                         3))
                                                                                     :recur)
                                                                                   10
                                                                                   (let 
                                                                                     [inst_22664
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        23)
                                                                                      inst_22670
                                                                                      (instance?
                                                                                        java.lang.Throwable
                                                                                        inst_22664)]
                                                                                     (if
                                                                                       inst_22670
                                                                                       (let 
                                                                                         [statearr_22716
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22716
                                                                                           1
                                                                                           12))
                                                                                       (let 
                                                                                         [statearr_22717
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22717
                                                                                           1
                                                                                           13)))
                                                                                     :recur)
                                                                                   4
                                                                                   (let 
                                                                                     [inst_22690
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)]
                                                                                     (clojure.core.async.impl.ioc-macros/return-chan
                                                                                       state_22692
                                                                                       inst_22690))
                                                                                   11
                                                                                   (let 
                                                                                     [inst_22664
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        23)
                                                                                      inst_22677
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        2)
                                                                                      inst_22678
                                                                                      (=
                                                                                        :ok
                                                                                        inst_22664)
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22718
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22718
                                                                                          28
                                                                                          inst_22677)
                                                                                        statearr_22718)]
                                                                                     (if
                                                                                       inst_22678
                                                                                       (let 
                                                                                         [statearr_22719
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22719
                                                                                           1
                                                                                           15))
                                                                                       (let 
                                                                                         [statearr_22720
                                                                                          state_22692]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22720
                                                                                           1
                                                                                           16)))
                                                                                     :recur)
                                                                                   16
                                                                                   (do
                                                                                     (let 
                                                                                       [statearr_22725
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22725
                                                                                         2
                                                                                         0)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22725
                                                                                         1
                                                                                         17))
                                                                                     :recur)
                                                                                   1
                                                                                   (let 
                                                                                     [inst_22620
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        6)
                                                                                      inst_22621
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22692
                                                                                        7)
                                                                                      inst_22618
                                                                                      (^clojure.lang.IFn G__22600)
                                                                                      cluster
                                                                                      inst_22618
                                                                                      inst_22619
                                                                                      (^clojure.lang.IFn G__22601)
                                                                                      inst_22620
                                                                                      inst_22618
                                                                                      inst_22621
                                                                                      inst_22619
                                                                                      cluster
                                                                                      inst_22620
                                                                                      garbage_ids_ref
                                                                                      inst_22621
                                                                                      inst_22622
                                                                                      (a/timeout
                                                                                        (long
                                                                                          (deref
                                                                                            pod-gc-delay-msec)))
                                                                                      state_22692
                                                                                      (let 
                                                                                        [statearr_22702
                                                                                         state_22692]
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22702
                                                                                          6
                                                                                          inst_22620)
                                                                                        (clojure.core.async.impl.ioc-macros/aset-object
                                                                                          statearr_22702
                                                                                          7
                                                                                          inst_22621)
                                                                                        statearr_22702)]
                                                                                     (clojure.core.async.impl.ioc-macros/take!
                                                                                       state_22692
                                                                                       2
                                                                                       inst_22622))
                                                                                   13
                                                                                   (do
                                                                                     (let 
                                                                                       [statearr_22722
                                                                                        state_22692]
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22722
                                                                                         2
                                                                                         nil)
                                                                                       (clojure.core.async.impl.ioc-macros/aset-object
                                                                                         statearr_22722
                                                                                         1
                                                                                         14))
                                                                                     :recur)))]
                                                                              (if
                                                                                (identical?
                                                                                  result__6363__auto__
                                                                                  :recur)
                                                                                (recur)
                                                                                result__6363__auto__))))
                                                                        (catch
                                                                          java.lang.Throwable
                                                                          ex__6364__auto__
                                                                          (do
                                                                            (let 
                                                                              [statearr_22728
                                                                               state_22692]
                                                                              (clojure.core.async.impl.ioc-macros/aset-object
                                                                                statearr_22728
                                                                                2
                                                                                ex__6364__auto__))
                                                                            (if
                                                                              (seq
                                                                                (clojure.core.async.impl.ioc-macros/aget-object
                                                                                  state_22692
                                                                                  4))
                                                                              (let 
                                                                                [statearr_22729
                                                                                 state_22692]
                                                                                (clojure.core.async.impl.ioc-macros/aset-object
                                                                                  statearr_22729
                                                                                  1
                                                                                  (first
                                                                                    (clojure.core.async.impl.ioc-macros/aget-object
                                                                                      state_22692
                                                                                      4))))
                                                                              (throw
                                                                                ^java.lang.Throwable ex__6364__auto__))
                                                                            :recur))
                                                                        (finally
                                                                          (do
                                                                            (clojure.core.async.impl.ioc-macros/aset-object
                                                                              state_22692
                                                                              3
                                                                              (clojure.lang.Var/getThreadBindingFrame))
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              old_frame__6361__auto__))))]
                                          (if (identical? ret_value__6362__auto__ :recur)
                                            (recur state_22692)
                                            ret_value__6362__auto__))))
                    state__6600__auto__ (let [statearr_22735 (^clojure.lang.IFn f__6599__auto__)]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22735
                                            5
                                            c__6597__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22735
                                            3
                                            captured_bindings__6598__auto__)
                                          statearr_22735)]
                (clojure.core.async.impl.ioc-macros/run-state-machine-wrapped
                  state__6600__auto__)))))
        c__6597__auto__))))