(do
  (clojure.core/in-ns 'datomic.garbage.pod)
  (.resetMeta
    (clojure.lang.Namespace/find 'datomic.garbage.pod)
    {:doc
     "Delays reclamation of replaced pod-tail values so concurrent readers can finish using the prior immutable chain. Scheduled deletes are cancellable during process shutdown and failures are reported as storage alarms."})
  (clojure.core/with-loading-context
    (do
      (clojure.core/refer 'clojure.core)
      (clojure.core/require
        ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
        ['datomic.cluster :as 'cluster]
        ['datomic.config :as 'config]
        ['datomic.future :as 'future]
        ['datomic.monitor :as 'monitor]
        ['datomic.process :as 'process]
        ['datomic.slf4j :as 'logger])))
  (when-not (.equals 'datomic.garbage.pod 'clojure.core)
    (dosync (commute (deref #'clojure.core/*loaded-libs*) conj 'datomic.garbage.pod))
    (clojure.core/with-loading-context
      (do
        (clojure.core/refer 'clojure.core)
        (clojure.core/require
          ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
          ['datomic.cluster :as 'cluster]
          ['datomic.config :as 'config]
          ['datomic.future :as 'future]
          ['datomic.monitor :as 'monitor]
          ['datomic.process :as 'process]
          ['datomic.slf4j :as 'logger]))))
  (set! *warn-on-reflection* true)
  (.setMeta
    (clojure.lang.RT/var "datomic.garbage.pod" "pod-gc-delay-msec")
    {:private true, :column (int 1)})
  (.bindRoot
    (clojure.lang.RT/var "datomic.garbage.pod" "pod-gc-delay-msec")
    (delay (config/property "datomic.podGcDelayMsec")))
  (defn warn
    ([msg ex]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod") ex ex]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg) ex)
          (logger/caused-by logger ex))
        nil))
    ([msg]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod")]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg)))
        nil)))
  (reset-meta!
    #'warn
    (assoc
      {:private true, :arglists (clojure.core/list ['msg] ['msg 'ex]), :column (int 1)}
      :name
      'warn
      :ns
      *ns*))
  ;; Waits the configured safety delay, then deletes the captured immutable tail identifiers.
  (defn schedule-gc
    ([cluster garbage_ids_ref]
      (let [c__5899__auto__ (a/chan 1)
            captured_bindings__5900__auto__ (clojure.lang.Var/getThreadBindingFrame)]
        (clojure.core.async.impl.dispatch/run
          (fn fn__22868
            ([]
              (let [G__22775 (fn G__22775 ([] cluster))
                    G__22776 (fn G__22776 ([] garbage_ids_ref))
                    f__5901__auto__ (fn state_machine__5804__auto__
                                      ([]
                                        (let [statearr_22874 (java.util.concurrent.atomic.AtomicReferenceArray.
                                                               (int 30))]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22874
                                            0
                                            state_machine__5804__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22874
                                            1
                                            1)
                                          statearr_22874))
                                      ([state_22867]
                                        (let [old_frame__5805__auto__ (clojure.lang.Var/getThreadBindingFrame)
                                              ret_value__5806__auto__ (try
                                                                        (try
                                                                          (do
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              (clojure.core.async.impl.ioc-macros/aget-object
                                                                                state_22867
                                                                                3))
                                                                            (loop
                                                                              []
                                                                              (let
                                                                                [result__5807__auto__
                                                                                 (let
                                                                                   [G__22876
                                                                                    (int
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22867
                                                                                        1))]
                                                                                   (case
                                                                                     G__22876
                                                                                     11
                                                                                     (let
                                                                                       [inst_22839
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          23)
                                                                                        inst_22852
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)
                                                                                        inst_22853
                                                                                        (=
                                                                                          :ok
                                                                                          inst_22839)
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22893
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22893
                                                                                            28
                                                                                            inst_22852)
                                                                                          statearr_22893)]
                                                                                       (if
                                                                                         inst_22853
                                                                                         (let
                                                                                           [statearr_22894
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22894
                                                                                             1
                                                                                             15))
                                                                                         (let
                                                                                           [statearr_22895
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22895
                                                                                             1
                                                                                             16)))
                                                                                       :recur)
                                                                                     14
                                                                                     (let
                                                                                       [inst_22850
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)]
                                                                                       (let
                                                                                         [statearr_22898
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22898
                                                                                           2
                                                                                           inst_22850)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22898
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     12
                                                                                     (let
                                                                                       [inst_22839
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          23)
                                                                                        inst_22847
                                                                                        (process/fail
                                                                                          process/instance
                                                                                          "Cluster pod gc failed"
                                                                                          inst_22839)]
                                                                                       (let
                                                                                         [statearr_22896
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22896
                                                                                           2
                                                                                           inst_22847)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22896
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     4
                                                                                     (let
                                                                                       [inst_22865
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)]
                                                                                       (clojure.core.async.impl.ioc-macros/return-chan
                                                                                         state_22867
                                                                                         inst_22865))
                                                                                     15
                                                                                     (do
                                                                                       (let
                                                                                         [statearr_22899
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22899
                                                                                           2
                                                                                           1)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22899
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     6
                                                                                     (let
                                                                                       [inst_22812
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          8)
                                                                                        inst_22807
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          9)
                                                                                        inst_22795
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          6)
                                                                                        inst_22805
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          10)
                                                                                        inst_22819
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          11)
                                                                                        inst_22804
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          12)
                                                                                        inst_22814
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          13)
                                                                                        inst_22830
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          14)
                                                                                        inst_22827
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          15)
                                                                                        inst_22796
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          7)
                                                                                        inst_22829
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          16)
                                                                                        inst_22815
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          17)
                                                                                        inst_22825
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          18)
                                                                                        inst_22831
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          19)
                                                                                        inst_22828
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          20)
                                                                                        vec__22783
                                                                                        inst_22812
                                                                                        to_ch
                                                                                        inst_22807
                                                                                        cluster
                                                                                        inst_22795
                                                                                        _
                                                                                        inst_22805
                                                                                        G__22782
                                                                                        inst_22819
                                                                                        garbage_ids
                                                                                        inst_22804
                                                                                        first__22785
                                                                                        inst_22814
                                                                                        result_chs
                                                                                        inst_22830
                                                                                        first__22789
                                                                                        inst_22827
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        ch
                                                                                        inst_22829
                                                                                        seq__22784
                                                                                        inst_22815
                                                                                        vec__22787
                                                                                        inst_22825
                                                                                        count
                                                                                        inst_22831
                                                                                        seq__22788
                                                                                        inst_22828
                                                                                        inst_22861
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageDeletedCount
                                                                                          count)]
                                                                                       (let
                                                                                         [statearr_22885
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22885
                                                                                           2
                                                                                           inst_22861)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22885
                                                                                           1
                                                                                           7))
                                                                                       :recur)
                                                                                     16
                                                                                     (do
                                                                                       (let
                                                                                         [statearr_22900
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22900
                                                                                           2
                                                                                           0)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22900
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     13
                                                                                     (do
                                                                                       (let
                                                                                         [statearr_22897
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22897
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22897
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     10
                                                                                     (let
                                                                                       [inst_22839
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          23)
                                                                                        inst_22845
                                                                                        (instance?
                                                                                          java.lang.Throwable
                                                                                          inst_22839)]
                                                                                       (if
                                                                                         inst_22845
                                                                                         (let
                                                                                           [statearr_22891
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22891
                                                                                             1
                                                                                             12))
                                                                                         (let
                                                                                           [statearr_22892
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22892
                                                                                             1
                                                                                             13)))
                                                                                       :recur)
                                                                                     17
                                                                                     (let
                                                                                       [inst_22831
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          19)
                                                                                        inst_22830
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          14)
                                                                                        inst_22857
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)
                                                                                        inst_22858
                                                                                        (+
                                                                                          inst_22831
                                                                                          inst_22857)
                                                                                        inst_22819
                                                                                        inst_22830
                                                                                        inst_22820
                                                                                        inst_22858
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22901
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22901
                                                                                            11
                                                                                            inst_22819)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22901
                                                                                            21
                                                                                            inst_22820)
                                                                                          statearr_22901)]
                                                                                       (let
                                                                                         [statearr_22902
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22902
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22902
                                                                                           1
                                                                                           3))
                                                                                       :recur)
                                                                                     5
                                                                                     (let
                                                                                       [inst_22829
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          16)
                                                                                        inst_22807
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          9)
                                                                                        inst_22833
                                                                                        (vector
                                                                                          inst_22829
                                                                                          inst_22807)]
                                                                                       (a/ioc-alts!
                                                                                         state_22867
                                                                                         8
                                                                                         inst_22833))
                                                                                     9
                                                                                     (let
                                                                                       [inst_22843
                                                                                        (warn
                                                                                          "Cluster pod gc timed out")]
                                                                                       (let
                                                                                         [statearr_22890
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22890
                                                                                           2
                                                                                           inst_22843)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22890
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     3
                                                                                     (let
                                                                                       [inst_22819
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          11)
                                                                                        inst_22820
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          21)
                                                                                        inst_22829
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          16)
                                                                                        inst_22822
                                                                                        (seq
                                                                                          inst_22819)
                                                                                        inst_22823
                                                                                        (first
                                                                                          inst_22822)
                                                                                        inst_22824
                                                                                        (next
                                                                                          inst_22822)
                                                                                        inst_22825
                                                                                        inst_22819
                                                                                        inst_22826
                                                                                        inst_22822
                                                                                        inst_22827
                                                                                        inst_22823
                                                                                        inst_22828
                                                                                        inst_22824
                                                                                        inst_22829
                                                                                        inst_22823
                                                                                        inst_22830
                                                                                        inst_22824
                                                                                        inst_22831
                                                                                        inst_22820
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22882
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            18
                                                                                            inst_22825)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            22
                                                                                            inst_22826)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            15
                                                                                            inst_22827)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            20
                                                                                            inst_22828)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            16
                                                                                            inst_22829)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            14
                                                                                            inst_22830)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22882
                                                                                            19
                                                                                            inst_22831)
                                                                                          statearr_22882)]
                                                                                       (if
                                                                                         inst_22829
                                                                                         (let
                                                                                           [statearr_22883
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22883
                                                                                             1
                                                                                             5))
                                                                                         (let
                                                                                           [statearr_22884
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22884
                                                                                             1
                                                                                             6)))
                                                                                       :recur)
                                                                                     1
                                                                                     (let
                                                                                       [inst_22795
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          6)
                                                                                        inst_22796
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          7)
                                                                                        inst_22793
                                                                                        (^clojure.lang.IFn G__22775)
                                                                                        cluster
                                                                                        inst_22793
                                                                                        inst_22794
                                                                                        (^clojure.lang.IFn G__22776)
                                                                                        inst_22795
                                                                                        inst_22793
                                                                                        inst_22796
                                                                                        inst_22794
                                                                                        cluster
                                                                                        inst_22795
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        inst_22797
                                                                                        (a/timeout
                                                                                          (long
                                                                                            (deref
                                                                                              pod-gc-delay-msec)))
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22877
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22877
                                                                                            6
                                                                                            inst_22795)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22877
                                                                                            7
                                                                                            inst_22796)
                                                                                          statearr_22877)]
                                                                                       (clojure.core.async.impl.ioc-macros/take!
                                                                                         state_22867
                                                                                         2
                                                                                         inst_22797))
                                                                                     7
                                                                                     (let
                                                                                       [inst_22863
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)]
                                                                                       (let
                                                                                         [statearr_22886
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22886
                                                                                           2
                                                                                           inst_22863)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22886
                                                                                           1
                                                                                           4))
                                                                                       :recur)
                                                                                     8
                                                                                     (let
                                                                                       [inst_22807
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          9)
                                                                                        inst_22835
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)
                                                                                        inst_22836
                                                                                        (nth
                                                                                          inst_22835
                                                                                          (int 0)
                                                                                          nil)
                                                                                        inst_22837
                                                                                        (nth
                                                                                          inst_22835
                                                                                          (int 1)
                                                                                          nil)
                                                                                        inst_22838
                                                                                        inst_22835
                                                                                        inst_22839
                                                                                        inst_22836
                                                                                        inst_22840
                                                                                        inst_22837
                                                                                        inst_22841
                                                                                        (=
                                                                                          inst_22840
                                                                                          inst_22807)
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22887
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22887
                                                                                            29
                                                                                            inst_22838)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22887
                                                                                            23
                                                                                            inst_22839)
                                                                                          statearr_22887)]
                                                                                       (if
                                                                                         inst_22841
                                                                                         (let
                                                                                           [statearr_22888
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22888
                                                                                             1
                                                                                             9))
                                                                                         (let
                                                                                           [statearr_22889
                                                                                            state_22867]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_22889
                                                                                             1
                                                                                             10)))
                                                                                       :recur)
                                                                                     2
                                                                                     (let
                                                                                       [inst_22795
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          6)
                                                                                        inst_22796
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          7)
                                                                                        inst_22807
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          9)
                                                                                        inst_22805
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          10)
                                                                                        inst_22804
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          12)
                                                                                        inst_22799
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_22867
                                                                                          2)
                                                                                        cluster
                                                                                        inst_22795
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        inst_22800
                                                                                        (deref
                                                                                          garbage_ids_ref)
                                                                                        cluster
                                                                                        inst_22795
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        garbage_ids
                                                                                        inst_22800
                                                                                        inst_22801
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageItems
                                                                                          (java.lang.Integer/valueOf
                                                                                            (int
                                                                                              (count
                                                                                                garbage_ids))))
                                                                                        cluster
                                                                                        inst_22795
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        garbage_ids
                                                                                        inst_22800
                                                                                        _
                                                                                        inst_22801
                                                                                        inst_22802
                                                                                        (mapv
                                                                                          (comp
                                                                                            future/get-channel
                                                                                            (fn
                                                                                              fn__22878
                                                                                              ([p1__22774#]
                                                                                                (cluster/delete
                                                                                                  cluster
                                                                                                  p1__22774#))))
                                                                                          garbage_ids)
                                                                                        cluster
                                                                                        inst_22795
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        garbage_ids
                                                                                        inst_22800
                                                                                        _
                                                                                        inst_22801
                                                                                        result_chs
                                                                                        inst_22802
                                                                                        inst_22803
                                                                                        (a/timeout
                                                                                          (long
                                                                                            cluster/BOUNDING_TIMEOUT_MSEC))
                                                                                        inst_22804
                                                                                        inst_22800
                                                                                        inst_22805
                                                                                        inst_22801
                                                                                        inst_22806
                                                                                        inst_22802
                                                                                        inst_22807
                                                                                        inst_22803
                                                                                        vec__22783
                                                                                        inst_22806
                                                                                        to_ch
                                                                                        inst_22807
                                                                                        cluster
                                                                                        inst_22795
                                                                                        _
                                                                                        inst_22805
                                                                                        G__22782
                                                                                        inst_22806
                                                                                        garbage_ids
                                                                                        inst_22804
                                                                                        result_chs
                                                                                        inst_22806
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        inst_22808
                                                                                        (seq
                                                                                          vec__22783)
                                                                                        vec__22783
                                                                                        inst_22806
                                                                                        to_ch
                                                                                        inst_22807
                                                                                        cluster
                                                                                        inst_22795
                                                                                        _
                                                                                        inst_22805
                                                                                        G__22782
                                                                                        inst_22806
                                                                                        garbage_ids
                                                                                        inst_22804
                                                                                        result_chs
                                                                                        inst_22806
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        seq__22784
                                                                                        inst_22808
                                                                                        inst_22809
                                                                                        (first
                                                                                          seq__22784)
                                                                                        vec__22783
                                                                                        inst_22806
                                                                                        to_ch
                                                                                        inst_22807
                                                                                        cluster
                                                                                        inst_22795
                                                                                        _
                                                                                        inst_22805
                                                                                        G__22782
                                                                                        inst_22806
                                                                                        garbage_ids
                                                                                        inst_22804
                                                                                        first__22785
                                                                                        inst_22809
                                                                                        result_chs
                                                                                        inst_22806
                                                                                        garbage_ids_ref
                                                                                        inst_22796
                                                                                        seq__22784
                                                                                        inst_22808
                                                                                        inst_22810
                                                                                        (next
                                                                                          seq__22784)
                                                                                        inst_22811
                                                                                        inst_22806
                                                                                        inst_22812
                                                                                        inst_22806
                                                                                        inst_22813
                                                                                        inst_22808
                                                                                        inst_22814
                                                                                        inst_22809
                                                                                        inst_22815
                                                                                        inst_22810
                                                                                        inst_22816
                                                                                        inst_22809
                                                                                        inst_22817
                                                                                        inst_22810
                                                                                        inst_22818
                                                                                        0
                                                                                        inst_22819
                                                                                        inst_22811
                                                                                        inst_22820
                                                                                        inst_22818
                                                                                        state_22867
                                                                                        (let
                                                                                          [statearr_22880
                                                                                           state_22867]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            24
                                                                                            inst_22799)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            12
                                                                                            inst_22804)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            10
                                                                                            inst_22805)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            9
                                                                                            inst_22807)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            8
                                                                                            inst_22812)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            25
                                                                                            inst_22813)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            13
                                                                                            inst_22814)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            17
                                                                                            inst_22815)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            26
                                                                                            inst_22816)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            27
                                                                                            inst_22817)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            11
                                                                                            inst_22819)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_22880
                                                                                            21
                                                                                            (long
                                                                                              inst_22820))
                                                                                          statearr_22880)]
                                                                                       (let
                                                                                         [statearr_22881
                                                                                          state_22867]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22881
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_22881
                                                                                           1
                                                                                           3))
                                                                                       :recur)))]
                                                                                (if
                                                                                  (identical?
                                                                                    result__5807__auto__
                                                                                    :recur)
                                                                                  (recur)
                                                                                  result__5807__auto__))))
                                                                          (catch
                                                                            java.lang.Throwable
                                                                            ex__5808__auto__
                                                                            (do
                                                                              (let
                                                                                [statearr_22903
                                                                                 state_22867]
                                                                                (clojure.core.async.impl.ioc-macros/aset-object
                                                                                  statearr_22903
                                                                                  2
                                                                                  ex__5808__auto__))
                                                                              (if
                                                                                (seq
                                                                                  (clojure.core.async.impl.ioc-macros/aget-object
                                                                                    state_22867
                                                                                    4))
                                                                                (let
                                                                                  [statearr_22904
                                                                                   state_22867]
                                                                                  (clojure.core.async.impl.ioc-macros/aset-object
                                                                                    statearr_22904
                                                                                    1
                                                                                    (first
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_22867
                                                                                        4))))
                                                                                (throw
                                                                                  ^java.lang.Throwable ex__5808__auto__))
                                                                              :recur)))
                                                                        (finally
                                                                          (do
                                                                            (clojure.core.async.impl.ioc-macros/aset-object
                                                                              state_22867
                                                                              3
                                                                              (clojure.lang.Var/getThreadBindingFrame))
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              old_frame__5805__auto__))))]
                                          (if (identical? ret_value__5806__auto__ :recur)
                                            (recur state_22867)
                                            ret_value__5806__auto__))))
                    state__5902__auto__ (let [statearr_22910 (^clojure.lang.IFn f__5901__auto__)]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22910
                                            5
                                            c__5899__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_22910
                                            3
                                            captured_bindings__5900__auto__)
                                          statearr_22910)]
                (clojure.core.async.impl.ioc-macros/run-state-machine-wrapped
                  state__5902__auto__)))))
        c__5899__auto__)))
  (reset-meta!
    #'schedule-gc
    (assoc
      {:arglists (clojure.core/list ['cluster 'garbage-ids-ref]), :column (int 1)}
      :name
      'schedule-gc
      :ns
      *ns*)))
