(do
  (clojure.core/in-ns 'datomic.garbage.pod)
  (clojure.core/with-loading-context
    (do
      (clojure.core/refer 'clojure.core)
      (clojure.core/require
        ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
        ['datomic.cluster :as 'cluster]
        ['datomic.config :as 'config]
        ['datomic.future :as 'future]
        ['datomic.monitor :as 'monitor]
        ['datomic.process :as 'process]
        ['datomic.slf4j :as 'logger])))
  (when-not (.equals 'datomic.garbage.pod 'clojure.core)
    (dosync (commute (deref #'clojure.core/*loaded-libs*) conj 'datomic.garbage.pod))
    (clojure.core/with-loading-context
      (do
        (clojure.core/refer 'clojure.core)
        (clojure.core/require
          ['clojure.core.async :as 'a :refer (clojure.core/list '<! 'alts! 'go)]
          ['datomic.cluster :as 'cluster]
          ['datomic.config :as 'config]
          ['datomic.future :as 'future]
          ['datomic.monitor :as 'monitor]
          ['datomic.process :as 'process]
          ['datomic.slf4j :as 'logger]))))
  (set! *warn-on-reflection* true)
  (.setMeta
    (clojure.lang.RT/var "datomic.garbage.pod" "pod-gc-delay-msec")
    {:private true, :column (int 1)})
  (.bindRoot
    (clojure.lang.RT/var "datomic.garbage.pod" "pod-gc-delay-msec")
    (delay (config/property "datomic.podGcDelayMsec")))
  (defn warn
    ([msg ex]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod") ex ex]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg) ex)
          (logger/caused-by logger ex))
        nil))
    ([msg]
      (let [logger (org.slf4j.LoggerFactory/getLogger "datomic.garbage.pod")]
        (when (.isWarnEnabled ^org.slf4j.Logger logger)
          (.warn ^org.slf4j.Logger logger (logger/process msg)))
        nil)))
  (reset-meta!
    #'warn
    (assoc
      {:private true, :arglists (clojure.core/list ['msg] ['msg 'ex]), :column (int 1)}
      :name
      'warn
      :ns
      *ns*))
  (defn schedule-gc
    ([cluster garbage_ids_ref]
      (let [c__6135__auto__ (a/chan 1)
            captured_bindings__6136__auto__ (clojure.lang.Var/getThreadBindingFrame)]
        (clojure.core.async.impl.dispatch/run
          (fn fn__20379
            ([]
              (let [G__20286 (fn G__20286 ([] cluster))
                    G__20287 (fn G__20287 ([] garbage_ids_ref))
                    f__6137__auto__ (fn state_machine__6040__auto__
                                      ([]
                                        (let [statearr_20385 (java.util.concurrent.atomic.AtomicReferenceArray.
                                                               (int 30))]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_20385
                                            0
                                            state_machine__6040__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_20385
                                            1
                                            1)
                                          statearr_20385))
                                      ([state_20378]
                                        (let [old_frame__6041__auto__ (clojure.lang.Var/getThreadBindingFrame)
                                              ret_value__6042__auto__ (try
                                                                        (try
                                                                          (do
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              (clojure.core.async.impl.ioc-macros/aget-object
                                                                                state_20378
                                                                                3))
                                                                            (loop 
                                                                              []
                                                                              (let 
                                                                                [result__6043__auto__
                                                                                 (let 
                                                                                   [G__20387
                                                                                    (int
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_20378
                                                                                        1))]
                                                                                   (case
                                                                                     G__20387
                                                                                     16
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_20411
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20411
                                                                                           2
                                                                                           0)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20411
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     4
                                                                                     (let 
                                                                                       [inst_20376
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)]
                                                                                       (clojure.core.async.impl.ioc-macros/return-chan
                                                                                         state_20378
                                                                                         inst_20376))
                                                                                     14
                                                                                     (let 
                                                                                       [inst_20361
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)]
                                                                                       (let 
                                                                                         [statearr_20409
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20409
                                                                                           2
                                                                                           inst_20361)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20409
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     9
                                                                                     (let 
                                                                                       [inst_20354
                                                                                        (warn
                                                                                          "Cluster pod gc timed out")]
                                                                                       (let 
                                                                                         [statearr_20401
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20401
                                                                                           2
                                                                                           inst_20354)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20401
                                                                                           1
                                                                                           11))
                                                                                       :recur)
                                                                                     8
                                                                                     (let 
                                                                                       [inst_20318
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          8)
                                                                                        inst_20346
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)
                                                                                        inst_20347
                                                                                        (nth
                                                                                          inst_20346
                                                                                          (int 0)
                                                                                          nil)
                                                                                        inst_20348
                                                                                        (nth
                                                                                          inst_20346
                                                                                          (int 1)
                                                                                          nil)
                                                                                        inst_20349
                                                                                        inst_20346
                                                                                        inst_20350
                                                                                        inst_20347
                                                                                        inst_20351
                                                                                        inst_20348
                                                                                        inst_20352
                                                                                        (=
                                                                                          inst_20351
                                                                                          inst_20318)
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20398
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20398
                                                                                            29
                                                                                            inst_20349)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20398
                                                                                            23
                                                                                            inst_20350)
                                                                                          statearr_20398)]
                                                                                       (if
                                                                                         inst_20352
                                                                                         (let 
                                                                                           [statearr_20399
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20399
                                                                                             1
                                                                                             9))
                                                                                         (let 
                                                                                           [statearr_20400
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20400
                                                                                             1
                                                                                             10)))
                                                                                       :recur)
                                                                                     10
                                                                                     (let 
                                                                                       [inst_20350
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          23)
                                                                                        inst_20356
                                                                                        (instance?
                                                                                          java.lang.Throwable
                                                                                          inst_20350)]
                                                                                       (if
                                                                                         inst_20356
                                                                                         (let 
                                                                                           [statearr_20402
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20402
                                                                                             1
                                                                                             12))
                                                                                         (let 
                                                                                           [statearr_20403
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20403
                                                                                             1
                                                                                             13)))
                                                                                       :recur)
                                                                                     1
                                                                                     (let 
                                                                                       [inst_20306
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          6)
                                                                                        inst_20307
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          7)
                                                                                        inst_20304
                                                                                        (^clojure.lang.IFn G__20286)
                                                                                        cluster
                                                                                        inst_20304
                                                                                        inst_20305
                                                                                        (^clojure.lang.IFn G__20287)
                                                                                        inst_20306
                                                                                        inst_20304
                                                                                        inst_20307
                                                                                        inst_20305
                                                                                        cluster
                                                                                        inst_20306
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        inst_20308
                                                                                        (a/timeout
                                                                                          (long
                                                                                            (deref
                                                                                              pod-gc-delay-msec)))
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20388
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20388
                                                                                            6
                                                                                            inst_20306)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20388
                                                                                            7
                                                                                            inst_20307)
                                                                                          statearr_20388)]
                                                                                       (clojure.core.async.impl.ioc-macros/take!
                                                                                         state_20378
                                                                                         2
                                                                                         inst_20308))
                                                                                     12
                                                                                     (let 
                                                                                       [inst_20350
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          23)
                                                                                        inst_20358
                                                                                        (process/fail
                                                                                          process/instance
                                                                                          "Cluster pod gc failed"
                                                                                          inst_20350)]
                                                                                       (let 
                                                                                         [statearr_20407
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20407
                                                                                           2
                                                                                           inst_20358)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20407
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     15
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_20410
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20410
                                                                                           2
                                                                                           1)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20410
                                                                                           1
                                                                                           17))
                                                                                       :recur)
                                                                                     5
                                                                                     (let 
                                                                                       [inst_20340
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          16)
                                                                                        inst_20318
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          8)
                                                                                        inst_20344
                                                                                        (vector
                                                                                          inst_20340
                                                                                          inst_20318)]
                                                                                       (a/ioc-alts!
                                                                                         state_20378
                                                                                         8
                                                                                         inst_20344))
                                                                                     11
                                                                                     (let 
                                                                                       [inst_20350
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          23)
                                                                                        inst_20363
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)
                                                                                        inst_20364
                                                                                        (=
                                                                                          :ok
                                                                                          inst_20350)
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20404
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20404
                                                                                            28
                                                                                            inst_20363)
                                                                                          statearr_20404)]
                                                                                       (if
                                                                                         inst_20364
                                                                                         (let 
                                                                                           [statearr_20405
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20405
                                                                                             1
                                                                                             15))
                                                                                         (let 
                                                                                           [statearr_20406
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20406
                                                                                             1
                                                                                             16)))
                                                                                       :recur)
                                                                                     17
                                                                                     (let 
                                                                                       [inst_20342
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          19)
                                                                                        inst_20341
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          15)
                                                                                        inst_20368
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)
                                                                                        inst_20369
                                                                                        (+
                                                                                          inst_20342
                                                                                          inst_20368)
                                                                                        inst_20330
                                                                                        inst_20341
                                                                                        inst_20331
                                                                                        inst_20369
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20412
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20412
                                                                                            9
                                                                                            inst_20330)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20412
                                                                                            21
                                                                                            inst_20331)
                                                                                          statearr_20412)]
                                                                                       (let 
                                                                                         [statearr_20413
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20413
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20413
                                                                                           1
                                                                                           3))
                                                                                       :recur)
                                                                                     7
                                                                                     (let 
                                                                                       [inst_20374
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)]
                                                                                       (let 
                                                                                         [statearr_20397
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20397
                                                                                           2
                                                                                           inst_20374)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20397
                                                                                           1
                                                                                           4))
                                                                                       :recur)
                                                                                     13
                                                                                     (do
                                                                                       (let 
                                                                                         [statearr_20408
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20408
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20408
                                                                                           1
                                                                                           14))
                                                                                       :recur)
                                                                                     2
                                                                                     (let 
                                                                                       [inst_20306
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          6)
                                                                                        inst_20307
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          7)
                                                                                        inst_20318
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          8)
                                                                                        inst_20316
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          11)
                                                                                        inst_20315
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          12)
                                                                                        inst_20310
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          2)
                                                                                        cluster
                                                                                        inst_20306
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        inst_20311
                                                                                        (deref
                                                                                          garbage_ids_ref)
                                                                                        cluster
                                                                                        inst_20306
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        garbage_ids
                                                                                        inst_20311
                                                                                        inst_20312
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageItems
                                                                                          (java.lang.Integer/valueOf
                                                                                            (int
                                                                                              (count
                                                                                                garbage_ids))))
                                                                                        cluster
                                                                                        inst_20306
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        garbage_ids
                                                                                        inst_20311
                                                                                        _
                                                                                        inst_20312
                                                                                        inst_20313
                                                                                        (mapv
                                                                                          (comp
                                                                                            future/get-channel
                                                                                            (fn 
                                                                                              fn__20389
                                                                                              ([p1__20285#]
                                                                                                (cluster/delete
                                                                                                  cluster
                                                                                                  p1__20285#))))
                                                                                          garbage_ids)
                                                                                        cluster
                                                                                        inst_20306
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        garbage_ids
                                                                                        inst_20311
                                                                                        _
                                                                                        inst_20312
                                                                                        result_chs
                                                                                        inst_20313
                                                                                        inst_20314
                                                                                        (a/timeout
                                                                                          (long
                                                                                            cluster/BOUNDING_TIMEOUT_MSEC))
                                                                                        inst_20315
                                                                                        inst_20311
                                                                                        inst_20316
                                                                                        inst_20312
                                                                                        inst_20317
                                                                                        inst_20313
                                                                                        inst_20318
                                                                                        inst_20314
                                                                                        to_ch
                                                                                        inst_20318
                                                                                        G__20293
                                                                                        inst_20317
                                                                                        vec__20294
                                                                                        inst_20317
                                                                                        cluster
                                                                                        inst_20306
                                                                                        _
                                                                                        inst_20316
                                                                                        garbage_ids
                                                                                        inst_20315
                                                                                        result_chs
                                                                                        inst_20317
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        inst_20319
                                                                                        (seq
                                                                                          vec__20294)
                                                                                        to_ch
                                                                                        inst_20318
                                                                                        G__20293
                                                                                        inst_20317
                                                                                        vec__20294
                                                                                        inst_20317
                                                                                        cluster
                                                                                        inst_20306
                                                                                        _
                                                                                        inst_20316
                                                                                        garbage_ids
                                                                                        inst_20315
                                                                                        seq__20295
                                                                                        inst_20319
                                                                                        result_chs
                                                                                        inst_20317
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        inst_20320
                                                                                        (first
                                                                                          seq__20295)
                                                                                        to_ch
                                                                                        inst_20318
                                                                                        G__20293
                                                                                        inst_20317
                                                                                        vec__20294
                                                                                        inst_20317
                                                                                        cluster
                                                                                        inst_20306
                                                                                        _
                                                                                        inst_20316
                                                                                        garbage_ids
                                                                                        inst_20315
                                                                                        seq__20295
                                                                                        inst_20319
                                                                                        first__20296
                                                                                        inst_20320
                                                                                        result_chs
                                                                                        inst_20317
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        inst_20321
                                                                                        (next
                                                                                          seq__20295)
                                                                                        inst_20322
                                                                                        inst_20317
                                                                                        inst_20323
                                                                                        inst_20317
                                                                                        inst_20324
                                                                                        inst_20319
                                                                                        inst_20325
                                                                                        inst_20320
                                                                                        inst_20326
                                                                                        inst_20321
                                                                                        inst_20327
                                                                                        inst_20320
                                                                                        inst_20328
                                                                                        inst_20321
                                                                                        inst_20329
                                                                                        0
                                                                                        inst_20330
                                                                                        inst_20322
                                                                                        inst_20331
                                                                                        inst_20329
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20391
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            24
                                                                                            inst_20310)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            12
                                                                                            inst_20315)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            11
                                                                                            inst_20316)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            8
                                                                                            inst_20318)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            10
                                                                                            inst_20323)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            25
                                                                                            inst_20324)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            14
                                                                                            inst_20325)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            13
                                                                                            inst_20326)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            26
                                                                                            inst_20327)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            27
                                                                                            inst_20328)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            9
                                                                                            inst_20330)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20391
                                                                                            21
                                                                                            (long
                                                                                              inst_20331))
                                                                                          statearr_20391)]
                                                                                       (let 
                                                                                         [statearr_20392
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20392
                                                                                           2
                                                                                           nil)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20392
                                                                                           1
                                                                                           3))
                                                                                       :recur)
                                                                                     6
                                                                                     (let 
                                                                                       [inst_20318
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          8)
                                                                                        inst_20330
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          9)
                                                                                        inst_20323
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          10)
                                                                                        inst_20306
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          6)
                                                                                        inst_20316
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          11)
                                                                                        inst_20315
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          12)
                                                                                        inst_20326
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          13)
                                                                                        inst_20325
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          14)
                                                                                        inst_20341
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          15)
                                                                                        inst_20307
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          7)
                                                                                        inst_20340
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          16)
                                                                                        inst_20336
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          17)
                                                                                        inst_20339
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          18)
                                                                                        inst_20342
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          19)
                                                                                        inst_20338
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          20)
                                                                                        to_ch
                                                                                        inst_20318
                                                                                        G__20293
                                                                                        inst_20330
                                                                                        vec__20294
                                                                                        inst_20323
                                                                                        cluster
                                                                                        inst_20306
                                                                                        _
                                                                                        inst_20316
                                                                                        garbage_ids
                                                                                        inst_20315
                                                                                        seq__20295
                                                                                        inst_20326
                                                                                        first__20296
                                                                                        inst_20325
                                                                                        result_chs
                                                                                        inst_20341
                                                                                        garbage_ids_ref
                                                                                        inst_20307
                                                                                        ch
                                                                                        inst_20340
                                                                                        vec__20298
                                                                                        inst_20336
                                                                                        seq__20299
                                                                                        inst_20339
                                                                                        count
                                                                                        inst_20342
                                                                                        first__20300
                                                                                        inst_20338
                                                                                        inst_20372
                                                                                        (monitor/add-stat
                                                                                          :PodGarbageDeletedCount
                                                                                          count)]
                                                                                       (let 
                                                                                         [statearr_20396
                                                                                          state_20378]
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20396
                                                                                           2
                                                                                           inst_20372)
                                                                                         (clojure.core.async.impl.ioc-macros/aset-object
                                                                                           statearr_20396
                                                                                           1
                                                                                           7))
                                                                                       :recur)
                                                                                     3
                                                                                     (let 
                                                                                       [inst_20330
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          9)
                                                                                        inst_20331
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          21)
                                                                                        inst_20340
                                                                                        (clojure.core.async.impl.ioc-macros/aget-object
                                                                                          state_20378
                                                                                          16)
                                                                                        inst_20333
                                                                                        (seq
                                                                                          inst_20330)
                                                                                        inst_20334
                                                                                        (first
                                                                                          inst_20333)
                                                                                        inst_20335
                                                                                        (next
                                                                                          inst_20333)
                                                                                        inst_20336
                                                                                        inst_20330
                                                                                        inst_20337
                                                                                        inst_20333
                                                                                        inst_20338
                                                                                        inst_20334
                                                                                        inst_20339
                                                                                        inst_20335
                                                                                        inst_20340
                                                                                        inst_20334
                                                                                        inst_20341
                                                                                        inst_20335
                                                                                        inst_20342
                                                                                        inst_20331
                                                                                        state_20378
                                                                                        (let 
                                                                                          [statearr_20393
                                                                                           state_20378]
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            17
                                                                                            inst_20336)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            22
                                                                                            inst_20337)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            20
                                                                                            inst_20338)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            18
                                                                                            inst_20339)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            16
                                                                                            inst_20340)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            15
                                                                                            inst_20341)
                                                                                          (clojure.core.async.impl.ioc-macros/aset-object
                                                                                            statearr_20393
                                                                                            19
                                                                                            inst_20342)
                                                                                          statearr_20393)]
                                                                                       (if
                                                                                         inst_20340
                                                                                         (let 
                                                                                           [statearr_20394
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20394
                                                                                             1
                                                                                             5))
                                                                                         (let 
                                                                                           [statearr_20395
                                                                                            state_20378]
                                                                                           (clojure.core.async.impl.ioc-macros/aset-object
                                                                                             statearr_20395
                                                                                             1
                                                                                             6)))
                                                                                       :recur)))]
                                                                                (if
                                                                                  (identical?
                                                                                    result__6043__auto__
                                                                                    :recur)
                                                                                  (recur)
                                                                                  result__6043__auto__))))
                                                                          (catch
                                                                            java.lang.Throwable
                                                                            ex__6044__auto__
                                                                            (do
                                                                              (let 
                                                                                [statearr_20414
                                                                                 state_20378]
                                                                                (clojure.core.async.impl.ioc-macros/aset-object
                                                                                  statearr_20414
                                                                                  2
                                                                                  ex__6044__auto__))
                                                                              (if
                                                                                (seq
                                                                                  (clojure.core.async.impl.ioc-macros/aget-object
                                                                                    state_20378
                                                                                    4))
                                                                                (let 
                                                                                  [statearr_20415
                                                                                   state_20378]
                                                                                  (clojure.core.async.impl.ioc-macros/aset-object
                                                                                    statearr_20415
                                                                                    1
                                                                                    (first
                                                                                      (clojure.core.async.impl.ioc-macros/aget-object
                                                                                        state_20378
                                                                                        4))))
                                                                                (throw
                                                                                  ^java.lang.Throwable ex__6044__auto__))
                                                                              :recur)))
                                                                        (finally
                                                                          (do
                                                                            (clojure.core.async.impl.ioc-macros/aset-object
                                                                              state_20378
                                                                              3
                                                                              (clojure.lang.Var/getThreadBindingFrame))
                                                                            (clojure.lang.Var/resetThreadBindingFrame
                                                                              old_frame__6041__auto__))))]
                                          (if (identical? ret_value__6042__auto__ :recur)
                                            (recur state_20378)
                                            ret_value__6042__auto__))))
                    state__6138__auto__ (let [statearr_20421 (^clojure.lang.IFn f__6137__auto__)]
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_20421
                                            5
                                            c__6135__auto__)
                                          (clojure.core.async.impl.ioc-macros/aset-object
                                            statearr_20421
                                            3
                                            captured_bindings__6136__auto__)
                                          statearr_20421)]
                (clojure.core.async.impl.ioc-macros/run-state-machine-wrapped
                  state__6138__auto__)))))
        c__6135__auto__)))
  (reset-meta!
    #'schedule-gc
    (assoc
      {:arglists (clojure.core/list ['cluster 'garbage-ids-ref]), :column (int 1)}
      :name
      'schedule-gc
      :ns
      *ns*)))