/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.api$add_listener;
import datomic.api$administer_system;
import datomic.api$as_of;
import datomic.api$as_of_t;
import datomic.api$attribute;
import datomic.api$basis_t;
import datomic.api$cancel;
import datomic.api$connect;
import datomic.api$create_database;
import datomic.api$datoms;
import datomic.api$db;
import datomic.api$db_stats;
import datomic.api$delete_database;
import datomic.api$entid;
import datomic.api$entid_at;
import datomic.api$entity;
import datomic.api$entity_db;
import datomic.api$filter;
import datomic.api$fn__19563;
import datomic.api$fn__19645;
import datomic.api$function;
import datomic.api$gc_storage;
import datomic.api$get_database_names;
import datomic.api$history;
import datomic.api$ident;
import datomic.api$implicit_part;
import datomic.api$implicit_part_id;
import datomic.api$index_pull;
import datomic.api$index_range;
import datomic.api$invoke;
import datomic.api$is_filtered;
import datomic.api$is_history;
import datomic.api$loading__6434__auto____17821;
import datomic.api$log;
import datomic.api$next_t;
import datomic.api$part;
import datomic.api$pull;
import datomic.api$pull_many;
import datomic.api$q;
import datomic.api$qseq;
import datomic.api$query;
import datomic.api$release;
import datomic.api$remove_tx_report_queue;
import datomic.api$rename_database;
import datomic.api$request_index;
import datomic.api$resolve_tempid;
import datomic.api$seek_datoms;
import datomic.api$shutdown;
import datomic.api$since;
import datomic.api$since_t;
import datomic.api$squuid;
import datomic.api$squuid_time_millis;
import datomic.api$sync;
import datomic.api$sync_excise;
import datomic.api$sync_index;
import datomic.api$sync_schema;
import datomic.api$t__GT_tx;
import datomic.api$tempid;
import datomic.api$touch;
import datomic.api$transact;
import datomic.api$transact_async;
import datomic.api$tx__GT_t;
import datomic.api$tx_range;
import datomic.api$tx_report_queue;
import datomic.api$with;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class api__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__11;
    public static final Var const__12;
    public static final AFn const__14;
    public static final Var const__15;
    public static final AFn const__17;
    public static final Var const__18;
    public static final AFn const__20;
    public static final Var const__21;
    public static final AFn const__23;
    public static final Var const__24;
    public static final AFn const__26;
    public static final Var const__27;
    public static final AFn const__29;
    public static final Var const__30;
    public static final AFn const__32;
    public static final Var const__33;
    public static final AFn const__35;
    public static final Var const__36;
    public static final AFn const__38;
    public static final Var const__39;
    public static final AFn const__41;
    public static final Var const__42;
    public static final AFn const__44;
    public static final Var const__45;
    public static final AFn const__47;
    public static final Var const__48;
    public static final AFn const__50;
    public static final Var const__51;
    public static final AFn const__54;
    public static final Var const__55;
    public static final AFn const__58;
    public static final Var const__59;
    public static final AFn const__61;
    public static final Var const__62;
    public static final AFn const__64;
    public static final Var const__65;
    public static final AFn const__67;
    public static final Var const__68;
    public static final AFn const__70;
    public static final Var const__71;
    public static final AFn const__73;
    public static final Var const__74;
    public static final AFn const__76;
    public static final Var const__77;
    public static final AFn const__79;
    public static final Var const__80;
    public static final AFn const__82;
    public static final Var const__83;
    public static final AFn const__85;
    public static final Var const__86;
    public static final AFn const__88;
    public static final Var const__89;
    public static final AFn const__91;
    public static final Var const__92;
    public static final AFn const__94;
    public static final Var const__95;
    public static final AFn const__97;
    public static final Var const__98;
    public static final AFn const__100;
    public static final Var const__101;
    public static final AFn const__103;
    public static final Var const__104;
    public static final AFn const__106;
    public static final Var const__107;
    public static final AFn const__109;
    public static final Var const__110;
    public static final AFn const__112;
    public static final Var const__113;
    public static final AFn const__115;
    public static final Var const__116;
    public static final AFn const__118;
    public static final Var const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final Var const__128;
    public static final AFn const__130;
    public static final Var const__131;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__136;
    public static final Var const__137;
    public static final AFn const__139;
    public static final Var const__140;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__145;
    public static final Var const__146;
    public static final AFn const__148;
    public static final Var const__149;
    public static final AFn const__151;
    public static final Var const__152;
    public static final AFn const__154;
    public static final Var const__155;
    public static final AFn const__157;
    public static final Var const__158;
    public static final AFn const__160;
    public static final Var const__161;
    public static final AFn const__163;
    public static final Var const__164;
    public static final AFn const__166;
    public static final Var const__167;
    public static final AFn const__169;
    public static final Var const__170;
    public static final AFn const__173;
    public static final Var const__174;
    public static final AFn const__176;
    public static final Var const__177;
    public static final AFn const__179;
    public static final Var const__180;
    public static final AFn const__182;
    public static final Var const__183;
    public static final AFn const__185;
    public static final Var const__186;
    public static final AFn const__188;
    public static final Var const__189;
    public static final AFn const__191;
    public static final Var const__192;
    public static final AFn const__194;
    public static final Var const__195;
    public static final AFn const__197;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new api$loading__6434__auto____17821()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new api$fn__19563())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__11);
        Var var2 = var;
        var.bindRoot((Object)new api$connect());
        Var var3 = const__12;
        var3.setMeta((IPersistentMap)const__14);
        Var var4 = var3;
        var3.bindRoot((Object)new api$create_database());
        Var var5 = const__15;
        var5.setMeta((IPersistentMap)const__17);
        Var var6 = var5;
        var5.bindRoot((Object)new api$delete_database());
        Var var7 = const__18;
        var7.setMeta((IPersistentMap)const__20);
        Var var8 = var7;
        var7.bindRoot((Object)new api$get_database_names());
        Var var9 = const__21;
        var9.setMeta((IPersistentMap)const__23);
        Var var10 = var9;
        var9.bindRoot((Object)new api$administer_system());
        Var var11 = const__24;
        var11.setMeta((IPersistentMap)const__26);
        Var var12 = var11;
        var11.bindRoot((Object)new api$rename_database());
        Var var13 = const__27;
        var13.setMeta((IPersistentMap)const__29);
        Var var14 = var13;
        var13.bindRoot((Object)new api$q());
        Var var15 = const__30;
        var15.setMeta((IPersistentMap)const__32);
        Var var16 = var15;
        var15.bindRoot((Object)new api$query());
        Var var17 = const__33;
        var17.setMeta((IPersistentMap)const__35);
        Var var18 = var17;
        var17.bindRoot((Object)new api$qseq());
        Var var19 = const__36;
        var19.setMeta((IPersistentMap)const__38);
        Var var20 = var19;
        var19.bindRoot((Object)new api$tempid());
        Var var21 = const__39;
        var21.setMeta((IPersistentMap)const__41);
        Var var22 = var21;
        var21.bindRoot((Object)new api$t__GT_tx());
        Var var23 = const__42;
        var23.setMeta((IPersistentMap)const__44);
        Var var24 = var23;
        var23.bindRoot((Object)new api$tx__GT_t());
        Var var25 = const__45;
        var25.setMeta((IPersistentMap)const__47);
        Var var26 = var25;
        var25.bindRoot((Object)new api$part());
        Var var27 = const__48;
        var27.setMeta((IPersistentMap)const__50);
        Var var28 = var27;
        var27.bindRoot((Object)new api$function());
        Var var29 = const__51;
        var29.setMeta((IPersistentMap)const__54);
        Var var30 = var29;
        var29.bindRoot((Object)new api$db());
        Var var31 = const__55;
        var31.setMeta((IPersistentMap)const__58);
        Var var32 = var31;
        var31.bindRoot((Object)new api$log());
        Var var33 = const__59;
        var33.setMeta((IPersistentMap)const__61);
        Var var34 = var33;
        var33.bindRoot((Object)new api$sync());
        Var var35 = const__62;
        var35.setMeta((IPersistentMap)const__64);
        Var var36 = var35;
        var35.bindRoot((Object)new api$sync_index());
        Var var37 = const__65;
        var37.setMeta((IPersistentMap)const__67);
        Var var38 = var37;
        var37.bindRoot((Object)new api$sync_schema());
        Var var39 = const__68;
        var39.setMeta((IPersistentMap)const__70);
        Var var40 = var39;
        var39.bindRoot((Object)new api$sync_excise());
        Var var41 = const__71;
        var41.setMeta((IPersistentMap)const__73);
        Var var42 = var41;
        var41.bindRoot((Object)new api$request_index());
        Var var43 = const__74;
        var43.setMeta((IPersistentMap)const__76);
        Var var44 = var43;
        var43.bindRoot((Object)new api$gc_storage());
        Var var45 = const__77;
        var45.setMeta((IPersistentMap)const__79);
        Var var46 = var45;
        var45.bindRoot((Object)new api$transact());
        Var var47 = const__80;
        var47.setMeta((IPersistentMap)const__82);
        Var var48 = var47;
        var47.bindRoot((Object)new api$transact_async());
        Var var49 = const__83;
        var49.setMeta((IPersistentMap)const__85);
        Var var50 = var49;
        var49.bindRoot((Object)new api$tx_report_queue());
        Var var51 = const__86;
        var51.setMeta((IPersistentMap)const__88);
        Var var52 = var51;
        var51.bindRoot((Object)new api$remove_tx_report_queue());
        Var var53 = const__89;
        var53.setMeta((IPersistentMap)const__91);
        Var var54 = var53;
        var53.bindRoot((Object)new api$as_of());
        Var var55 = const__92;
        var55.setMeta((IPersistentMap)const__94);
        Var var56 = var55;
        var55.bindRoot((Object)new api$since());
        Var var57 = const__95;
        var57.setMeta((IPersistentMap)const__97);
        Var var58 = var57;
        var57.bindRoot((Object)new api$history());
        Var var59 = const__98;
        var59.setMeta((IPersistentMap)const__100);
        Var var60 = var59;
        var59.bindRoot((Object)new api$filter());
        Var var61 = const__101;
        var61.setMeta((IPersistentMap)const__103);
        Var var62 = var61;
        var61.bindRoot((Object)new api$with());
        Var var63 = const__104;
        var63.setMeta((IPersistentMap)const__106);
        Var var64 = var63;
        var63.bindRoot((Object)new api$basis_t());
        Var var65 = const__107;
        var65.setMeta((IPersistentMap)const__109);
        Var var66 = var65;
        var65.bindRoot((Object)new api$next_t());
        Var var67 = const__110;
        var67.setMeta((IPersistentMap)const__112);
        Var var68 = var67;
        var67.bindRoot((Object)new api$as_of_t());
        Var var69 = const__113;
        var69.setMeta((IPersistentMap)const__115);
        Var var70 = var69;
        var69.bindRoot((Object)new api$since_t());
        Var var71 = const__116;
        var71.setMeta((IPersistentMap)const__118);
        Var var72 = var71;
        var71.bindRoot((Object)new api$is_history());
        Var var73 = const__119;
        var73.setMeta((IPersistentMap)const__121);
        Var var74 = var73;
        var73.bindRoot((Object)new api$is_filtered());
        Var var75 = const__122;
        var75.setMeta((IPersistentMap)const__124);
        Var var76 = var75;
        var75.bindRoot((Object)new api$attribute());
        Var var77 = const__125;
        var77.setMeta((IPersistentMap)const__127);
        Var var78 = var77;
        var77.bindRoot((Object)new api$entity());
        Var var79 = const__128;
        var79.setMeta((IPersistentMap)const__130);
        Var var80 = var79;
        var79.bindRoot((Object)new api$pull());
        Var var81 = const__131;
        var81.setMeta((IPersistentMap)const__133);
        Var var82 = var81;
        var81.bindRoot((Object)new api$index_pull());
        Var var83 = const__134;
        var83.setMeta((IPersistentMap)const__136);
        Var var84 = var83;
        var83.bindRoot((Object)new api$pull_many());
        Var var85 = const__137;
        var85.setMeta((IPersistentMap)const__139);
        Var var86 = var85;
        var85.bindRoot((Object)new api$touch());
        Var var87 = const__140;
        var87.setMeta((IPersistentMap)const__142);
        Var var88 = var87;
        var87.bindRoot((Object)new api$entity_db());
        Var var89 = const__143;
        var89.setMeta((IPersistentMap)const__145);
        Var var90 = var89;
        var89.bindRoot((Object)new api$index_range());
        Var var91 = const__146;
        var91.setMeta((IPersistentMap)const__148);
        Var var92 = var91;
        var91.bindRoot((Object)new api$tx_range());
        Var var93 = const__149;
        var93.setMeta((IPersistentMap)const__151);
        Var var94 = var93;
        var93.bindRoot((Object)new api$ident());
        Var var95 = const__152;
        var95.setMeta((IPersistentMap)const__154);
        Var var96 = var95;
        var95.bindRoot((Object)new api$entid());
        Var var97 = const__155;
        var97.setMeta((IPersistentMap)const__157);
        Var var98 = var97;
        var97.bindRoot((Object)new api$entid_at());
        Var var99 = const__158;
        var99.setMeta((IPersistentMap)const__160);
        Var var100 = var99;
        var99.bindRoot((Object)new api$invoke());
        Var var101 = const__161;
        var101.setMeta((IPersistentMap)const__163);
        Var var102 = var101;
        var101.bindRoot((Object)new api$datoms());
        Var var103 = const__164;
        var103.setMeta((IPersistentMap)const__166);
        Var var104 = var103;
        var103.bindRoot((Object)new api$seek_datoms());
        Var var105 = const__167;
        var105.setMeta((IPersistentMap)const__169);
        Var var106 = var105;
        var105.bindRoot((Object)new api$resolve_tempid());
        Var var107 = const__170;
        var107.setMeta((IPersistentMap)const__173);
        Var var108 = var107;
        var107.bindRoot((Object)new api$shutdown());
        Var var109 = const__174;
        var109.setMeta((IPersistentMap)const__176);
        Var var110 = var109;
        var109.bindRoot((Object)new api$release());
        Var var111 = const__177;
        var111.setMeta((IPersistentMap)const__179);
        Var var112 = var111;
        var111.bindRoot((Object)new api$cancel());
        Var var113 = const__180;
        var113.setMeta((IPersistentMap)const__182);
        Var var114 = var113;
        var113.bindRoot((Object)new api$squuid());
        Var var115 = const__183;
        var115.setMeta((IPersistentMap)const__185);
        Var var116 = var115;
        var115.bindRoot((Object)new api$squuid_time_millis());
        Var var117 = const__186;
        var117.setMeta((IPersistentMap)const__188);
        Var var118 = var117;
        var117.bindRoot((Object)new api$add_listener());
        Var var119 = const__189;
        var119.setMeta((IPersistentMap)const__191);
        Var var120 = var119;
        var119.bindRoot((Object)new api$db_stats());
        Var var121 = const__192;
        var121.setMeta((IPersistentMap)const__194);
        Var var122 = var121;
        var121.bindRoot((Object)new api$implicit_part());
        Var var123 = const__195;
        var123.setMeta((IPersistentMap)const__197);
        Var var124 = var123;
        var123.bindRoot((Object)new api$implicit_part_id());
        Object v128 = null;
        Object object4 = ((IFn)new api$fn__19645()).invoke();
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.api");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.api", (String)"connect");
        const__11 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Connection"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__12 = RT.var((String)"datomic.api", (String)"create-database");
        const__14 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__15 = RT.var((String)"datomic.api", (String)"delete-database");
        const__17 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__18 = RT.var((String)"datomic.api", (String)"get-database-names");
        const__20 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__21 = RT.var((String)"datomic.api", (String)"administer-system");
        const__23 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"options")))), RT.keyword(null, (String)"column"), 1});
        const__24 = RT.var((String)"datomic.api", (String)"rename-database");
        const__26 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)((IObj)Symbol.intern(null, (String)"new-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__27 = RT.var((String)"datomic.api", (String)"q");
        const__29 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"inputs")))), RT.keyword(null, (String)"column"), 1});
        const__30 = RT.var((String)"datomic.api", (String)"query");
        const__32 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query-map")))), RT.keyword(null, (String)"column"), 1});
        const__33 = RT.var((String)"datomic.api", (String)"qseq");
        const__35 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query-map")))), RT.keyword(null, (String)"column"), 1});
        const__36 = RT.var((String)"datomic.api", (String)"tempid");
        const__38 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"partition")), Tuple.create((Object)Symbol.intern(null, (String)"partition"), (Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__39 = RT.var((String)"datomic.api", (String)"t->tx");
        const__41 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")}))))), RT.keyword(null, (String)"column"), 1});
        const__42 = RT.var((String)"datomic.api", (String)"tx->t");
        const__44 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"tx"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__45 = RT.var((String)"datomic.api", (String)"part");
        const__47 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"eid")))), RT.keyword(null, (String)"column"), 1});
        const__48 = RT.var((String)"datomic.api", (String)"function");
        const__50 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__51 = RT.var((String)"datomic.api", (String)"db");
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Database"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__55 = RT.var((String)"datomic.api", (String)"log");
        const__58 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Log"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__59 = RT.var((String)"datomic.api", (String)"sync");
        const__61 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))), Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__62 = RT.var((String)"datomic.api", (String)"sync-index");
        const__64 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__65 = RT.var((String)"datomic.api", (String)"sync-schema");
        const__67 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__68 = RT.var((String)"datomic.api", (String)"sync-excise");
        const__70 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__71 = RT.var((String)"datomic.api", (String)"request-index");
        const__73 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__74 = RT.var((String)"datomic.api", (String)"gc-storage");
        const__76 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"older-than")))), RT.keyword(null, (String)"column"), 1});
        const__77 = RT.var((String)"datomic.api", (String)"transact");
        const__79 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"tx-data"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"options")})))), RT.keyword(null, (String)"column"), 1});
        const__80 = RT.var((String)"datomic.api", (String)"transact-async");
        const__82 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")})), (Object)Symbol.intern(null, (String)"tx-data"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"options")})))), RT.keyword(null, (String)"column"), 1});
        const__83 = RT.var((String)"datomic.api", (String)"tx-report-queue");
        const__85 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__86 = RT.var((String)"datomic.api", (String)"remove-tx-report-queue");
        const__88 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"connection")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__89 = RT.var((String)"datomic.api", (String)"as-of");
        const__91 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Database"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__92 = RT.var((String)"datomic.api", (String)"since");
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Database"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__95 = RT.var((String)"datomic.api", (String)"history");
        const__97 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Database"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__98 = RT.var((String)"datomic.api", (String)"filter");
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.Database"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)((IObj)Symbol.intern(null, (String)"pred")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")}))))), RT.keyword(null, (String)"column"), 1});
        const__101 = RT.var((String)"datomic.api", (String)"with");
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"tx-data")), Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"tx-data"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"opts")))), RT.keyword(null, (String)"column"), 1});
        const__104 = RT.var((String)"datomic.api", (String)"basis-t");
        const__106 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__107 = RT.var((String)"datomic.api", (String)"next-t");
        const__109 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__110 = RT.var((String)"datomic.api", (String)"as-of-t");
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__113 = RT.var((String)"datomic.api", (String)"since-t");
        const__115 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__116 = RT.var((String)"datomic.api", (String)"is-history");
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__119 = RT.var((String)"datomic.api", (String)"is-filtered");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.api", (String)"attribute");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"attrid")))), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.api", (String)"entity");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"eid")))), RT.keyword(null, (String)"column"), 1});
        const__128 = RT.var((String)"datomic.api", (String)"pull");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"pattern"), (Object)Symbol.intern(null, (String)"eid"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"options")})))), RT.keyword(null, (String)"column"), 1});
        const__131 = RT.var((String)"datomic.api", (String)"index-pull");
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"arg-map")))), RT.keyword(null, (String)"column"), 1});
        const__134 = RT.var((String)"datomic.api", (String)"pull-many");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"pattern"), (Object)Symbol.intern(null, (String)"eids"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"options")})))), RT.keyword(null, (String)"column"), 1});
        const__137 = RT.var((String)"datomic.api", (String)"touch");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"entity")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Entity")}))))), RT.keyword(null, (String)"column"), 1});
        const__140 = RT.var((String)"datomic.api", (String)"entity-db");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"entity")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Entity")}))))), RT.keyword(null, (String)"column"), 1});
        const__143 = RT.var((String)"datomic.api", (String)"index-range");
        const__145 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"attrid"), (Object)Symbol.intern(null, (String)"start"), (Object)Symbol.intern(null, (String)"end")))), RT.keyword(null, (String)"column"), 1});
        const__146 = RT.var((String)"datomic.api", (String)"tx-range");
        const__148 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"log")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Log")})), (Object)Symbol.intern(null, (String)"start"), (Object)Symbol.intern(null, (String)"end")))), RT.keyword(null, (String)"column"), 1});
        const__149 = RT.var((String)"datomic.api", (String)"ident");
        const__151 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"eid")))), RT.keyword(null, (String)"column"), 1});
        const__152 = RT.var((String)"datomic.api", (String)"entid");
        const__154 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"ident")))), RT.keyword(null, (String)"column"), 1});
        const__155 = RT.var((String)"datomic.api", (String)"entid-at");
        const__157 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"part"), (Object)Symbol.intern(null, (String)"t-or-date")))), RT.keyword(null, (String)"column"), 1});
        const__158 = RT.var((String)"datomic.api", (String)"invoke");
        const__160 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"eid-or-ident"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__161 = RT.var((String)"datomic.api", (String)"datoms");
        const__163 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"components")))), RT.keyword(null, (String)"column"), 1});
        const__164 = RT.var((String)"datomic.api", (String)"seek-datoms");
        const__166 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"components")))), RT.keyword(null, (String)"column"), 1});
        const__167 = RT.var((String)"datomic.api", (String)"resolve-tempid");
        const__169 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"tempids"), (Object)Symbol.intern(null, (String)"tempid")))), RT.keyword(null, (String)"column"), 1});
        const__170 = RT.var((String)"datomic.api", (String)"shutdown");
        const__173 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"shutdown-clojure")))), RT.keyword(null, (String)"added"), "0.8.3861", RT.keyword(null, (String)"column"), 1});
        const__174 = RT.var((String)"datomic.api", (String)"release");
        const__176 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"conn")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Connection")}))))), RT.keyword(null, (String)"added"), "0.8.3861", RT.keyword(null, (String)"column"), 1});
        const__177 = RT.var((String)"datomic.api", (String)"cancel");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern((String)"cognitect.anomalies", (String)"category")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"anomaly-map")})))), RT.keyword(null, (String)"column"), 1});
        const__180 = RT.var((String)"datomic.api", (String)"squuid");
        const__182 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__183 = RT.var((String)"datomic.api", (String)"squuid-time-millis");
        const__185 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"squuid"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__186 = RT.var((String)"datomic.api", (String)"add-listener");
        const__188 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"fut")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.ListenableFuture")})), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"executor")))), RT.keyword(null, (String)"column"), 1});
        const__189 = RT.var((String)"datomic.api", (String)"db-stats");
        const__191 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"added"), "1.0.6333", RT.keyword(null, (String)"column"), 1});
        const__192 = RT.var((String)"datomic.api", (String)"implicit-part");
        const__194 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"id")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__195 = RT.var((String)"datomic.api", (String)"implicit-part-id");
        const__197 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"part")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")}))))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        api__init.__init0();
        api__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.api__init").getClassLoader());
        try {
            api__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

