/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.common$_GT__SINGLEQUOTE_;
import datomic.common$_LT__SINGLEQUOTE_;
import datomic.common$array_cat;
import datomic.common$assert_all;
import datomic.common$await_derefs;
import datomic.common$bean_setters;
import datomic.common$bounded_deref;
import datomic.common$cc;
import datomic.common$cl;
import datomic.common$clj_key__GT_env_key;
import datomic.common$closing_watch;
import datomic.common$coerce_args;
import datomic.common$coll_compare;
import datomic.common$compare;
import datomic.common$compare_byte_arrays;
import datomic.common$compare_ex;
import datomic.common$create_temp_directory;
import datomic.common$cx;
import datomic.common$delete_file_recursively;
import datomic.common$distinct_by;
import datomic.common$endpoint_QMARK_;
import datomic.common$ensure_vector;
import datomic.common$ensure_vectors_in_array;
import datomic.common$env_key__GT_clj_key;
import datomic.common$equals_with_strict_scale;
import datomic.common$find_free_port;
import datomic.common$fire;
import datomic.common$fn__9011;
import datomic.common$fn__9074;
import datomic.common$fn__9077;
import datomic.common$force_keyword;
import datomic.common$force_map_keywords;
import datomic.common$getx;
import datomic.common$getx_in;
import datomic.common$into_bean;
import datomic.common$key_comparator;
import datomic.common$load_properties;
import datomic.common$loading__6434__auto____882;
import datomic.common$log_and_print;
import datomic.common$log_retry;
import datomic.common$map__GT_env;
import datomic.common$map__GT_props;
import datomic.common$map_from_env;
import datomic.common$mapk;
import datomic.common$maybe_class;
import datomic.common$maybe_deref;
import datomic.common$maybe_require;
import datomic.common$pfuture;
import datomic.common$pooled_mapv;
import datomic.common$pop_atom_BANG_;
import datomic.common$props__GT_map;
import datomic.common$qualified_name;
import datomic.common$qualified_symbol_QMARK_;
import datomic.common$rand_uuid;
import datomic.common$require_keys;
import datomic.common$requiring_resolve_BANG_;
import datomic.common$result_count;
import datomic.common$result_xform;
import datomic.common$retry_fn;
import datomic.common$return_or_throw;
import datomic.common$returning_throwable;
import datomic.common$root_cause;
import datomic.common$schedule;
import datomic.common$split_filter;
import datomic.common$squuid;
import datomic.common$squuid_time_ms;
import datomic.common$store_properties;
import datomic.common$sync_shutdown;
import datomic.common$throw_anom;
import datomic.common$with_nano_time;
import datomic.common$with_shutdown;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class common__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final Var const__5;
    public static final AFn const__9;
    public static final Var const__10;
    public static final AFn const__13;
    public static final Var const__14;
    public static final AFn const__15;
    public static final Var const__16;
    public static final AFn const__19;
    public static final Var const__20;
    public static final AFn const__22;
    public static final Var const__23;
    public static final AFn const__25;
    public static final Var const__26;
    public static final AFn const__28;
    public static final Var const__29;
    public static final AFn const__31;
    public static final Var const__32;
    public static final AFn const__34;
    public static final Var const__35;
    public static final AFn const__37;
    public static final AFn const__39;
    public static final Var const__40;
    public static final AFn const__42;
    public static final Var const__43;
    public static final AFn const__45;
    public static final Var const__46;
    public static final AFn const__48;
    public static final Var const__49;
    public static final AFn const__51;
    public static final Var const__52;
    public static final AFn const__54;
    public static final Var const__55;
    public static final AFn const__57;
    public static final Var const__58;
    public static final AFn const__60;
    public static final Var const__61;
    public static final AFn const__63;
    public static final Var const__64;
    public static final AFn const__66;
    public static final Var const__67;
    public static final AFn const__69;
    public static final Var const__70;
    public static final AFn const__72;
    public static final Var const__73;
    public static final AFn const__75;
    public static final Var const__76;
    public static final AFn const__78;
    public static final Object const__79;
    public static final Var const__80;
    public static final Var const__81;
    public static final Var const__82;
    public static final Keyword const__83;
    public static final Var const__84;
    public static final ISeq const__85;
    public static final Var const__86;
    public static final Var const__87;
    public static final AFn const__91;
    public static final Keyword const__92;
    public static final AFn const__93;
    public static final Keyword const__94;
    public static final Keyword const__95;
    public static final AFn const__97;
    public static final Keyword const__98;
    public static final Var const__99;
    public static final Var const__100;
    public static final Var const__101;
    public static final AFn const__102;
    public static final AFn const__103;
    public static final Keyword const__104;
    public static final Var const__105;
    public static final AFn const__106;
    public static final Var const__107;
    public static final AFn const__109;
    public static final Var const__110;
    public static final AFn const__112;
    public static final Var const__113;
    public static final AFn const__115;
    public static final Var const__116;
    public static final AFn const__118;
    public static final Var const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final Var const__128;
    public static final AFn const__130;
    public static final Var const__131;
    public static final AFn const__132;
    public static final Var const__133;
    public static final AFn const__135;
    public static final Var const__136;
    public static final AFn const__138;
    public static final Var const__139;
    public static final AFn const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;
    public static final Var const__163;
    public static final AFn const__165;
    public static final Var const__166;
    public static final AFn const__168;
    public static final Var const__169;
    public static final AFn const__171;
    public static final Var const__172;
    public static final AFn const__174;
    public static final Var const__175;
    public static final AFn const__177;
    public static final Var const__178;
    public static final AFn const__180;
    public static final Var const__181;
    public static final AFn const__183;
    public static final Var const__184;
    public static final AFn const__186;
    public static final Var const__187;
    public static final AFn const__189;
    public static final Var const__190;
    public static final AFn const__192;
    public static final Var const__193;
    public static final AFn const__195;
    public static final Var const__196;
    public static final AFn const__198;
    public static final Var const__199;
    public static final AFn const__201;
    public static final Var const__202;
    public static final AFn const__204;
    public static final Var const__205;
    public static final AFn const__207;
    public static final Var const__208;
    public static final AFn const__210;
    public static final Var const__211;
    public static final AFn const__213;
    public static final Var const__214;
    public static final AFn const__215;
    public static final Var const__216;
    public static final AFn const__218;
    public static final Var const__219;
    public static final AFn const__221;
    public static final Var const__222;
    public static final AFn const__224;
    public static final Var const__225;
    public static final AFn const__226;
    public static final Var const__227;
    public static final Var const__228;
    public static final AFn const__229;
    public static final Var const__230;
    public static final Var const__231;
    public static final AFn const__232;
    public static final Var const__233;
    public static final Var const__234;
    public static final AFn const__236;
    public static final Var const__237;
    public static final AFn const__239;
    public static final Var const__240;
    public static final AFn const__242;
    public static final Var const__243;
    public static final AFn const__245;
    public static final Var const__246;
    public static final AFn const__248;
    public static final Var const__249;
    public static final AFn const__251;
    public static final Var const__252;
    public static final AFn const__254;
    public static final Var const__255;
    public static final AFn const__257;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new common$loading__6434__auto____882()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new common$fn__9011())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = const__4.set((Object)Boolean.TRUE);
        Var var = const__5;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)"_default");
        Var var3 = const__10;
        var3.setMeta((IPersistentMap)const__13);
        Var var4 = var3;
        var3.bindRoot((Object)new common$compare_byte_arrays());
        Var var5 = const__14;
        var5.setMeta((IPersistentMap)const__15);
        Var var6 = var5;
        var5.bindRoot(Class.forName("[B"));
        Var var7 = const__16;
        Var var8 = var7;
        var7.setMeta((IPersistentMap)const__19);
        Var var9 = const__20;
        var9.setMeta((IPersistentMap)const__22);
        Var var10 = var9;
        var9.bindRoot((Object)new common$compare_ex());
        Var var11 = const__23;
        var11.setMeta((IPersistentMap)const__25);
        Var var12 = var11;
        var11.bindRoot((Object)new common$compare());
        Var var13 = const__26;
        var13.setMeta((IPersistentMap)const__28);
        Var var14 = var13;
        var13.bindRoot((Object)new common$equals_with_strict_scale());
        Var var15 = const__29;
        var15.setMeta((IPersistentMap)const__31);
        Var var16 = var15;
        var15.bindRoot((Object)new common$cl());
        Var var17 = const__32;
        var17.setMeta((IPersistentMap)const__34);
        Var var18 = var17;
        var17.bindRoot((Object)new common$cx());
        Var var19 = const__35;
        var19.setMeta((IPersistentMap)const__37);
        Var var20 = var19;
        var19.bindRoot((Object)new common$cc());
        Var var21 = const__16;
        var21.setMeta((IPersistentMap)const__39);
        Var var22 = var21;
        var21.bindRoot((Object)new common$coll_compare());
        Var var23 = const__40;
        var23.setMeta((IPersistentMap)const__42);
        Var var24 = var23;
        var23.bindRoot((Object)new common$_LT__SINGLEQUOTE_());
        Var var25 = const__43;
        var25.setMeta((IPersistentMap)const__45);
        Var var26 = var25;
        var25.bindRoot((Object)new common$_GT__SINGLEQUOTE_());
        Var var27 = const__46;
        var27.setMeta((IPersistentMap)const__48);
        Var var28 = var27;
        var27.bindRoot((Object)new common$split_filter());
        Var var29 = const__49;
        var29.setMeta((IPersistentMap)const__51);
        Var var30 = var29;
        var29.bindRoot((Object)new common$getx());
        Var var31 = const__52;
        var31.setMeta((IPersistentMap)const__54);
        Var var32 = var31;
        var31.bindRoot((Object)new common$getx_in());
        Var var33 = const__55;
        var33.setMeta((IPersistentMap)const__57);
        Var var34 = var33;
        var33.bindRoot((Object)new common$require_keys());
        Var var35 = const__58;
        var35.setMeta((IPersistentMap)const__60);
        Var var36 = var35;
        var35.bindRoot((Object)new common$env_key__GT_clj_key());
        Var var37 = const__61;
        var37.setMeta((IPersistentMap)const__63);
        Var var38 = var37;
        var37.bindRoot((Object)new common$clj_key__GT_env_key());
        Var var39 = const__64;
        var39.setMeta((IPersistentMap)const__66);
        Var var40 = var39;
        var39.bindRoot((Object)new common$map__GT_env());
        Var var41 = const__67;
        var41.setMeta((IPersistentMap)const__69);
        Var var42 = var41;
        var41.bindRoot((Object)new common$map_from_env());
        Var var43 = const__70;
        var43.setMeta((IPersistentMap)const__72);
        Var var44 = var43;
        var43.bindRoot((Object)new common$coerce_args());
        Var var45 = const__73;
        var45.setMeta((IPersistentMap)const__75);
        Var var46 = var45;
        var45.bindRoot((Object)new common$assert_all());
        const__73.setMacro();
        Object v51 = null;
        Var var47 = const__73;
        Var var48 = const__76;
        var48.setMeta((IPersistentMap)const__78);
        Var var49 = var48;
        var48.bindRoot((Object)new common$log_and_print());
        Object object5 = ((IFn)new common$fn__9074()).invoke();
        Object object6 = const__79;
        Object object7 = ((IFn)const__80.getRawRoot()).invoke((Object)const__81, const__82.getRawRoot(), (Object)const__83, null);
        Object object8 = ((IFn)const__84).invoke((Object)const__81, (Object)const__85);
        Object object9 = ((IFn)const__86.getRawRoot()).invoke((Object)const__81, const__87.getRawRoot(), ((IFn)const__82.getRawRoot()).invoke((Object)const__91, (Object)const__92, (Object)const__93, (Object)const__94, (Object)const__81, (Object)const__95, (Object)const__97, (Object)const__98, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__99.getRawRoot()).invoke(const__100.get(), ((IFn)const__101.getRawRoot()).invoke((Object)const__102, ((IFn)const__87.getRawRoot()).invoke((Object)const__103, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__104, const__81})))), new common$fn__9077()})));
        Object object10 = ((IFn)const__105.getRawRoot()).invoke(const__81.getRawRoot());
        AFn aFn = const__106;
        Var var50 = const__107;
        var50.setMeta((IPersistentMap)const__109);
        Var var51 = var50;
        var50.bindRoot((Object)new common$sync_shutdown());
        Var var52 = const__110;
        var52.setMeta((IPersistentMap)const__112);
        Var var53 = var52;
        var52.bindRoot((Object)new common$with_shutdown());
        const__110.setMacro();
        Object v66 = null;
        Var var54 = const__110;
        Var var55 = const__113;
        var55.setMeta((IPersistentMap)const__115);
        Var var56 = var55;
        var55.bindRoot((Object)new common$await_derefs());
        Var var57 = const__116;
        var57.setMeta((IPersistentMap)const__118);
        Var var58 = var57;
        var57.bindRoot((Object)new common$find_free_port());
        Var var59 = const__119;
        var59.setMeta((IPersistentMap)const__121);
        Var var60 = var59;
        var59.bindRoot((Object)new common$array_cat());
        Var var61 = const__122;
        var61.setMeta((IPersistentMap)const__124);
        Var var62 = var61;
        var61.bindRoot((Object)new common$squuid());
        Var var63 = const__125;
        var63.setMeta((IPersistentMap)const__127);
        Var var64 = var63;
        var63.bindRoot((Object)new common$squuid_time_ms());
        Var var65 = const__128;
        var65.setMeta((IPersistentMap)const__130);
        Var var66 = var65;
        var65.bindRoot((Object)new common$rand_uuid());
        Var var67 = const__131;
        var67.setMeta((IPersistentMap)const__132);
        Var var68 = var67;
        var67.bindRoot(((IFn)const__128.getRawRoot()).invoke());
        Var var69 = const__133;
        var69.setMeta((IPersistentMap)const__135);
        Var var70 = var69;
        var69.bindRoot((Object)new common$root_cause());
        Var var71 = const__136;
        var71.setMeta((IPersistentMap)const__138);
        Var var72 = var71;
        var71.bindRoot((Object)new common$qualified_symbol_QMARK_());
        Var var73 = const__139;
        var73.setMeta((IPersistentMap)const__141);
        Var var74 = var73;
        var73.bindRoot((Object)new common$requiring_resolve_BANG_());
        Var var75 = const__142;
        var75.setMeta((IPersistentMap)const__144);
        Var var76 = var75;
        var75.bindRoot((Object)new common$maybe_class());
        Var var77 = const__145;
        var77.setMeta((IPersistentMap)const__147);
        Var var78 = var77;
        var77.bindRoot((Object)new common$maybe_require());
        Var var79 = const__148;
        var79.setMeta((IPersistentMap)const__150);
        Var var80 = var79;
        var79.bindRoot((Object)new common$throw_anom());
        Object v94 = null;
        Var var81 = const__151;
        var81.setMeta((IPersistentMap)const__153);
        Var var82 = var81;
        var81.bindRoot((Object)new common$key_comparator());
        Var var83 = const__154;
        var83.setMeta((IPersistentMap)const__156);
        Var var84 = var83;
        var83.bindRoot((Object)new common$fire());
        const__154.setMacro();
        Object v99 = null;
        Var var85 = const__154;
        Var var86 = const__157;
        var86.setMeta((IPersistentMap)const__159);
        Var var87 = var86;
        var86.bindRoot((Object)new common$schedule());
        Var var88 = const__160;
        var88.setMeta((IPersistentMap)const__162);
        Var var89 = var88;
        var88.bindRoot((Object)new common$mapk());
        Var var90 = const__163;
        var90.setMeta((IPersistentMap)const__165);
        Var var91 = var90;
        var90.bindRoot((Object)new common$returning_throwable());
        const__163.setMacro();
        Object v107 = null;
        Var var92 = const__163;
        Var var93 = const__166;
        var93.setMeta((IPersistentMap)const__168);
        Var var94 = var93;
        var93.bindRoot((Object)new common$log_retry());
        Var var95 = const__169;
        var95.setMeta((IPersistentMap)const__171);
        Var var96 = var95;
        var95.bindRoot((Object)new common$return_or_throw());
        Var var97 = const__172;
        var97.setMeta((IPersistentMap)const__174);
        Var var98 = var97;
        var97.bindRoot((Object)new common$with_nano_time());
        const__172.setMacro();
        Object v115 = null;
        Var var99 = const__172;
        Var var100 = const__175;
        var100.setMeta((IPersistentMap)const__177);
        Var var101 = var100;
        var100.bindRoot((Object)new common$retry_fn());
        Var var102 = const__178;
        var102.setMeta((IPersistentMap)const__180);
        Var var103 = var102;
        var102.bindRoot((Object)new common$create_temp_directory());
        Var var104 = const__181;
        var104.setMeta((IPersistentMap)const__183);
        Var var105 = var104;
        var104.bindRoot((Object)new common$delete_file_recursively());
        Var var106 = const__184;
        var106.setMeta((IPersistentMap)const__186);
        Var var107 = var106;
        var106.bindRoot((Object)new common$bean_setters());
        Var var108 = const__187;
        var108.setMeta((IPersistentMap)const__189);
        Var var109 = var108;
        var108.bindRoot((Object)new common$into_bean());
        Var var110 = const__190;
        var110.setMeta((IPersistentMap)const__192);
        Var var111 = var110;
        var110.bindRoot((Object)new common$endpoint_QMARK_());
        Var var112 = const__193;
        var112.setMeta((IPersistentMap)const__195);
        Var var113 = var112;
        var112.bindRoot((Object)new common$qualified_name());
        Var var114 = const__196;
        var114.setMeta((IPersistentMap)const__198);
        Var var115 = var114;
        var114.bindRoot((Object)new common$force_keyword());
        Var var116 = const__199;
        var116.setMeta((IPersistentMap)const__201);
        Var var117 = var116;
        var116.bindRoot((Object)new common$force_map_keywords());
        Var var118 = const__202;
        var118.setMeta((IPersistentMap)const__204);
        Var var119 = var118;
        var118.bindRoot((Object)new common$load_properties());
        Var var120 = const__205;
        var120.setMeta((IPersistentMap)const__207);
        Var var121 = var120;
        var120.bindRoot((Object)new common$store_properties());
        Var var122 = const__208;
        var122.setMeta((IPersistentMap)const__210);
        Var var123 = var122;
        var122.bindRoot((Object)new common$map__GT_props());
        Var var124 = const__211;
        var124.setMeta((IPersistentMap)const__213);
        Var var125 = var124;
        var124.bindRoot((Object)new common$props__GT_map());
        Var var126 = const__214;
        var126.setMeta((IPersistentMap)const__215);
        Var var127 = var126;
        var126.bindRoot((Object)"probe-fa35e6c5-a886-46e7-b90b-1f0d36b3f2fe");
        Var var128 = const__216;
        var128.setMeta((IPersistentMap)const__218);
        Var var129 = var128;
        var128.bindRoot((Object)new common$pop_atom_BANG_());
        Var var130 = const__219;
        var130.setMeta((IPersistentMap)const__221);
        Var var131 = var130;
        var130.bindRoot((Object)new common$closing_watch());
        Var var132 = const__222;
        var132.setMeta((IPersistentMap)const__224);
        Var var133 = var132;
        var132.bindRoot((Object)new common$pfuture());
        Var var134 = const__225;
        var134.setMeta((IPersistentMap)const__226);
        Var var135 = var134;
        var134.bindRoot(const__227.getRawRoot());
        Var var136 = const__228;
        var136.setMeta((IPersistentMap)const__229);
        Var var137 = var136;
        var136.bindRoot(const__230.getRawRoot());
        Var var138 = const__231;
        var138.setMeta((IPersistentMap)const__232);
        Var var139 = var138;
        var138.bindRoot(const__233.getRawRoot());
        Var var140 = const__234;
        var140.setMeta((IPersistentMap)const__236);
        Var var141 = var140;
        var140.bindRoot((Object)new common$bounded_deref());
        Var var142 = const__237;
        var142.setMeta((IPersistentMap)const__239);
        Var var143 = var142;
        var142.bindRoot((Object)new common$pooled_mapv());
        Var var144 = const__240;
        var144.setMeta((IPersistentMap)const__242);
        Var var145 = var144;
        var144.bindRoot((Object)new common$distinct_by());
        Var var146 = const__243;
        var146.setMeta((IPersistentMap)const__245);
        Var var147 = var146;
        var146.bindRoot((Object)new common$ensure_vector());
        Var var148 = const__246;
        var148.setMeta((IPersistentMap)const__248);
        Var var149 = var148;
        var148.bindRoot((Object)new common$ensure_vectors_in_array());
        Var var150 = const__249;
        var150.setMeta((IPersistentMap)const__251);
        Var var151 = var150;
        var150.bindRoot((Object)new common$maybe_deref());
        Var var152 = const__252;
        var152.setMeta((IPersistentMap)const__254);
        Var var153 = var152;
        var152.bindRoot((Object)new common$result_count());
        Var var154 = const__255;
        var154.setMeta((IPersistentMap)const__257);
        Var var155 = var154;
        var154.bindRoot((Object)new common$result_xform());
        Object v173 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.common");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"clojure.core", (String)"*unchecked-math*");
        const__5 = RT.var((String)"datomic.common", (String)"DEFAULT_SYSTEM_NAME");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"datomic.common", (String)"compare-byte-arrays");
        const__13 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__14 = RT.var((String)"datomic.common", (String)"BYTES");
        const__15 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__16 = RT.var((String)"datomic.common", (String)"coll-compare");
        const__19 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__20 = RT.var((String)"datomic.common", (String)"compare-ex");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"a")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})), (Object)((IObj)Symbol.intern(null, (String)"b")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__23 = RT.var((String)"datomic.common", (String)"compare");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"a")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})), (Object)((IObj)Symbol.intern(null, (String)"b")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__26 = RT.var((String)"datomic.common", (String)"equals-with-strict-scale");
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b")))), RT.keyword(null, (String)"column"), 1});
        const__29 = RT.var((String)"datomic.common", (String)"cl");
        const__31 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"a")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"List")})), (Object)((IObj)Symbol.intern(null, (String)"b")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"List")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__32 = RT.var((String)"datomic.common", (String)"cx");
        const__34 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__35 = RT.var((String)"datomic.common", (String)"cc");
        const__37 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"a")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})), (Object)((IObj)Symbol.intern(null, (String)"b")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Object")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__40 = RT.var((String)"datomic.common", (String)"<'");
        const__42 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b")))), RT.keyword(null, (String)"column"), 1});
        const__43 = RT.var((String)"datomic.common", (String)">'");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"b")))), RT.keyword(null, (String)"column"), 1});
        const__46 = RT.var((String)"datomic.common", (String)"split-filter");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__49 = RT.var((String)"datomic.common", (String)"getx");
        const__51 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__52 = RT.var((String)"datomic.common", (String)"getx-in");
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m"), (Object)Symbol.intern(null, (String)"ks")))), RT.keyword(null, (String)"column"), 1});
        const__55 = RT.var((String)"datomic.common", (String)"require-keys");
        const__57 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m"), (Object)Symbol.intern(null, (String)"keyseq")))), RT.keyword(null, (String)"column"), 1});
        const__58 = RT.var((String)"datomic.common", (String)"env-key->clj-key");
        const__60 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__61 = RT.var((String)"datomic.common", (String)"clj-key->env-key");
        const__63 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__64 = RT.var((String)"datomic.common", (String)"map->env");
        const__66 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__67 = RT.var((String)"datomic.common", (String)"map-from-env");
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"env")))), RT.keyword(null, (String)"column"), 1});
        const__70 = RT.var((String)"datomic.common", (String)"coerce-args");
        const__72 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"predfns")))), RT.keyword(null, (String)"column"), 1});
        const__73 = RT.var((String)"datomic.common", (String)"assert-all");
        const__75 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__76 = RT.var((String)"datomic.common", (String)"log-and-print");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"xs")))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.classForName((String)"datomic.common.AsyncShutdown");
        const__80 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__81 = RT.var((String)"datomic.common", (String)"AsyncShutdown");
        const__82 = RT.var((String)"clojure.core", (String)"assoc");
        const__83 = RT.keyword(null, (String)"doc");
        const__84 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__85 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"async-shutdown")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))}))));
        const__86 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__87 = RT.var((String)"clojure.core", (String)"merge");
        const__91 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.common.AsyncShutdown"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.common.AsyncShutdown")});
        const__92 = RT.keyword(null, (String)"sigs");
        const__93 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"async-shutdown"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"async-shutdown")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"doc"), "Returns an IBlockingDeref that will deref to some true value on successful\n    shutdown, or to a Throwable if shutdown is known to have failed."})});
        const__94 = RT.keyword(null, (String)"var");
        const__95 = RT.keyword(null, (String)"method-map");
        const__97 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"async-shutdown"), RT.keyword(null, (String)"async-shutdown")});
        const__98 = RT.keyword(null, (String)"method-builders");
        const__99 = RT.var((String)"clojure.core", (String)"intern");
    }

    public static void __init1() {
        const__100 = RT.var((String)"clojure.core", (String)"*ns*");
        const__101 = RT.var((String)"clojure.core", (String)"with-meta");
        const__102 = (AFn)((IObj)Symbol.intern(null, (String)"async-shutdown")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))}));
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"async-shutdown")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"doc"), "Returns an IBlockingDeref that will deref to some true value on successful\n    shutdown, or to a Throwable if shutdown is known to have failed."});
        const__104 = RT.keyword(null, (String)"protocol");
        const__105 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__106 = (AFn)Symbol.intern(null, (String)"AsyncShutdown");
        const__107 = RT.var((String)"datomic.common", (String)"sync-shutdown");
        const__109 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__110 = RT.var((String)"datomic.common", (String)"with-shutdown");
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bindings"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__113 = RT.var((String)"datomic.common", (String)"await-derefs");
        const__115 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coll")), Tuple.create((Object)Symbol.intern(null, (String)"msec"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__116 = RT.var((String)"datomic.common", (String)"find-free-port");
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__119 = RT.var((String)"datomic.common", (String)"array-cat");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Tuple.create((Object)Symbol.intern(null, (String)"a"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"as"))))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.common", (String)"squuid");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.common", (String)"squuid-time-ms");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"squuid")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.util.UUID")}))))), RT.keyword(null, (String)"column"), 1});
        const__128 = RT.var((String)"datomic.common", (String)"rand-uuid");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__131 = RT.var((String)"datomic.common", (String)"run-uuid");
        const__132 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__133 = RT.var((String)"datomic.common", (String)"root-cause");
        const__135 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"x")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Throwable")}))))), RT.keyword(null, (String)"column"), 1});
        const__136 = RT.var((String)"datomic.common", (String)"qualified-symbol?");
        const__138 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__139 = RT.var((String)"datomic.common", (String)"requiring-resolve!");
        const__141 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__142 = RT.var((String)"datomic.common", (String)"maybe-class");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cls")))), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.common", (String)"maybe-require");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ns"), (Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.common", (String)"throw-anom");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"anom")))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.common", (String)"key-comparator");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"key-fn")), Tuple.create((Object)Symbol.intern(null, (String)"key-fn"), (Object)((IObj)Symbol.intern(null, (String)"comp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Comparator")}))))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.common", (String)"fire");
        const__156 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__157 = RT.var((String)"datomic.common", (String)"schedule");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"taskname"), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"msec"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"once"))}))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.io.Closeable")})))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.common", (String)"mapk");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__163 = RT.var((String)"datomic.common", (String)"returning-throwable");
        const__165 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"forms")))), RT.keyword(null, (String)"column"), 1});
        const__166 = RT.var((String)"datomic.common", (String)"log-retry");
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"result"), (Object)Symbol.intern(null, (String)"backoff"), (Object)Symbol.intern(null, (String)"attempts"), (Object)Symbol.intern(null, (String)"max-retries")))), RT.keyword(null, (String)"column"), 1});
        const__169 = RT.var((String)"datomic.common", (String)"return-or-throw");
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__172 = RT.var((String)"datomic.common", (String)"with-nano-time");
        const__174 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__175 = RT.var((String)"datomic.common", (String)"retry-fn");
        const__177 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"backoff"), (Object)Symbol.intern(null, (String)"max-retries"), (Object)Symbol.intern(null, (String)"log-retry"))})))), RT.keyword(null, (String)"column"), 1});
        const__178 = RT.var((String)"datomic.common", (String)"create-temp-directory");
        const__180 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dir")))), RT.keyword(null, (String)"column"), 1});
        const__181 = RT.var((String)"datomic.common", (String)"delete-file-recursively");
        const__183 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"&"), (Object)Tuple.create((Object)Symbol.intern(null, (String)"silently"))))), RT.keyword(null, (String)"column"), 1});
        const__184 = RT.var((String)"datomic.common", (String)"bean-setters");
        const__186 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean-class")))), RT.keyword(null, (String)"column"), 1});
        const__187 = RT.var((String)"datomic.common", (String)"into-bean");
        const__189 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean"), (Object)Symbol.intern(null, (String)"props")))), RT.keyword(null, (String)"column"), 1});
        const__190 = RT.var((String)"datomic.common", (String)"endpoint?");
        const__192 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__193 = RT.var((String)"datomic.common", (String)"qualified-name");
        const__195 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"k")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"clojure.lang.Keyword")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.lang.String")})))), RT.keyword(null, (String)"column"), 1});
        const__196 = RT.var((String)"datomic.common", (String)"force-keyword");
        const__198 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__199 = RT.var((String)"datomic.common", (String)"force-map-keywords");
    }

    public static void __init2() {
        const__201 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__202 = RT.var((String)"datomic.common", (String)"load-properties");
        const__204 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"filename")))), RT.keyword(null, (String)"column"), 1});
        const__205 = RT.var((String)"datomic.common", (String)"store-properties");
        const__207 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"props")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Properties")})), (Object)Symbol.intern(null, (String)"filename")))), RT.keyword(null, (String)"column"), 1});
        const__208 = RT.var((String)"datomic.common", (String)"map->props");
        const__210 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__211 = RT.var((String)"datomic.common", (String)"props->map");
        const__213 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"props")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Properties")}))))), RT.keyword(null, (String)"column"), 1});
        const__214 = RT.var((String)"datomic.common", (String)"probe-name");
        const__215 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__216 = RT.var((String)"datomic.common", (String)"pop-atom!");
        const__218 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"atm")))), RT.keyword(null, (String)"column"), 1});
        const__219 = RT.var((String)"datomic.common", (String)"closing-watch");
        const__221 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"_"), (Object)((IObj)Symbol.intern(null, (String)"old")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.lang.AutoCloseable")})), (Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"column"), 1});
        const__222 = RT.var((String)"datomic.common", (String)"pfuture");
        const__224 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"exec")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ExecutorService")})), (Object)((IObj)Symbol.intern(null, (String)"f")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.util.concurrent.Callable")}))))), RT.keyword(null, (String)"column"), 1});
        const__225 = RT.var((String)"datomic.common", (String)"thread-pool");
        const__226 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__227 = RT.var((String)"datomic.core2.thread", (String)"thread-pool");
        const__228 = RT.var((String)"datomic.common", (String)"handoff-thread-pool");
        const__229 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__230 = RT.var((String)"datomic.core2.thread", (String)"handoff-thread-pool");
        const__231 = RT.var((String)"datomic.common", (String)"cached-thread-pool");
        const__232 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__233 = RT.var((String)"datomic.core2.thread", (String)"cached-thread-pool");
        const__234 = RT.var((String)"datomic.common", (String)"bounded-deref");
        const__236 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ref"), (Object)Symbol.intern(null, (String)"timeout-ms")))), RT.keyword(null, (String)"column"), 1});
        const__237 = RT.var((String)"datomic.common", (String)"pooled-mapv");
        const__239 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"exec")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ExecutorService")})), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__240 = RT.var((String)"datomic.common", (String)"distinct-by");
        const__242 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f")), Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__243 = RT.var((String)"datomic.common", (String)"ensure-vector");
        const__245 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__246 = RT.var((String)"datomic.common", (String)"ensure-vectors-in-array");
        const__248 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"vs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")}))))), RT.keyword(null, (String)"column"), 1});
        const__249 = RT.var((String)"datomic.common", (String)"maybe-deref");
        const__251 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"v")))), RT.keyword(null, (String)"column"), 1});
        const__252 = RT.var((String)"datomic.common", (String)"result-count");
        const__254 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"offset"), (Object)Symbol.intern(null, (String)"limit"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__255 = RT.var((String)"datomic.common", (String)"result-xform");
        const__257 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"offset"), (Object)Symbol.intern(null, (String)"limit"), (Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        common__init.__init0();
        common__init.__init1();
        common__init.__init2();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.common__init").getClassLoader());
        try {
            common__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

