/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.Delay
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.Numbers
 *  clojure.lang.PersistentHashSet
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.Delay;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.Numbers;
import clojure.lang.PersistentHashSet;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.config$at_least;
import datomic.config$bool_QMARK_;
import datomic.config$ddb_client_args;
import datomic.config$fn__714;
import datomic.config$fn__721;
import datomic.config$fn__724;
import datomic.config$fn__735;
import datomic.config$fn__746;
import datomic.config$fn__748;
import datomic.config$fn__750;
import datomic.config$fn__752;
import datomic.config$fn__785;
import datomic.config$fn__789;
import datomic.config$fn__791;
import datomic.config$fn__793;
import datomic.config$fn__795;
import datomic.config$fn__797;
import datomic.config$fn__799;
import datomic.config$fn__801;
import datomic.config$fn__803;
import datomic.config$fn__805;
import datomic.config$fn__807;
import datomic.config$fn__809;
import datomic.config$fn__813;
import datomic.config$fn__816;
import datomic.config$fn__820;
import datomic.config$fn__822;
import datomic.config$fn__826;
import datomic.config$fn__829;
import datomic.config$fn__831;
import datomic.config$fn__833;
import datomic.config$fn__835;
import datomic.config$fn__846;
import datomic.config$fn__855;
import datomic.config$fn__859;
import datomic.config$fn__861;
import datomic.config$fn__863;
import datomic.config$fn__865;
import datomic.config$fn__867;
import datomic.config$fn__879;
import datomic.config$folsom_QMARK_;
import datomic.config$in_range;
import datomic.config$limited_edition_QMARK_;
import datomic.config$loading__6434__auto____626;
import datomic.config$local_memcached_args;
import datomic.config$local_valcache_enabled_QMARK_;
import datomic.config$max_gb__GT_eviction_threshold_mb;
import datomic.config$memcached_args;
import datomic.config$parse_memory_string;
import datomic.config$prefetch_enabled_QMARK_;
import datomic.config$pro_QMARK_;
import datomic.config$property;
import datomic.config$property_map;
import datomic.config$protocol_supports_ha_QMARK_;
import datomic.config$read_revision;
import datomic.config$read_system_property;
import datomic.config$reset_BANG_;
import datomic.config$s3_client_args;
import datomic.config$set_pro;
import datomic.config$valcache_args;
import datomic.config$validate_properties;
import datomic.config$version;
import datomic.config$version_unique;
import datomic.config$warn_deprecations;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class config__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Object const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final Var const__13;
    public static final Keyword const__14;
    public static final Var const__15;
    public static final ISeq const__16;
    public static final Var const__17;
    public static final Var const__18;
    public static final AFn const__22;
    public static final Keyword const__23;
    public static final AFn const__24;
    public static final Keyword const__25;
    public static final Keyword const__26;
    public static final Keyword const__27;
    public static final Keyword const__28;
    public static final AFn const__29;
    public static final Keyword const__30;
    public static final Var const__31;
    public static final Var const__32;
    public static final Var const__33;
    public static final AFn const__34;
    public static final AFn const__35;
    public static final Keyword const__36;
    public static final AFn const__37;
    public static final AFn const__38;
    public static final Var const__39;
    public static final AFn const__40;
    public static final Var const__41;
    public static final Object const__42;
    public static final Object const__43;
    public static final Var const__44;
    public static final AFn const__45;
    public static final Keyword const__46;
    public static final Var const__47;
    public static final AFn const__49;
    public static final Var const__50;
    public static final AFn const__52;
    public static final Var const__53;
    public static final AFn const__55;
    public static final Var const__56;
    public static final AFn const__58;
    public static final Var const__59;
    public static final AFn const__61;
    public static final Var const__62;
    public static final AFn const__64;
    public static final Object const__65;
    public static final Var const__66;
    public static final AFn const__68;
    public static final Var const__69;
    public static final AFn const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final AFn const__78;
    public static final Var const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__84;
    public static final Var const__85;
    public static final AFn const__87;
    public static final Var const__88;
    public static final AFn const__89;
    public static final Var const__90;
    public static final Object const__91;
    public static final Object const__92;
    public static final Var const__93;
    public static final Object const__95;
    public static final Object const__96;
    public static final Object const__97;
    public static final Var const__98;
    public static final Keyword const__99;
    public static final Object const__100;
    public static final Var const__101;
    public static final Object const__102;
    public static final Var const__103;
    public static final Var const__104;
    public static final AFn const__105;
    public static final Object const__106;
    public static final Object const__107;
    public static final Object const__108;
    public static final Object const__109;
    public static final Object const__110;
    public static final Object const__111;
    public static final Object const__112;
    public static final Object const__113;
    public static final Object const__114;
    public static final Object const__115;
    public static final Object const__119;
    public static final Object const__122;
    public static final Object const__123;
    public static final Object const__124;
    public static final Object const__125;
    public static final Var const__126;
    public static final Var const__131;
    public static final Var const__132;
    public static final Var const__133;
    public static final Var const__134;
    public static final Object const__137;
    public static final Object const__138;
    public static final Var const__139;
    public static final AFn const__141;
    public static final Var const__142;
    public static final AFn const__143;
    public static final Var const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__149;
    public static final Var const__150;
    public static final AFn const__152;
    public static final Var const__153;
    public static final AFn const__155;
    public static final Var const__156;
    public static final AFn const__158;
    public static final Var const__159;
    public static final Keyword const__160;
    public static final Keyword const__161;
    public static final Keyword const__162;
    public static final Keyword const__163;
    public static final Var const__164;
    public static final AFn const__165;
    public static final Var const__166;
    public static final AFn const__168;
    public static final Var const__169;
    public static final AFn const__171;
    public static final Var const__172;
    public static final AFn const__174;
    public static final Var const__175;
    public static final AFn const__177;
    public static final Var const__178;
    public static final AFn const__180;
    public static final Var const__181;
    public static final AFn const__183;
    public static final Var const__184;
    public static final AFn const__186;
    public static final Var const__187;
    public static final AFn const__188;
    public static final Var const__189;
    public static final AFn const__191;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new config$loading__6434__auto____626()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new config$fn__714())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new config$protocol_supports_ha_QMARK_());
        Object object4 = ((IFn)new config$fn__721()).invoke();
        Object object5 = const__10;
        Object object6 = ((IFn)const__11.getRawRoot()).invoke((Object)const__12, const__13.getRawRoot(), (Object)const__14, null);
        Object object7 = ((IFn)const__15).invoke((Object)const__12, (Object)const__16);
        Object object8 = ((IFn)const__17.getRawRoot()).invoke((Object)const__12, const__18.getRawRoot(), ((IFn)const__13.getRawRoot()).invoke((Object)const__22, (Object)const__23, (Object)const__24, (Object)const__25, (Object)const__12, (Object)const__26, (Object)const__29, (Object)const__30, (Object)RT.map((Object[])new Object[]{((IFn)const__31.getRawRoot()).invoke(const__32.get(), ((IFn)const__33.getRawRoot()).invoke((Object)const__34, ((IFn)const__18.getRawRoot()).invoke((Object)const__35, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__36, const__12})))), new config$fn__724(), ((IFn)const__31.getRawRoot()).invoke(const__32.get(), ((IFn)const__33.getRawRoot()).invoke((Object)const__37, ((IFn)const__18.getRawRoot()).invoke((Object)const__38, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__36, const__12})))), new config$fn__735()})));
        Object object9 = ((IFn)const__39.getRawRoot()).invoke(const__12.getRawRoot());
        AFn aFn = const__40;
        Object object10 = ((IFn)const__41.getRawRoot()).invoke(null, const__12.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__27, new config$fn__746()}));
        Object object11 = ((IFn)const__41.getRawRoot()).invoke(const__42, const__12.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__27, new config$fn__748()}));
        Object object12 = ((IFn)const__41.getRawRoot()).invoke(const__43, const__12.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__27, new config$fn__750(), const__28, new config$fn__752()}));
        Var var3 = const__44;
        var3.setMeta((IPersistentMap)const__45);
        Var var4 = var3;
        var3.bindRoot((Object)const__46);
        Var var5 = const__47;
        var5.setMeta((IPersistentMap)const__49);
        Var var6 = var5;
        var5.bindRoot((Object)new config$set_pro());
        Var var7 = const__50;
        var7.setMeta((IPersistentMap)const__52);
        Var var8 = var7;
        var7.bindRoot((Object)new config$pro_QMARK_());
        Var var9 = const__53;
        var9.setMeta((IPersistentMap)const__55);
        Var var10 = var9;
        var9.bindRoot((Object)new config$limited_edition_QMARK_());
        Var var11 = const__56;
        var11.setMeta((IPersistentMap)const__58);
        Var var12 = var11;
        var11.bindRoot((Object)new config$parse_memory_string());
        Var var13 = const__59;
        var13.setMeta((IPersistentMap)const__61);
        Var var14 = var13;
        var13.bindRoot((Object)new config$read_system_property());
        Var var15 = const__62;
        var15.setMeta((IPersistentMap)const__64);
        Var var16 = var15;
        var15.bindRoot(const__65);
        Var var17 = const__66;
        var17.setMeta((IPersistentMap)const__68);
        Var var18 = var17;
        var17.bindRoot((Object)new config$at_least());
        Var var19 = const__69;
        var19.setMeta((IPersistentMap)const__71);
        Var var20 = var19;
        var19.bindRoot((Object)new config$in_range());
        Var var21 = const__72;
        var21.setMeta((IPersistentMap)const__74);
        Var var22 = var21;
        var21.bindRoot((Object)new config$warn_deprecations());
        Var var23 = const__75;
        var23.setMeta((IPersistentMap)const__78);
        Var var24 = var23;
        var23.bindRoot((Object)new config$version());
        Var var25 = const__79;
        var25.setMeta((IPersistentMap)const__81);
        Var var26 = var25;
        var25.bindRoot((Object)new config$version_unique());
        Var var27 = const__82;
        var27.setMeta((IPersistentMap)const__84);
        Var var28 = var27;
        var27.bindRoot((Object)new config$read_revision());
        Var var29 = const__85;
        var29.setMeta((IPersistentMap)const__87);
        Var var30 = var29;
        var29.bindRoot((Object)new config$bool_QMARK_());
        Var var31 = const__88;
        var31.setMeta((IPersistentMap)const__89);
        Var var32 = var31;
        Object[] objectArray = new Object[79];
        objectArray[0] = Tuple.create((Object)"datomic.heartbeatIntervalMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__91), (Object)const__92);
        objectArray[1] = Tuple.create((Object)"datomic.readAheadPool", (Object)((Object)new config$fn__785()), (Object)const__93.getRawRoot(), (Object)Numbers.num((long)Numbers.add((long)2L, (long)Runtime.getRuntime().availableProcessors())));
        objectArray[2] = Tuple.create((Object)"datomic.queryPool", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__96);
        objectArray[3] = Tuple.create((Object)"datomic.externalSortPool", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__789()), (Object)const__97);
        objectArray[4] = Tuple.create((Object)"datomic.defaultPartition", (Object)const__90.getRawRoot(), (Object)const__98.getRawRoot(), (Object)const__99);
        objectArray[5] = Tuple.create((Object)"datomic.indexMetrics", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.TRUE);
        objectArray[6] = Tuple.create((Object)"datomic.pingPort", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__100), null);
        objectArray[7] = Tuple.create((Object)"datomic.pingHost", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[8] = Tuple.create((Object)"datomic.pingConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), null);
        objectArray[9] = Tuple.create((Object)"datomic.printConnectionInfo", (Object)const__90.getRawRoot(), (Object)((IFn)const__103.getRawRoot()).invoke(const__104.getRawRoot(), (Object)const__105), (Object)Boolean.FALSE);
        objectArray[10] = Tuple.create((Object)"datomic.writeConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__97);
        objectArray[11] = Tuple.create((Object)"datomic.efsWritePool", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__106);
        objectArray[12] = Tuple.create((Object)"datomic.efsDeletePool", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__107);
        objectArray[13] = Tuple.create((Object)"datomic.deleteConcurrency", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__791()), (Object)const__102);
        objectArray[14] = Tuple.create((Object)"datomic.backupPaceMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__108), null);
        objectArray[15] = Tuple.create((Object)"datomic.gcStoragePaceMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__108), null);
        objectArray[16] = Tuple.create((Object)"datomic.podGcDelayMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), (Object)const__109);
        objectArray[17] = Tuple.create((Object)"datomic.fileBackupConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__108);
        objectArray[18] = Tuple.create((Object)"datomic.sqlValidationQuery", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[19] = Tuple.create((Object)"datomic.backupBranchConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), (Object)const__96);
        objectArray[20] = Tuple.create((Object)"datomic.s3BackupConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__110);
        objectArray[21] = Tuple.create((Object)"datomic.s3MaxRetries", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__111);
        objectArray[22] = Tuple.create((Object)"datomic.s3RetryBaseDelay", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)const__112);
        objectArray[23] = Tuple.create((Object)"datomic.backupUseSegsetStorage", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.TRUE);
        objectArray[24] = Tuple.create((Object)"datomic.readConcurrency", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__95), (Object)((Object)new config$fn__793()));
        objectArray[25] = Tuple.create((Object)"datomic.ddbRequestTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)const__114);
        objectArray[26] = Tuple.create((Object)"datomic.ddbSocketTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__795()));
        objectArray[27] = Tuple.create((Object)"datomic.ddbClientExecutionTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__797()));
        objectArray[28] = Tuple.create((Object)"datomic.ddbConnectionTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__799()));
        objectArray[29] = Tuple.create((Object)"datomic.s3RequestTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)const__115);
        objectArray[30] = Tuple.create((Object)"datomic.s3SocketTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__801()));
        objectArray[31] = Tuple.create((Object)"datomic.s3ClientExecutionTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__803()));
        objectArray[32] = Tuple.create((Object)"datomic.s3ConnectionTimeout", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__113), (Object)((Object)new config$fn__805()));
        objectArray[33] = Tuple.create((Object)"datomic.memoryIndexMax", (Object)const__56.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke((Object)Numbers.num((long)Numbers.multiply((long)Numbers.multiply((long)32L, (long)1024L), (long)1024L))), (Object)const__65);
        objectArray[34] = Tuple.create((Object)"datomic.memoryIndexThreshold", (Object)const__56.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke((Object)Numbers.num((long)Numbers.multiply((long)Numbers.multiply((long)8L, (long)1024L), (long)1024L))), (Object)((Object)new config$fn__807()));
        objectArray[35] = Tuple.create((Object)"datomic.allowLogOverlap", (Object)const__90.getRawRoot(), (Object)const__93.getRawRoot(), (Object)Boolean.FALSE);
        objectArray[36] = Tuple.create((Object)"datomic.luceneLogFile", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[37] = Tuple.create((Object)"datomic.pidFile", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[38] = Tuple.create((Object)"datomic.peerConnectionTTLMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__122), (Object)const__123);
        objectArray[39] = Tuple.create((Object)"datomic.txTimeoutMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__100), (Object)const__124);
        objectArray[40] = Tuple.create((Object)"datomic.memcachedExpirationDays", (Object)const__90.getRawRoot(), (Object)((IFn)const__69.getRawRoot()).invoke(const__100, const__125), (Object)const__125);
        objectArray[41] = Tuple.create((Object)"datomic.localMemcachedServers", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[42] = Tuple.create((Object)"datomic.localMemcachedUsername", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[43] = Tuple.create((Object)"datomic.localMemcachedPassword", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[44] = Tuple.create((Object)"datomic.localMemcachedAutoDiscovery", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.FALSE);
        objectArray[45] = Tuple.create((Object)"datomic.localMemcachedConfigTimeoutMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), (Object)const__112);
        objectArray[46] = Tuple.create((Object)"datomic.memcachedServers", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[47] = Tuple.create((Object)"datomic.memcachedUsername", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[48] = Tuple.create((Object)"datomic.memcachedPassword", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[49] = Tuple.create((Object)"datomic.memcachedAutoDiscovery", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.FALSE);
        objectArray[50] = Tuple.create((Object)"datomic.memcachedConfigTimeoutMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), (Object)const__112);
        objectArray[51] = Tuple.create((Object)"datomic.dataDir", (Object)const__126.getRawRoot(), (Object)const__93.getRawRoot(), (Object)((IFn)const__126.getRawRoot()).invoke((Object)"./data"));
        objectArray[52] = Tuple.create((Object)"datomic.exciseIOParallelism", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__809()), (Object)const__112);
        objectArray[53] = Tuple.create((Object)"datomic.dynamicIndexParallelism", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.FALSE);
        objectArray[54] = Tuple.create((Object)"datomic.indexSegsPerSecond", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__813()), null);
        objectArray[55] = Tuple.create((Object)"datomic.indexParallelism", (Object)const__90.getRawRoot(), (Object)((IFn)const__69.getRawRoot()).invoke(const__102, const__119), (Object)const__102);
        objectArray[56] = Tuple.create((Object)"datomic.indexIOParallelism", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__816()), (Object)const__112);
        objectArray[57] = Tuple.create((Object)"datomic.indexWorkDir", (Object)const__126.getRawRoot(), (Object)const__93.getRawRoot(), (Object)((Object)new config$fn__820()));
        objectArray[58] = Tuple.create((Object)"datomic.objectCacheMax", (Object)const__56.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke((Object)Numbers.num((long)Numbers.multiply((long)Numbers.multiply((long)32L, (long)1024L), (long)1024L))), (Object)Numbers.num((long)Math.round(Numbers.multiply((double)0.5, (long)Runtime.getRuntime().maxMemory()))));
        objectArray[59] = Tuple.create((Object)"datomic.version", (Object)((IFn)const__131.getRawRoot()).invoke(((IFn)const__75.getRawRoot()).invoke()), (Object)const__101.getRawRoot(), (Object)((IFn)const__131.getRawRoot()).invoke(((IFn)const__75.getRawRoot()).invoke()));
        objectArray[60] = Tuple.create((Object)"datomic.versionUnique", (Object)((IFn)const__131.getRawRoot()).invoke(((IFn)const__79.getRawRoot()).invoke()), (Object)const__101.getRawRoot(), (Object)((IFn)const__131.getRawRoot()).invoke(((IFn)const__79.getRawRoot()).invoke()));
        objectArray[61] = Tuple.create((Object)"datomic.buildRevision", (Object)const__82.getRawRoot(), (Object)const__93.getRawRoot(), (Object)const__82.getRawRoot());
        objectArray[62] = Tuple.create((Object)"datomic.cloudwatchName", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[63] = Tuple.create((Object)"datomic.cloudwatchAccessKeyId", (Object)const__90.getRawRoot(), (Object)const__132.getRawRoot(), null);
        objectArray[64] = Tuple.create((Object)"datomic.cloudwatchSecretKey", (Object)const__90.getRawRoot(), (Object)const__132.getRawRoot(), null);
        objectArray[65] = Tuple.create((Object)"datomic.cloudwatchDimension", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[66] = Tuple.create((Object)"datomic.cloudwatchRegion", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[67] = Tuple.create((Object)"datomic.metricsCallback", (Object)const__90.getRawRoot(), (Object)const__133.getRawRoot(), (Object)((Object)new config$fn__822()));
        objectArray[68] = Tuple.create((Object)"datomic.cassandraClusterCallback", (Object)const__90.getRawRoot(), (Object)const__133.getRawRoot(), null);
        objectArray[69] = Tuple.create((Object)"datomic.indexDirScale", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__826()), (Object)const__102);
        objectArray[70] = Tuple.create((Object)"datomic.valcachePutsPool", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__829()), (Object)const__97);
        objectArray[71] = Tuple.create((Object)"datomic.valcachePath", (Object)const__93.getRawRoot(), (Object)const__101.getRawRoot(), null);
        objectArray[72] = Tuple.create((Object)"datomic.valcacheMaxGb", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__102), null);
        objectArray[73] = Tuple.create((Object)"datomic.useIndexArrayCaches", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)Boolean.TRUE);
        objectArray[74] = Tuple.create((Object)"datomic.prefetchConcurrency", (Object)const__90.getRawRoot(), (Object)const__134.getRawRoot(), (Object)Numbers.num((long)Numbers.max((long)((long)Runtime.getRuntime().availableProcessors() / 2L), (long)1L)));
        objectArray[75] = Tuple.create((Object)"datomic.prefetchProbes", (Object)const__90.getRawRoot(), (Object)const__85.getRawRoot(), (Object)((Object)new config$fn__831()));
        objectArray[76] = Tuple.create((Object)"datomic.memcachedLib", (Object)const__93.getRawRoot(), (Object)((Object)new config$fn__833()), (Object)"spy");
        objectArray[77] = Tuple.create((Object)"datomic.memcachedGetTimeoutMsec", (Object)const__90.getRawRoot(), (Object)((IFn)const__66.getRawRoot()).invoke(const__108), (Object)const__137);
        objectArray[78] = Tuple.create((Object)"datomic.memcachedRepairFromSpyRatio", (Object)const__90.getRawRoot(), (Object)((Object)new config$fn__835()), (Object)const__138);
        var31.bindRoot((Object)RT.vector((Object[])objectArray));
        Var var33 = const__139;
        var33.setMeta((IPersistentMap)const__141);
        Var var34 = var33;
        var33.bindRoot((Object)new config$validate_properties());
        Var var35 = const__142;
        var35.setMeta((IPersistentMap)const__143);
        Var var36 = var35;
        var35.bindRoot(((IFn)const__144.getRawRoot()).invoke(null));
        Var var37 = const__145;
        var37.setMeta((IPersistentMap)const__147);
        Var var38 = var37;
        var37.bindRoot((Object)new config$reset_BANG_());
        Var var39 = const__148;
        var39.setMeta((IPersistentMap)const__149);
        Var var40 = var39;
        var39.bindRoot((Object)new Delay((IFn)new config$fn__846()));
        Var var41 = const__150;
        var41.setMeta((IPersistentMap)const__152);
        Var var42 = var41;
        var41.bindRoot((Object)new config$property());
        Var var43 = const__153;
        var43.setMeta((IPersistentMap)const__155);
        Var var44 = var43;
        var43.bindRoot((Object)new config$local_valcache_enabled_QMARK_());
        Var var45 = const__156;
        var45.setMeta((IPersistentMap)const__158);
        Var var46 = var45;
        var45.bindRoot((Object)new config$property_map());
        Object object13 = ((IFn)new config$fn__855()).invoke();
        MultiFn multiFn = ((MultiFn)const__159.getRawRoot()).addMethod((Object)const__160, (IFn)new config$fn__859());
        MultiFn multiFn2 = ((MultiFn)const__159.getRawRoot()).addMethod((Object)const__161, (IFn)new config$fn__861());
        MultiFn multiFn3 = ((MultiFn)const__159.getRawRoot()).addMethod((Object)const__162, (IFn)new config$fn__863());
        MultiFn multiFn4 = ((MultiFn)const__159.getRawRoot()).addMethod((Object)const__163, (IFn)new config$fn__865());
        Var var47 = const__164;
        var47.setMeta((IPersistentMap)const__165);
        Var var48 = var47;
        var47.bindRoot((Object)new Delay((IFn)new config$fn__867()));
        Var var49 = const__166;
        var49.setMeta((IPersistentMap)const__168);
        Var var50 = var49;
        var49.bindRoot((Object)new config$folsom_QMARK_());
        Var var51 = const__169;
        var51.setMeta((IPersistentMap)const__171);
        Var var52 = var51;
        var51.bindRoot((Object)new config$local_memcached_args());
        Var var53 = const__172;
        var53.setMeta((IPersistentMap)const__174);
        Var var54 = var53;
        var53.bindRoot((Object)new config$memcached_args());
        Var var55 = const__175;
        var55.setMeta((IPersistentMap)const__177);
        Var var56 = var55;
        var55.bindRoot((Object)new config$max_gb__GT_eviction_threshold_mb());
        Var var57 = const__178;
        var57.setMeta((IPersistentMap)const__180);
        Var var58 = var57;
        var57.bindRoot((Object)new config$valcache_args());
        Var var59 = const__181;
        var59.setMeta((IPersistentMap)const__183);
        Var var60 = var59;
        var59.bindRoot((Object)new config$ddb_client_args());
        Var var61 = const__184;
        var61.setMeta((IPersistentMap)const__186);
        Var var62 = var61;
        var61.bindRoot((Object)new config$s3_client_args());
        Var var63 = const__187;
        var63.setMeta((IPersistentMap)const__188);
        Var var64 = var63;
        var63.bindRoot((Object)new Delay((IFn)new config$fn__879()));
        Var var65 = const__189;
        var65.setMeta((IPersistentMap)const__191);
        Var var66 = var65;
        var65.bindRoot((Object)new config$prefetch_enabled_QMARK_());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.config");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.config", (String)"protocol-supports-ha?");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"protocol")))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.classForName((String)"datomic.config.Symbolish");
        const__11 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__12 = RT.var((String)"datomic.config", (String)"Symbolish");
        const__13 = RT.var((String)"clojure.core", (String)"assoc");
        const__14 = RT.keyword(null, (String)"doc");
        const__15 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__16 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"sym-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), ((IObj)Symbol.intern(null, (String)"sym-namespace")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}))));
        const__17 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__18 = RT.var((String)"clojure.core", (String)"merge");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.config.Symbolish"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.config.Symbolish")});
        const__23 = RT.keyword(null, (String)"sigs");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"sym-name"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sym-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), null}), RT.keyword(null, (String)"sym-namespace"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sym-namespace")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), null})});
        const__25 = RT.keyword(null, (String)"var");
        const__26 = RT.keyword(null, (String)"method-map");
        const__27 = RT.keyword(null, (String)"sym-name");
        const__28 = RT.keyword(null, (String)"sym-namespace");
        const__29 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"sym-name"), RT.keyword(null, (String)"sym-name"), RT.keyword(null, (String)"sym-namespace"), RT.keyword(null, (String)"sym-namespace")});
        const__30 = RT.keyword(null, (String)"method-builders");
        const__31 = RT.var((String)"clojure.core", (String)"intern");
        const__32 = RT.var((String)"clojure.core", (String)"*ns*");
        const__33 = RT.var((String)"clojure.core", (String)"with-meta");
        const__34 = (AFn)((IObj)Symbol.intern(null, (String)"sym-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__35 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sym-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), null});
        const__36 = RT.keyword(null, (String)"protocol");
        const__37 = (AFn)((IObj)Symbol.intern(null, (String)"sym-namespace")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__38 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sym-namespace")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), null});
        const__39 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__40 = (AFn)Symbol.intern(null, (String)"Symbolish");
        const__41 = RT.var((String)"clojure.core", (String)"extend");
        const__42 = RT.classForName((String)"java.lang.Object");
        const__43 = RT.classForName((String)"clojure.lang.Named");
        const__44 = RT.var((String)"datomic.config", (String)"datomic-edition");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__46 = RT.keyword(null, (String)"limited-edition");
        const__47 = RT.var((String)"datomic.config", (String)"set-pro");
        const__49 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__50 = RT.var((String)"datomic.config", (String)"pro?");
        const__52 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__53 = RT.var((String)"datomic.config", (String)"limited-edition?");
        const__55 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__56 = RT.var((String)"datomic.config", (String)"parse-memory-string");
        const__58 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__59 = RT.var((String)"datomic.config", (String)"read-system-property");
        const__61 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"prop"), (Object)Symbol.intern(null, (String)"coerce"), (Object)Symbol.intern(null, (String)"valid?"), (Object)Symbol.intern(null, (String)"default")))), RT.keyword(null, (String)"column"), 1});
        const__62 = RT.var((String)"datomic.config", (String)"DEFAULT_MEMIDX_MAX");
        const__64 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__65 = 0x4000000L;
        const__66 = RT.var((String)"datomic.config", (String)"at-least");
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"minval")))), RT.keyword(null, (String)"column"), 1});
        const__69 = RT.var((String)"datomic.config", (String)"in-range");
        const__71 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"lo"), (Object)Symbol.intern(null, (String)"hi")))), RT.keyword(null, (String)"column"), 1});
        const__72 = RT.var((String)"datomic.config", (String)"warn-deprecations");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.config", (String)"version");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.var((String)"datomic.config", (String)"version-unique");
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__82 = RT.var((String)"datomic.config", (String)"read-revision");
        const__84 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"props")))), RT.keyword(null, (String)"column"), 1});
        const__85 = RT.var((String)"datomic.config", (String)"bool?");
        const__87 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__88 = RT.var((String)"datomic.config", (String)"config-table");
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__90 = RT.var((String)"clojure.edn", (String)"read-string");
        const__91 = 1000L;
        const__92 = 5000L;
        const__93 = RT.var((String)"clojure.core", (String)"identity");
        const__95 = 2L;
        const__96 = 32L;
        const__97 = 4L;
        const__98 = RT.var((String)"clojure.core", (String)"keyword?");
        const__99 = RT.keyword((String)"db.part", (String)"user");
    }

    public static void __init1() {
        const__100 = 0L;
        const__101 = RT.var((String)"clojure.core", (String)"string?");
        const__102 = 1L;
        const__103 = RT.var((String)"clojure.core", (String)"partial");
        const__104 = RT.var((String)"clojure.core", (String)"contains?");
        const__105 = (AFn)PersistentHashSet.create((Object[])new Object[]{Boolean.TRUE, Boolean.FALSE});
        const__106 = 128L;
        const__107 = 128L;
        const__108 = 5L;
        const__109 = 60000L;
        const__110 = 25L;
        const__111 = 9L;
        const__112 = 100L;
        const__113 = -1L;
        const__114 = 1000L;
        const__115 = 5000L;
        const__119 = 8L;
        const__122 = 10000L;
        const__123 = 10000L;
        const__124 = 10000L;
        const__125 = 30L;
        const__126 = RT.var((String)"clojure.java.io", (String)"file");
        const__131 = RT.var((String)"clojure.core", (String)"constantly");
        const__132 = RT.var((String)"clojure.core", (String)"map?");
        const__133 = RT.var((String)"clojure.core", (String)"symbol?");
        const__134 = RT.var((String)"clojure.core", (String)"pos-int?");
        const__137 = 20L;
        const__138 = 0.1;
        const__139 = RT.var((String)"datomic.config", (String)"validate-properties");
        const__141 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__142 = RT.var((String)"datomic.config", (String)"properties-ref");
        const__143 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__144 = RT.var((String)"clojure.core", (String)"atom");
        const__145 = RT.var((String)"datomic.config", (String)"reset!");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.config", (String)"initialized");
        const__149 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__150 = RT.var((String)"datomic.config", (String)"property");
        const__152 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"name")))), RT.keyword(null, (String)"column"), 1});
        const__153 = RT.var((String)"datomic.config", (String)"local-valcache-enabled?");
        const__155 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__156 = RT.var((String)"datomic.config", (String)"property-map");
        const__158 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__159 = RT.var((String)"datomic.config", (String)"edition-has-feature?");
        const__160 = RT.keyword((String)"monitor", (String)"logrotate");
        const__161 = RT.keyword((String)"monitor", (String)"metrics");
        const__162 = RT.keyword((String)"protocol", (String)"dev");
        const__163 = RT.keyword((String)"lifecycle", (String)"ha");
        const__164 = RT.var((String)"datomic.config", (String)"is-folsom?");
        const__165 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__166 = RT.var((String)"datomic.config", (String)"folsom?");
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__169 = RT.var((String)"datomic.config", (String)"local-memcached-args");
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__172 = RT.var((String)"datomic.config", (String)"memcached-args");
        const__174 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__175 = RT.var((String)"datomic.config", (String)"max-gb->eviction-threshold-mb");
        const__177 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"max-gb")))), RT.keyword(null, (String)"column"), 1});
        const__178 = RT.var((String)"datomic.config", (String)"valcache-args");
        const__180 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__181 = RT.var((String)"datomic.config", (String)"ddb-client-args");
        const__183 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__184 = RT.var((String)"datomic.config", (String)"s3-client-args");
        const__186 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create(), Tuple.create((Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__187 = RT.var((String)"datomic.config", (String)"is-prefetch?");
        const__188 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__189 = RT.var((String)"datomic.config", (String)"prefetch-enabled?");
        const__191 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
    }

    static {
        config__init.__init0();
        config__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.config__init").getClassLoader());
        try {
            config__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

