/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.PersistentArrayMap
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.PersistentArrayMap;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.datafy$can_data_to_object_QMARK_;
import datomic.datafy$define_data_to_object;
import datomic.datafy$define_data_to_object_for;
import datomic.datafy$define_list_valued_property_to_object;
import datomic.datafy$define_list_valued_property_to_object_for;
import datomic.datafy$define_map_valued_property_to_object;
import datomic.datafy$define_map_valued_property_to_object_for;
import datomic.datafy$define_method_to_fn;
import datomic.datafy$define_object_to_data;
import datomic.datafy$define_object_to_data_for;
import datomic.datafy$define_object_to_functions_for;
import datomic.datafy$filter_overlapped_setters;
import datomic.datafy$fn__17156;
import datomic.datafy$fn__17182;
import datomic.datafy$fn__17186;
import datomic.datafy$fn__17192;
import datomic.datafy$fn__17198;
import datomic.datafy$fn__17201;
import datomic.datafy$fn__17204;
import datomic.datafy$fn__17211;
import datomic.datafy$fn__17216;
import datomic.datafy$fn__17220;
import datomic.datafy$fn__17223;
import datomic.datafy$fn__17235;
import datomic.datafy$fn__17237;
import datomic.datafy$fn__17239;
import datomic.datafy$fn__17254;
import datomic.datafy$fn__17260;
import datomic.datafy$fn__17262;
import datomic.datafy$fn__17264;
import datomic.datafy$fn__17266;
import datomic.datafy$fn__17268;
import datomic.datafy$fn__17271;
import datomic.datafy$fn__17274;
import datomic.datafy$fn__17276;
import datomic.datafy$fn__17282;
import datomic.datafy$get_java_method;
import datomic.datafy$getter_QMARK_;
import datomic.datafy$getters;
import datomic.datafy$invoke_getter;
import datomic.datafy$invoke_setter;
import datomic.datafy$loading__6434__auto____17154;
import datomic.datafy$method_input_classes;
import datomic.datafy$object_to_data_wrapper;
import datomic.datafy$setter_name__GT_keyword;
import datomic.datafy$setters;
import datomic.datafy$type_descriptor_category;
import datomic.datafy$type_docstring;
import datomic.datafy$val_setters;
import datomic.datafy$vals_to_bean;
import datomic.datafy$vals_to_data;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class datafy__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Var const__10;
    public static final AFn const__12;
    public static final Var const__13;
    public static final AFn const__15;
    public static final Var const__16;
    public static final AFn const__18;
    public static final Var const__19;
    public static final AFn const__21;
    public static final Var const__22;
    public static final AFn const__24;
    public static final Var const__25;
    public static final AFn const__26;
    public static final Var const__27;
    public static final AFn const__28;
    public static final Var const__29;
    public static final Keyword const__30;
    public static final Keyword const__31;
    public static final Keyword const__32;
    public static final Var const__33;
    public static final Keyword const__34;
    public static final Keyword const__35;
    public static final Object const__36;
    public static final Var const__37;
    public static final Var const__38;
    public static final Var const__39;
    public static final Keyword const__40;
    public static final Var const__41;
    public static final ISeq const__42;
    public static final Var const__43;
    public static final Var const__44;
    public static final AFn const__48;
    public static final Keyword const__49;
    public static final AFn const__50;
    public static final Keyword const__51;
    public static final Keyword const__52;
    public static final Keyword const__53;
    public static final AFn const__54;
    public static final Keyword const__55;
    public static final Var const__56;
    public static final Var const__57;
    public static final Var const__58;
    public static final AFn const__59;
    public static final AFn const__60;
    public static final Keyword const__61;
    public static final Var const__62;
    public static final AFn const__63;
    public static final Var const__64;
    public static final AFn const__66;
    public static final Var const__67;
    public static final Object const__68;
    public static final Object const__69;
    public static final Object const__70;
    public static final Var const__71;
    public static final AFn const__73;
    public static final Var const__74;
    public static final Keyword const__75;
    public static final AFn const__77;
    public static final AFn const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final Var const__83;
    public static final AFn const__85;
    public static final Var const__86;
    public static final AFn const__88;
    public static final Var const__89;
    public static final AFn const__91;
    public static final Var const__92;
    public static final AFn const__94;
    public static final Var const__95;
    public static final AFn const__97;
    public static final Var const__98;
    public static final AFn const__100;
    public static final Var const__101;
    public static final AFn const__103;
    public static final Var const__104;
    public static final AFn const__106;
    public static final Var const__107;
    public static final AFn const__109;
    public static final Var const__110;
    public static final AFn const__112;
    public static final Var const__113;
    public static final AFn const__115;
    public static final Var const__116;
    public static final AFn const__118;
    public static final Var const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final Var const__128;
    public static final AFn const__130;
    public static final Var const__131;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__136;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new datafy$loading__6434__auto____17154()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new datafy$fn__17156())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new datafy$setters());
        Var var3 = const__10;
        var3.setMeta((IPersistentMap)const__12);
        Var var4 = var3;
        var3.bindRoot((Object)new datafy$setter_name__GT_keyword());
        Var var5 = const__13;
        var5.setMeta((IPersistentMap)const__15);
        Var var6 = var5;
        var5.bindRoot((Object)new datafy$filter_overlapped_setters());
        Var var7 = const__16;
        var7.setMeta((IPersistentMap)const__18);
        Var var8 = var7;
        var7.bindRoot((Object)new datafy$getter_QMARK_());
        Var var9 = const__19;
        var9.setMeta((IPersistentMap)const__21);
        Var var10 = var9;
        var9.bindRoot((Object)new datafy$getters());
        Var var11 = const__22;
        var11.setMeta((IPersistentMap)const__24);
        Var var12 = var11;
        var11.bindRoot((Object)new datafy$type_descriptor_category());
        Object object4 = ((IFn)new datafy$fn__17182()).invoke();
        Object object5 = ((IFn)new datafy$fn__17186()).invoke();
        Var var13 = const__25;
        var13.setMeta((IPersistentMap)const__26);
        Var var14 = var13;
        var13.bindRoot((Object)PersistentArrayMap.EMPTY);
        Var var15 = const__27;
        var15.setMeta((IPersistentMap)const__28);
        Var var16 = var15;
        var15.bindRoot((Object)PersistentArrayMap.EMPTY);
        MultiFn multiFn = ((MultiFn)const__29.getRawRoot()).addMethod((Object)const__30, (IFn)new datafy$fn__17192());
        MultiFn multiFn2 = ((MultiFn)const__29.getRawRoot()).addMethod((Object)const__31, (IFn)new datafy$fn__17198());
        MultiFn multiFn3 = ((MultiFn)const__29.getRawRoot()).addMethod((Object)const__32, (IFn)new datafy$fn__17201());
        MultiFn multiFn4 = ((MultiFn)const__33.getRawRoot()).addMethod((Object)const__34, (IFn)new datafy$fn__17204());
        MultiFn multiFn5 = ((MultiFn)const__33.getRawRoot()).addMethod((Object)const__35, (IFn)new datafy$fn__17211());
        MultiFn multiFn6 = ((MultiFn)const__33.getRawRoot()).addMethod((Object)const__32, (IFn)new datafy$fn__17216());
        Object object6 = ((IFn)new datafy$fn__17220()).invoke();
        Object object7 = const__36;
        Object object8 = ((IFn)const__37.getRawRoot()).invoke((Object)const__38, const__39.getRawRoot(), (Object)const__40, null);
        Object object9 = ((IFn)const__41).invoke((Object)const__38, (Object)const__42);
        Object object10 = ((IFn)const__43.getRawRoot()).invoke((Object)const__38, const__44.getRawRoot(), ((IFn)const__39.getRawRoot()).invoke((Object)const__48, (Object)const__49, (Object)const__50, (Object)const__51, (Object)const__38, (Object)const__52, (Object)const__54, (Object)const__55, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__56.getRawRoot()).invoke(const__57.get(), ((IFn)const__58.getRawRoot()).invoke((Object)const__59, ((IFn)const__44.getRawRoot()).invoke((Object)const__60, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__61, const__38})))), new datafy$fn__17223()})));
        Object object11 = ((IFn)const__62.getRawRoot()).invoke(const__38.getRawRoot());
        AFn aFn = const__63;
        Var var17 = const__64;
        var17.setMeta((IPersistentMap)const__66);
        Var var18 = var17;
        var17.bindRoot((Object)new datafy$object_to_data_wrapper());
        Object object12 = ((IFn)const__67.getRawRoot()).invoke(const__68, const__38.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__53, new datafy$fn__17235()}));
        Object object13 = ((IFn)const__67.getRawRoot()).invoke(const__69, const__38.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__53, new datafy$fn__17237()}));
        Object object14 = ((IFn)const__67.getRawRoot()).invoke(const__70, const__38.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__53, new datafy$fn__17239()}));
        Var var19 = const__71;
        var19.setMeta((IPersistentMap)const__73);
        Var var20 = var19;
        var19.bindRoot((Object)new datafy$vals_to_data());
        Object object15 = ((IFn)new datafy$fn__17254()).invoke();
        MultiFn multiFn7 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)const__77, (IFn)new datafy$fn__17260());
        MultiFn multiFn8 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)Tuple.create((Object)const__75, Integer.TYPE), (IFn)new datafy$fn__17262());
        MultiFn multiFn9 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)const__79, (IFn)new datafy$fn__17264());
        MultiFn multiFn10 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)Tuple.create((Object)const__75, Long.TYPE), (IFn)new datafy$fn__17266());
        MultiFn multiFn11 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)const__81, (IFn)new datafy$fn__17268());
        MultiFn multiFn12 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)Tuple.create((Object)const__75, Boolean.TYPE), (IFn)new datafy$fn__17271());
        MultiFn multiFn13 = ((MultiFn)const__74.getRawRoot()).addMethod((Object)const__32, (IFn)new datafy$fn__17274());
        Object object16 = ((IFn)new datafy$fn__17276()).invoke();
        MultiFn multiFn14 = ((MultiFn)const__82.getRawRoot()).addMethod((Object)const__32, (IFn)new datafy$fn__17282());
        Var var21 = const__83;
        var21.setMeta((IPersistentMap)const__85);
        Var var22 = var21;
        var21.bindRoot((Object)new datafy$invoke_setter());
        Var var23 = const__86;
        var23.setMeta((IPersistentMap)const__88);
        Var var24 = var23;
        var23.bindRoot((Object)new datafy$invoke_getter());
        Var var25 = const__89;
        var25.setMeta((IPersistentMap)const__91);
        Var var26 = var25;
        var25.bindRoot((Object)new datafy$can_data_to_object_QMARK_());
        Var var27 = const__92;
        var27.setMeta((IPersistentMap)const__94);
        Var var28 = var27;
        var27.bindRoot((Object)new datafy$method_input_classes());
        Var var29 = const__95;
        var29.setMeta((IPersistentMap)const__97);
        Var var30 = var29;
        var29.bindRoot((Object)new datafy$define_data_to_object());
        Var var31 = const__98;
        var31.setMeta((IPersistentMap)const__100);
        Var var32 = var31;
        var31.bindRoot((Object)new datafy$define_object_to_data());
        Var var33 = const__101;
        var33.setMeta((IPersistentMap)const__103);
        Var var34 = var33;
        var33.bindRoot((Object)new datafy$type_docstring());
        Var var35 = const__104;
        var35.setMeta((IPersistentMap)const__106);
        Var var36 = var35;
        var35.bindRoot((Object)new datafy$define_method_to_fn());
        Var var37 = const__107;
        var37.setMeta((IPersistentMap)const__109);
        Var var38 = var37;
        var37.bindRoot((Object)new datafy$get_java_method());
        Var var39 = const__110;
        var39.setMeta((IPersistentMap)const__112);
        Var var40 = var39;
        var39.bindRoot((Object)new datafy$define_object_to_functions_for());
        const__110.setMacro();
        Object v72 = null;
        Var var41 = const__110;
        Var var42 = const__113;
        var42.setMeta((IPersistentMap)const__115);
        Var var43 = var42;
        var42.bindRoot((Object)new datafy$define_data_to_object_for());
        const__113.setMacro();
        Object v76 = null;
        Var var44 = const__113;
        Var var45 = const__116;
        var45.setMeta((IPersistentMap)const__118);
        Var var46 = var45;
        var45.bindRoot((Object)new datafy$define_object_to_data_for());
        const__116.setMacro();
        Object v80 = null;
        Var var47 = const__116;
        Var var48 = const__119;
        var48.setMeta((IPersistentMap)const__121);
        Var var49 = var48;
        var48.bindRoot((Object)new datafy$define_map_valued_property_to_object());
        Var var50 = const__122;
        var50.setMeta((IPersistentMap)const__124);
        Var var51 = var50;
        var50.bindRoot((Object)new datafy$define_map_valued_property_to_object_for());
        const__122.setMacro();
        Object v86 = null;
        Var var52 = const__122;
        Var var53 = const__125;
        var53.setMeta((IPersistentMap)const__127);
        Var var54 = var53;
        var53.bindRoot((Object)new datafy$define_list_valued_property_to_object());
        Var var55 = const__128;
        var55.setMeta((IPersistentMap)const__130);
        Var var56 = var55;
        var55.bindRoot((Object)new datafy$define_list_valued_property_to_object_for());
        const__128.setMacro();
        Object v92 = null;
        Var var57 = const__128;
        Var var58 = const__131;
        var58.setMeta((IPersistentMap)const__133);
        Var var59 = var58;
        var58.bindRoot((Object)new datafy$val_setters());
        Var var60 = const__134;
        var60.setMeta((IPersistentMap)const__136);
        Var var61 = var60;
        var60.bindRoot((Object)new datafy$vals_to_bean());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.datafy");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.datafy", (String)"setters");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cls")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Class")}))))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"datomic.datafy", (String)"setter-name->keyword");
        const__12 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__13 = RT.var((String)"datomic.datafy", (String)"filter-overlapped-setters");
        const__15 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__16 = RT.var((String)"datomic.datafy", (String)"getter?");
        const__18 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"m")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Method")}))))), RT.keyword(null, (String)"column"), 1});
        const__19 = RT.var((String)"datomic.datafy", (String)"getters");
        const__21 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cls")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Class")}))))), RT.keyword(null, (String)"column"), 1});
        const__22 = RT.var((String)"datomic.datafy", (String)"type-descriptor-category");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"c")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Class")}))))), RT.keyword(null, (String)"column"), 1});
        const__25 = RT.var((String)"datomic.datafy", (String)"map-property-types");
        const__26 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__27 = RT.var((String)"datomic.datafy", (String)"list-property-types");
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__29 = RT.var((String)"datomic.datafy", (String)"property-descriptor");
        const__30 = RT.keyword(null, (String)"map");
        const__31 = RT.keyword(null, (String)"list");
        const__32 = RT.keyword(null, (String)"default");
        const__33 = RT.var((String)"datomic.datafy", (String)"type-descriptor");
        const__34 = RT.keyword(null, (String)"enum");
        const__35 = RT.keyword(null, (String)"bean");
        const__36 = RT.classForName((String)"datomic.datafy.ObjectToData");
        const__37 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__38 = RT.var((String)"datomic.datafy", (String)"ObjectToData");
        const__39 = RT.var((String)"clojure.core", (String)"assoc");
        const__40 = RT.keyword(null, (String)"doc");
        const__41 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__42 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"object-to-data")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))}))));
        const__43 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__44 = RT.var((String)"clojure.core", (String)"merge");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.datafy.ObjectToData"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.datafy.ObjectToData")});
        const__49 = RT.keyword(null, (String)"sigs");
        const__50 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"object-to-data"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"object-to-data")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"doc"), "Recursively convert data hidden in DAOs, DTOs, etc. into generic, usable data."})});
        const__51 = RT.keyword(null, (String)"var");
        const__52 = RT.keyword(null, (String)"method-map");
        const__53 = RT.keyword(null, (String)"object-to-data");
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"object-to-data"), RT.keyword(null, (String)"object-to-data")});
        const__55 = RT.keyword(null, (String)"method-builders");
        const__56 = RT.var((String)"clojure.core", (String)"intern");
        const__57 = RT.var((String)"clojure.core", (String)"*ns*");
        const__58 = RT.var((String)"clojure.core", (String)"with-meta");
        const__59 = (AFn)((IObj)Symbol.intern(null, (String)"object-to-data")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))}));
        const__60 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"object-to-data")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"doc"), "Recursively convert data hidden in DAOs, DTOs, etc. into generic, usable data."});
        const__61 = RT.keyword(null, (String)"protocol");
        const__62 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__63 = (AFn)Symbol.intern(null, (String)"ObjectToData");
        const__64 = RT.var((String)"datomic.datafy", (String)"object-to-data-wrapper");
        const__66 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__67 = RT.var((String)"clojure.core", (String)"extend");
        const__68 = RT.classForName((String)"java.lang.Object");
        const__69 = RT.classForName((String)"java.util.ArrayList");
        const__70 = RT.classForName((String)"java.util.Map");
        const__71 = RT.var((String)"datomic.datafy", (String)"vals-to-data");
        const__73 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__74 = RT.var((String)"datomic.datafy", (String)"data-to-object");
        const__75 = RT.keyword(null, (String)"atom");
        const__77 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"atom"), (Object)RT.classForName((String)"java.lang.Integer"));
        const__79 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"atom"), (Object)RT.classForName((String)"java.lang.Long"));
        const__81 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"atom"), (Object)RT.classForName((String)"java.lang.Boolean"));
        const__82 = RT.var((String)"datomic.datafy", (String)"property-to-object");
        const__83 = RT.var((String)"datomic.datafy", (String)"invoke-setter");
        const__85 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"), (Object)Symbol.intern(null, (String)"m"), (Object)((IObj)Symbol.intern(null, (String)"meth")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Method")}))))), RT.keyword(null, (String)"column"), 1});
        const__86 = RT.var((String)"datomic.datafy", (String)"invoke-getter");
        const__88 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o"), (Object)Symbol.intern(null, (String)"m"), (Object)((IObj)Symbol.intern(null, (String)"meth")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Method")}))))), RT.keyword(null, (String)"column"), 1});
        const__89 = RT.var((String)"datomic.datafy", (String)"can-data-to-object?");
        const__91 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cls")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Class")}))))), RT.keyword(null, (String)"column"), 1});
        const__92 = RT.var((String)"datomic.datafy", (String)"method-input-classes");
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"m")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Method")}))))), RT.keyword(null, (String)"column"), 1});
        const__95 = RT.var((String)"datomic.datafy", (String)"define-data-to-object");
        const__97 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean-class")))), RT.keyword(null, (String)"column"), 1});
        const__98 = RT.var((String)"datomic.datafy", (String)"define-object-to-data");
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean-class")))), RT.keyword(null, (String)"column"), 1});
        const__101 = RT.var((String)"datomic.datafy", (String)"type-docstring");
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"argname"), (Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"argclass"))))), RT.keyword(null, (String)"column"), 1});
        const__104 = RT.var((String)"datomic.datafy", (String)"define-method-to-fn");
        const__106 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"m")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Method")})), (Object)Symbol.intern(null, (String)"fname"), (Object)Symbol.intern(null, (String)"docstring")))), RT.keyword(null, (String)"column"), 1});
        const__107 = RT.var((String)"datomic.datafy", (String)"get-java-method");
        const__109 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cls")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Class")})), (Object)Symbol.intern(null, (String)"mname"), (Object)Symbol.intern(null, (String)"arity"), (Object)Symbol.intern(null, (String)"types")))), RT.keyword(null, (String)"column"), 1});
        const__110 = RT.var((String)"datomic.datafy", (String)"define-object-to-functions-for");
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"clsname"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"specs")))), RT.keyword(null, (String)"column"), 1});
        const__113 = RT.var((String)"datomic.datafy", (String)"define-data-to-object-for");
        const__115 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"classes")))), RT.keyword(null, (String)"column"), 1});
        const__116 = RT.var((String)"datomic.datafy", (String)"define-object-to-data-for");
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"classes")))), RT.keyword(null, (String)"column"), 1});
        const__119 = RT.var((String)"datomic.datafy", (String)"define-map-valued-property-to-object");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"container"), (Object)Symbol.intern(null, (String)"property"), (Object)Symbol.intern(null, (String)"map-key-type"), (Object)Symbol.intern(null, (String)"map-value-type")))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.datafy", (String)"define-map-valued-property-to-object-for");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"descs")))), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.datafy", (String)"define-list-valued-property-to-object");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"container"), (Object)Symbol.intern(null, (String)"property"), (Object)Symbol.intern(null, (String)"list-value-type")))), RT.keyword(null, (String)"column"), 1});
        const__128 = RT.var((String)"datomic.datafy", (String)"define-list-valued-property-to-object-for");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"descs")))), RT.keyword(null, (String)"column"), 1});
        const__131 = RT.var((String)"datomic.datafy", (String)"val-setters");
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean-class")))), RT.keyword(null, (String)"column"), 1});
        const__134 = RT.var((String)"datomic.datafy", (String)"vals-to-bean");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bean"), (Object)Symbol.intern(null, (String)"props")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        datafy__init.__init0();
        datafy__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.datafy__init").getClassLoader());
        try {
            datafy__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

