/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.ddb$client;
import datomic.ddb$create_item;
import datomic.ddb$create_key;
import datomic.ddb$create_table;
import datomic.ddb$deattr;
import datomic.ddb$deitem;
import datomic.ddb$delete_item;
import datomic.ddb$delete_table;
import datomic.ddb$describe_table;
import datomic.ddb$fn__17402;
import datomic.ddb$fn__17405;
import datomic.ddb$fn__17413;
import datomic.ddb$fn__17421;
import datomic.ddb$fn__17429;
import datomic.ddb$fn__17437;
import datomic.ddb$fn__17445;
import datomic.ddb$fn__17453;
import datomic.ddb$fn__17461;
import datomic.ddb$fn__17465;
import datomic.ddb$fn__17469;
import datomic.ddb$fn__17472;
import datomic.ddb$fn__17475;
import datomic.ddb$fn__17478;
import datomic.ddb$fn__17481;
import datomic.ddb$fn__17484;
import datomic.ddb$fn__17487;
import datomic.ddb$fn__17490;
import datomic.ddb$fn__17493;
import datomic.ddb$fn__17495;
import datomic.ddb$fn__17498;
import datomic.ddb$fn__17501;
import datomic.ddb$fn__17503;
import datomic.ddb$fn__17506;
import datomic.ddb$fn__17509;
import datomic.ddb$fn__17512;
import datomic.ddb$fn__17516;
import datomic.ddb$fn__17524;
import datomic.ddb$fn__17534;
import datomic.ddb$fn__17546;
import datomic.ddb$fn__17556;
import datomic.ddb$fn__17582;
import datomic.ddb$fn__17588;
import datomic.ddb$fn__17600;
import datomic.ddb$fn__17608;
import datomic.ddb$fn__17616;
import datomic.ddb$fn__17666;
import datomic.ddb$fn__17678;
import datomic.ddb$fn__17686;
import datomic.ddb$fullname;
import datomic.ddb$get_item;
import datomic.ddb$get_item_STAR_;
import datomic.ddb$list_tables;
import datomic.ddb$loading__6434__auto____17152;
import datomic.ddb$log_errors;
import datomic.ddb$put_item;
import datomic.ddb$put_item_STAR_;
import datomic.ddb$update_table;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class ddb__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Var const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final AFn const__15;
    public static final Object const__17;
    public static final AFn const__18;
    public static final Var const__19;
    public static final AFn const__20;
    public static final AFn const__22;
    public static final AFn const__24;
    public static final AFn const__25;
    public static final AFn const__28;
    public static final AFn const__29;
    public static final AFn const__30;
    public static final Object const__31;
    public static final AFn const__32;
    public static final AFn const__33;
    public static final AFn const__34;
    public static final Object const__35;
    public static final AFn const__37;
    public static final AFn const__38;
    public static final AFn const__39;
    public static final AFn const__41;
    public static final AFn const__42;
    public static final AFn const__43;
    public static final AFn const__44;
    public static final AFn const__45;
    public static final AFn const__46;
    public static final Var const__47;
    public static final AFn const__50;
    public static final Object const__51;
    public static final AFn const__52;
    public static final AFn const__54;
    public static final Object const__55;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__60;
    public static final AFn const__61;
    public static final AFn const__63;
    public static final AFn const__64;
    public static final AFn const__65;
    public static final AFn const__66;
    public static final AFn const__67;
    public static final AFn const__68;
    public static final AFn const__71;
    public static final AFn const__73;
    public static final AFn const__74;
    public static final AFn const__76;
    public static final AFn const__77;
    public static final AFn const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final Object const__83;
    public static final Var const__84;
    public static final Keyword const__85;
    public static final Object const__86;
    public static final Object const__87;
    public static final Object const__88;
    public static final Object const__89;
    public static final Object const__90;
    public static final Object const__91;
    public static final Object const__92;
    public static final Object const__93;
    public static final Var const__94;
    public static final AFn const__98;
    public static final Var const__99;
    public static final AFn const__101;
    public static final Var const__102;
    public static final AFn const__104;
    public static final Var const__105;
    public static final AFn const__107;
    public static final Var const__108;
    public static final AFn const__110;
    public static final Var const__111;
    public static final AFn const__113;
    public static final Var const__114;
    public static final AFn const__116;
    public static final Var const__117;
    public static final AFn const__119;
    public static final Var const__120;
    public static final AFn const__122;
    public static final Var const__123;
    public static final AFn const__125;
    public static final Var const__126;
    public static final AFn const__128;
    public static final Var const__129;
    public static final AFn const__131;
    public static final Var const__132;
    public static final AFn const__134;
    public static final Var const__135;
    public static final AFn const__137;
    public static final Var const__138;
    public static final AFn const__140;
    public static final Var const__141;
    public static final AFn const__143;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new ddb$loading__6434__auto____17152()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new ddb$fn__17402())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new ddb$client());
        Object object4 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__15, (Object)const__18);
        MultiFn multiFn = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__20, (IFn)new ddb$fn__17405());
        Object object5 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__22, (Object)const__24);
        MultiFn multiFn2 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__25, (IFn)new ddb$fn__17413());
        Object object6 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__28, (Object)const__29);
        MultiFn multiFn3 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__30, (IFn)new ddb$fn__17421());
        Object object7 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__32, (Object)const__33);
        MultiFn multiFn4 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__34, (IFn)new ddb$fn__17429());
        Object object8 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__37, (Object)const__38);
        MultiFn multiFn5 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__39, (IFn)new ddb$fn__17437());
        Object object9 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__41, (Object)const__42);
        MultiFn multiFn6 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__43, (IFn)new ddb$fn__17445());
        Object object10 = ((IFn)const__10.getRawRoot()).invoke((Object)const__11, const__12.getRawRoot(), (Object)const__44, (Object)const__45);
        MultiFn multiFn7 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__46, (IFn)new ddb$fn__17453());
        Object object11 = ((IFn)const__10.getRawRoot()).invoke((Object)const__47, const__12.getRawRoot(), (Object)const__50, const__51);
        MultiFn multiFn8 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__52, (IFn)new ddb$fn__17461());
        Object object12 = ((IFn)const__10.getRawRoot()).invoke((Object)const__47, const__12.getRawRoot(), (Object)const__54, const__55);
        MultiFn multiFn9 = ((MultiFn)const__19.getRawRoot()).addMethod((Object)const__56, (IFn)new ddb$fn__17465());
        MultiFn multiFn10 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__60, (IFn)new ddb$fn__17469());
        MultiFn multiFn11 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__61, (IFn)new ddb$fn__17472());
        MultiFn multiFn12 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__63, (IFn)new ddb$fn__17475());
        MultiFn multiFn13 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__64, (IFn)new ddb$fn__17478());
        MultiFn multiFn14 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__65, (IFn)new ddb$fn__17481());
        MultiFn multiFn15 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__66, (IFn)new ddb$fn__17484());
        MultiFn multiFn16 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__67, (IFn)new ddb$fn__17487());
        MultiFn multiFn17 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__68, (IFn)new ddb$fn__17490());
        MultiFn multiFn18 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__71, (IFn)new ddb$fn__17493());
        MultiFn multiFn19 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__73, (IFn)new ddb$fn__17495());
        MultiFn multiFn20 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__74, (IFn)new ddb$fn__17498());
        MultiFn multiFn21 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__76, (IFn)new ddb$fn__17501());
        MultiFn multiFn22 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__77, (IFn)new ddb$fn__17503());
        MultiFn multiFn23 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__79, (IFn)new ddb$fn__17506());
        MultiFn multiFn24 = ((MultiFn)const__57.getRawRoot()).addMethod((Object)const__81, (IFn)new ddb$fn__17509());
        Object object13 = ((IFn)const__82.getRawRoot()).invoke(const__83, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17512()}));
        Object object14 = ((IFn)const__82.getRawRoot()).invoke(const__86, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17516()}));
        Object object15 = ((IFn)const__82.getRawRoot()).invoke(const__87, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17524()}));
        Object object16 = ((IFn)const__82.getRawRoot()).invoke(const__88, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17534()}));
        Object object17 = ((IFn)const__82.getRawRoot()).invoke(const__31, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17546()}));
        Object object18 = ((IFn)const__82.getRawRoot()).invoke(const__17, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17556()}));
        Object object19 = ((IFn)const__82.getRawRoot()).invoke(const__55, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17582()}));
        Object object20 = ((IFn)const__82.getRawRoot()).invoke(const__35, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17588()}));
        Object object21 = ((IFn)const__82.getRawRoot()).invoke(const__89, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17600()}));
        Object object22 = ((IFn)const__82.getRawRoot()).invoke(const__90, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17608()}));
        Object object23 = ((IFn)const__82.getRawRoot()).invoke(const__91, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17616()}));
        Object object24 = ((IFn)const__82.getRawRoot()).invoke(const__92, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17666()}));
        Object object25 = ((IFn)const__82.getRawRoot()).invoke(const__93, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17678()}));
        Object object26 = ((IFn)const__82.getRawRoot()).invoke(const__51, const__84.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__85, new ddb$fn__17686()}));
        Var var3 = const__94;
        var3.setMeta((IPersistentMap)const__98);
        Var var4 = var3;
        var3.bindRoot((Object)new ddb$list_tables());
        Var var5 = const__99;
        var5.setMeta((IPersistentMap)const__101);
        Var var6 = var5;
        var5.bindRoot((Object)new ddb$create_table());
        Var var7 = const__102;
        var7.setMeta((IPersistentMap)const__104);
        Var var8 = var7;
        var7.bindRoot((Object)new ddb$update_table());
        Var var9 = const__105;
        var9.setMeta((IPersistentMap)const__107);
        Var var10 = var9;
        var9.bindRoot((Object)new ddb$delete_table());
        Var var11 = const__108;
        var11.setMeta((IPersistentMap)const__110);
        Var var12 = var11;
        var11.bindRoot((Object)new ddb$describe_table());
        Var var13 = const__111;
        var13.setMeta((IPersistentMap)const__113);
        Var var14 = var13;
        var13.bindRoot((Object)new ddb$put_item_STAR_());
        Var var15 = const__114;
        var15.setMeta((IPersistentMap)const__116);
        Var var16 = var15;
        var15.bindRoot((Object)new ddb$get_item_STAR_());
        Var var17 = const__117;
        var17.setMeta((IPersistentMap)const__119);
        Var var18 = var17;
        var17.bindRoot((Object)new ddb$delete_item());
        Var var19 = const__120;
        var19.setMeta((IPersistentMap)const__122);
        Var var20 = var19;
        var19.bindRoot((Object)new ddb$log_errors());
        Var var21 = const__123;
        var21.setMeta((IPersistentMap)const__125);
        Var var22 = var21;
        var21.bindRoot((Object)new ddb$put_item());
        Var var23 = const__126;
        var23.setMeta((IPersistentMap)const__128);
        Var var24 = var23;
        var23.bindRoot((Object)new ddb$get_item());
        Var var25 = const__129;
        var25.setMeta((IPersistentMap)const__131);
        Var var26 = var25;
        var25.bindRoot((Object)new ddb$fullname());
        Var var27 = const__132;
        var27.setMeta((IPersistentMap)const__134);
        Var var28 = var27;
        var27.bindRoot((Object)new ddb$create_item());
        Var var29 = const__135;
        var29.setMeta((IPersistentMap)const__137);
        Var var30 = var29;
        var29.bindRoot((Object)new ddb$deattr());
        Var var31 = const__138;
        var31.setMeta((IPersistentMap)const__140);
        Var var32 = var31;
        var31.bindRoot((Object)new ddb$deitem());
        Var var33 = const__141;
        var33.setMeta((IPersistentMap)const__143);
        Var var34 = var33;
        var33.bindRoot((Object)new ddb$create_key());
        Object v85 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.ddb");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.ddb", (String)"client");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create()).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), ((IObj)Tuple.create((Object)Symbol.intern(null, (String)"creds"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), ((IObj)Tuple.create((Object)Symbol.intern(null, (String)"creds"), (Object)Symbol.intern(null, (String)"config"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__11 = RT.var((String)"datomic.datafy", (String)"map-property-types");
        const__12 = RT.var((String)"clojure.core", (String)"assoc");
        const__15 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemRequest"), (Object)RT.keyword(null, (String)"item"));
        const__17 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue");
        const__18 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__19 = RT.var((String)"datomic.datafy", (String)"property-to-object");
        const__20 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemRequest"), (Object)RT.keyword(null, (String)"item"));
        const__22 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemRequest"), (Object)RT.keyword(null, (String)"expected"));
        const__24 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ExpectedAttributeValue"));
        const__25 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemRequest"), (Object)RT.keyword(null, (String)"expected"));
        const__28 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemRequest"), (Object)RT.keyword(null, (String)"key"));
        const__29 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__30 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemRequest"), (Object)RT.keyword(null, (String)"key"));
        const__31 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemResult");
        const__32 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemResult"), (Object)RT.keyword(null, (String)"item"));
        const__33 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__34 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemResult"), (Object)RT.keyword(null, (String)"item"));
        const__35 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemResult");
        const__37 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemResult"), (Object)RT.keyword(null, (String)"attributes"));
        const__38 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__39 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemResult"), (Object)RT.keyword(null, (String)"attributes"));
        const__41 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemRequest"), (Object)RT.keyword(null, (String)"expected"));
        const__42 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ExpectedAttributeValue"));
        const__43 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemRequest"), (Object)RT.keyword(null, (String)"expected"));
        const__44 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemRequest"), (Object)RT.keyword(null, (String)"key"));
        const__45 = (AFn)Tuple.create((Object)RT.classForName((String)"java.lang.String"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__46 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemRequest"), (Object)RT.keyword(null, (String)"key"));
        const__47 = RT.var((String)"datomic.datafy", (String)"list-property-types");
        const__50 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableRequest"), (Object)RT.keyword(null, (String)"keySchema"));
        const__51 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.KeySchemaElement");
        const__52 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableRequest"), (Object)RT.keyword(null, (String)"keySchema"));
        const__54 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableRequest"), (Object)RT.keyword(null, (String)"attributeDefinitions"));
        const__55 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeDefinition");
        const__56 = (AFn)Tuple.create((Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableRequest"), (Object)RT.keyword(null, (String)"attributeDefinitions"));
        const__57 = RT.var((String)"datomic.datafy", (String)"data-to-object");
        const__60 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.UpdateTableRequest"));
        const__61 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.GetItemRequest"));
        const__63 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ListTablesRequest"));
        const__64 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableRequest"));
        const__65 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemRequest"));
        const__66 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ExpectedAttributeValue"));
        const__67 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeValue"));
        const__68 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.AttributeDefinition"));
        const__71 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"atom"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ReturnValue"));
        const__73 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ProvisionedThroughput"));
        const__74 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.KeySchemaElement"));
        const__76 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"atom"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ScalarAttributeType"));
        const__77 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteItemRequest"));
        const__79 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteTableRequest"));
        const__81 = (AFn)Tuple.create((Object)RT.keyword(null, (String)"map"), (Object)RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DescribeTableRequest"));
        const__82 = RT.var((String)"clojure.core", (String)"extend");
        const__83 = RT.classForName((String)"com.amazonaws.ResponseMetadata");
        const__84 = RT.var((String)"datomic.datafy", (String)"ObjectToData");
        const__85 = RT.keyword(null, (String)"object-to-data");
        const__86 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.UpdateTableResult");
        const__87 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ListTablesResult");
        const__88 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.PutItemResult");
        const__89 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DeleteTableResult");
        const__90 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.DescribeTableResult");
        const__91 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.TableDescription");
        const__92 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.ProvisionedThroughputDescription");
        const__93 = RT.classForName((String)"com.amazonaws.services.dynamodbv2.model.CreateTableResult");
        const__94 = RT.var((String)"datomic.ddb", (String)"list-tables");
        const__98 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__99 = RT.var((String)"datomic.ddb", (String)"create-table");
    }

    public static void __init1() {
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__102 = RT.var((String)"datomic.ddb", (String)"update-table");
        const__104 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__105 = RT.var((String)"datomic.ddb", (String)"delete-table");
        const__107 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__108 = RT.var((String)"datomic.ddb", (String)"describe-table");
        const__110 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__111 = RT.var((String)"datomic.ddb", (String)"put-item*");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__114 = RT.var((String)"datomic.ddb", (String)"get-item*");
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__117 = RT.var((String)"datomic.ddb", (String)"delete-item");
        const__119 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"related-class"), RT.classForName((String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"o")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient")})), (Object)Symbol.intern(null, (String)"x1")))), RT.keyword(null, (String)"column"), 1});
        const__120 = RT.var((String)"datomic.ddb", (String)"log-errors");
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__123 = RT.var((String)"datomic.ddb", (String)"put-item");
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ddb-client"), (Object)Symbol.intern(null, (String)"request")))), RT.keyword(null, (String)"column"), 1});
        const__126 = RT.var((String)"datomic.ddb", (String)"get-item");
        const__128 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ddb-client"), (Object)Symbol.intern(null, (String)"request")))), RT.keyword(null, (String)"column"), 1});
        const__129 = RT.var((String)"datomic.ddb", (String)"fullname");
        const__131 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__132 = RT.var((String)"datomic.ddb", (String)"create-item");
        const__134 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__135 = RT.var((String)"datomic.ddb", (String)"deattr");
        const__137 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__138 = RT.var((String)"datomic.ddb", (String)"deitem");
        const__140 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__141 = RT.var((String)"datomic.ddb", (String)"create-key");
        const__143 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        ddb__init.__init0();
        ddb__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.ddb__init").getClassLoader());
        try {
            ddb__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

