/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.AReference
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.Namespace
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.AReference;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.Namespace;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.valcache$direct_get;
import datomic.valcache$direct_init;
import datomic.valcache$direct_put;
import datomic.valcache$dirname;
import datomic.valcache$eviction_loop;
import datomic.valcache$fn__9627;
import datomic.valcache$fn__9630;
import datomic.valcache$fn__9638;
import datomic.valcache$fn__9659;
import datomic.valcache$fn__9661;
import datomic.valcache$fn__9667;
import datomic.valcache$fn__9677;
import datomic.valcache$fn__9684;
import datomic.valcache$fn__9693;
import datomic.valcache$fn__9711;
import datomic.valcache$fn__9714;
import datomic.valcache$fn__9725;
import datomic.valcache$fn__9736;
import datomic.valcache$fn__9747;
import datomic.valcache$fn__9758;
import datomic.valcache$full_path;
import datomic.valcache$loading__6434__auto____9625;
import datomic.valcache$mkdirs;
import datomic.valcache$noop_quit;
import datomic.valcache$read_header;
import datomic.valcache$read_key;
import datomic.valcache$remote_ip;
import datomic.valcache$reply_empty_ok;
import datomic.valcache$reply_with_error;
import datomic.valcache$sasl_loop;
import datomic.valcache$scan_strings;
import datomic.valcache$shutdown;
import datomic.valcache$start_server;
import datomic.valcache$supported_or_drain;
import datomic.valcache$uuid_prefix;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class valcache__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final Keyword const__2;
    public static final AFn const__3;
    public static final AFn const__4;
    public static final Var const__5;
    public static final Var const__6;
    public static final AFn const__10;
    public static final Object const__11;
    public static final Var const__12;
    public static final AFn const__13;
    public static final Object const__14;
    public static final Var const__15;
    public static final AFn const__16;
    public static final Object const__17;
    public static final Var const__18;
    public static final AFn const__19;
    public static final Object const__20;
    public static final Var const__21;
    public static final AFn const__22;
    public static final Object const__23;
    public static final Var const__24;
    public static final AFn const__25;
    public static final Object const__26;
    public static final Var const__27;
    public static final AFn const__28;
    public static final Object const__29;
    public static final Var const__30;
    public static final AFn const__31;
    public static final Object const__32;
    public static final Var const__33;
    public static final AFn const__34;
    public static final Object const__35;
    public static final Var const__36;
    public static final AFn const__37;
    public static final Object const__38;
    public static final Var const__39;
    public static final AFn const__40;
    public static final Var const__41;
    public static final AFn const__42;
    public static final Object const__43;
    public static final Var const__44;
    public static final AFn const__45;
    public static final Object const__46;
    public static final Var const__47;
    public static final AFn const__48;
    public static final Object const__49;
    public static final Var const__50;
    public static final AFn const__51;
    public static final Object const__52;
    public static final Var const__53;
    public static final AFn const__54;
    public static final Var const__55;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__58;
    public static final Object const__59;
    public static final Var const__60;
    public static final AFn const__61;
    public static final Object const__62;
    public static final Var const__63;
    public static final AFn const__67;
    public static final Var const__68;
    public static final AFn const__70;
    public static final Var const__71;
    public static final AFn const__73;
    public static final Var const__74;
    public static final AFn const__76;
    public static final Var const__77;
    public static final AFn const__79;
    public static final Var const__80;
    public static final Var const__81;
    public static final AFn const__83;
    public static final Var const__84;
    public static final AFn const__86;
    public static final Var const__87;
    public static final AFn const__89;
    public static final Var const__90;
    public static final AFn const__92;
    public static final Var const__93;
    public static final Var const__94;
    public static final AFn const__96;
    public static final Var const__97;
    public static final AFn const__99;
    public static final Object const__100;
    public static final Var const__101;
    public static final Var const__102;
    public static final Var const__103;
    public static final Var const__104;
    public static final ISeq const__105;
    public static final Var const__106;
    public static final Var const__107;
    public static final AFn const__111;
    public static final Keyword const__112;
    public static final AFn const__113;
    public static final Keyword const__114;
    public static final Keyword const__115;
    public static final AFn const__120;
    public static final Keyword const__121;
    public static final Var const__122;
    public static final Var const__123;
    public static final Var const__124;
    public static final AFn const__125;
    public static final AFn const__126;
    public static final Keyword const__127;
    public static final AFn const__128;
    public static final AFn const__129;
    public static final AFn const__130;
    public static final AFn const__131;
    public static final AFn const__132;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__135;
    public static final Var const__136;
    public static final AFn const__138;
    public static final Var const__139;
    public static final AFn const__140;
    public static final Var const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;

    public static void load() {
        Object v3;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        IPersistentMap iPersistentMap = ((AReference)Namespace.find((Symbol)((Symbol)const__1))).resetMeta((IPersistentMap)const__3);
        Object object2 = ((IFn)new valcache$loading__6434__auto____9625()).invoke();
        if (((Symbol)const__1).equals((Object)const__4)) {
            v3 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new valcache$fn__9627())));
            v3 = null;
        }
        Object object3 = const__5.set((Object)Boolean.TRUE);
        Var var = const__6;
        var.setMeta((IPersistentMap)const__10);
        Var var2 = var;
        var.bindRoot(const__11);
        Var var3 = const__12;
        var3.setMeta((IPersistentMap)const__13);
        Var var4 = var3;
        var3.bindRoot(const__14);
        Var var5 = const__15;
        var5.setMeta((IPersistentMap)const__16);
        Var var6 = var5;
        var5.bindRoot(const__17);
        Var var7 = const__18;
        var7.setMeta((IPersistentMap)const__19);
        Var var8 = var7;
        var7.bindRoot(const__20);
        Var var9 = const__21;
        var9.setMeta((IPersistentMap)const__22);
        Var var10 = var9;
        var9.bindRoot(const__23);
        Var var11 = const__24;
        var11.setMeta((IPersistentMap)const__25);
        Var var12 = var11;
        var11.bindRoot(const__26);
        Var var13 = const__27;
        var13.setMeta((IPersistentMap)const__28);
        Var var14 = var13;
        var13.bindRoot(const__29);
        Var var15 = const__30;
        var15.setMeta((IPersistentMap)const__31);
        Var var16 = var15;
        var15.bindRoot(const__32);
        Var var17 = const__33;
        var17.setMeta((IPersistentMap)const__34);
        Var var18 = var17;
        var17.bindRoot(const__35);
        Var var19 = const__36;
        var19.setMeta((IPersistentMap)const__37);
        Var var20 = var19;
        var19.bindRoot(const__38);
        Var var21 = const__39;
        var21.setMeta((IPersistentMap)const__40);
        Var var22 = var21;
        var21.bindRoot(const__20);
        Var var23 = const__41;
        var23.setMeta((IPersistentMap)const__42);
        Var var24 = var23;
        var23.bindRoot(const__43);
        Var var25 = const__44;
        var25.setMeta((IPersistentMap)const__45);
        Var var26 = var25;
        var25.bindRoot(const__46);
        Var var27 = const__47;
        var27.setMeta((IPersistentMap)const__48);
        Var var28 = var27;
        var27.bindRoot(const__49);
        Var var29 = const__50;
        var29.setMeta((IPersistentMap)const__51);
        Var var30 = var29;
        var29.bindRoot(const__52);
        Var var31 = const__53;
        var31.setMeta((IPersistentMap)const__54);
        Var var32 = var31;
        var31.bindRoot(const__38);
        Var var33 = const__55;
        var33.setMeta((IPersistentMap)const__56);
        Var var34 = var33;
        var33.bindRoot(const__20);
        Var var35 = const__57;
        var35.setMeta((IPersistentMap)const__58);
        Var var36 = var35;
        var35.bindRoot(const__59);
        Var var37 = const__60;
        var37.setMeta((IPersistentMap)const__61);
        Var var38 = var37;
        var37.bindRoot(const__62);
        Var var39 = const__63;
        var39.setMeta((IPersistentMap)const__67);
        Var var40 = var39;
        var39.bindRoot((Object)new valcache$read_header());
        Object object4 = ((IFn)new valcache$fn__9630()).invoke();
        Object object5 = ((IFn)new valcache$fn__9638()).invoke();
        Var var41 = const__68;
        var41.setMeta((IPersistentMap)const__70);
        Var var42 = var41;
        var41.bindRoot((Object)new valcache$reply_with_error());
        Var var43 = const__71;
        var43.setMeta((IPersistentMap)const__73);
        Var var44 = var43;
        var43.bindRoot((Object)new valcache$supported_or_drain());
        Var var45 = const__74;
        var45.setMeta((IPersistentMap)const__76);
        Var var46 = var45;
        var45.bindRoot((Object)new valcache$reply_empty_ok());
        Var var47 = const__77;
        var47.setMeta((IPersistentMap)const__79);
        Var var48 = var47;
        var47.bindRoot((Object)new valcache$noop_quit());
        MultiFn multiFn = ((MultiFn)const__80.getRawRoot()).addMethod(const__46, (IFn)new valcache$fn__9659());
        MultiFn multiFn2 = ((MultiFn)const__80.getRawRoot()).addMethod(const__43, (IFn)new valcache$fn__9661());
        Var var49 = const__81;
        var49.setMeta((IPersistentMap)const__83);
        Var var50 = var49;
        var49.bindRoot((Object)new valcache$uuid_prefix());
        Var var51 = const__84;
        var51.setMeta((IPersistentMap)const__86);
        Var var52 = var51;
        var51.bindRoot((Object)new valcache$full_path());
        MultiFn multiFn3 = ((MultiFn)const__80.getRawRoot()).addMethod(const__38, (IFn)new valcache$fn__9667());
        Var var53 = const__87;
        var53.setMeta((IPersistentMap)const__89);
        Var var54 = var53;
        var53.bindRoot((Object)new valcache$read_key());
        MultiFn multiFn4 = ((MultiFn)const__80.getRawRoot()).addMethod(const__35, (IFn)new valcache$fn__9677());
        MultiFn multiFn5 = ((MultiFn)const__80.getRawRoot()).addMethod(const__20, (IFn)new valcache$fn__9684());
        Var var55 = const__90;
        var55.setMeta((IPersistentMap)const__92);
        Var var56 = var55;
        var55.bindRoot((Object)new valcache$scan_strings());
        MultiFn multiFn6 = ((MultiFn)const__93.getRawRoot()).addMethod(const__52, (IFn)new valcache$fn__9693());
        Var var57 = const__94;
        var57.setMeta((IPersistentMap)const__96);
        Var var58 = var57;
        var57.bindRoot((Object)new valcache$dirname());
        Var var59 = const__97;
        var59.setMeta((IPersistentMap)const__99);
        Var var60 = var59;
        var59.bindRoot((Object)new valcache$mkdirs());
        Object object6 = ((IFn)new valcache$fn__9711()).invoke();
        Object object7 = const__100;
        Object object8 = ((IFn)const__101.getRawRoot()).invoke((Object)const__102, const__103.getRawRoot(), (Object)const__2, null);
        Object object9 = ((IFn)const__104).invoke((Object)const__102, (Object)const__105);
        Object object10 = ((IFn)const__106.getRawRoot()).invoke((Object)const__102, const__107.getRawRoot(), ((IFn)const__103.getRawRoot()).invoke((Object)const__111, (Object)const__112, (Object)const__113, (Object)const__114, (Object)const__102, (Object)const__115, (Object)const__120, (Object)const__121, (Object)RT.map((Object[])new Object[]{((IFn)const__122.getRawRoot()).invoke(const__123.get(), ((IFn)const__124.getRawRoot()).invoke((Object)const__125, ((IFn)const__107.getRawRoot()).invoke((Object)const__126, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__127, const__102})))), new valcache$fn__9714(), ((IFn)const__122.getRawRoot()).invoke(const__123.get(), ((IFn)const__124.getRawRoot()).invoke((Object)const__128, ((IFn)const__107.getRawRoot()).invoke((Object)const__129, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__127, const__102})))), new valcache$fn__9725(), ((IFn)const__122.getRawRoot()).invoke(const__123.get(), ((IFn)const__124.getRawRoot()).invoke((Object)const__130, ((IFn)const__107.getRawRoot()).invoke((Object)const__131, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__127, const__102})))), new valcache$fn__9736(), ((IFn)const__122.getRawRoot()).invoke(const__123.get(), ((IFn)const__124.getRawRoot()).invoke((Object)const__132, ((IFn)const__107.getRawRoot()).invoke((Object)const__133, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__127, const__102})))), new valcache$fn__9747()})));
        Object object11 = ((IFn)const__134.getRawRoot()).invoke(const__102.getRawRoot());
        AFn aFn = const__135;
        Object object12 = ((IFn)new valcache$fn__9758()).invoke();
        Var var61 = const__136;
        var61.setMeta((IPersistentMap)const__138);
        Var var62 = var61;
        var61.bindRoot((Object)new valcache$eviction_loop());
        Var var63 = const__139;
        var63.setMeta((IPersistentMap)const__140);
        Var var64 = var63;
        var63.bindRoot(((IFn)const__141.getRawRoot()).invoke(null));
        Var var65 = const__142;
        var65.setMeta((IPersistentMap)const__144);
        Var var66 = var65;
        var65.bindRoot((Object)new valcache$shutdown());
        Var var67 = const__145;
        var67.setMeta((IPersistentMap)const__147);
        Var var68 = var67;
        var67.bindRoot((Object)new valcache$sasl_loop());
        Var var69 = const__148;
        var69.setMeta((IPersistentMap)const__150);
        Var var70 = var69;
        var69.bindRoot((Object)new valcache$remote_ip());
        Var var71 = const__151;
        var71.setMeta((IPersistentMap)const__153);
        Var var72 = var71;
        var71.bindRoot((Object)new valcache$start_server());
        Var var73 = const__154;
        var73.setMeta((IPersistentMap)const__156);
        Var var74 = var73;
        var73.bindRoot((Object)new valcache$direct_init());
        Var var75 = const__157;
        var75.setMeta((IPersistentMap)const__159);
        Var var76 = var75;
        var75.bindRoot((Object)new valcache$direct_get());
        Var var77 = const__160;
        var77.setMeta((IPersistentMap)const__162);
        Var var78 = var77;
        var77.bindRoot((Object)new valcache$direct_put());
        Object v99 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)((IObj)Symbol.intern(null, (String)"datomic.valcache")).withMeta(RT.map((Object[])new Object[0]));
        const__2 = RT.keyword(null, (String)"doc");
        const__3 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"doc"), "valcache implements a subset of the memcached binary protocol on top of the file system.\n per: https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped\n\nNarrowing presumptions are:\n\nvalues never change\nare named by uuid-as-string keys\nare big enough to justify being stored in files (several kb +)\neviction is based on (required) threshold\nLRU, tracked with atime (use strictatime + lazytime flags when mounting)\nprovided/required dir is 'owned' by valcache, subdir structure is an impl detail\nlowish connection counts (< 1000)\n\nThe supported memcached commands are get/set/delete/noop/quit\ndata type, vbucket, cas, and expiry are not supported - non-zero values will be rejected.\n"});
        const__4 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__5 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__6 = RT.var((String)"datomic.valcache", (String)"HEADER_LENGTH");
        const__10 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__11 = 24L;
        const__12 = RT.var((String)"datomic.valcache", (String)"REQUEST_MAGIC");
        const__13 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__14 = -128L;
        const__15 = RT.var((String)"datomic.valcache", (String)"RESPONSE_MAGIC");
        const__16 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__17 = -127L;
        const__18 = RT.var((String)"datomic.valcache", (String)"FILE_MAGIC_LENGTH");
        const__19 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__20 = 4L;
        const__21 = RT.var((String)"datomic.valcache", (String)"FILE_MAGIC");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__23 = 2048L;
        const__24 = RT.var((String)"datomic.valcache", (String)"DIRS");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__26 = 4096L;
        const__27 = RT.var((String)"datomic.valcache", (String)"MEG");
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__29 = 0x100000L;
        const__30 = RT.var((String)"datomic.valcache", (String)"BLOCK_SIZE_WASTE");
        const__31 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__32 = 2048L;
        const__33 = RT.var((String)"datomic.valcache", (String)"GET");
        const__34 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__35 = 0L;
        const__36 = RT.var((String)"datomic.valcache", (String)"SET");
        const__37 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__38 = 1L;
        const__39 = RT.var((String)"datomic.valcache", (String)"DELETE");
        const__40 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__41 = RT.var((String)"datomic.valcache", (String)"QUIT");
        const__42 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__43 = 7L;
        const__44 = RT.var((String)"datomic.valcache", (String)"NOOP");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__46 = 10L;
        const__47 = RT.var((String)"datomic.valcache", (String)"SASL_AUTH");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__49 = 33L;
        const__50 = RT.var((String)"datomic.valcache", (String)"SASL_STEP");
        const__51 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__52 = 34L;
        const__53 = RT.var((String)"datomic.valcache", (String)"NOT_FOUND");
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__55 = RT.var((String)"datomic.valcache", (String)"INVALID");
        const__56 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__57 = RT.var((String)"datomic.valcache", (String)"UNAUTHORIZED");
        const__58 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__59 = 32L;
        const__60 = RT.var((String)"datomic.valcache", (String)"NOT_SUPPORTED");
        const__61 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__62 = 131L;
        const__63 = RT.var((String)"datomic.valcache", (String)"read-header");
        const__67 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"sc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"SocketChannel")})), (Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__68 = RT.var((String)"datomic.valcache", (String)"reply-with-error");
        const__70 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"opcode"), (Object)Symbol.intern(null, (String)"status"), (Object)((IObj)Symbol.intern(null, (String)"msg")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"sc")))), RT.keyword(null, (String)"column"), 1});
        const__71 = RT.var((String)"datomic.valcache", (String)"supported-or-drain");
        const__73 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"opcode"), (Object)Symbol.intern(null, (String)"data-type"), (Object)Symbol.intern(null, (String)"vbucket-id"), (Object)Symbol.intern(null, (String)"cas"), (Object)Symbol.intern(null, (String)"total-body-length")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"header")}), (Object)Symbol.intern(null, (String)"sc"), (Object)Symbol.intern(null, (String)"mmeth")))), RT.keyword(null, (String)"column"), 1});
        const__74 = RT.var((String)"datomic.valcache", (String)"reply-empty-ok");
        const__76 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"opcode"), (Object)Symbol.intern(null, (String)"sc")))), RT.keyword(null, (String)"column"), 1});
        const__77 = RT.var((String)"datomic.valcache", (String)"noop-quit");
        const__79 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"opcode"), (Object)Symbol.intern(null, (String)"key-length"), (Object)Symbol.intern(null, (String)"extras-length"), (Object)Symbol.intern(null, (String)"total-body-length"))}), (Object)Symbol.intern(null, (String)"sc")))), RT.keyword(null, (String)"column"), 1});
        const__80 = RT.var((String)"datomic.valcache", (String)"handle");
        const__81 = RT.var((String)"datomic.valcache", (String)"uuid-prefix");
        const__83 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__84 = RT.var((String)"datomic.valcache", (String)"full-path");
        const__86 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"root"), (Object)Symbol.intern(null, (String)"k"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.nio.file.Path")})))), RT.keyword(null, (String)"column"), 1});
        const__87 = RT.var((String)"datomic.valcache", (String)"read-key");
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"key-length"), (Object)Symbol.intern(null, (String)"sc")))), RT.keyword(null, (String)"column"), 1});
        const__90 = RT.var((String)"datomic.valcache", (String)"scan-strings");
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__93 = RT.var((String)"datomic.valcache", (String)"sasl");
        const__94 = RT.var((String)"datomic.valcache", (String)"dirname");
        const__96 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__97 = RT.var((String)"datomic.valcache", (String)"mkdirs");
        const__99 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"root")))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init1() {
        const__100 = RT.classForName((String)"datomic.valcache.IServer");
        const__101 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__102 = RT.var((String)"datomic.valcache", (String)"IServer");
        const__103 = RT.var((String)"clojure.core", (String)"assoc");
        const__104 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__105 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"connection-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), ((IObj)Symbol.intern(null, (String)"running-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), ((IObj)Symbol.intern(null, (String)"pending-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), ((IObj)Symbol.intern(null, (String)"handled-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}))));
        const__106 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__107 = RT.var((String)"clojure.core", (String)"merge");
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.valcache.IServer"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.valcache.IServer")});
        const__112 = RT.keyword(null, (String)"sigs");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"connection-count"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"connection-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of connected sockets"}), RT.keyword(null, (String)"running-count"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"running-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of running handler threads"}), RT.keyword(null, (String)"pending-count"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"pending-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of pending handler threads"}), RT.keyword(null, (String)"handled-count"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"handled-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of handled requests"})});
        const__114 = RT.keyword(null, (String)"var");
        const__115 = RT.keyword(null, (String)"method-map");
        const__120 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"connection-count"), RT.keyword(null, (String)"connection-count"), RT.keyword(null, (String)"running-count"), RT.keyword(null, (String)"running-count"), RT.keyword(null, (String)"pending-count"), RT.keyword(null, (String)"pending-count"), RT.keyword(null, (String)"handled-count"), RT.keyword(null, (String)"handled-count")});
        const__121 = RT.keyword(null, (String)"method-builders");
        const__122 = RT.var((String)"clojure.core", (String)"intern");
        const__123 = RT.var((String)"clojure.core", (String)"*ns*");
        const__124 = RT.var((String)"clojure.core", (String)"with-meta");
        const__125 = (AFn)((IObj)Symbol.intern(null, (String)"connection-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__126 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"connection-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of connected sockets"});
        const__127 = RT.keyword(null, (String)"protocol");
        const__128 = (AFn)((IObj)Symbol.intern(null, (String)"pending-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__129 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"pending-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of pending handler threads"});
        const__130 = (AFn)((IObj)Symbol.intern(null, (String)"handled-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__131 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"handled-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of handled requests"});
        const__132 = (AFn)((IObj)Symbol.intern(null, (String)"running-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))}));
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"running-count")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"doc"), "Number of running handler threads"});
        const__134 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__135 = (AFn)Symbol.intern(null, (String)"IServer");
        const__136 = RT.var((String)"datomic.valcache", (String)"eviction-loop");
        const__138 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"threshold"), (Object)Symbol.intern(null, (String)"interval-secs"), (Object)Symbol.intern(null, (String)"file-window"), (Object)Symbol.intern(null, (String)"shutdown-requested")))), RT.keyword(null, (String)"column"), 1});
        const__139 = RT.var((String)"datomic.valcache", (String)"valcache-ref");
        const__140 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__141 = RT.var((String)"clojure.core", (String)"atom");
        const__142 = RT.var((String)"datomic.valcache", (String)"shutdown");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.valcache", (String)"sasl-loop");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"creds"), (Object)((IObj)Symbol.intern(null, (String)"sc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"SocketChannel")})), (Object)((IObj)Symbol.intern(null, (String)"sem")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Semaphore")}))))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.valcache", (String)"remote-ip");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"sc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"SocketChannel")}))))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.valcache", (String)"start-server");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), RT.vector((Object[])new Object[]{((IObj)Symbol.intern(null, (String)"host")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), ((IObj)Symbol.intern(null, (String)"port")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})), ((IObj)Symbol.intern(null, (String)"path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), Symbol.intern(null, (String)"eviction-threshold-mb"), ((IObj)Symbol.intern(null, (String)"concurrency")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})), Symbol.intern(null, (String)"eviction-interval-secs"), Symbol.intern(null, (String)"eviction-file-window"), Symbol.intern(null, (String)"sasl"), Symbol.intern(null, (String)"ip-validator")}), RT.keyword(null, (String)"or"), RT.map((Object[])new Object[]{Symbol.intern(null, (String)"port"), 11211L, Symbol.intern(null, (String)"concurrency"), 8L, Symbol.intern(null, (String)"eviction-interval-secs"), 60L, Symbol.intern(null, (String)"eviction-file-window"), 10000L, Symbol.intern(null, (String)"ip-validator"), ((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"constantly"), Boolean.TRUE))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 101}))})})))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.valcache", (String)"direct-init");
        const__156 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)((IObj)Symbol.intern(null, (String)"path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"eviction-threshold-mb"), (Object)((IObj)Symbol.intern(null, (String)"concurrency")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})), (Object)Symbol.intern(null, (String)"eviction-interval-secs"), (Object)Symbol.intern(null, (String)"eviction-file-window")), RT.keyword(null, (String)"or"), RT.map((Object[])new Object[]{Symbol.intern(null, (String)"concurrency"), 8L, Symbol.intern(null, (String)"eviction-interval-secs"), 60L, Symbol.intern(null, (String)"eviction-file-window"), 10000L})}))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"eviction-threshold-mb"))})))), RT.keyword(null, (String)"column"), 1});
        const__157 = RT.var((String)"datomic.valcache", (String)"direct-get");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"root"), (Object)Symbol.intern(null, (String)"k"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"root"), (Object)Symbol.intern(null, (String)"k"))})))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.valcache", (String)"direct-put");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"root"), (Object)Symbol.intern(null, (String)"k"), (Object)((IObj)Symbol.intern(null, (String)"v")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"root"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"v"))})))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        valcache__init.__init0();
        valcache__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.valcache__init").getClassLoader());
        try {
            valcache__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

