/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.datalog$add_rule;
import datomic.datalog$adorned_pred;
import datomic.datalog$all_pred;
import datomic.datalog$attr_QMARK_;
import datomic.datalog$binding_type;
import datomic.datalog$bound_consts;
import datomic.datalog$callees;
import datomic.datalog$compile_expr_clause;
import datomic.datalog$create_join_maps;
import datomic.datalog$dbrel;
import datomic.datalog$eval_clause;
import datomic.datalog$eval_not_join;
import datomic.datalog$eval_query;
import datomic.datalog$eval_rule;
import datomic.datalog$expr_clause;
import datomic.datalog$extensional_QMARK_;
import datomic.datalog$extrel_coll;
import datomic.datalog$fn__18043;
import datomic.datalog$fn__18046;
import datomic.datalog$fn__18050;
import datomic.datalog$fn__18059;
import datomic.datalog$fn__18062;
import datomic.datalog$fn__18083;
import datomic.datalog$fn__18156;
import datomic.datalog$fn__18158;
import datomic.datalog$fn__18160;
import datomic.datalog$fn__18162;
import datomic.datalog$fn__18164;
import datomic.datalog$fn__18182;
import datomic.datalog$fn__18185;
import datomic.datalog$fn__18207;
import datomic.datalog$fn__18209;
import datomic.datalog$fn__18211;
import datomic.datalog$fn__18213;
import datomic.datalog$fn__18215;
import datomic.datalog$fn__18231;
import datomic.datalog$fn__18233;
import datomic.datalog$fn__18347;
import datomic.datalog$fn__18396;
import datomic.datalog$fnrel;
import datomic.datalog$free_var_QMARK_;
import datomic.datalog$free_vars;
import datomic.datalog$hashxf;
import datomic.datalog$hashyf;
import datomic.datalog$iterator;
import datomic.datalog$join_project_coll;
import datomic.datalog$join_project_coll_with;
import datomic.datalog$lift_consts_from_preds;
import datomic.datalog$loading__6434__auto____17825;
import datomic.datalog$matchf;
import datomic.datalog$maybe_cancel;
import datomic.datalog$normalize_or_join;
import datomic.datalog$not_join_clause_QMARK_;
import datomic.datalog$not_or__GT_not_or_join;
import datomic.datalog$not_or_all_pred;
import datomic.datalog$on_query_thread_QMARK_;
import datomic.datalog$or_join__GT_rule_preds;
import datomic.datalog$partv;
import datomic.datalog$predrel;
import datomic.datalog$prep_clauses;
import datomic.datalog$project;
import datomic.datalog$push_preds;
import datomic.datalog$qmapv;
import datomic.datalog$qsqr;
import datomic.datalog$ranges;
import datomic.datalog$recursive_QMARK_;
import datomic.datalog$rel_fn;
import datomic.datalog$rel_pred;
import datomic.datalog$remap_bounds;
import datomic.datalog$resolve_id;
import datomic.datalog$rule_map;
import datomic.datalog$rules_QMARK_;
import datomic.datalog$scalar__GT_rel;
import datomic.datalog$sched_in_order;
import datomic.datalog$source_QMARK_;
import datomic.datalog$to_pred;
import datomic.datalog$truep;
import datomic.datalog$tuple;
import datomic.datalog$tuple__GT_rel;
import datomic.datalog$unifying_var_set;
import datomic.datalog$unifying_vars;
import datomic.datalog$used_srcs;
import datomic.datalog$variable_QMARK_;
import datomic.datalog$variable_or_blank_QMARK_;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class datalog__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final Var const__5;
    public static final AFn const__9;
    public static final Var const__10;
    public static final AFn const__13;
    public static final Var const__14;
    public static final AFn const__16;
    public static final Var const__17;
    public static final AFn const__18;
    public static final Var const__19;
    public static final AFn const__21;
    public static final Var const__22;
    public static final Var const__23;
    public static final AFn const__25;
    public static final Object const__26;
    public static final Var const__27;
    public static final Var const__28;
    public static final Var const__29;
    public static final Keyword const__30;
    public static final Var const__31;
    public static final ISeq const__32;
    public static final Var const__33;
    public static final Var const__34;
    public static final AFn const__38;
    public static final Keyword const__39;
    public static final AFn const__40;
    public static final Keyword const__41;
    public static final Keyword const__42;
    public static final Keyword const__43;
    public static final Keyword const__44;
    public static final AFn const__45;
    public static final Keyword const__46;
    public static final Var const__47;
    public static final Var const__48;
    public static final Var const__49;
    public static final AFn const__50;
    public static final AFn const__51;
    public static final Keyword const__52;
    public static final AFn const__53;
    public static final AFn const__54;
    public static final Var const__55;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__59;
    public static final Var const__60;
    public static final AFn const__62;
    public static final Var const__63;
    public static final AFn const__68;
    public static final Var const__69;
    public static final AFn const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final AFn const__77;
    public static final Var const__78;
    public static final AFn const__80;
    public static final Var const__81;
    public static final AFn const__83;
    public static final Var const__84;
    public static final AFn const__86;
    public static final Var const__87;
    public static final Object const__88;
    public static final Object const__89;
    public static final Var const__90;
    public static final AFn const__92;
    public static final Var const__93;
    public static final AFn const__95;
    public static final Object const__96;
    public static final Var const__97;
    public static final ISeq const__98;
    public static final AFn const__100;
    public static final AFn const__101;
    public static final Keyword const__102;
    public static final AFn const__103;
    public static final AFn const__104;
    public static final AFn const__105;
    public static final AFn const__106;
    public static final Var const__107;
    public static final AFn const__109;
    public static final Object const__110;
    public static final Object const__111;
    public static final Var const__112;
    public static final AFn const__113;
    public static final Object const__114;
    public static final Var const__115;
    public static final AFn const__116;
    public static final Object const__117;
    public static final Var const__118;
    public static final AFn const__119;
    public static final Object const__120;
    public static final Var const__121;
    public static final AFn const__122;
    public static final Object const__123;
    public static final Var const__124;
    public static final AFn const__125;
    public static final Object const__126;
    public static final Var const__127;
    public static final AFn const__128;
    public static final Object const__129;
    public static final Object const__130;
    public static final Var const__131;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__136;
    public static final Var const__137;
    public static final AFn const__139;
    public static final Var const__140;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__145;
    public static final Var const__146;
    public static final AFn const__148;
    public static final Var const__149;
    public static final AFn const__151;
    public static final Var const__152;
    public static final AFn const__154;
    public static final Var const__155;
    public static final AFn const__157;
    public static final Var const__158;
    public static final AFn const__160;
    public static final Var const__161;
    public static final AFn const__163;
    public static final Var const__164;
    public static final AFn const__166;
    public static final Var const__167;
    public static final AFn const__169;
    public static final Var const__170;
    public static final AFn const__172;
    public static final Var const__173;
    public static final AFn const__175;
    public static final Var const__176;
    public static final AFn const__178;
    public static final Var const__179;
    public static final AFn const__181;
    public static final Var const__182;
    public static final AFn const__184;
    public static final Var const__185;
    public static final AFn const__187;
    public static final Var const__188;
    public static final AFn const__190;
    public static final Var const__191;
    public static final AFn const__193;
    public static final Var const__194;
    public static final AFn const__196;
    public static final Var const__197;
    public static final AFn const__199;
    public static final Var const__200;
    public static final AFn const__202;
    public static final Var const__203;
    public static final AFn const__205;
    public static final Var const__206;
    public static final AFn const__208;
    public static final Var const__209;
    public static final AFn const__211;
    public static final Var const__212;
    public static final AFn const__214;
    public static final Var const__215;
    public static final AFn const__217;
    public static final Var const__218;
    public static final AFn const__220;
    public static final Var const__221;
    public static final AFn const__223;
    public static final Var const__224;
    public static final AFn const__226;
    public static final Var const__227;
    public static final AFn const__229;
    public static final Var const__230;
    public static final AFn const__231;
    public static final Var const__232;
    public static final AFn const__234;
    public static final Var const__235;
    public static final AFn const__237;
    public static final AFn const__239;
    public static final Var const__240;
    public static final AFn const__242;
    public static final Var const__243;
    public static final AFn const__244;
    public static final Var const__245;
    public static final Object const__246;
    public static final Var const__247;
    public static final AFn const__248;
    public static final Var const__249;
    public static final AFn const__251;
    public static final Var const__252;
    public static final AFn const__254;
    public static final Var const__255;
    public static final AFn const__257;
    public static final Var const__258;
    public static final AFn const__260;
    public static final AFn const__262;
    public static final Var const__263;
    public static final AFn const__265;
    public static final Var const__266;
    public static final AFn const__268;
    public static final Var const__269;
    public static final AFn const__271;
    public static final Var const__272;
    public static final AFn const__274;
    public static final Var const__275;
    public static final AFn const__277;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new datalog$loading__6434__auto____17825()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new datalog$fn__18043())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = const__4.set((Object)Boolean.TRUE);
        Var var = const__5;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)"query-40e7d292-b60a-40ef-b6d8-db96660e415b-");
        Var var3 = const__10;
        var3.setMeta((IPersistentMap)const__13);
        Var var4 = var3;
        var3.bindRoot((Object)new datalog$on_query_thread_QMARK_());
        Object object5 = ((IFn)new datalog$fn__18046()).invoke();
        Var var5 = const__14;
        var5.setMeta((IPersistentMap)const__16);
        Var var6 = var5;
        var5.bindRoot((Object)new datalog$qmapv());
        Object object6 = ((IFn)new datalog$fn__18050()).invoke();
        Var var7 = const__17;
        var7.setMeta((IPersistentMap)const__18);
        Var var8 = var7;
        var7.bindRoot(null);
        Var var9 = const__19.setDynamic(true);
        var9.setMeta((IPersistentMap)const__21);
        Var var10 = var9;
        var9.bindRoot(((IFn)const__22.getRawRoot()).invoke(null));
        Var var11 = const__23;
        var11.setMeta((IPersistentMap)const__25);
        Var var12 = var11;
        var11.bindRoot((Object)new datalog$maybe_cancel());
        Object object7 = ((IFn)new datalog$fn__18059()).invoke();
        Object object8 = const__26;
        Object object9 = ((IFn)const__27.getRawRoot()).invoke((Object)const__28, const__29.getRawRoot(), (Object)const__30, null);
        Object object10 = ((IFn)const__31).invoke((Object)const__28, (Object)const__32);
        Object object11 = ((IFn)const__33.getRawRoot()).invoke((Object)const__28, const__34.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__38, (Object)const__39, (Object)const__40, (Object)const__41, (Object)const__28, (Object)const__42, (Object)const__45, (Object)const__46, (Object)RT.map((Object[])new Object[]{((IFn)const__47.getRawRoot()).invoke(const__48.get(), ((IFn)const__49.getRawRoot()).invoke((Object)const__50, ((IFn)const__34.getRawRoot()).invoke((Object)const__51, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__52, const__28})))), new datalog$fn__18062(), ((IFn)const__47.getRawRoot()).invoke(const__48.get(), ((IFn)const__49.getRawRoot()).invoke((Object)const__53, ((IFn)const__34.getRawRoot()).invoke((Object)const__54, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__52, const__28})))), new datalog$fn__18083()})));
        Object object12 = ((IFn)const__55.getRawRoot()).invoke(const__28.getRawRoot());
        AFn aFn = const__56;
        Var var13 = const__57;
        var13.setMeta((IPersistentMap)const__59);
        Var var14 = var13;
        var13.bindRoot((Object)new datalog$truep());
        Var var15 = const__60;
        var15.setMeta((IPersistentMap)const__62);
        Var var16 = var15;
        var15.bindRoot((Object)new datalog$tuple());
        Var var17 = const__63;
        var17.setMeta((IPersistentMap)const__68);
        Var var18 = var17;
        var17.bindRoot((Object)new datalog$iterator());
        Var var19 = const__69;
        var19.setMeta((IPersistentMap)const__71);
        Var var20 = var19;
        var19.bindRoot((Object)new datalog$matchf());
        Var var21 = const__72;
        var21.setMeta((IPersistentMap)const__74);
        Var var22 = var21;
        var21.bindRoot((Object)new datalog$hashxf());
        Var var23 = const__75;
        var23.setMeta((IPersistentMap)const__77);
        Var var24 = var23;
        var23.bindRoot((Object)new datalog$hashyf());
        Var var25 = const__78;
        var25.setMeta((IPersistentMap)const__80);
        Var var26 = var25;
        var25.bindRoot((Object)new datalog$partv());
        Var var27 = const__81;
        var27.setMeta((IPersistentMap)const__83);
        Var var28 = var27;
        var27.bindRoot((Object)new datalog$join_project_coll());
        Var var29 = const__84;
        var29.setMeta((IPersistentMap)const__86);
        Var var30 = var29;
        var29.bindRoot((Object)new datalog$join_project_coll_with());
        Object object13 = ((IFn)const__87.getRawRoot()).invoke(const__88, const__28.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__44, new datalog$fn__18156(), const__43, new datalog$fn__18158()}));
        Object object14 = ((IFn)const__87.getRawRoot()).invoke(const__89, const__28.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__44, new datalog$fn__18160(), const__43, new datalog$fn__18162()}));
        Object object15 = ((IFn)new datalog$fn__18164()).invoke();
        Var var31 = const__90;
        var31.setMeta((IPersistentMap)const__92);
        Var var32 = var31;
        var31.bindRoot((Object)new datalog$resolve_id());
        Var var33 = const__93;
        var33.setMeta((IPersistentMap)const__95);
        Var var34 = var33;
        var33.bindRoot((Object)new datalog$dbrel());
        Object object16 = ((IFn)new datalog$fn__18182()).invoke();
        Object object17 = const__96;
        Object object18 = ((IFn)const__27.getRawRoot()).invoke((Object)const__97, const__29.getRawRoot(), (Object)const__30, null);
        Object object19 = ((IFn)const__31).invoke((Object)const__97, (Object)const__98);
        Object object20 = ((IFn)const__33.getRawRoot()).invoke((Object)const__97, const__34.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__100, (Object)const__39, (Object)const__101, (Object)const__41, (Object)const__97, (Object)const__42, (Object)const__103, (Object)const__46, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__47.getRawRoot()).invoke(const__48.get(), ((IFn)const__49.getRawRoot()).invoke((Object)const__104, ((IFn)const__34.getRawRoot()).invoke((Object)const__105, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__52, const__97})))), new datalog$fn__18185()})));
        Object object21 = ((IFn)const__55.getRawRoot()).invoke(const__97.getRawRoot());
        AFn aFn2 = const__106;
        Var var35 = const__107;
        var35.setMeta((IPersistentMap)const__109);
        Var var36 = var35;
        var35.bindRoot((Object)new datalog$extrel_coll());
        Object object22 = ((IFn)const__87.getRawRoot()).invoke(null, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new datalog$fn__18207()}));
        Object object23 = ((IFn)const__87.getRawRoot()).invoke(const__89, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new datalog$fn__18209()}));
        Object object24 = ((IFn)const__87.getRawRoot()).invoke(const__110, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new datalog$fn__18211()}));
        Object object25 = ((IFn)const__87.getRawRoot()).invoke(const__111, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new datalog$fn__18213()}));
        Object object26 = ((IFn)const__87.getRawRoot()).invoke(const__88, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new datalog$fn__18215()}));
        Var var37 = const__112;
        var37.setMeta((IPersistentMap)const__113);
        Var var38 = var37;
        var37.bindRoot(const__114);
        Var var39 = const__115;
        var39.setMeta((IPersistentMap)const__116);
        Var var40 = var39;
        var39.bindRoot(const__117);
        Var var41 = const__118;
        var41.setMeta((IPersistentMap)const__119);
        Var var42 = var41;
        var41.bindRoot(const__120);
        Var var43 = const__121;
        var43.setMeta((IPersistentMap)const__122);
        Var var44 = var43;
        var43.bindRoot(const__123);
        Var var45 = const__124;
        var45.setMeta((IPersistentMap)const__125);
        Var var46 = var45;
        var45.bindRoot(const__126);
        Var var47 = const__127;
        var47.setMeta((IPersistentMap)const__128);
        Var var48 = var47;
        var47.bindRoot(const__129);
        Object object27 = ((IFn)const__87.getRawRoot()).invoke(const__130, const__28.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__44, new datalog$fn__18231(), const__43, new datalog$fn__18233()}));
        Object object28 = ((IFn)new datalog$fn__18347()).invoke();
        Var var49 = const__131;
        var49.setMeta((IPersistentMap)const__133);
        Var var50 = var49;
        var49.bindRoot((Object)new datalog$fnrel());
        Var var51 = const__134;
        var51.setMeta((IPersistentMap)const__136);
        Var var52 = var51;
        var51.bindRoot((Object)new datalog$create_join_maps());
        Var var53 = const__137;
        var53.setMeta((IPersistentMap)const__139);
        Var var54 = var53;
        var53.bindRoot((Object)new datalog$project());
        Object object29 = ((IFn)new datalog$fn__18396()).invoke();
        Var var55 = const__140;
        var55.setMeta((IPersistentMap)const__142);
        Var var56 = var55;
        var55.bindRoot((Object)new datalog$predrel());
        Var var57 = const__143;
        var57.setMeta((IPersistentMap)const__145);
        Var var58 = var57;
        var57.bindRoot((Object)new datalog$variable_QMARK_());
        Var var59 = const__146;
        var59.setMeta((IPersistentMap)const__148);
        Var var60 = var59;
        var59.bindRoot((Object)new datalog$source_QMARK_());
        Var var61 = const__149;
        var61.setMeta((IPersistentMap)const__151);
        Var var62 = var61;
        var61.bindRoot((Object)new datalog$variable_or_blank_QMARK_());
        Var var63 = const__152;
        var63.setMeta((IPersistentMap)const__154);
        Var var64 = var63;
        var63.bindRoot((Object)new datalog$attr_QMARK_());
        Var var65 = const__155;
        var65.setMeta((IPersistentMap)const__157);
        Var var66 = var65;
        var65.bindRoot((Object)new datalog$extensional_QMARK_());
        Var var67 = const__158;
        var67.setMeta((IPersistentMap)const__160);
        Var var68 = var67;
        var67.bindRoot((Object)new datalog$adorned_pred());
        Var var69 = const__161;
        Var var70 = var69;
        var69.setMeta((IPersistentMap)const__163);
        Var var71 = const__164;
        var71.setMeta((IPersistentMap)const__166);
        Var var72 = var71;
        var71.bindRoot((Object)new datalog$not_join_clause_QMARK_());
        Var var73 = const__167;
        var73.setMeta((IPersistentMap)const__169);
        Var var74 = var73;
        var73.bindRoot((Object)new datalog$free_var_QMARK_());
        Var var75 = const__170;
        var75.setMeta((IPersistentMap)const__172);
        Var var76 = var75;
        var75.bindRoot((Object)new datalog$free_vars());
        Var var77 = const__173;
        var77.setMeta((IPersistentMap)const__175);
        Var var78 = var77;
        var77.bindRoot((Object)new datalog$unifying_vars());
        Var var79 = const__176;
        var79.setMeta((IPersistentMap)const__178);
        Var var80 = var79;
        var79.bindRoot((Object)new datalog$unifying_var_set());
        Var var81 = const__179;
        var81.setMeta((IPersistentMap)const__181);
        Var var82 = var81;
        var81.bindRoot((Object)new datalog$used_srcs());
        Var var83 = const__182;
        var83.setMeta((IPersistentMap)const__184);
        Var var84 = var83;
        var83.bindRoot((Object)new datalog$sched_in_order());
        Var var85 = const__185;
        var85.setMeta((IPersistentMap)const__187);
        Var var86 = var85;
        var85.bindRoot((Object)new datalog$push_preds());
        Var var87 = const__188;
        var87.setMeta((IPersistentMap)const__190);
        Var var88 = var87;
        var87.bindRoot((Object)new datalog$recursive_QMARK_());
        Var var89 = const__191;
        var89.setMeta((IPersistentMap)const__193);
        Var var90 = var89;
        var89.bindRoot((Object)new datalog$rules_QMARK_());
        Var var91 = const__194;
        var91.setMeta((IPersistentMap)const__196);
        Var var92 = var91;
        var91.bindRoot((Object)new datalog$scalar__GT_rel());
        Var var93 = const__197;
        var93.setMeta((IPersistentMap)const__199);
        Var var94 = var93;
        var93.bindRoot((Object)new datalog$tuple__GT_rel());
        Var var95 = const__200;
        var95.setMeta((IPersistentMap)const__202);
        Var var96 = var95;
        var95.bindRoot((Object)new datalog$compile_expr_clause());
        Var var97 = const__203;
        var97.setMeta((IPersistentMap)const__205);
        Var var98 = var97;
        var97.bindRoot((Object)new datalog$binding_type());
        Var var99 = const__206;
        var99.setMeta((IPersistentMap)const__208);
        Var var100 = var99;
        var99.bindRoot((Object)new datalog$expr_clause());
        Var var101 = const__209;
        var101.setMeta((IPersistentMap)const__211);
        Var var102 = var101;
        var101.bindRoot((Object)new datalog$lift_consts_from_preds());
        Var var103 = const__212;
        var103.setMeta((IPersistentMap)const__214);
        Var var104 = var103;
        var103.bindRoot((Object)new datalog$all_pred());
        Var var105 = const__215;
        var105.setMeta((IPersistentMap)const__217);
        Var var106 = var105;
        var105.bindRoot((Object)new datalog$to_pred());
        Var var107 = const__218;
        var107.setMeta((IPersistentMap)const__220);
        Var var108 = var107;
        var107.bindRoot((Object)new datalog$not_or_all_pred());
        Var var109 = const__221;
        var109.setMeta((IPersistentMap)const__223);
        Var var110 = var109;
        var109.bindRoot((Object)new datalog$not_or__GT_not_or_join());
        Var var111 = const__224;
        var111.setMeta((IPersistentMap)const__226);
        Var var112 = var111;
        var111.bindRoot((Object)new datalog$normalize_or_join());
        Var var113 = const__227;
        var113.setMeta((IPersistentMap)const__229);
        Var var114 = var113;
        var113.bindRoot((Object)new datalog$or_join__GT_rule_preds());
        Var var115 = const__230;
        Var var116 = var115;
        var115.setMeta((IPersistentMap)const__231);
        Var var117 = const__232;
        var117.setMeta((IPersistentMap)const__234);
        Var var118 = var117;
        var117.bindRoot((Object)new datalog$prep_clauses());
        Var var119 = const__235;
        var119.setMeta((IPersistentMap)const__237);
        Var var120 = var119;
        var119.bindRoot((Object)new datalog$callees());
        Var var121 = const__230;
        var121.setMeta((IPersistentMap)const__239);
        Var var122 = var121;
        var121.bindRoot((Object)new datalog$add_rule());
        Var var123 = const__240;
        var123.setMeta((IPersistentMap)const__242);
        Var var124 = var123;
        var123.bindRoot((Object)new datalog$rule_map());
        Var var125 = const__243;
        var125.setMeta((IPersistentMap)const__244);
        Var var126 = var125;
        var125.bindRoot(((IFn)const__245.getRawRoot()).invoke(const__240.getRawRoot(), const__246));
        Var var127 = const__247;
        var127.setMeta((IPersistentMap)const__248);
        Var var128 = var127;
        var127.bindRoot((Object)RT.var((String)"datomic.query", (String)"q"));
        Var var129 = const__249;
        var129.setMeta((IPersistentMap)const__251);
        Var var130 = var129;
        var129.bindRoot((Object)new datalog$eval_not_join());
        Var var131 = const__252;
        var131.setMeta((IPersistentMap)const__254);
        Var var132 = var131;
        var131.bindRoot((Object)new datalog$eval_clause());
        Var var133 = const__255;
        var133.setMeta((IPersistentMap)const__257);
        Var var134 = var133;
        var133.bindRoot((Object)new datalog$remap_bounds());
        Var var135 = const__258;
        var135.setMeta((IPersistentMap)const__260);
        Var var136 = var135;
        var135.bindRoot((Object)new datalog$eval_rule());
        Var var137 = const__161;
        var137.setMeta((IPersistentMap)const__262);
        Var var138 = var137;
        var137.bindRoot((Object)new datalog$eval_query());
        Var var139 = const__263;
        var139.setMeta((IPersistentMap)const__265);
        Var var140 = var139;
        var139.bindRoot((Object)new datalog$bound_consts());
        Var var141 = const__266;
        var141.setMeta((IPersistentMap)const__268);
        Var var142 = var141;
        var141.bindRoot((Object)new datalog$ranges());
        Var var143 = const__269;
        var143.setMeta((IPersistentMap)const__271);
        Var var144 = var143;
        var143.bindRoot((Object)new datalog$qsqr());
        Var var145 = const__272;
        var145.setMeta((IPersistentMap)const__274);
        Var var146 = var145;
        var145.bindRoot((Object)new datalog$rel_fn());
        Var var147 = const__275;
        var147.setMeta((IPersistentMap)const__277);
        Var var148 = var147;
        var147.bindRoot((Object)new datalog$rel_pred());
        Object v180 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.datalog");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"clojure.core", (String)"*unchecked-math*");
        const__5 = RT.var((String)"datomic.datalog", (String)"query-thread-prefix");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"datomic.datalog", (String)"on-query-thread?");
        const__13 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__14 = RT.var((String)"datomic.datalog", (String)"qmapv");
        const__16 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__17 = RT.var((String)"datomic.datalog", (String)"QUERY_DEFAULT_TIMEOUT");
        const__18 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__19 = RT.var((String)"datomic.datalog", (String)"*cancel*");
        const__21 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"dynamic"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__22 = RT.var((String)"clojure.core", (String)"atom");
        const__23 = RT.var((String)"datomic.datalog", (String)"maybe-cancel");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__26 = RT.classForName((String)"datomic.datalog.IJoin");
        const__27 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__28 = RT.var((String)"datomic.datalog", (String)"IJoin");
        const__29 = RT.var((String)"clojure.core", (String)"assoc");
        const__30 = RT.keyword(null, (String)"doc");
        const__31 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__32 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"join-project")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))})), ((IObj)Symbol.intern(null, (String)"join-project-with")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))}))));
        const__33 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__34 = RT.var((String)"clojure.core", (String)"merge");
        const__38 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.datalog.IJoin"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.datalog.IJoin")});
        const__39 = RT.keyword(null, (String)"sigs");
        const__40 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"join-project"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"join-project")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"doc"), null}), RT.keyword(null, (String)"join-project-with"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"join-project-with")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"doc"), null})});
        const__41 = RT.keyword(null, (String)"var");
        const__42 = RT.keyword(null, (String)"method-map");
        const__43 = RT.keyword(null, (String)"join-project-with");
        const__44 = RT.keyword(null, (String)"join-project");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"join-project-with"), RT.keyword(null, (String)"join-project-with"), RT.keyword(null, (String)"join-project"), RT.keyword(null, (String)"join-project")});
        const__46 = RT.keyword(null, (String)"method-builders");
        const__47 = RT.var((String)"clojure.core", (String)"intern");
        const__48 = RT.var((String)"clojure.core", (String)"*ns*");
        const__49 = RT.var((String)"clojure.core", (String)"with-meta");
        const__50 = (AFn)((IObj)Symbol.intern(null, (String)"join-project")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))}));
        const__51 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"join-project")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"doc"), null});
        const__52 = RT.keyword(null, (String)"protocol");
        const__53 = (AFn)((IObj)Symbol.intern(null, (String)"join-project-with")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))}));
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"join-project-with")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"doc"), null});
        const__55 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__56 = (AFn)Symbol.intern(null, (String)"IJoin");
        const__57 = RT.var((String)"datomic.datalog", (String)"truep");
        const__59 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__60 = RT.var((String)"datomic.datalog", (String)"tuple");
        const__62 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"arr")))), RT.keyword(null, (String)"column"), 1});
        const__63 = RT.var((String)"datomic.datalog", (String)"iterator");
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.util.Iterator"), RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"xs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Iterable")}))))), RT.keyword(null, (String)"column"), 1});
        const__69 = RT.var((String)"datomic.datalog", (String)"matchf");
        const__71 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bindings")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")}))))), RT.keyword(null, (String)"column"), 1});
        const__72 = RT.var((String)"datomic.datalog", (String)"hashxf");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bindings")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")}))))), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.datalog", (String)"hashyf");
        const__77 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bindings")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")}))))), RT.keyword(null, (String)"column"), 1});
        const__78 = RT.var((String)"datomic.datalog", (String)"partv");
        const__80 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"n")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})), (Object)((IObj)Symbol.intern(null, (String)"coll")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Iterable")}))))), RT.keyword(null, (String)"column"), 1});
        const__81 = RT.var((String)"datomic.datalog", (String)"join-project-coll");
        const__83 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"column"), 1});
        const__84 = RT.var((String)"datomic.datalog", (String)"join-project-coll-with");
        const__86 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"ys"), (Object)Symbol.intern(null, (String)"join-map"), (Object)Symbol.intern(null, (String)"project-map-x"), (Object)Symbol.intern(null, (String)"project-map-y"), (Object)Symbol.intern(null, (String)"predctor")))), RT.keyword(null, (String)"column"), 1});
        const__87 = RT.var((String)"clojure.core", (String)"extend");
        const__88 = RT.classForName((String)"java.util.Collection");
        const__89 = RT.classForName((String)"java.lang.Object");
        const__90 = RT.var((String)"datomic.datalog", (String)"resolve-id");
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__93 = RT.var((String)"datomic.datalog", (String)"dbrel");
        const__95 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Tuple.create((Object)Symbol.intern(null, (String)"e"), (Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"v"), (Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"added")), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles")))), RT.keyword(null, (String)"column"), 1});
        const__96 = RT.classForName((String)"datomic.datalog.ExtRel");
        const__97 = RT.var((String)"datomic.datalog", (String)"ExtRel");
        const__98 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"extrel")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles"))))}))));
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.datalog.ExtRel"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.datalog.ExtRel")});
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"extrel"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"extrel")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles")))), RT.keyword(null, (String)"doc"), null})});
        const__102 = RT.keyword(null, (String)"extrel");
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"extrel"), RT.keyword(null, (String)"extrel")});
        const__104 = (AFn)((IObj)Symbol.intern(null, (String)"extrel")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles"))))}));
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"extrel")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts"), (Object)Symbol.intern(null, (String)"starts"), (Object)Symbol.intern(null, (String)"whiles")))), RT.keyword(null, (String)"doc"), null});
        const__106 = (AFn)Symbol.intern(null, (String)"ExtRel");
        const__107 = RT.var((String)"datomic.datalog", (String)"extrel-coll");
        const__109 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"src"), (Object)Symbol.intern(null, (String)"consts")))), RT.keyword(null, (String)"column"), 1});
        const__110 = RT.classForName((String)"datomic.db.Db");
        const__111 = RT.classForName((String)"java.util.Map");
        const__112 = RT.var((String)"datomic.datalog", (String)"E");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__114 = 0L;
        const__115 = RT.var((String)"datomic.datalog", (String)"A");
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__117 = 1L;
        const__118 = RT.var((String)"datomic.datalog", (String)"V");
        const__119 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__120 = 2L;
        const__121 = RT.var((String)"datomic.datalog", (String)"T");
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__123 = 3L;
        const__124 = RT.var((String)"datomic.datalog", (String)"ADDED");
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__126 = 4L;
        const__127 = RT.var((String)"datomic.datalog", (String)"DCOUNT");
        const__128 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__129 = 5L;
        const__130 = RT.classForName((String)"datomic.datalog.DbRel");
        const__131 = RT.var((String)"datomic.datalog", (String)"fnrel");
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"emap"), (Object)Symbol.intern(null, (String)"consts")))), RT.keyword(null, (String)"column"), 1});
        const__134 = RT.var((String)"datomic.datalog", (String)"create-join-maps");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xbinds"), (Object)Symbol.intern(null, (String)"ybinds"), (Object)Symbol.intern(null, (String)"zbinds")))), RT.keyword(null, (String)"column"), 1});
        const__137 = RT.var((String)"datomic.datalog", (String)"project");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"xs"), (Object)Symbol.intern(null, (String)"xbinds"), (Object)Symbol.intern(null, (String)"ybinds")))), RT.keyword(null, (String)"column"), 1});
        const__140 = RT.var((String)"datomic.datalog", (String)"predrel");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"emap"), (Object)Symbol.intern(null, (String)"consts")))), RT.keyword(null, (String)"column"), 1});
        const__143 = RT.var((String)"datomic.datalog", (String)"variable?");
        const__145 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__146 = RT.var((String)"datomic.datalog", (String)"source?");
        const__148 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__149 = RT.var((String)"datomic.datalog", (String)"variable-or-blank?");
        const__151 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__152 = RT.var((String)"datomic.datalog", (String)"attr?");
        const__154 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__155 = RT.var((String)"datomic.datalog", (String)"extensional?");
        const__157 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"rules"), (Object)Symbol.intern(null, (String)"pred")))), RT.keyword(null, (String)"column"), 1});
        const__158 = RT.var((String)"datomic.datalog", (String)"adorned-pred");
        const__160 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query")), Tuple.create((Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"bindset")))), RT.keyword(null, (String)"column"), 1});
        const__161 = RT.var((String)"datomic.datalog", (String)"eval-query");
        const__163 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__164 = RT.var((String)"datomic.datalog", (String)"not-join-clause?");
        const__166 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"column"), 1});
        const__167 = RT.var((String)"datomic.datalog", (String)"free-var?");
        const__169 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__170 = RT.var((String)"datomic.datalog", (String)"free-vars");
        const__172 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"column"), 1});
        const__173 = RT.var((String)"datomic.datalog", (String)"unifying-vars");
        const__175 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__176 = RT.var((String)"datomic.datalog", (String)"unifying-var-set");
        const__178 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"column"), 1});
        const__179 = RT.var((String)"datomic.datalog", (String)"used-srcs");
        const__181 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"srcs"), (Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"column"), 1});
        const__182 = RT.var((String)"datomic.datalog", (String)"sched-in-order");
        const__184 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"srcs"), (Object)Symbol.intern(null, (String)"prog"), (Object)Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"hpred"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"hargs")), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"rule")), (Object)Symbol.intern(null, (String)"init-binds")))), RT.keyword(null, (String)"column"), 1});
        const__185 = RT.var((String)"datomic.datalog", (String)"push-preds");
        const__187 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"srcs"), (Object)Symbol.intern(null, (String)"sched")))), RT.keyword(null, (String)"column"), 1});
        const__188 = RT.var((String)"datomic.datalog", (String)"recursive?");
        const__190 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"prog"), (Object)Symbol.intern(null, (String)"pred")), Tuple.create((Object)Symbol.intern(null, (String)"prog"), (Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"seen")))), RT.keyword(null, (String)"column"), 1});
        const__191 = RT.var((String)"datomic.datalog", (String)"rules?");
        const__193 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__194 = RT.var((String)"datomic.datalog", (String)"scalar->rel");
        const__196 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__197 = RT.var((String)"datomic.datalog", (String)"tuple->rel");
        const__199 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init2() {
        const__200 = RT.var((String)"datomic.datalog", (String)"compile-expr-clause");
        const__202 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"sources"), (Object)Symbol.intern(null, (String)"vars"), (Object)Symbol.intern(null, (String)"expr"), (Object)Symbol.intern(null, (String)"bind-type"), (Object)Symbol.intern(null, (String)"binds")))), RT.keyword(null, (String)"column"), 1});
        const__203 = RT.var((String)"datomic.datalog", (String)"binding-type");
        const__205 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"binds")))), RT.keyword(null, (String)"column"), 1});
        const__206 = RT.var((String)"datomic.datalog", (String)"expr-clause");
        const__208 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"call"), (Object)Symbol.intern(null, (String)"binds"), (Object)Symbol.intern(null, (String)"xtra"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"clause"))))), RT.keyword(null, (String)"column"), 1});
        const__209 = RT.var((String)"datomic.datalog", (String)"lift-consts-from-preds");
        const__211 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"clauses")))), RT.keyword(null, (String)"column"), 1});
        const__212 = RT.var((String)"datomic.datalog", (String)"all-pred");
        const__214 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__215 = RT.var((String)"datomic.datalog", (String)"to-pred");
        const__217 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__218 = RT.var((String)"datomic.datalog", (String)"not-or-all-pred");
        const__220 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__221 = RT.var((String)"datomic.datalog", (String)"not-or->not-or-join");
        const__223 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__224 = RT.var((String)"datomic.datalog", (String)"normalize-or-join");
        const__226 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"vs"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"c"))))), RT.keyword(null, (String)"column"), 1});
        const__227 = RT.var((String)"datomic.datalog", (String)"or-join->rule-preds");
        const__229 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"vs"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"))))), RT.keyword(null, (String)"column"), 1});
        const__230 = RT.var((String)"datomic.datalog", (String)"add-rule");
        const__231 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__232 = RT.var((String)"datomic.datalog", (String)"prep-clauses");
        const__234 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"rm"), (Object)Symbol.intern(null, (String)"clauses")))), RT.keyword(null, (String)"column"), 1});
        const__235 = RT.var((String)"datomic.datalog", (String)"callees");
        const__237 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__239 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"rm"), (Object)Symbol.intern(null, (String)"rname"), (Object)Symbol.intern(null, (String)"preds")))), RT.keyword(null, (String)"column"), 1});
        const__240 = RT.var((String)"datomic.datalog", (String)"rule-map");
        const__242 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"rules")))), RT.keyword(null, (String)"column"), 1});
        const__243 = RT.var((String)"datomic.datalog", (String)"rule-cache");
        const__244 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__245 = RT.var((String)"datomic.cache", (String)"create-computing");
        const__246 = 1000L;
        const__247 = RT.var((String)"datomic.datalog", (String)"q");
        const__248 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__249 = RT.var((String)"datomic.datalog", (String)"eval-not-join");
        const__251 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"srcs"), (Object)Symbol.intern(null, (String)"prog"), (Object)((IObj)Symbol.intern(null, (String)"inrel")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Collection")})), (Object)Symbol.intern(null, (String)"inbinds"), (Object)Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"vars"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"cs"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"not-join-clause"))))), RT.keyword(null, (String)"column"), 1});
        const__252 = RT.var((String)"datomic.datalog", (String)"eval-clause");
        const__254 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"db"), Symbol.intern(null, (String)"srcs"), Symbol.intern(null, (String)"prog"), Symbol.intern(null, (String)"oprog"), Symbol.intern(null, (String)"clause"), Symbol.intern(null, (String)"predctor"), Symbol.intern(null, (String)"inrel"), Symbol.intern(null, (String)"inbinds"), Symbol.intern(null, (String)"next-binds"), Symbol.intern(null, (String)"sched-fn"), Symbol.intern(null, (String)"src"), Symbol.intern(null, (String)"ans"), Symbol.intern(null, (String)"ins"), Symbol.intern(null, (String)"top-bounds")}))), RT.keyword(null, (String)"column"), 1});
        const__255 = RT.var((String)"datomic.datalog", (String)"remap-bounds");
        const__257 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"nb"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__258 = RT.var((String)"datomic.datalog", (String)"eval-rule");
        const__260 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"db"), Symbol.intern(null, (String)"prog"), Symbol.intern(null, (String)"oprog"), Tuple.create((Object)Symbol.intern(null, (String)"head"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"rule")), Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"adorn"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"apred")), Symbol.intern(null, (String)"inrel"), Symbol.intern(null, (String)"sched-fn"), Symbol.intern(null, (String)"src"), ((IObj)Symbol.intern(null, (String)"ans")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Map")})), Symbol.intern(null, (String)"ins"), Symbol.intern(null, (String)"top-bounds"), Symbol.intern(null, (String)"nested-bounds")}))), RT.keyword(null, (String)"column"), 1});
        const__262 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"db"), Symbol.intern(null, (String)"prog"), Symbol.intern(null, (String)"oprog"), Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"adorn"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"apred")), ((IObj)Symbol.intern(null, (String)"input")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Set")})), Symbol.intern(null, (String)"sched-fn"), Symbol.intern(null, (String)"src"), Symbol.intern(null, (String)"ans"), ((IObj)Symbol.intern(null, (String)"ins")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Map")})), Symbol.intern(null, (String)"top-bounds"), Symbol.intern(null, (String)"nested-bounds")}))), RT.keyword(null, (String)"column"), 1});
        const__263 = RT.var((String)"datomic.datalog", (String)"bound-consts");
        const__265 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"srcs"), (Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__266 = RT.var((String)"datomic.datalog", (String)"ranges");
        const__268 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"in-consts"), (Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__269 = RT.var((String)"datomic.datalog", (String)"qsqr");
        const__271 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"query")), Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"sched-fn")))), RT.keyword(null, (String)"column"), 1});
        const__272 = RT.var((String)"datomic.datalog", (String)"rel-fn");
        const__274 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__275 = RT.var((String)"datomic.datalog", (String)"rel-pred");
        const__277 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        datalog__init.__init0();
        datalog__init.__init1();
        datalog__init.__init2();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.datalog__init").getClassLoader());
        try {
            datalog__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

