/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.Delay
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.PersistentArrayMap
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.Delay;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.PersistentArrayMap;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.peer$accept_new_data;
import datomic.peer$administer_system;
import datomic.peer$await_tx_result;
import datomic.peer$connect_local_database;
import datomic.peer$connect_uri;
import datomic.peer$create_connection;
import datomic.peer$create_database;
import datomic.peer$create_local_database;
import datomic.peer$create_t_watcher;
import datomic.peer$db;
import datomic.peer$delete_database;
import datomic.peer$delete_local_database;
import datomic.peer$ensure_schema_level;
import datomic.peer$fail_pending_txes;
import datomic.peer$fn__21307;
import datomic.peer$fn__21310;
import datomic.peer$fn__21348;
import datomic.peer$fn__21351;
import datomic.peer$fn__21362;
import datomic.peer$fn__21373;
import datomic.peer$fn__21401;
import datomic.peer$fn__21404;
import datomic.peer$fn__21417;
import datomic.peer$fn__21430;
import datomic.peer$fn__21445;
import datomic.peer$fn__21458;
import datomic.peer$fn__21498;
import datomic.peer$fn__21501;
import datomic.peer$fn__21599;
import datomic.peer$fn__21677;
import datomic.peer$fn__21679;
import datomic.peer$get_catalog;
import datomic.peer$get_connection;
import datomic.peer$get_cstate;
import datomic.peer$get_database_names;
import datomic.peer$integrate_lucene;
import datomic.peer$loading__6434__auto____20733;
import datomic.peer$local_connection;
import datomic.peer$peer_queue_exceeded;
import datomic.peer$rename_database;
import datomic.peer$rename_local_database;
import datomic.peer$resolve_tempid;
import datomic.peer$revert_to_log_version_1;
import datomic.peer$send_admin_request;
import datomic.peer$seq_iterable;
import datomic.peer$seq_iterator;
import datomic.peer$shutdown;
import datomic.peer$stop_connection;
import datomic.peer$submit_data_script;
import datomic.peer$t__GT_tx;
import datomic.peer$transact;
import datomic.peer$transact_all;
import datomic.peer$transactor_endpoint;
import datomic.peer$transactor_unavailable;
import datomic.peer$tx_group_endpoint;
import datomic.peer$undelete_database;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class peer__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Object const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final Var const__13;
    public static final Keyword const__14;
    public static final Var const__15;
    public static final ISeq const__16;
    public static final Var const__17;
    public static final Var const__18;
    public static final AFn const__22;
    public static final Keyword const__23;
    public static final AFn const__24;
    public static final Keyword const__25;
    public static final Keyword const__26;
    public static final AFn const__30;
    public static final Keyword const__31;
    public static final Var const__32;
    public static final Var const__33;
    public static final Var const__34;
    public static final AFn const__35;
    public static final AFn const__36;
    public static final Keyword const__37;
    public static final AFn const__38;
    public static final AFn const__39;
    public static final AFn const__40;
    public static final AFn const__41;
    public static final Var const__42;
    public static final AFn const__43;
    public static final Var const__44;
    public static final AFn const__46;
    public static final Var const__47;
    public static final AFn const__48;
    public static final Var const__49;
    public static final AFn const__50;
    public static final Var const__51;
    public static final Object const__52;
    public static final Var const__53;
    public static final ISeq const__54;
    public static final AFn const__56;
    public static final AFn const__57;
    public static final AFn const__62;
    public static final AFn const__63;
    public static final AFn const__64;
    public static final AFn const__65;
    public static final AFn const__66;
    public static final AFn const__67;
    public static final AFn const__68;
    public static final AFn const__69;
    public static final AFn const__70;
    public static final AFn const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final AFn const__78;
    public static final Var const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__84;
    public static final Var const__85;
    public static final AFn const__87;
    public static final Var const__88;
    public static final AFn const__89;
    public static final Var const__90;
    public static final AFn const__92;
    public static final Var const__93;
    public static final AFn const__95;
    public static final Object const__96;
    public static final Var const__97;
    public static final AFn const__98;
    public static final Object const__99;
    public static final Var const__100;
    public static final AFn const__102;
    public static final Var const__103;
    public static final AFn const__105;
    public static final Var const__106;
    public static final AFn const__107;
    public static final Var const__108;
    public static final Var const__109;
    public static final AFn const__110;
    public static final Var const__111;
    public static final AFn const__113;
    public static final Var const__114;
    public static final AFn const__116;
    public static final Var const__117;
    public static final AFn const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final AFn const__129;
    public static final Var const__130;
    public static final AFn const__132;
    public static final Var const__133;
    public static final AFn const__135;
    public static final Var const__136;
    public static final AFn const__138;
    public static final Var const__139;
    public static final AFn const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final Object const__155;
    public static final Var const__156;
    public static final AFn const__157;
    public static final Var const__158;
    public static final AFn const__160;
    public static final Var const__161;
    public static final AFn const__163;
    public static final Var const__164;
    public static final AFn const__166;
    public static final Var const__167;
    public static final AFn const__169;
    public static final Var const__170;
    public static final AFn const__172;
    public static final Var const__173;
    public static final AFn const__175;
    public static final Var const__176;
    public static final AFn const__178;
    public static final Var const__179;
    public static final AFn const__181;
    public static final Var const__182;
    public static final AFn const__184;
    public static final Var const__185;
    public static final AFn const__187;
    public static final Var const__188;
    public static final AFn const__190;
    public static final Var const__191;
    public static final AFn const__193;
    public static final Var const__194;
    public static final AFn const__196;
    public static final Var const__197;
    public static final AFn const__199;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new peer$loading__6434__auto____20733()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new peer$fn__21307())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = ((IFn)new peer$fn__21310()).invoke();
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new peer$get_cstate());
        Object object5 = ((IFn)new peer$fn__21348()).invoke();
        Object object6 = const__10;
        Object object7 = ((IFn)const__11.getRawRoot()).invoke((Object)const__12, const__13.getRawRoot(), (Object)const__14, null);
        Object object8 = ((IFn)const__15).invoke((Object)const__12, (Object)const__16);
        Object object9 = ((IFn)const__17.getRawRoot()).invoke((Object)const__12, const__18.getRawRoot(), ((IFn)const__13.getRawRoot()).invoke((Object)const__22, (Object)const__23, (Object)const__24, (Object)const__25, (Object)const__12, (Object)const__26, (Object)const__30, (Object)const__31, (Object)RT.map((Object[])new Object[]{((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__35, ((IFn)const__18.getRawRoot()).invoke((Object)const__36, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__12})))), new peer$fn__21351(), ((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__38, ((IFn)const__18.getRawRoot()).invoke((Object)const__39, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__12})))), new peer$fn__21362(), ((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__40, ((IFn)const__18.getRawRoot()).invoke((Object)const__41, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__12})))), new peer$fn__21373()})));
        Object object10 = ((IFn)const__42.getRawRoot()).invoke(const__12.getRawRoot());
        AFn aFn = const__43;
        Var var3 = const__44;
        var3.setMeta((IPersistentMap)const__46);
        Var var4 = var3;
        var3.bindRoot((Object)new peer$await_tx_result());
        Var var5 = const__47;
        var5.setMeta((IPersistentMap)const__48);
        Var var6 = var5;
        var5.bindRoot(new Object());
        Var var7 = const__49;
        var7.setMeta((IPersistentMap)const__50);
        Var var8 = var7;
        var7.bindRoot(((IFn)const__51.getRawRoot()).invoke());
        Object object11 = ((IFn)new peer$fn__21401()).invoke();
        Object object12 = const__52;
        Object object13 = ((IFn)const__11.getRawRoot()).invoke((Object)const__53, const__13.getRawRoot(), (Object)const__14, null);
        Object object14 = ((IFn)const__15).invoke((Object)const__53, (Object)const__54);
        Object object15 = ((IFn)const__17.getRawRoot()).invoke((Object)const__53, const__18.getRawRoot(), ((IFn)const__13.getRawRoot()).invoke((Object)const__56, (Object)const__23, (Object)const__57, (Object)const__25, (Object)const__53, (Object)const__26, (Object)const__62, (Object)const__31, (Object)RT.map((Object[])new Object[]{((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__63, ((IFn)const__18.getRawRoot()).invoke((Object)const__64, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__53})))), new peer$fn__21404(), ((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__65, ((IFn)const__18.getRawRoot()).invoke((Object)const__66, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__53})))), new peer$fn__21417(), ((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__67, ((IFn)const__18.getRawRoot()).invoke((Object)const__68, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__53})))), new peer$fn__21430(), ((IFn)const__32.getRawRoot()).invoke(const__33.get(), ((IFn)const__34.getRawRoot()).invoke((Object)const__69, ((IFn)const__18.getRawRoot()).invoke((Object)const__70, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__37, const__53})))), new peer$fn__21445()})));
        Object object16 = ((IFn)const__42.getRawRoot()).invoke(const__53.getRawRoot());
        AFn aFn2 = const__71;
        Object object17 = ((IFn)new peer$fn__21458()).invoke();
        Var var9 = const__72;
        var9.setMeta((IPersistentMap)const__74);
        Var var10 = var9;
        var9.bindRoot((Object)new peer$create_t_watcher());
        Var var11 = const__75;
        var11.setMeta((IPersistentMap)const__78);
        Var var12 = var11;
        var11.bindRoot((Object)new peer$accept_new_data());
        Var var13 = const__79;
        var13.setMeta((IPersistentMap)const__81);
        Var var14 = var13;
        var13.bindRoot((Object)new peer$transactor_unavailable());
        Var var15 = const__82;
        var15.setMeta((IPersistentMap)const__84);
        Var var16 = var15;
        var15.bindRoot((Object)new peer$peer_queue_exceeded());
        Var var17 = const__85;
        var17.setMeta((IPersistentMap)const__87);
        Var var18 = var17;
        var17.bindRoot((Object)new peer$fail_pending_txes());
        Var var19 = const__88;
        var19.setMeta((IPersistentMap)const__89);
        Var var20 = var19;
        var19.bindRoot((Object)new Delay((IFn)new peer$fn__21498()));
        Var var21 = const__90;
        Var var22 = var21;
        var21.setMeta((IPersistentMap)const__92);
        Object object18 = ((IFn)new peer$fn__21501()).invoke();
        Var var23 = const__93;
        var23.setMeta((IPersistentMap)const__95);
        Var var24 = var23;
        var23.bindRoot(const__96);
        Var var25 = const__97;
        var25.setMeta((IPersistentMap)const__98);
        Var var26 = var25;
        var25.bindRoot(const__99);
        Var var27 = const__100;
        var27.setMeta((IPersistentMap)const__102);
        Var var28 = var27;
        var27.bindRoot((Object)new peer$integrate_lucene());
        Var var29 = const__103;
        var29.setMeta((IPersistentMap)const__105);
        Var var30 = var29;
        var29.bindRoot((Object)new peer$create_connection());
        Var var31 = const__106;
        var31.setMeta((IPersistentMap)const__107);
        Var var32 = var31;
        var31.bindRoot(((IFn)const__108.getRawRoot()).invoke((Object)PersistentArrayMap.EMPTY));
        Var var33 = const__109;
        Var var34 = var33;
        var33.setMeta((IPersistentMap)const__110);
        Object object19 = ((IFn)new peer$fn__21599()).invoke();
        Var var35 = const__111;
        var35.setMeta((IPersistentMap)const__113);
        Var var36 = var35;
        var35.bindRoot((Object)new peer$local_connection());
        Var var37 = const__114;
        var37.setMeta((IPersistentMap)const__116);
        Var var38 = var37;
        var37.bindRoot((Object)new peer$connect_local_database());
        Var var39 = const__117;
        var39.setMeta((IPersistentMap)const__119);
        Var var40 = var39;
        var39.bindRoot((Object)new peer$create_local_database());
        Var var41 = const__109;
        var41.setMeta((IPersistentMap)const__121);
        Var var42 = var41;
        var41.bindRoot((Object)new peer$delete_local_database());
        Var var43 = const__122;
        var43.setMeta((IPersistentMap)const__124);
        Var var44 = var43;
        var43.bindRoot((Object)new peer$rename_local_database());
        Var var45 = const__125;
        var45.setMeta((IPersistentMap)const__127);
        Var var46 = var45;
        var45.bindRoot((Object)new peer$shutdown());
        Var var47 = const__90;
        var47.setMeta((IPersistentMap)const__129);
        Var var48 = var47;
        var47.bindRoot((Object)new peer$stop_connection());
        Var var49 = const__130;
        var49.setMeta((IPersistentMap)const__132);
        Var var50 = var49;
        var49.bindRoot((Object)new peer$get_connection());
        Var var51 = const__133;
        var51.setMeta((IPersistentMap)const__135);
        Var var52 = var51;
        var51.bindRoot((Object)new peer$revert_to_log_version_1());
        Var var53 = const__136;
        var53.setMeta((IPersistentMap)const__138);
        Var var54 = var53;
        var53.bindRoot((Object)new peer$db());
        Var var55 = const__139;
        var55.setMeta((IPersistentMap)const__141);
        Var var56 = var55;
        var55.bindRoot((Object)new peer$transact());
        Var var57 = const__142;
        var57.setMeta((IPersistentMap)const__144);
        Var var58 = var57;
        var57.bindRoot((Object)new peer$transact_all());
        Var var59 = const__145;
        var59.setMeta((IPersistentMap)const__147);
        Var var60 = var59;
        var59.bindRoot((Object)new peer$seq_iterator());
        Var var61 = const__148;
        var61.setMeta((IPersistentMap)const__150);
        Var var62 = var61;
        var61.bindRoot((Object)new peer$seq_iterable());
        Var var63 = const__151;
        var63.setMeta((IPersistentMap)const__153);
        Var var64 = var63;
        var63.bindRoot((Object)new peer$submit_data_script());
        MultiFn multiFn = ((MultiFn)const__154.getRawRoot()).addMethod(const__155, (IFn)new peer$fn__21677());
        Var var65 = const__156;
        var65.setMeta((IPersistentMap)const__157);
        Var var66 = var65;
        var65.bindRoot((Object)new Delay((IFn)new peer$fn__21679()));
        Var var67 = const__158;
        var67.setMeta((IPersistentMap)const__160);
        Var var68 = var67;
        var67.bindRoot((Object)new peer$ensure_schema_level());
        Var var69 = const__161;
        var69.setMeta((IPersistentMap)const__163);
        Var var70 = var69;
        var69.bindRoot((Object)new peer$connect_uri());
        Var var71 = const__164;
        var71.setMeta((IPersistentMap)const__166);
        Var var72 = var71;
        var71.bindRoot((Object)new peer$administer_system());
        Var var73 = const__167;
        var73.setMeta((IPersistentMap)const__169);
        Var var74 = var73;
        var73.bindRoot((Object)new peer$send_admin_request());
        Var var75 = const__170;
        var75.setMeta((IPersistentMap)const__172);
        Var var76 = var75;
        var75.bindRoot((Object)new peer$create_database());
        Var var77 = const__173;
        var77.setMeta((IPersistentMap)const__175);
        Var var78 = var77;
        var77.bindRoot((Object)new peer$delete_database());
        Var var79 = const__176;
        var79.setMeta((IPersistentMap)const__178);
        Var var80 = var79;
        var79.bindRoot((Object)new peer$rename_database());
        Var var81 = const__179;
        var81.setMeta((IPersistentMap)const__181);
        Var var82 = var81;
        var81.bindRoot((Object)new peer$get_catalog());
        Var var83 = const__182;
        var83.setMeta((IPersistentMap)const__184);
        Var var84 = var83;
        var83.bindRoot((Object)new peer$undelete_database());
        Var var85 = const__185;
        var85.setMeta((IPersistentMap)const__187);
        Var var86 = var85;
        var85.bindRoot((Object)new peer$get_database_names());
        Var var87 = const__188;
        var87.setMeta((IPersistentMap)const__190);
        Var var88 = var87;
        var87.bindRoot((Object)new peer$tx_group_endpoint());
        Var var89 = const__191;
        var89.setMeta((IPersistentMap)const__193);
        Var var90 = var89;
        var89.bindRoot((Object)new peer$transactor_endpoint());
        Var var91 = const__194;
        var91.setMeta((IPersistentMap)const__196);
        Var var92 = var91;
        var91.bindRoot((Object)new peer$t__GT_tx());
        Var var93 = const__197;
        var93.setMeta((IPersistentMap)const__199);
        Var var94 = var93;
        var93.bindRoot((Object)new peer$resolve_tempid());
        Object v117 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.peer");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.peer", (String)"get-cstate");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"state-ref"), (Object)Symbol.intern(null, (String)"or-else")))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.classForName((String)"datomic.peer.RemoteConnection");
        const__11 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__12 = RT.var((String)"datomic.peer", (String)"RemoteConnection");
        const__13 = RT.var((String)"clojure.core", (String)"assoc");
        const__14 = RT.keyword(null, (String)"doc");
        const__15 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__16 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"get-cluster")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), ((IObj)Symbol.intern(null, (String)"get-olookup")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), ((IObj)Symbol.intern(null, (String)"create-connection-state")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode"))))}))));
        const__17 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__18 = RT.var((String)"clojure.core", (String)"merge");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.peer.RemoteConnection"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.peer.RemoteConnection")});
        const__23 = RT.keyword(null, (String)"sigs");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"get-cluster"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-cluster")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), null}), RT.keyword(null, (String)"get-olookup"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-olookup")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), null}), RT.keyword(null, (String)"create-connection-state"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"create-connection-state")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode")))), RT.keyword(null, (String)"doc"), "mode is :initial for first connect from this peer, :reconnect after"})});
        const__25 = RT.keyword(null, (String)"var");
        const__26 = RT.keyword(null, (String)"method-map");
        const__30 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"get-olookup"), RT.keyword(null, (String)"get-olookup"), RT.keyword(null, (String)"create-connection-state"), RT.keyword(null, (String)"create-connection-state"), RT.keyword(null, (String)"get-cluster"), RT.keyword(null, (String)"get-cluster")});
        const__31 = RT.keyword(null, (String)"method-builders");
        const__32 = RT.var((String)"clojure.core", (String)"intern");
        const__33 = RT.var((String)"clojure.core", (String)"*ns*");
        const__34 = RT.var((String)"clojure.core", (String)"with-meta");
        const__35 = (AFn)((IObj)Symbol.intern(null, (String)"get-cluster")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__36 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-cluster")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), null});
        const__37 = RT.keyword(null, (String)"protocol");
        const__38 = (AFn)((IObj)Symbol.intern(null, (String)"get-olookup")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-olookup")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), null});
        const__40 = (AFn)((IObj)Symbol.intern(null, (String)"create-connection-state")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode"))))}));
        const__41 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"create-connection-state")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"endpoint"), (Object)Symbol.intern(null, (String)"mode")))), RT.keyword(null, (String)"doc"), "mode is :initial for first connect from this peer, :reconnect after"});
        const__42 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__43 = (AFn)Symbol.intern(null, (String)"RemoteConnection");
        const__44 = RT.var((String)"datomic.peer", (String)"await-tx-result");
        const__46 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"prom")))), RT.keyword(null, (String)"column"), 1});
        const__47 = RT.var((String)"datomic.peer", (String)"connection-lock");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__49 = RT.var((String)"datomic.peer", (String)"connection-cache");
        const__50 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__51 = RT.var((String)"datomic.cache", (String)"create-soft-limited");
        const__52 = RT.classForName((String)"datomic.peer.TWatcher");
        const__53 = RT.var((String)"datomic.peer", (String)"TWatcher");
        const__54 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"sync-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), ((IObj)Symbol.intern(null, (String)"sync-background-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t"))))})), ((IObj)Symbol.intern(null, (String)"wait-for-future-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), ((IObj)Symbol.intern(null, (String)"release-pending-syncs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db"))))}))));
        const__56 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.peer.TWatcher"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.peer.TWatcher")});
        const__57 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"sync-t"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns future that will get a database where (<= t (f db))"}), RT.keyword(null, (String)"sync-background-t"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-background-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns future that will get a database where background jobs requested up\nto t are completed.  Note that this may be before indexing is complete to t."}), RT.keyword(null, (String)"wait-for-future-t"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"wait-for-future-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Return a promise that will be delivered by release-pending-syncs."}), RT.keyword(null, (String)"release-pending-syncs"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"release-pending-syncs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db")))), RT.keyword(null, (String)"doc"), "Release any pending syncs on this db value"})});
        const__62 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"wait-for-future-t"), RT.keyword(null, (String)"wait-for-future-t"), RT.keyword(null, (String)"sync-background-t"), RT.keyword(null, (String)"sync-background-t"), RT.keyword(null, (String)"sync-t"), RT.keyword(null, (String)"sync-t"), RT.keyword(null, (String)"release-pending-syncs"), RT.keyword(null, (String)"release-pending-syncs")});
        const__63 = (AFn)((IObj)Symbol.intern(null, (String)"release-pending-syncs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db"))))}));
        const__64 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"release-pending-syncs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"new-db")))), RT.keyword(null, (String)"doc"), "Release any pending syncs on this db value"});
        const__65 = (AFn)((IObj)Symbol.intern(null, (String)"wait-for-future-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__66 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"wait-for-future-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Return a promise that will be delivered by release-pending-syncs."});
        const__67 = (AFn)((IObj)Symbol.intern(null, (String)"sync-background-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-background-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"btype"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns future that will get a database where background jobs requested up\nto t are completed.  Note that this may be before indexing is complete to t."});
        const__69 = (AFn)((IObj)Symbol.intern(null, (String)"sync-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__70 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns future that will get a database where (<= t (f db))"});
        const__71 = (AFn)Symbol.intern(null, (String)"TWatcher");
        const__72 = RT.var((String)"datomic.peer", (String)"create-t-watcher");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"db-ref")))), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.peer", (String)"accept-new-data");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"data")))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.var((String)"datomic.peer", (String)"transactor-unavailable");
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__82 = RT.var((String)"datomic.peer", (String)"peer-queue-exceeded");
        const__84 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__85 = RT.var((String)"datomic.peer", (String)"fail-pending-txes");
        const__87 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"unsent-updates-queue"), (Object)Symbol.intern(null, (String)"pending-txes")))), RT.keyword(null, (String)"column"), 1});
        const__88 = RT.var((String)"datomic.peer", (String)"start-kv-cache-delay");
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__90 = RT.var((String)"datomic.peer", (String)"stop-connection");
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__93 = RT.var((String)"datomic.peer", (String)"MAX_UNSENT_QUEUE");
        const__95 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__96 = 128L;
        const__97 = RT.var((String)"datomic.peer", (String)"MAX_LUCENE_QUEUE");
        const__98 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__99 = 128L;
    }

    public static void __init1() {
        const__100 = RT.var((String)"datomic.peer", (String)"integrate-lucene");
        const__102 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db-ref"), (Object)Symbol.intern(null, (String)"q")))), RT.keyword(null, (String)"column"), 1});
        const__103 = RT.var((String)"datomic.peer", (String)"create-connection");
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster-conf")))), RT.keyword(null, (String)"column"), 1});
        const__106 = RT.var((String)"datomic.peer", (String)"local-dbs");
        const__107 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__108 = RT.var((String)"clojure.core", (String)"atom");
        const__109 = RT.var((String)"datomic.peer", (String)"delete-local-database");
        const__110 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__111 = RT.var((String)"datomic.peer", (String)"local-connection");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dbname")))), RT.keyword(null, (String)"column"), 1});
        const__114 = RT.var((String)"datomic.peer", (String)"connect-local-database");
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dbname")))), RT.keyword(null, (String)"column"), 1});
        const__117 = RT.var((String)"datomic.peer", (String)"create-local-database");
        const__119 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dbname"), (Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dbname")))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.peer", (String)"rename-local-database");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dbname"), (Object)Symbol.intern(null, (String)"newname")))), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.peer", (String)"shutdown");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"shutdown-clojure")))), RT.keyword(null, (String)"column"), 1});
        const__129 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)RT.keyword(null, (String)"db-id")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"resolved-cluster-conf")})))), RT.keyword(null, (String)"column"), 1});
        const__130 = RT.var((String)"datomic.peer", (String)"get-connection");
        const__132 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster-conf")))), RT.keyword(null, (String)"column"), 1});
        const__133 = RT.var((String)"datomic.peer", (String)"revert-to-log-version-1");
        const__135 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"db-uri"))})))), RT.keyword(null, (String)"column"), 1});
        const__136 = RT.var((String)"datomic.peer", (String)"db");
        const__138 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"conn")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.Connection")}))))), RT.keyword(null, (String)"column"), 1});
        const__139 = RT.var((String)"datomic.peer", (String)"transact");
        const__141 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"conn")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.Connection")})), (Object)Symbol.intern(null, (String)"txdata")))), RT.keyword(null, (String)"column"), 1});
        const__142 = RT.var((String)"datomic.peer", (String)"transact-all");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"conn")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.Connection")})), (Object)Symbol.intern(null, (String)"txdata")))), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.peer", (String)"seq-iterator");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"aseq")))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.peer", (String)"seq-iterable");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"aseq")))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.peer", (String)"submit-data-script");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn"), (Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"clojure.pprint", (String)"simple-dispatch");
        const__155 = RT.classForName((String)"datomic.db.Db");
        const__156 = RT.var((String)"datomic.peer", (String)"initialize");
        const__157 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__158 = RT.var((String)"datomic.peer", (String)"ensure-schema-level");
        const__160 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn")))), RT.keyword(null, (String)"column"), 1});
        const__161 = RT.var((String)"datomic.peer", (String)"connect-uri");
        const__163 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__164 = RT.var((String)"datomic.peer", (String)"administer-system");
        const__166 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"action"))})))), RT.keyword(null, (String)"column"), 1});
        const__167 = RT.var((String)"datomic.peer", (String)"send-admin-request");
        const__169 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"request"), (Object)Symbol.intern(null, (String)"arg")))), RT.keyword(null, (String)"column"), 1});
        const__170 = RT.var((String)"datomic.peer", (String)"create-database");
        const__172 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")), Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"desc")))), RT.keyword(null, (String)"column"), 1});
        const__173 = RT.var((String)"datomic.peer", (String)"delete-database");
        const__175 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__176 = RT.var((String)"datomic.peer", (String)"rename-database");
        const__178 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)((IObj)Symbol.intern(null, (String)"new-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__179 = RT.var((String)"datomic.peer", (String)"get-catalog");
        const__181 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__182 = RT.var((String)"datomic.peer", (String)"undelete-database");
        const__184 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db-id"), (Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__185 = RT.var((String)"datomic.peer", (String)"get-database-names");
        const__187 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__188 = RT.var((String)"datomic.peer", (String)"tx-group-endpoint");
        const__190 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__191 = RT.var((String)"datomic.peer", (String)"transactor-endpoint");
        const__193 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__194 = RT.var((String)"datomic.peer", (String)"t->tx");
        const__196 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__197 = RT.var((String)"datomic.peer", (String)"resolve-tempid");
        const__199 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"tempids"), (Object)Symbol.intern(null, (String)"tempid")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        peer__init.__init0();
        peer__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.peer__init").getClassLoader());
        try {
            peer__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

