use super::*;

#[derive(Clone)]
pub struct RemoteAuthToken(pub(super) Arc<[u8; 32]>);
impl fmt::Debug for RemoteAuthToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RemoteAuthToken([REDACTED])")
    }
}
impl RemoteAuthToken {
    /// Supply 256 bits generated by a cryptographically secure RNG. Token
    /// possession grants transaction submission to this server's database.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(Arc::new(bytes))
    }
    pub fn from_hex(text: &str) -> Result<Self, SemanticError> {
        if text.len() != 64 {
            return Err(invalid(
                "remote/auth-token",
                "authentication token must contain exactly 64 hexadecimal digits",
            ));
        }
        let mut bytes = [0; 32];
        for (index, pair) in text.as_bytes().chunks_exact(2).enumerate() {
            let nibble = |byte: u8| match byte {
                b'0'..=b'9' => Some(byte - b'0'),
                b'a'..=b'f' => Some(byte - b'a' + 10),
                b'A'..=b'F' => Some(byte - b'A' + 10),
                _ => None,
            };
            bytes[index] = nibble(pair[0])
                .zip(nibble(pair[1]))
                .map(|(hi, lo)| hi * 16 + lo)
                .ok_or_else(|| {
                    invalid(
                        "remote/auth-token",
                        "authentication token must contain exactly 64 hexadecimal digits",
                    )
                })?;
        }
        Ok(Self::from_bytes(bytes))
    }
}

#[derive(Clone)]
pub struct RemoteClientConfig {
    pub(super) token: RemoteAuthToken,
    pub(super) connector: TlsConnector,
    pub(super) roots: Vec<Certificate>,
}
impl fmt::Debug for RemoteClientConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RemoteClientConfig")
            .field("token", &self.token)
            .field("tls", &"verified TLS >=1.2")
            .finish()
    }
}
impl RemoteClientConfig {
    pub fn new(token: RemoteAuthToken) -> Result<Self, SemanticError> {
        let mut builder = TlsConnector::builder();
        builder.min_protocol_version(Some(Protocol::Tlsv12));
        Ok(Self {
            token,
            connector: builder.build().map_err(tls_error)?,
            roots: Vec::new(),
        })
    }
    /// System trust remains enabled; the supplied PEM is an additional trust
    /// anchor. Hostname verification can never be disabled through this API.
    pub fn with_root_certificate_pem(mut self, pem: &[u8]) -> Result<Self, SemanticError> {
        let mut builder = TlsConnector::builder();
        builder.min_protocol_version(Some(Protocol::Tlsv12));
        self.roots
            .push(Certificate::from_pem(pem).map_err(tls_error)?);
        for root in &self.roots {
            builder.add_root_certificate(root.clone());
        }
        self.connector = builder.build().map_err(tls_error)?;
        Ok(self)
    }
}

#[derive(Clone, Copy, Debug)]
pub struct RemoteTransportConfig {
    pub max_in_flight: usize,
    /// Cumulative handshake/request/response deadline.
    pub request_timeout: Duration,
    pub max_frame_bytes: usize,
    pub max_hint_bytes: usize,
}
impl Default for RemoteTransportConfig {
    fn default() -> Self {
        Self {
            max_in_flight: 4,
            request_timeout: Duration::from_secs(30),
            max_frame_bytes: MAX_FRAME,
            max_hint_bytes: hints::MAX_WIRE_BYTES,
        }
    }
}
impl RemoteTransportConfig {
    pub fn validate(&self) -> Result<(), SemanticError> {
        if !(1..=256).contains(&self.max_in_flight)
            || self.request_timeout.is_zero()
            || Instant::now().checked_add(self.request_timeout).is_none()
            || !(48..=MAX_FRAME).contains(&self.max_frame_bytes)
            || self.max_hint_bytes > hints::MAX_WIRE_BYTES
        {
            return Err(invalid(
                "remote/config",
                "invalid bounded remote transport settings",
            ));
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RemoteWriterEndpoint {
    pub(super) identity: DatabaseIdentity,
    pub(super) address: SocketAddr,
    pub(super) tls_server_name: String,
    pub(super) holder_id: String,
    pub(super) lease_epoch: u64,
    pub(super) instance_id: Digest,
}
impl RemoteWriterEndpoint {
    pub fn identity(&self) -> &DatabaseIdentity {
        &self.identity
    }
    pub fn address(&self) -> SocketAddr {
        self.address
    }
    pub fn tls_server_name(&self) -> &str {
        &self.tls_server_name
    }
    pub fn lease_epoch(&self) -> u64 {
        self.lease_epoch
    }
    pub fn instance_id(&self) -> Digest {
        self.instance_id
    }
    pub fn holder_id(&self) -> &str {
        &self.holder_id
    }
}
