//! TLS-authenticated, lease-bound remote submission. PostgreSQL remains the
//! only durable authority; endpoint discovery contains no credentials.
use crate::encoding::{
    WireOutcome, decode_submission, decode_submission_outcome, encode_submission,
    encode_submission_outcome,
};
use crate::postgres::{TransactorLease, postgres_error, verify_schema_compatibility};
use crate::{
    CommittedTransaction, Connection, DatabaseIdentity, Digest, ErrorCategory,
    PostgresConnectionConfig, SemanticError, TransactionClient, TransactionHints,
    TransactionRequest,
};
use native_tls::{Certificate, Identity, Protocol, TlsAcceptor, TlsConnector};
use rand::TryRng;
use std::fmt;
use std::io::{self, Read, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::sync::{
    Arc,
    atomic::{AtomicBool, AtomicU64, AtomicUsize, Ordering},
};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};

#[path = "remote_hints.rs"]
mod hints;
const PROTOCOL: u32 = 1;
const HELLO: &[u8; 8] = b"ATREMOTE";
const MAX_FRAME: usize = 64 * 1024 * 1024 + 48;
const MAX_HELLO: usize = 256 * 1024;

#[derive(Clone)]
pub struct RemoteAuthToken(Arc<[u8; 32]>);
impl fmt::Debug for RemoteAuthToken {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RemoteAuthToken([REDACTED])")
    }
}
impl RemoteAuthToken {
    /// Supply 256 bits generated by a cryptographically secure RNG. Token
    /// possession grants transaction submission to this server's database.
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(Arc::new(bytes))
    }
    pub fn from_hex(text: &str) -> Result<Self, SemanticError> {
        if text.len() != 64 {
            return Err(invalid(
                "remote/auth-token",
                "authentication token must contain exactly 64 hexadecimal digits",
            ));
        }
        let mut bytes = [0; 32];
        for (index, pair) in text.as_bytes().chunks_exact(2).enumerate() {
            let nibble = |byte: u8| match byte {
                b'0'..=b'9' => Some(byte - b'0'),
                b'a'..=b'f' => Some(byte - b'a' + 10),
                b'A'..=b'F' => Some(byte - b'A' + 10),
                _ => None,
            };
            bytes[index] = nibble(pair[0])
                .zip(nibble(pair[1]))
                .map(|(hi, lo)| hi * 16 + lo)
                .ok_or_else(|| {
                    invalid(
                        "remote/auth-token",
                        "authentication token must contain exactly 64 hexadecimal digits",
                    )
                })?;
        }
        Ok(Self::from_bytes(bytes))
    }
}

#[derive(Clone)]
pub struct RemoteClientConfig {
    token: RemoteAuthToken,
    connector: TlsConnector,
    roots: Vec<Certificate>,
}
impl fmt::Debug for RemoteClientConfig {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("RemoteClientConfig")
            .field("token", &self.token)
            .field("tls", &"verified TLS >=1.2")
            .finish()
    }
}
impl RemoteClientConfig {
    pub fn new(token: RemoteAuthToken) -> Result<Self, SemanticError> {
        let mut builder = TlsConnector::builder();
        builder.min_protocol_version(Some(Protocol::Tlsv12));
        Ok(Self {
            token,
            connector: builder.build().map_err(tls_error)?,
            roots: Vec::new(),
        })
    }
    /// System trust remains enabled; the supplied PEM is an additional trust
    /// anchor. Hostname verification can never be disabled through this API.
    pub fn with_root_certificate_pem(mut self, pem: &[u8]) -> Result<Self, SemanticError> {
        let mut builder = TlsConnector::builder();
        builder.min_protocol_version(Some(Protocol::Tlsv12));
        self.roots.push(Certificate::from_pem(pem).map_err(tls_error)?);
        for root in &self.roots {builder.add_root_certificate(root.clone());}
        self.connector = builder.build().map_err(tls_error)?;
        Ok(self)
    }
}

#[derive(Clone, Copy, Debug)]
pub struct RemoteTransportConfig {
    pub max_in_flight: usize,
    /// Cumulative handshake/request/response/receipt handoff deadline.
    pub request_timeout: Duration,
    pub max_frame_bytes: usize,
    pub max_hint_bytes: usize,
}
impl Default for RemoteTransportConfig {
    fn default() -> Self {
        Self {
            max_in_flight: 4,
            request_timeout: Duration::from_secs(30),
            max_frame_bytes: MAX_FRAME,
            max_hint_bytes: hints::MAX_WIRE_BYTES,
        }
    }
}
impl RemoteTransportConfig {
    pub fn validate(&self) -> Result<(), SemanticError> {
        if !(1..=256).contains(&self.max_in_flight)
            || self.request_timeout.is_zero()
            || Instant::now().checked_add(self.request_timeout).is_none()
            || !(48..=MAX_FRAME).contains(&self.max_frame_bytes)
            || self.max_hint_bytes > hints::MAX_WIRE_BYTES
        {
            return Err(invalid(
                "remote/config",
                "invalid bounded remote transport settings",
            ));
        }
        Ok(())
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RemoteWriterEndpoint {
    identity: DatabaseIdentity,
    address: SocketAddr,
    tls_server_name: String,
    holder_id: String,
    lease_epoch: u64,
    instance_id: Digest,
}
impl RemoteWriterEndpoint {
    pub fn identity(&self) -> &DatabaseIdentity {
        &self.identity
    }
    pub fn address(&self) -> SocketAddr {
        self.address
    }
    pub fn tls_server_name(&self) -> &str {
        &self.tls_server_name
    }
    pub fn lease_epoch(&self) -> u64 {
        self.lease_epoch
    }
    pub fn instance_id(&self) -> Digest {
        self.instance_id
    }
    pub fn holder_id(&self) -> &str {
        &self.holder_id
    }
}

pub struct RemoteTransactionEndpoint {
    listener: TcpListener,
    acceptor: TlsAcceptor,
}
impl RemoteTransactionEndpoint {
    pub fn bind(address: SocketAddr, identity: Identity) -> Result<Self, SemanticError> {
        let mut builder = TlsAcceptor::builder(identity);
        builder.min_protocol_version(Some(Protocol::Tlsv12));
        let acceptor = builder.build().map_err(tls_error)?;
        let listener = TcpListener::bind(address).map_err(unavailable)?;
        listener.set_nonblocking(true).map_err(unavailable)?;
        Ok(Self { listener, acceptor })
    }
    pub fn local_addr(&self) -> Result<SocketAddr, SemanticError> {
        self.listener.local_addr().map_err(unavailable)
    }
    pub fn start(
        self,
        client: TransactionClient,
        config: RemoteTransportConfig,
        token: RemoteAuthToken,
    ) -> Result<RemoteTransactionServer, SemanticError> {
        config.validate()?;
        if !client.is_available() {
            return Err(SemanticError::new(
                ErrorCategory::Unavailable,
                "remote/writer-unavailable",
                "writer is not accepting submissions",
            ));
        }
        let lease = client.transport_lease();
        let identity = client.identity();
        let mut instance_id = [0; 32];
        rand::rngs::SysRng
            .try_fill_bytes(&mut instance_id)
            .map_err(|_| {
                SemanticError::new(
                    ErrorCategory::Unavailable,
                    "remote/randomness",
                    "operating system randomness is unavailable",
                )
            })?;
        let hello = encode_hello(&identity, &lease, instance_id)?;
        let address = self.local_addr()?;
        let stats = Arc::new(Counters::default());
        let worker_stats = Arc::clone(&stats);
        let stop = Arc::new(AtomicBool::new(false));
        let stopped = Arc::clone(&stop);
        let server_client = client.clone();
        let worker = thread::Builder::new()
            .name("atomic-remote-listener".into())
            .spawn(move || {
                let mut workers: Vec<JoinHandle<()>> = Vec::new();
                while !stopped.load(Ordering::Acquire) {
                    workers.retain_mut(|worker| !worker.is_finished());
                    match self.listener.accept() {
                        Ok((socket, _)) => {
                            if workers.len() >= config.max_in_flight {
                                worker_stats.rejected_full.fetch_add(1, Ordering::Relaxed);
                                continue;
                            }
                            let client = server_client.clone();
                            let acceptor = self.acceptor.clone();
                            let hello = hello.clone();
                            let token = token.clone();
                            let stats = Arc::clone(&worker_stats);
                            if let Ok(worker) = thread::Builder::new()
                                .name("atomic-remote-request".into())
                                .spawn(move || {
                                    let active = stats.active.fetch_add(1, Ordering::Relaxed) + 1;
                                    stats.max_active.fetch_max(active, Ordering::Relaxed);
                                    let _active = Active(Arc::clone(&stats));
                                    let _ = serve(
                                        socket, &acceptor, client, config, &token, &hello, &stats,
                                    );
                                })
                            {
                                workers.push(worker);
                            }
                        }
                        Err(error) if error.kind() == io::ErrorKind::WouldBlock => {
                            thread::sleep(Duration::from_millis(5))
                        }
                        Err(_) => break,
                    }
                }
                for worker in workers {
                    let _ = worker.join();
                }
            })
            .map_err(unavailable)?;
        Ok(RemoteTransactionServer {
            address,
            identity,
            lease,
            instance_id,
            client,
            stop,
            worker: Some(worker),
            stats,
        })
    }
}
#[derive(Default)]
struct Counters {
    active: AtomicUsize,
    max_active: AtomicUsize,
    rejected_full: AtomicU64,
    auth_rejected: AtomicU64,
    ignored_hints: AtomicU64,
    lose_next_response: AtomicBool,
}
struct Active(Arc<Counters>);
impl Drop for Active {
    fn drop(&mut self) {
        self.0.active.fetch_sub(1, Ordering::Relaxed);
    }
}
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct RemoteTransportStats {
    pub active: usize,
    pub max_active: usize,
    pub rejected_full: u64,
    pub auth_rejected: u64,
    pub ignored_hints: u64,
}
pub struct RemoteTransactionServer {
    address: SocketAddr,
    identity: DatabaseIdentity,
    lease: TransactorLease,
    instance_id: Digest,
    client: TransactionClient,
    stop: Arc<AtomicBool>,
    worker: Option<JoinHandle<()>>,
    stats: Arc<Counters>,
}
impl RemoteTransactionServer {
    /// Deterministic fault-injection seam: next confirmed commit loses its
    /// response. The transaction stays durable and must use identical-key retry.
    #[doc(hidden)]
    pub fn inject_lost_next_committed_response(&self) {
        self.stats.lose_next_response.store(true, Ordering::Release);
    }
    pub fn local_addr(&self) -> SocketAddr {
        self.address
    }
    pub fn is_available(&self) -> bool {
        self.client.is_available()
            && self
                .worker
                .as_ref()
                .is_some_and(|worker| !worker.is_finished())
    }
    pub fn stats(&self) -> RemoteTransportStats {
        RemoteTransportStats {
            active: self.stats.active.load(Ordering::Relaxed),
            max_active: self.stats.max_active.load(Ordering::Relaxed),
            rejected_full: self.stats.rejected_full.load(Ordering::Relaxed),
            auth_rejected: self.stats.auth_rejected.load(Ordering::Relaxed),
            ignored_hints: self.stats.ignored_hints.load(Ordering::Relaxed),
        }
    }
    pub fn publish(
        &self,
        connection: &PostgresConnectionConfig,
        address: SocketAddr,
        tls_server_name: &str,
    ) -> Result<RemoteWriterEndpoint, SemanticError> {
        validate_route(address, tls_server_name)?;
        if !self.is_available() {
            return Err(SemanticError::new(
                ErrorCategory::Unavailable,
                "remote/writer-unavailable",
                "writer endpoint is not available",
            ));
        }
        let mut sql = connection.connect_for("remote/register-connect")?;
        verify_schema_compatibility(&mut sql)?;
        sql.execute("INSERT INTO atomic_remote_writer_endpoints(database_id,lineage_id,holder_id,lease_epoch,instance_id,network_address,tls_server_name,protocol_version) VALUES($1,$2,$3,$4,$5,$6,$7,1) ON CONFLICT(database_id) DO UPDATE SET lineage_id=EXCLUDED.lineage_id,holder_id=EXCLUDED.holder_id,lease_epoch=EXCLUDED.lease_epoch,instance_id=EXCLUDED.instance_id,network_address=EXCLUDED.network_address,tls_server_name=EXCLUDED.tls_server_name,protocol_version=EXCLUDED.protocol_version", &[&self.identity.database_id(),&self.identity.lineage_id(),&self.lease.holder_id,&sql_epoch(self.lease.epoch)?,&&self.instance_id[..],&address.to_string(),&tls_server_name]).map_err(|e|postgres_error("remote/register",e))?;
        Ok(RemoteWriterEndpoint {
            identity: self.identity.clone(),
            address,
            tls_server_name: tls_server_name.into(),
            holder_id: self.lease.holder_id.clone(),
            lease_epoch: self.lease.epoch,
            instance_id: self.instance_id,
        })
    }
}
impl Drop for RemoteTransactionServer {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::Release);
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}

impl Connection {
    pub fn discover_remote_writer(
        &self,
        connection: &PostgresConnectionConfig,
    ) -> Result<RemoteWriterEndpoint, SemanticError> {
        let mut sql = connection.connect_for("remote/discover-connect")?;
        verify_schema_compatibility(&mut sql)?;
        let row=sql.query_opt("SELECT holder_id,lease_epoch,instance_id,network_address,tls_server_name,protocol_version FROM atomic_discover_remote_writer($1,$2)", &[&self.identity().database_id(),&self.identity().lineage_id()]).map_err(|e|postgres_error("remote/discover",e))?
            .ok_or_else(||SemanticError::new(ErrorCategory::Unavailable,"remote/no-writer","no published remote endpoint has a current lease for this database lineage"))?;
        let address: SocketAddr = row.get::<_, String>(3).parse().map_err(|_| {
            invalid(
                "remote/discovery",
                "discovered address is not a numeric TCP socket address",
            )
        })?;
        let name: String = row.get(4);
        validate_route(address, &name)?;
        if row.get::<_, i32>(5) != PROTOCOL as i32 {
            return Err(invalid(
                "remote/version",
                "discovered protocol version is unsupported",
            ));
        }
        Ok(RemoteWriterEndpoint {
            identity: self.identity().clone(),
            address,
            tls_server_name: name,
            holder_id: row.get(0),
            lease_epoch: u64::try_from(row.get::<_, i64>(1))
                .map_err(|_| invalid("remote/discovery", "invalid lease epoch"))?,
            instance_id: row
                .get::<_, Vec<u8>>(2)
                .try_into()
                .map_err(|_| invalid("remote/discovery", "invalid endpoint instance"))?,
        })
    }
    pub fn transact_remote(
        &self,
        endpoint: &RemoteWriterEndpoint,
        config: &RemoteClientConfig,
        request: TransactionRequest,
        timeout: Duration,
    ) -> Result<CommittedTransaction, SemanticError> {
        self.transact_remote_inner(endpoint, config, request, None, timeout)
    }
    pub fn transact_remote_with_hints(
        &self,
        endpoint: &RemoteWriterEndpoint,
        config: &RemoteClientConfig,
        request: TransactionRequest,
        hints: TransactionHints,
        timeout: Duration,
    ) -> Result<CommittedTransaction, SemanticError> {
        self.transact_remote_inner(endpoint, config, request, Some(hints), timeout)
    }
    fn transact_remote_inner(
        &self,
        endpoint: &RemoteWriterEndpoint,
        config: &RemoteClientConfig,
        request: TransactionRequest,
        hints: Option<TransactionHints>,
        timeout: Duration,
    ) -> Result<CommittedTransaction, SemanticError> {
        let deadline = Instant::now()
            .checked_add(timeout)
            .filter(|_| !timeout.is_zero())
            .ok_or_else(|| {
                invalid(
                    "remote/timeout",
                    "timeout must be positive and representable",
                )
            })?;
        if endpoint.identity != *self.identity() {
            return Err(SemanticError::conflict(
                "remote/database-identity",
                "endpoint and peer address different database lineages",
            ));
        }
        let request = encode_submission(self.identity(), &request)?;
        if request.len() > MAX_FRAME {
            return Err(invalid(
                "remote/frame-limit",
                "request exceeds remote frame policy",
            ));
        }
        let hints = hints
            .as_ref()
            .and_then(|hints| hints::encode(hints).ok())
            .unwrap_or_default();
        let socket = TcpStream::connect_timeout(
            &endpoint.address,
            remaining(deadline).map_err(unavailable)?,
        )
        .map_err(unavailable)?;
        socket.set_nodelay(true).map_err(unavailable)?;
        let mut tls = config
            .connector
            .connect(
                &endpoint.tls_server_name,
                DeadlineStream { socket, deadline },
            )
            .map_err(|_| {
                SemanticError::new(
                    ErrorCategory::Unavailable,
                    "remote/tls",
                    "TLS server authentication or handshake failed",
                )
            })?;
        let hello = read_frame(&mut tls, MAX_HELLO).map_err(unavailable)?;
        validate_hello(&hello, endpoint)?;
        // No request has been attempted until the server's lineage/fence and
        // instance have been checked through verified TLS.
        tls.write_all(config.token.0.as_ref())
            .map_err(unavailable)?;
        let mut authorized = [0];
        tls.read_exact(&mut authorized).map_err(unavailable)?;
        if authorized != [1] {
            return Err(SemanticError::new(
                ErrorCategory::Forbidden,
                "remote/authentication",
                "remote database authentication failed",
            ));
        }
        write_frame(&mut tls, &request).map_err(unknown)?;
        write_frame(&mut tls, &hints).map_err(unknown)?;
        let outcome = read_frame(&mut tls, MAX_FRAME).map_err(unknown)?;
        match decode_submission_outcome(&outcome).map_err(|_| {
            SemanticError::new(
                ErrorCategory::UnknownOutcome,
                "remote/invalid-outcome",
                "received no usable authenticated transaction outcome",
            )
        })? {
            WireOutcome::Rejected(error) => Err(error),
            WireOutcome::Committed(wire) => {
                let basis_t = wire.after.basis_t;
                let tx_hash = wire.after.tx_hash;
                let replayed = wire.replayed;
                let report = self.open_socket_report(*wire);
                let _ = tls.write_all(&[1]);
                Ok(CommittedTransaction {
                    basis_t,
                    tx_hash,
                    replayed,
                    report,
                })
            }
        }
    }
}

struct DeadlineStream {
    socket: TcpStream,
    deadline: Instant,
}
impl Read for DeadlineStream {
    fn read(&mut self, bytes: &mut [u8]) -> io::Result<usize> {
        self.socket
            .set_read_timeout(Some(remaining(self.deadline)?))?;
        self.socket.read(bytes)
    }
}
impl Write for DeadlineStream {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        self.socket
            .set_write_timeout(Some(remaining(self.deadline)?))?;
        self.socket.write(bytes)
    }
    fn flush(&mut self) -> io::Result<()> {
        self.socket
            .set_write_timeout(Some(remaining(self.deadline)?))?;
        self.socket.flush()
    }
}
fn serve(
    socket: TcpStream,
    acceptor: &TlsAcceptor,
    client: TransactionClient,
    config: RemoteTransportConfig,
    token: &RemoteAuthToken,
    hello: &[u8],
    stats: &Counters,
) -> io::Result<()> {
    let deadline = Instant::now() + config.request_timeout;
    let mut tls = acceptor
        .accept(DeadlineStream { socket, deadline })
        .map_err(|_| io::Error::other("TLS handshake failed"))?;
    write_frame(&mut tls, hello)?;
    let mut received = [0; 32];
    tls.read_exact(&mut received)?;
    if !openssl::memcmp::eq(&received, token.0.as_ref()) {
        stats.auth_rejected.fetch_add(1, Ordering::Relaxed);
        tls.write_all(&[0])?;
        return Ok(());
    }
    tls.write_all(&[1])?;
    let request = read_frame(&mut tls, config.max_frame_bytes)?;
    let hint_bytes = read_frame(&mut tls, config.max_hint_bytes)?;
    let result = decode_submission(&request).and_then(|(identity, request)| {
        if identity != client.identity() {
            return Err(SemanticError::conflict(
                "remote/database-identity",
                "endpoint and peer address different database lineages",
            ));
        }
        let hints = if hint_bytes.is_empty() {
            None
        } else {
            match hints::decode(&hint_bytes) {
                Ok(hints) => Some(hints),
                Err(_) => {
                    stats.ignored_hints.fetch_add(1, Ordering::Relaxed);
                    None
                }
            }
        };
        let timeout = remaining(deadline).map_err(unavailable)?;
        if let Some(hints) = hints {
            client
                .submit_with_hints(request, hints, crate::HintPrefetchOptions::default())?
                .0
                .wait(timeout)
        } else {
            client.transact(request, timeout)
        }
    });
    let outcome = encode_submission_outcome(&result).map_err(io::Error::other)?;
    if result.is_ok() && stats.lose_next_response.swap(false, Ordering::AcqRel) {
        return Err(io::Error::other("injected lost committed response"));
    }
    if outcome.len() > config.max_frame_bytes {
        return Err(io::Error::other(
            "response exceeds configured remote frame policy",
        ));
    }
    write_frame(&mut tls, &outcome)?;
    if result.is_ok() {
        let mut ack = [0];
        let _ = tls.read_exact(&mut ack);
    }
    drop(result);
    Ok(())
}
fn write_frame(stream: &mut impl Write, bytes: &[u8]) -> io::Result<()> {
    stream.write_all(&(bytes.len() as u64).to_be_bytes())?;
    stream.write_all(bytes)
}
fn read_frame(stream: &mut impl Read, maximum: usize) -> io::Result<Vec<u8>> {
    let mut length = [0; 8];
    stream.read_exact(&mut length)?;
    let length = usize::try_from(u64::from_be_bytes(length)).map_err(io::Error::other)?;
    if length > maximum {
        return Err(io::Error::other("remote frame exceeds configured limit"));
    }
    let mut bytes = vec![0; length];
    stream.read_exact(&mut bytes)?;
    Ok(bytes)
}
fn remaining(deadline: Instant) -> io::Result<Duration> {
    let left = deadline.saturating_duration_since(Instant::now());
    if left.is_zero() {
        Err(io::Error::new(
            io::ErrorKind::TimedOut,
            "remote deadline elapsed",
        ))
    } else {
        Ok(left)
    }
}
fn invalid(code: &'static str, message: &'static str) -> SemanticError {
    SemanticError::incorrect(code, message)
}
fn unavailable(error: io::Error) -> SemanticError {
    SemanticError::new(
        ErrorCategory::Unavailable,
        "remote/unavailable",
        error.to_string(),
    )
}
fn unknown(error: io::Error) -> SemanticError {
    SemanticError::new(
        ErrorCategory::UnknownOutcome,
        "remote/unknown-outcome",
        error.to_string(),
    )
}
fn tls_error(_: native_tls::Error) -> SemanticError {
    invalid(
        "remote/tls-config",
        "TLS identity or trust configuration is invalid",
    )
}
fn sql_epoch(epoch: u64) -> Result<i64, SemanticError> {
    i64::try_from(epoch)
        .map_err(|_| invalid("remote/lease-epoch", "lease epoch exceeds PostgreSQL range"))
}
fn validate_route(address: SocketAddr, name: &str) -> Result<(), SemanticError> {
    if address.port() == 0
        || address.ip().is_unspecified()
        || address.ip().is_multicast()
        || name.is_empty()
        || name.len() > 253
        || !name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b".-:".contains(&b))
    {
        Err(invalid(
            "remote/endpoint",
            "advertised endpoint requires a unicast numeric address, nonzero port and TLS server name",
        ))
    } else {
        Ok(())
    }
}
fn encode_hello(
    identity: &DatabaseIdentity,
    lease: &TransactorLease,
    instance: Digest,
) -> Result<Vec<u8>, SemanticError> {
    let mut bytes = HELLO.to_vec();
    bytes.extend_from_slice(&PROTOCOL.to_be_bytes());
    for name in [
        identity.database_id(),
        identity.lineage_id(),
        lease.holder_id.as_str(),
    ] {
        if name.len() > 64 * 1024 {
            return Err(invalid(
                "remote/identity-capacity",
                "remote identity metadata exceeds capacity",
            ));
        }
        bytes.extend_from_slice(&(name.len() as u32).to_be_bytes());
        bytes.extend_from_slice(name.as_bytes());
    }
    bytes.extend_from_slice(&lease.epoch.to_be_bytes());
    bytes.extend_from_slice(&instance);
    Ok(bytes)
}
fn validate_hello(bytes: &[u8], endpoint: &RemoteWriterEndpoint) -> Result<(), SemanticError> {
    let expected = encode_hello(
        &endpoint.identity,
        &TransactorLease {
            database_id: endpoint.identity.database_id().into(),
            holder_id: endpoint.holder_id.clone(),
            epoch: endpoint.lease_epoch,
        },
        endpoint.instance_id,
    )?;
    if bytes != expected {
        Err(SemanticError::conflict(
            "remote/stale-endpoint",
            "authenticated server does not match the discovered database, writer lease or endpoint instance",
        ))
    } else {
        Ok(())
    }
}
