/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.Numbers
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.Numbers;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.backup$add_key_prefix;
import datomic.backup$backup;
import datomic.backup$backup__GT_mem;
import datomic.backup$backup_concurrency;
import datomic.backup$backup_db;
import datomic.backup$backup_k_factory;
import datomic.backup$backup_key__GT_seg_id;
import datomic.backup$backup_roots;
import datomic.backup$backup_seg_ids;
import datomic.backup$claim;
import datomic.backup$claimed_by;
import datomic.backup$create_backup_job;
import datomic.backup$create_cluster;
import datomic.backup$create_restore_job;
import datomic.backup$create_restore_target;
import datomic.backup$create_storage;
import datomic.backup$create_value_backup;
import datomic.backup$create_value_restore;
import datomic.backup$describe_backups;
import datomic.backup$ensure_claim;
import datomic.backup$fn__19929;
import datomic.backup$fn__19931;
import datomic.backup$fn__19936;
import datomic.backup$fn__19949;
import datomic.backup$fn__19952;
import datomic.backup$fn__19965;
import datomic.backup$fn__19978;
import datomic.backup$fn__19993;
import datomic.backup$fn__20012;
import datomic.backup$fn__20026;
import datomic.backup$fn__20032;
import datomic.backup$fn__20034;
import datomic.backup$fn__20036;
import datomic.backup$fn__20056;
import datomic.backup$fn__20059;
import datomic.backup$fn__20072;
import datomic.backup$fn__20087;
import datomic.backup$fn__20141;
import datomic.backup$fn__20144;
import datomic.backup$fn__20157;
import datomic.backup$fn__20170;
import datomic.backup$fn__20269;
import datomic.backup$fn__20316;
import datomic.backup$latest_t;
import datomic.backup$loading__6434__auto____17819;
import datomic.backup$maybe_segset_storage;
import datomic.backup$mem__GT_backup;
import datomic.backup$missing_seg_ids;
import datomic.backup$read_roots;
import datomic.backup$require_latest_t;
import datomic.backup$restore;
import datomic.backup$restore_db;
import datomic.backup$restore_roots;
import datomic.backup$retry;
import datomic.backup$roots_path;
import datomic.backup$segset_storage;
import datomic.backup$storage_olookup;
import datomic.backup$strip_prefix;
import datomic.backup$subkey;
import datomic.backup$substorage;
import datomic.backup$uncached_storage_lookup;
import datomic.backup$unreadable_seg_ids;
import datomic.backup$verify_backup;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class backup__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__7;
    public static final Var const__9;
    public static final Var const__10;
    public static final AFn const__11;
    public static final Object const__12;
    public static final Var const__13;
    public static final Var const__14;
    public static final Var const__15;
    public static final Keyword const__16;
    public static final Var const__17;
    public static final ISeq const__18;
    public static final Var const__19;
    public static final Var const__20;
    public static final AFn const__24;
    public static final Keyword const__25;
    public static final AFn const__26;
    public static final Keyword const__27;
    public static final Keyword const__28;
    public static final AFn const__33;
    public static final Keyword const__34;
    public static final Var const__35;
    public static final Var const__36;
    public static final Var const__37;
    public static final AFn const__38;
    public static final AFn const__39;
    public static final Keyword const__40;
    public static final AFn const__41;
    public static final AFn const__42;
    public static final AFn const__43;
    public static final AFn const__44;
    public static final AFn const__45;
    public static final AFn const__46;
    public static final Var const__47;
    public static final AFn const__48;
    public static final Var const__49;
    public static final AFn const__53;
    public static final Var const__54;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__59;
    public static final Var const__60;
    public static final AFn const__62;
    public static final Var const__63;
    public static final AFn const__65;
    public static final Var const__66;
    public static final AFn const__68;
    public static final Var const__69;
    public static final AFn const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final Keyword const__76;
    public static final Var const__77;
    public static final AFn const__79;
    public static final Var const__80;
    public static final AFn const__82;
    public static final Var const__83;
    public static final AFn const__85;
    public static final Var const__86;
    public static final AFn const__88;
    public static final Object const__89;
    public static final Var const__90;
    public static final ISeq const__91;
    public static final AFn const__93;
    public static final AFn const__94;
    public static final AFn const__97;
    public static final AFn const__98;
    public static final AFn const__99;
    public static final AFn const__100;
    public static final AFn const__101;
    public static final AFn const__102;
    public static final Var const__103;
    public static final AFn const__105;
    public static final Object const__106;
    public static final Var const__107;
    public static final ISeq const__108;
    public static final AFn const__110;
    public static final AFn const__111;
    public static final AFn const__114;
    public static final AFn const__115;
    public static final AFn const__116;
    public static final AFn const__117;
    public static final AFn const__118;
    public static final AFn const__119;
    public static final Var const__120;
    public static final AFn const__122;
    public static final Var const__123;
    public static final AFn const__125;
    public static final Var const__126;
    public static final AFn const__127;
    public static final AFn const__136;
    public static final Var const__137;
    public static final AFn const__139;
    public static final Object const__140;
    public static final Var const__141;
    public static final AFn const__142;
    public static final AFn const__146;
    public static final Var const__147;
    public static final AFn const__149;
    public static final Var const__150;
    public static final AFn const__152;
    public static final Var const__153;
    public static final AFn const__155;
    public static final Var const__156;
    public static final AFn const__158;
    public static final Var const__159;
    public static final AFn const__161;
    public static final Var const__162;
    public static final AFn const__164;
    public static final Var const__165;
    public static final AFn const__167;
    public static final Var const__168;
    public static final AFn const__170;
    public static final Var const__171;
    public static final AFn const__173;
    public static final Var const__174;
    public static final AFn const__176;
    public static final Var const__177;
    public static final AFn const__179;
    public static final Var const__180;
    public static final AFn const__182;
    public static final Var const__183;
    public static final AFn const__184;
    public static final Var const__185;
    public static final Var const__186;
    public static final AFn const__188;
    public static final Var const__189;
    public static final AFn const__191;
    public static final Var const__192;
    public static final AFn const__194;
    public static final Var const__195;
    public static final AFn const__197;
    public static final Var const__198;
    public static final AFn const__200;
    public static final Var const__201;
    public static final AFn const__203;
    public static final Var const__204;
    public static final AFn const__206;
    public static final Var const__207;
    public static final AFn const__209;
    public static final Var const__210;
    public static final AFn const__212;
    public static final Var const__213;
    public static final AFn const__214;
    public static final Var const__215;
    public static final Var const__216;
    public static final AFn const__217;
    public static final Var const__218;
    public static final Var const__219;
    public static final Var const__220;
    public static final Var const__221;
    public static final Object const__222;
    public static final Var const__223;
    public static final AFn const__225;
    public static final Var const__226;
    public static final AFn const__228;
    public static final Var const__229;
    public static final AFn const__231;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new backup$loading__6434__auto____17819()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new backup$fn__19929())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__7);
        Var var2 = var;
        var.bindRoot(Numbers.max((Object)((IFn)const__9.getRawRoot()).invoke((Object)"datomic.fileBackupConcurrency"), (Object)((IFn)const__9.getRawRoot()).invoke((Object)"datomic.s3BackupConcurrency")));
        Var var3 = const__10;
        var3.setMeta((IPersistentMap)const__11);
        Var var4 = var3;
        var3.bindRoot(((IFn)const__9.getRawRoot()).invoke((Object)"datomic.backupBranchConcurrency"));
        Object object4 = ((IFn)new backup$fn__19931()).invoke();
        Object object5 = ((IFn)new backup$fn__19936()).invoke();
        Object object6 = ((IFn)new backup$fn__19949()).invoke();
        Object object7 = const__12;
        Object object8 = ((IFn)const__13.getRawRoot()).invoke((Object)const__14, const__15.getRawRoot(), (Object)const__16, null);
        Object object9 = ((IFn)const__17).invoke((Object)const__14, (Object)const__18);
        Object object10 = ((IFn)const__19.getRawRoot()).invoke((Object)const__14, const__20.getRawRoot(), ((IFn)const__15.getRawRoot()).invoke((Object)const__24, (Object)const__25, (Object)const__26, (Object)const__27, (Object)const__14, (Object)const__28, (Object)const__33, (Object)const__34, (Object)RT.map((Object[])new Object[]{((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__38, ((IFn)const__20.getRawRoot()).invoke((Object)const__39, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__14})))), new backup$fn__19952(), ((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__41, ((IFn)const__20.getRawRoot()).invoke((Object)const__42, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__14})))), new backup$fn__19965(), ((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__43, ((IFn)const__20.getRawRoot()).invoke((Object)const__44, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__14})))), new backup$fn__19978(), ((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__45, ((IFn)const__20.getRawRoot()).invoke((Object)const__46, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__14})))), new backup$fn__19993()})));
        Object object11 = ((IFn)const__47.getRawRoot()).invoke(const__14.getRawRoot());
        AFn aFn = const__48;
        Var var5 = const__49;
        var5.setMeta((IPersistentMap)const__53);
        Var var6 = var5;
        var5.bindRoot((Object)new backup$subkey());
        Var var7 = const__54;
        var7.setMeta((IPersistentMap)const__56);
        Var var8 = var7;
        var7.bindRoot((Object)new backup$strip_prefix());
        Var var9 = const__57;
        var9.setMeta((IPersistentMap)const__59);
        Var var10 = var9;
        var9.bindRoot((Object)new backup$add_key_prefix());
        Var var11 = const__60;
        var11.setMeta((IPersistentMap)const__62);
        Var var12 = var11;
        var11.bindRoot((Object)new backup$backup_k_factory());
        Object object12 = ((IFn)new backup$fn__20012()).invoke();
        Var var13 = const__63;
        var13.setMeta((IPersistentMap)const__65);
        Var var14 = var13;
        var13.bindRoot((Object)new backup$substorage());
        Var var15 = const__66;
        var15.setMeta((IPersistentMap)const__68);
        Var var16 = var15;
        var15.bindRoot((Object)new backup$claim());
        Var var17 = const__69;
        var17.setMeta((IPersistentMap)const__71);
        Var var18 = var17;
        var17.bindRoot((Object)new backup$claimed_by());
        Var var19 = const__72;
        var19.setMeta((IPersistentMap)const__74);
        Var var20 = var19;
        var19.bindRoot((Object)new backup$ensure_claim());
        Object object13 = ((IFn)new backup$fn__20026()).invoke();
        MultiFn multiFn = ((MultiFn)const__75.getRawRoot()).addMethod((Object)"file", (IFn)new backup$fn__20032());
        MultiFn multiFn2 = ((MultiFn)const__75.getRawRoot()).addMethod((Object)"s3", (IFn)new backup$fn__20034());
        MultiFn multiFn3 = ((MultiFn)const__75.getRawRoot()).addMethod((Object)const__76, (IFn)new backup$fn__20036());
        Var var21 = const__77;
        var21.setMeta((IPersistentMap)const__79);
        Var var22 = var21;
        var21.bindRoot((Object)new backup$create_storage());
        Var var23 = const__80;
        var23.setMeta((IPersistentMap)const__82);
        Var var24 = var23;
        var23.bindRoot((Object)new backup$retry());
        Var var25 = const__83;
        var25.setMeta((IPersistentMap)const__85);
        Var var26 = var25;
        var25.bindRoot((Object)new backup$uncached_storage_lookup());
        Var var27 = const__86;
        var27.setMeta((IPersistentMap)const__88);
        Var var28 = var27;
        var27.bindRoot((Object)new backup$storage_olookup());
        Object object14 = ((IFn)new backup$fn__20056()).invoke();
        Object object15 = const__89;
        Object object16 = ((IFn)const__13.getRawRoot()).invoke((Object)const__90, const__15.getRawRoot(), (Object)const__16, null);
        Object object17 = ((IFn)const__17).invoke((Object)const__90, (Object)const__91);
        Object object18 = ((IFn)const__19.getRawRoot()).invoke((Object)const__90, const__20.getRawRoot(), ((IFn)const__15.getRawRoot()).invoke((Object)const__93, (Object)const__25, (Object)const__94, (Object)const__27, (Object)const__90, (Object)const__28, (Object)const__97, (Object)const__34, (Object)RT.map((Object[])new Object[]{((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__98, ((IFn)const__20.getRawRoot()).invoke((Object)const__99, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__90})))), new backup$fn__20059(), ((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__100, ((IFn)const__20.getRawRoot()).invoke((Object)const__101, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__90})))), new backup$fn__20072()})));
        Object object19 = ((IFn)const__47.getRawRoot()).invoke(const__90.getRawRoot());
        AFn aFn2 = const__102;
        Object object20 = ((IFn)new backup$fn__20087()).invoke();
        Var var29 = const__103;
        var29.setMeta((IPersistentMap)const__105);
        Var var30 = var29;
        var29.bindRoot((Object)new backup$create_value_backup());
        Object object21 = ((IFn)new backup$fn__20141()).invoke();
        Object object22 = const__106;
        Object object23 = ((IFn)const__13.getRawRoot()).invoke((Object)const__107, const__15.getRawRoot(), (Object)const__16, null);
        Object object24 = ((IFn)const__17).invoke((Object)const__107, (Object)const__108);
        Object object25 = ((IFn)const__19.getRawRoot()).invoke((Object)const__107, const__20.getRawRoot(), ((IFn)const__15.getRawRoot()).invoke((Object)const__110, (Object)const__25, (Object)const__111, (Object)const__27, (Object)const__107, (Object)const__28, (Object)const__114, (Object)const__34, (Object)RT.map((Object[])new Object[]{((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__115, ((IFn)const__20.getRawRoot()).invoke((Object)const__116, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__107})))), new backup$fn__20144(), ((IFn)const__35.getRawRoot()).invoke(const__36.get(), ((IFn)const__37.getRawRoot()).invoke((Object)const__117, ((IFn)const__20.getRawRoot()).invoke((Object)const__118, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, const__107})))), new backup$fn__20157()})));
        Object object26 = ((IFn)const__47.getRawRoot()).invoke(const__107.getRawRoot());
        AFn aFn3 = const__119;
        Object object27 = ((IFn)new backup$fn__20170()).invoke();
        Var var31 = const__120;
        var31.setMeta((IPersistentMap)const__122);
        Var var32 = var31;
        var31.bindRoot((Object)new backup$create_value_restore());
        Var var33 = const__123;
        var33.setMeta((IPersistentMap)const__125);
        Var var34 = var33;
        var33.bindRoot((Object)new backup$roots_path());
        Var var35 = const__126;
        var35.setMeta((IPersistentMap)const__127);
        Var var36 = var35;
        var35.bindRoot((Object)const__136);
        Var var37 = const__137;
        var37.setMeta((IPersistentMap)const__139);
        Var var38 = var37;
        var37.bindRoot(const__140);
        Var var39 = const__141;
        var39.setMeta((IPersistentMap)const__142);
        Var var40 = var39;
        var39.bindRoot((Object)const__146);
        Var var41 = const__147;
        var41.setMeta((IPersistentMap)const__149);
        Var var42 = var41;
        var41.bindRoot((Object)new backup$mem__GT_backup());
        Var var43 = const__150;
        var43.setMeta((IPersistentMap)const__152);
        Var var44 = var43;
        var43.bindRoot((Object)new backup$backup__GT_mem());
        Var var45 = const__153;
        var45.setMeta((IPersistentMap)const__155);
        Var var46 = var45;
        var45.bindRoot((Object)new backup$backup_roots());
        Var var47 = const__156;
        var47.setMeta((IPersistentMap)const__158);
        Var var48 = var47;
        var47.bindRoot((Object)new backup$read_roots());
        Var var49 = const__159;
        var49.setMeta((IPersistentMap)const__161);
        Var var50 = var49;
        var49.bindRoot((Object)new backup$describe_backups());
        Var var51 = const__162;
        var51.setMeta((IPersistentMap)const__164);
        Var var52 = var51;
        var51.bindRoot((Object)new backup$restore_roots());
        Var var53 = const__165;
        var53.setMeta((IPersistentMap)const__167);
        Var var54 = var53;
        var53.bindRoot((Object)new backup$create_backup_job());
        Var var55 = const__168;
        var55.setMeta((IPersistentMap)const__170);
        Var var56 = var55;
        var55.bindRoot((Object)new backup$create_restore_job());
        Var var57 = const__171;
        var57.setMeta((IPersistentMap)const__173);
        Var var58 = var57;
        var57.bindRoot((Object)new backup$create_cluster());
        Var var59 = const__174;
        var59.setMeta((IPersistentMap)const__176);
        Var var60 = var59;
        var59.bindRoot((Object)new backup$create_restore_target());
        Var var61 = const__177;
        var61.setMeta((IPersistentMap)const__179);
        Var var62 = var61;
        var61.bindRoot((Object)new backup$latest_t());
        Var var63 = const__180;
        var63.setMeta((IPersistentMap)const__182);
        Var var64 = var63;
        var63.bindRoot((Object)new backup$require_latest_t());
        Var var65 = const__183;
        var65.setMeta((IPersistentMap)const__184);
        Var var66 = var65;
        var65.bindRoot(const__185.getRawRoot());
        Var var67 = const__186;
        var67.setMeta((IPersistentMap)const__188);
        Var var68 = var67;
        var67.bindRoot((Object)new backup$restore_db());
        Var var69 = const__189;
        var69.setMeta((IPersistentMap)const__191);
        Var var70 = var69;
        var69.bindRoot((Object)new backup$backup_key__GT_seg_id());
        Object object28 = ((IFn)new backup$fn__20269()).invoke();
        Var var71 = const__192;
        var71.setMeta((IPersistentMap)const__194);
        Var var72 = var71;
        var71.bindRoot((Object)new backup$backup_seg_ids());
        Var var73 = const__195;
        var73.setMeta((IPersistentMap)const__197);
        Var var74 = var73;
        var73.bindRoot((Object)new backup$segset_storage());
        Var var75 = const__198;
        var75.setMeta((IPersistentMap)const__200);
        Var var76 = var75;
        var75.bindRoot((Object)new backup$maybe_segset_storage());
        Var var77 = const__201;
        var77.setMeta((IPersistentMap)const__203);
        Var var78 = var77;
        var77.bindRoot((Object)new backup$backup_db());
        Var var79 = const__204;
        var79.setMeta((IPersistentMap)const__206);
        Var var80 = var79;
        var79.bindRoot((Object)new backup$backup_concurrency());
        Var var81 = const__207;
        var81.setMeta((IPersistentMap)const__209);
        Var var82 = var81;
        var81.bindRoot((Object)new backup$backup());
        Var var83 = const__210;
        var83.setMeta((IPersistentMap)const__212);
        Var var84 = var83;
        var83.bindRoot((Object)new backup$restore());
        Var var85 = const__213;
        var85.setMeta((IPersistentMap)const__214);
        Var var86 = var85;
        var85.bindRoot(const__215.getRawRoot());
        Var var87 = const__216;
        var87.setMeta((IPersistentMap)const__217);
        Var var88 = var87;
        var87.bindRoot(((IFn)const__218.getRawRoot()).invoke(((IFn)const__219.getRawRoot()).invoke(), ((IFn)const__220.getRawRoot()).invoke((Object)new backup$fn__20316(), ((IFn)const__221.getRawRoot()).invoke(const__222))));
        Var var89 = const__223;
        var89.setMeta((IPersistentMap)const__225);
        Var var90 = var89;
        var89.bindRoot((Object)new backup$missing_seg_ids());
        Var var91 = const__226;
        var91.setMeta((IPersistentMap)const__228);
        Var var92 = var91;
        var91.bindRoot((Object)new backup$unreadable_seg_ids());
        Var var93 = const__229;
        var93.setMeta((IPersistentMap)const__231);
        Var var94 = var93;
        var93.bindRoot((Object)new backup$verify_backup());
        Object v129 = null;
        Object v130 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.backup");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.backup", (String)"pool-size");
        const__7 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__9 = RT.var((String)"datomic.config", (String)"property");
        const__10 = RT.var((String)"datomic.backup", (String)"backup-branch-size");
        const__11 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__12 = RT.classForName((String)"datomic.backup.Storage");
        const__13 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__14 = RT.var((String)"datomic.backup", (String)"Storage");
        const__15 = RT.var((String)"clojure.core", (String)"assoc");
        const__16 = RT.keyword(null, (String)"doc");
        const__17 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__18 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf"))))})), ((IObj)Symbol.intern(null, (String)"list-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix"))))})), ((IObj)Symbol.intern(null, (String)"exists?")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), ((IObj)Symbol.intern(null, (String)"retrieve")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))}))));
        const__19 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__20 = RT.var((String)"clojure.core", (String)"merge");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.backup.Storage"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.backup.Storage")});
        const__25 = RT.keyword(null, (String)"sigs");
        const__26 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"store"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf")))), RT.keyword(null, (String)"doc"), "Place a byte buffer into storage under pathkey.\n    Returns {:k k} on success."}), RT.keyword(null, (String)"list-keys"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"list-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix")))), RT.keyword(null, (String)"doc"), "Returns {:ks keys} on success."}), RT.keyword(null, (String)"exists?"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"exists?")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns a boolean"}), RT.keyword(null, (String)"retrieve"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"retrieve")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns {:v buf} if path exists."})});
        const__27 = RT.keyword(null, (String)"var");
        const__28 = RT.keyword(null, (String)"method-map");
        const__33 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"list-keys"), RT.keyword(null, (String)"list-keys"), RT.keyword(null, (String)"store"), RT.keyword(null, (String)"store"), RT.keyword(null, (String)"retrieve"), RT.keyword(null, (String)"retrieve"), RT.keyword(null, (String)"exists?"), RT.keyword(null, (String)"exists?")});
        const__34 = RT.keyword(null, (String)"method-builders");
        const__35 = RT.var((String)"clojure.core", (String)"intern");
        const__36 = RT.var((String)"clojure.core", (String)"*ns*");
        const__37 = RT.var((String)"clojure.core", (String)"with-meta");
        const__38 = (AFn)((IObj)Symbol.intern(null, (String)"exists?")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))}));
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"exists?")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns a boolean"});
        const__40 = RT.keyword(null, (String)"protocol");
        const__41 = (AFn)((IObj)Symbol.intern(null, (String)"list-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix"))))}));
        const__42 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"list-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"prefix")))), RT.keyword(null, (String)"doc"), "Returns {:ks keys} on success."});
        const__43 = (AFn)((IObj)Symbol.intern(null, (String)"store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf"))))}));
        const__44 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf")))), RT.keyword(null, (String)"doc"), "Place a byte buffer into storage under pathkey.\n    Returns {:k k} on success."});
        const__45 = (AFn)((IObj)Symbol.intern(null, (String)"retrieve")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))}));
        const__46 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"retrieve")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns {:v buf} if path exists."});
        const__47 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__48 = (AFn)Symbol.intern(null, (String)"Storage");
        const__49 = RT.var((String)"datomic.backup", (String)"subkey");
        const__53 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"prefix"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__54 = RT.var((String)"datomic.backup", (String)"strip-prefix");
        const__56 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"prefix"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__57 = RT.var((String)"datomic.backup", (String)"add-key-prefix");
        const__59 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__60 = RT.var((String)"datomic.backup", (String)"backup-k-factory");
        const__62 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"backup-version")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")}))))), RT.keyword(null, (String)"column"), 1});
        const__63 = RT.var((String)"datomic.backup", (String)"substorage");
        const__65 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage"), (Object)Symbol.intern(null, (String)"prefix")))), RT.keyword(null, (String)"column"), 1});
        const__66 = RT.var((String)"datomic.backup", (String)"claim");
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage"), (Object)Symbol.intern(null, (String)"id")))), RT.keyword(null, (String)"column"), 1});
        const__69 = RT.var((String)"datomic.backup", (String)"claimed-by");
        const__71 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage")))), RT.keyword(null, (String)"column"), 1});
        const__72 = RT.var((String)"datomic.backup", (String)"ensure-claim");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage"), (Object)Symbol.intern(null, (String)"id")))), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.backup", (String)"create-storage*");
        const__76 = RT.keyword(null, (String)"default");
        const__77 = RT.var((String)"datomic.backup", (String)"create-storage");
        const__79 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage-uri")), Tuple.create((Object)Symbol.intern(null, (String)"storage-uri"), (Object)Symbol.intern(null, (String)"sse?")))), RT.keyword(null, (String)"column"), 1});
        const__80 = RT.var((String)"datomic.backup", (String)"retry");
        const__82 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__83 = RT.var((String)"datomic.backup", (String)"uncached-storage-lookup");
        const__85 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage")))), RT.keyword(null, (String)"column"), 1});
        const__86 = RT.var((String)"datomic.backup", (String)"storage-olookup");
        const__88 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage"), (Object)Symbol.intern(null, (String)"backup-version")))), RT.keyword(null, (String)"column"), 1});
        const__89 = RT.classForName((String)"datomic.backup.IValueBackup");
        const__90 = RT.var((String)"datomic.backup", (String)"IValueBackup");
        const__91 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"backup-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k"))))})), ((IObj)Symbol.intern(null, (String)"backup-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))}))));
        const__93 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.backup.IValueBackup"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.backup.IValueBackup")});
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"backup-val"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"backup-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k")))), RT.keyword(null, (String)"doc"), "Backup a segment from storage k to backup backup-k."}), RT.keyword(null, (String)"backup-node"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"backup-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node")))), RT.keyword(null, (String)"doc"), "Backup a node's children, then the node."})});
        const__97 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"backup-node"), RT.keyword(null, (String)"backup-node"), RT.keyword(null, (String)"backup-val"), RT.keyword(null, (String)"backup-val")});
        const__98 = (AFn)((IObj)Symbol.intern(null, (String)"backup-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))}));
        const__99 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"backup-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node")))), RT.keyword(null, (String)"doc"), "Backup a node's children, then the node."});
    }

    public static void __init1() {
        const__100 = (AFn)((IObj)Symbol.intern(null, (String)"backup-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k"))))}));
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"backup-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"backup-k")))), RT.keyword(null, (String)"doc"), "Backup a segment from storage k to backup backup-k."});
        const__102 = (AFn)Symbol.intern(null, (String)"IValueBackup");
        const__103 = RT.var((String)"datomic.backup", (String)"create-value-backup");
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"from-cluster"), (Object)Symbol.intern(null, (String)"to-storage"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"incremental?"), (Object)Symbol.intern(null, (String)"ids->nodes"), (Object)Symbol.intern(null, (String)"concurrency"))}))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"from-cluster"), (Object)Symbol.intern(null, (String)"to-storage"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"ids->nodes"), (Object)Symbol.intern(null, (String)"concurrency"))})))), RT.keyword(null, (String)"column"), 1});
        const__106 = RT.classForName((String)"datomic.backup.IValueRestore");
        const__107 = RT.var((String)"datomic.backup", (String)"IValueRestore");
        const__108 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"restore-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), ((IObj)Symbol.intern(null, (String)"restore-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))}))));
        const__110 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.backup.IValueRestore"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.backup.IValueRestore")});
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"restore-val"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"restore-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Restore segment with key k from backup to storage."}), RT.keyword(null, (String)"restore-node"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"restore-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node")))), RT.keyword(null, (String)"doc"), "Restores a node's children, then the node"})});
        const__114 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"restore-val"), RT.keyword(null, (String)"restore-val"), RT.keyword(null, (String)"restore-node"), RT.keyword(null, (String)"restore-node")});
        const__115 = (AFn)((IObj)Symbol.intern(null, (String)"restore-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))}));
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"restore-node")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"node")))), RT.keyword(null, (String)"doc"), "Restores a node's children, then the node"});
        const__117 = (AFn)((IObj)Symbol.intern(null, (String)"restore-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))}));
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"restore-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Restore segment with key k from backup to storage."});
        const__119 = (AFn)Symbol.intern(null, (String)"IValueRestore");
        const__120 = RT.var((String)"datomic.backup", (String)"create-value-restore");
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"from-storage"), Symbol.intern(null, (String)"to-cluster"), Symbol.intern(null, (String)"backup-version"), Symbol.intern(null, (String)"progress"), Symbol.intern(null, (String)"incremental?"), Symbol.intern(null, (String)"concurrency"), Symbol.intern(null, (String)"ids->nodes")})}))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"from-storage"), (Object)Symbol.intern(null, (String)"to-cluster"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"concurrency"), (Object)Symbol.intern(null, (String)"ids->nodes"))})))), RT.keyword(null, (String)"column"), 1});
        const__123 = RT.var((String)"datomic.backup", (String)"roots-path");
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__126 = RT.var((String)"datomic.backup", (String)"v1->v2-keymap");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"index-root-id"), RT.keyword((String)"index", (String)"root-id"), RT.keyword(null, (String)"log-root-id"), RT.keyword((String)"log", (String)"root-id"), RT.keyword(null, (String)"log-tail"), RT.keyword((String)"log", (String)"tail"), RT.keyword(null, (String)"db-id"), RT.keyword((String)"db", (String)"id")});
        const__137 = RT.var((String)"datomic.backup", (String)"BACKUP_VERSION");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__140 = 3L;
        const__141 = RT.var((String)"datomic.backup", (String)"mem-keys");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__146 = (AFn)RT.vector((Object[])new Object[]{RT.keyword(null, (String)"index-root-id"), RT.keyword(null, (String)"log-root-id"), RT.keyword(null, (String)"log-tail"), RT.keyword(null, (String)"db-id"), RT.keyword((String)"log", (String)"version"), RT.keyword((String)"index", (String)"version"), RT.keyword((String)"backup", (String)"version")});
        const__147 = RT.var((String)"datomic.backup", (String)"mem->backup");
        const__149 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"roots")))), RT.keyword(null, (String)"column"), 1});
        const__150 = RT.var((String)"datomic.backup", (String)"backup->mem");
        const__152 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"roots")))), RT.keyword(null, (String)"column"), 1});
        const__153 = RT.var((String)"datomic.backup", (String)"backup-roots");
        const__155 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"job"), (Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"to-storage")))), RT.keyword(null, (String)"column"), 1});
        const__156 = RT.var((String)"datomic.backup", (String)"read-roots");
        const__158 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"from-storage")))), RT.keyword(null, (String)"column"), 1});
        const__159 = RT.var((String)"datomic.backup", (String)"describe-backups");
        const__161 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage")))), RT.keyword(null, (String)"column"), 1});
        const__162 = RT.var((String)"datomic.backup", (String)"restore-roots");
        const__164 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"job"), (Object)Symbol.intern(null, (String)"cluster")))), RT.keyword(null, (String)"column"), 1});
        const__165 = RT.var((String)"datomic.backup", (String)"create-backup-job");
        const__167 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"lookup")))), RT.keyword(null, (String)"column"), 1});
        const__168 = RT.var((String)"datomic.backup", (String)"create-restore-job");
        const__170 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"storage"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__171 = RT.var((String)"datomic.backup", (String)"create-cluster");
        const__173 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster-conf"), (Object)Symbol.intern(null, (String)"concurrency")))), RT.keyword(null, (String)"column"), 1});
        const__174 = RT.var((String)"datomic.backup", (String)"create-restore-target");
        const__176 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"desc"), (Object)Symbol.intern(null, (String)"concurrency")))), RT.keyword(null, (String)"column"), 1});
        const__177 = RT.var((String)"datomic.backup", (String)"latest-t");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__180 = RT.var((String)"datomic.backup", (String)"require-latest-t");
        const__182 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__183 = RT.var((String)"datomic.backup", (String)"create-ids->nodes");
        const__184 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__185 = RT.var((String)"datomic.treewalk", (String)"create-ids->nodes");
        const__186 = RT.var((String)"datomic.backup", (String)"restore-db");
        const__188 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"from-storage"), (Object)Symbol.intern(null, (String)"t"))}), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"to-uri"))}), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"concurrency"), (Object)Symbol.intern(null, (String)"incremental?")))), RT.keyword(null, (String)"column"), 1});
        const__189 = RT.var((String)"datomic.backup", (String)"backup-key->seg-id");
        const__191 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"s")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__192 = RT.var((String)"datomic.backup", (String)"backup-seg-ids");
        const__194 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"backup-storage"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__195 = RT.var((String)"datomic.backup", (String)"segset-storage");
        const__197 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"backup-storage"), (Object)Symbol.intern(null, (String)"seg-id-set")))), RT.keyword(null, (String)"column"), 1});
        const__198 = RT.var((String)"datomic.backup", (String)"maybe-segset-storage");
    }

    public static void __init2() {
        const__200 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"backup-storage")))), RT.keyword(null, (String)"column"), 1});
        const__201 = RT.var((String)"datomic.backup", (String)"backup-db");
        const__203 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"from-uri"), (Object)Symbol.intern(null, (String)"to-storage"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"concurrency"), (Object)Symbol.intern(null, (String)"incremental?")))), RT.keyword(null, (String)"column"), 1});
        const__204 = RT.var((String)"datomic.backup", (String)"backup-concurrency");
        const__206 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__207 = RT.var((String)"datomic.backup", (String)"backup");
        const__209 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"from-conn-uri"), (Object)Symbol.intern(null, (String)"to-storage-uri"), (Object)Symbol.intern(null, (String)"sse?"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"incremental?")))), RT.keyword(null, (String)"column"), 1});
        const__210 = RT.var((String)"datomic.backup", (String)"restore");
        const__212 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"from-storage-uri"), (Object)Symbol.intern(null, (String)"to-uri"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"incremental?")))), RT.keyword(null, (String)"column"), 1});
        const__213 = RT.var((String)"datomic.backup", (String)"gc-deleted-dbs");
        const__214 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__215 = RT.var((String)"datomic.garbage", (String)"gc-deleted-dbs");
        const__216 = RT.var((String)"datomic.backup", (String)"prefixes");
        const__217 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__218 = RT.var((String)"clojure.core", (String)"into");
        const__219 = RT.var((String)"clojure.core", (String)"sorted-set");
        const__220 = RT.var((String)"clojure.core", (String)"mapcat");
        const__221 = RT.var((String)"clojure.core", (String)"range");
        const__222 = 256L;
        const__223 = RT.var((String)"datomic.backup", (String)"missing-seg-ids");
        const__225 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"backup-storage"), (Object)Symbol.intern(null, (String)"seg-id-set")))), RT.keyword(null, (String)"column"), 1});
        const__226 = RT.var((String)"datomic.backup", (String)"unreadable-seg-ids");
        const__228 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"seg-ids")))), RT.keyword(null, (String)"column"), 1});
        const__229 = RT.var((String)"datomic.backup", (String)"verify-backup");
        const__231 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"backup-uri"), (Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"read-all"))})))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        backup__init.__init0();
        backup__init.__init1();
        backup__init.__init2();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.backup__init").getClassLoader());
        try {
            backup__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

