/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.cluster$claim_pod;
import datomic.cluster$clone_pod;
import datomic.cluster$clone_ref;
import datomic.cluster$close;
import datomic.cluster$fn__10410;
import datomic.cluster$fn__10424;
import datomic.cluster$fn__10427;
import datomic.cluster$fn__10456;
import datomic.cluster$fn__10459;
import datomic.cluster$fn__10472;
import datomic.cluster$fn__10489;
import datomic.cluster$fn__10510;
import datomic.cluster$fn__10523;
import datomic.cluster$fn__10536;
import datomic.cluster$fn__10549;
import datomic.cluster$fn__10574;
import datomic.cluster$fn__10587;
import datomic.cluster$fn__10602;
import datomic.cluster$fn__10605;
import datomic.cluster$fn__10692;
import datomic.cluster$fn__10695;
import datomic.cluster$fn__10706;
import datomic.cluster$fn__10717;
import datomic.cluster$fn__10729;
import datomic.cluster$fn__10732;
import datomic.cluster$get_ref_store;
import datomic.cluster$loading__6434__auto____10375;
import datomic.cluster$new_pod_key;
import datomic.cluster$new_ref_key;
import datomic.cluster$new_val_key;
import datomic.cluster$path;
import datomic.cluster$pod_key__GT_uuid;
import datomic.cluster$queueing_writer;
import datomic.cluster$reset_pod;
import datomic.cluster$reset_ref;
import datomic.cluster$touch_pod;
import datomic.cluster$touch_ref;
import datomic.cluster$uncached_val_lookup;
import datomic.cluster$update_pod;
import datomic.cluster$uuid__GT_pod_key;
import datomic.cluster$uuid__GT_val_key;
import datomic.cluster$val_key__GT_uuid;
import datomic.cluster$write_vals;
import datomic.cluster$write_vals_STAR_;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class cluster__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Var const__10;
    public static final AFn const__12;
    public static final Var const__13;
    public static final AFn const__15;
    public static final Var const__16;
    public static final AFn const__18;
    public static final Var const__19;
    public static final AFn const__21;
    public static final Var const__22;
    public static final AFn const__24;
    public static final Var const__25;
    public static final AFn const__27;
    public static final AFn const__29;
    public static final Var const__30;
    public static final AFn const__34;
    public static final Var const__35;
    public static final AFn const__37;
    public static final Object const__38;
    public static final Var const__39;
    public static final AFn const__40;
    public static final Object const__41;
    public static final Var const__42;
    public static final AFn const__43;
    public static final Object const__44;
    public static final Object const__45;
    public static final Var const__46;
    public static final Var const__47;
    public static final Var const__48;
    public static final Keyword const__49;
    public static final Var const__50;
    public static final ISeq const__51;
    public static final Var const__52;
    public static final Var const__53;
    public static final AFn const__57;
    public static final Keyword const__58;
    public static final AFn const__59;
    public static final Keyword const__60;
    public static final Keyword const__61;
    public static final AFn const__63;
    public static final Keyword const__64;
    public static final Var const__65;
    public static final Var const__66;
    public static final Var const__67;
    public static final AFn const__68;
    public static final AFn const__69;
    public static final Keyword const__70;
    public static final Var const__71;
    public static final AFn const__72;
    public static final Object const__73;
    public static final Var const__74;
    public static final ISeq const__75;
    public static final AFn const__77;
    public static final AFn const__78;
    public static final AFn const__88;
    public static final AFn const__89;
    public static final AFn const__90;
    public static final AFn const__91;
    public static final AFn const__92;
    public static final AFn const__93;
    public static final AFn const__94;
    public static final AFn const__95;
    public static final AFn const__96;
    public static final AFn const__97;
    public static final AFn const__98;
    public static final AFn const__99;
    public static final AFn const__100;
    public static final AFn const__101;
    public static final AFn const__102;
    public static final AFn const__103;
    public static final AFn const__104;
    public static final AFn const__105;
    public static final AFn const__106;
    public static final AFn const__107;
    public static final Object const__108;
    public static final Var const__109;
    public static final ISeq const__110;
    public static final AFn const__112;
    public static final AFn const__113;
    public static final AFn const__115;
    public static final AFn const__116;
    public static final AFn const__117;
    public static final AFn const__118;
    public static final Var const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final Var const__128;
    public static final AFn const__130;
    public static final Var const__131;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__136;
    public static final Var const__137;
    public static final AFn const__139;
    public static final Var const__140;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__145;
    public static final Var const__146;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__149;
    public static final Var const__150;
    public static final Object const__151;
    public static final Var const__152;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__155;
    public static final Object const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;
    public static final Object const__163;
    public static final Var const__164;
    public static final ISeq const__165;
    public static final AFn const__167;
    public static final AFn const__168;
    public static final AFn const__171;
    public static final AFn const__172;
    public static final AFn const__173;
    public static final AFn const__174;
    public static final AFn const__175;
    public static final AFn const__176;
    public static final Var const__177;
    public static final AFn const__179;
    public static final Object const__180;
    public static final Var const__181;
    public static final ISeq const__182;
    public static final AFn const__184;
    public static final AFn const__185;
    public static final AFn const__187;
    public static final AFn const__188;
    public static final AFn const__189;
    public static final AFn const__190;
    public static final Var const__191;
    public static final AFn const__193;
    public static final Var const__194;
    public static final AFn const__196;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new cluster$loading__6434__auto____10375()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new cluster$fn__10410())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new cluster$uuid__GT_val_key());
        Var var3 = const__10;
        var3.setMeta((IPersistentMap)const__12);
        Var var4 = var3;
        var3.bindRoot((Object)new cluster$val_key__GT_uuid());
        Var var5 = const__13;
        var5.setMeta((IPersistentMap)const__15);
        Var var6 = var5;
        var5.bindRoot((Object)new cluster$uuid__GT_pod_key());
        Var var7 = const__16;
        var7.setMeta((IPersistentMap)const__18);
        Var var8 = var7;
        var7.bindRoot((Object)new cluster$pod_key__GT_uuid());
        Var var9 = const__19;
        var9.setMeta((IPersistentMap)const__21);
        Var var10 = var9;
        var9.bindRoot((Object)new cluster$new_val_key());
        Var var11 = const__22;
        var11.setMeta((IPersistentMap)const__24);
        Var var12 = var11;
        var11.bindRoot((Object)new cluster$new_pod_key());
        Var var13 = const__25;
        var13.setMeta((IPersistentMap)const__27);
        Var var14 = var13;
        var13.bindRoot((Object)new cluster$new_ref_key());
        Var var15 = const__22;
        var15.setMeta((IPersistentMap)const__29);
        Var var16 = var15;
        var15.bindRoot((Object)new cluster$new_pod_key());
        Var var17 = const__30;
        var17.setMeta((IPersistentMap)const__34);
        Var var18 = var17;
        var17.bindRoot((Object)new cluster$path());
        Var var19 = const__35;
        var19.setMeta((IPersistentMap)const__37);
        Var var20 = var19;
        var19.bindRoot(const__38);
        Var var21 = const__39;
        var21.setMeta((IPersistentMap)const__40);
        Var var22 = var21;
        var21.bindRoot(const__41);
        Var var23 = const__42;
        var23.setMeta((IPersistentMap)const__43);
        Var var24 = var23;
        var23.bindRoot(const__44);
        Object object4 = ((IFn)new cluster$fn__10424()).invoke();
        Object object5 = const__45;
        Object object6 = ((IFn)const__46.getRawRoot()).invoke((Object)const__47, const__48.getRawRoot(), (Object)const__49, null);
        Object object7 = ((IFn)const__50).invoke((Object)const__47, (Object)const__51);
        Object object8 = ((IFn)const__52.getRawRoot()).invoke((Object)const__47, const__53.getRawRoot(), ((IFn)const__48.getRawRoot()).invoke((Object)const__57, (Object)const__58, (Object)const__59, (Object)const__60, (Object)const__47, (Object)const__61, (Object)const__63, (Object)const__64, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__68, ((IFn)const__53.getRawRoot()).invoke((Object)const__69, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__47})))), new cluster$fn__10427()})));
        Object object9 = ((IFn)const__71.getRawRoot()).invoke(const__47.getRawRoot());
        AFn aFn = const__72;
        Object object10 = ((IFn)new cluster$fn__10456()).invoke();
        Object object11 = const__73;
        Object object12 = ((IFn)const__46.getRawRoot()).invoke((Object)const__74, const__48.getRawRoot(), (Object)const__49, (Object)"An interface to a clustered store. All fns might throw an exception on deref if no quorum is available.");
        Object object13 = ((IFn)const__50).invoke((Object)const__74, (Object)const__75);
        Object object14 = ((IFn)const__52.getRawRoot()).invoke((Object)const__74, const__53.getRawRoot(), ((IFn)const__48.getRawRoot()).invoke((Object)const__77, (Object)const__58, (Object)const__78, (Object)const__60, (Object)const__74, (Object)const__61, (Object)const__88, (Object)const__64, (Object)RT.map((Object[])new Object[]{((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__89, ((IFn)const__53.getRawRoot()).invoke((Object)const__90, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10459(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__91, ((IFn)const__53.getRawRoot()).invoke((Object)const__92, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10472(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__93, ((IFn)const__53.getRawRoot()).invoke((Object)const__94, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10489(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__95, ((IFn)const__53.getRawRoot()).invoke((Object)const__96, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10510(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__97, ((IFn)const__53.getRawRoot()).invoke((Object)const__98, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10523(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__99, ((IFn)const__53.getRawRoot()).invoke((Object)const__100, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10536(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__101, ((IFn)const__53.getRawRoot()).invoke((Object)const__102, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10549(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__103, ((IFn)const__53.getRawRoot()).invoke((Object)const__104, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10574(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__105, ((IFn)const__53.getRawRoot()).invoke((Object)const__106, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__74})))), new cluster$fn__10587()})));
        Object object15 = ((IFn)const__71.getRawRoot()).invoke(const__74.getRawRoot());
        AFn aFn2 = const__107;
        Object object16 = ((IFn)new cluster$fn__10602()).invoke();
        Object object17 = const__108;
        Object object18 = ((IFn)const__46.getRawRoot()).invoke((Object)const__109, const__48.getRawRoot(), (Object)const__49, (Object)"Enhanced ClusteredStore/get-val that accepts opts map.");
        Object object19 = ((IFn)const__50).invoke((Object)const__109, (Object)const__110);
        Object object20 = ((IFn)const__52.getRawRoot()).invoke((Object)const__109, const__53.getRawRoot(), ((IFn)const__48.getRawRoot()).invoke((Object)const__112, (Object)const__58, (Object)const__113, (Object)const__60, (Object)const__109, (Object)const__61, (Object)const__115, (Object)const__64, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__116, ((IFn)const__53.getRawRoot()).invoke((Object)const__117, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__109})))), new cluster$fn__10605()})));
        Object object21 = ((IFn)const__71.getRawRoot()).invoke(const__109.getRawRoot());
        AFn aFn3 = const__118;
        Var var25 = const__119;
        var25.setMeta((IPersistentMap)const__121);
        Var var26 = var25;
        var25.bindRoot((Object)new cluster$update_pod());
        Var var27 = const__122;
        var27.setMeta((IPersistentMap)const__124);
        Var var28 = var27;
        var27.bindRoot((Object)new cluster$reset_ref());
        Var var29 = const__125;
        var29.setMeta((IPersistentMap)const__127);
        Var var30 = var29;
        var29.bindRoot((Object)new cluster$touch_ref());
        Var var31 = const__128;
        var31.setMeta((IPersistentMap)const__130);
        Var var32 = var31;
        var31.bindRoot((Object)new cluster$reset_pod());
        Var var33 = const__131;
        var33.setMeta((IPersistentMap)const__133);
        Var var34 = var33;
        var33.bindRoot((Object)new cluster$touch_pod());
        Var var35 = const__134;
        var35.setMeta((IPersistentMap)const__136);
        Var var36 = var35;
        var35.bindRoot((Object)new cluster$claim_pod());
        Var var37 = const__137;
        var37.setMeta((IPersistentMap)const__139);
        Var var38 = var37;
        var37.bindRoot((Object)new cluster$clone_pod());
        Var var39 = const__140;
        var39.setMeta((IPersistentMap)const__142);
        Var var40 = var39;
        var39.bindRoot((Object)new cluster$clone_ref());
        Var var41 = const__143;
        var41.setMeta((IPersistentMap)const__145);
        Var var42 = var41;
        var41.bindRoot((Object)new cluster$uncached_val_lookup());
        Var var43 = const__146;
        var43.setMeta((IPersistentMap)const__147);
        Var var44 = var43;
        var43.bindRoot(new Object());
        Var var45 = const__148;
        var45.setMeta((IPersistentMap)const__149);
        Var var46 = var45;
        var45.bindRoot(((IFn)const__150.getRawRoot()).invoke(const__151));
        Var var47 = const__152;
        var47.setMeta((IPersistentMap)const__153);
        Var var48 = var47;
        var47.bindRoot(((IFn)const__150.getRawRoot()).invoke(null));
        Var var49 = const__154;
        var49.setMeta((IPersistentMap)const__155);
        Var var50 = var49;
        var49.bindRoot(const__156);
        Var var51 = const__157;
        var51.setMeta((IPersistentMap)const__159);
        Var var52 = var51;
        var51.bindRoot((Object)new cluster$write_vals_STAR_());
        Var var53 = const__160;
        var53.setMeta((IPersistentMap)const__162);
        Var var54 = var53;
        var53.bindRoot((Object)new cluster$write_vals());
        Object object22 = ((IFn)new cluster$fn__10692()).invoke();
        Object object23 = const__163;
        Object object24 = ((IFn)const__46.getRawRoot()).invoke((Object)const__164, const__48.getRawRoot(), (Object)const__49, null);
        Object object25 = ((IFn)const__50).invoke((Object)const__164, (Object)const__165);
        Object object26 = ((IFn)const__52.getRawRoot()).invoke((Object)const__164, const__53.getRawRoot(), ((IFn)const__48.getRawRoot()).invoke((Object)const__167, (Object)const__58, (Object)const__168, (Object)const__60, (Object)const__164, (Object)const__61, (Object)const__171, (Object)const__64, (Object)RT.map((Object[])new Object[]{((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__172, ((IFn)const__53.getRawRoot()).invoke((Object)const__173, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__164})))), new cluster$fn__10695(), ((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__174, ((IFn)const__53.getRawRoot()).invoke((Object)const__175, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__164})))), new cluster$fn__10706()})));
        Object object27 = ((IFn)const__71.getRawRoot()).invoke(const__164.getRawRoot());
        AFn aFn4 = const__176;
        Object object28 = ((IFn)new cluster$fn__10717()).invoke();
        Var var55 = const__177;
        var55.setMeta((IPersistentMap)const__179);
        Var var56 = var55;
        var55.bindRoot((Object)new cluster$queueing_writer());
        Object object29 = ((IFn)new cluster$fn__10729()).invoke();
        Object object30 = const__180;
        Object object31 = ((IFn)const__46.getRawRoot()).invoke((Object)const__181, const__48.getRawRoot(), (Object)const__49, (Object)"Helper for getting a ref store from a cluster");
        Object object32 = ((IFn)const__50).invoke((Object)const__181, (Object)const__182);
        Object object33 = ((IFn)const__52.getRawRoot()).invoke((Object)const__181, const__53.getRawRoot(), ((IFn)const__48.getRawRoot()).invoke((Object)const__184, (Object)const__58, (Object)const__185, (Object)const__60, (Object)const__181, (Object)const__61, (Object)const__187, (Object)const__64, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__65.getRawRoot()).invoke(const__66.get(), ((IFn)const__67.getRawRoot()).invoke((Object)const__188, ((IFn)const__53.getRawRoot()).invoke((Object)const__189, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__70, const__181})))), new cluster$fn__10732()})));
        Object object34 = ((IFn)const__71.getRawRoot()).invoke(const__181.getRawRoot());
        AFn aFn5 = const__190;
        Var var57 = const__191;
        var57.setMeta((IPersistentMap)const__193);
        Var var58 = var57;
        var57.bindRoot((Object)new cluster$get_ref_store());
        Var var59 = const__194;
        var59.setMeta((IPersistentMap)const__196);
        Var var60 = var59;
        var59.bindRoot((Object)new cluster$close());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.cluster");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.cluster", (String)"uuid->val-key");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"uuid")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"UUID")}))))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"datomic.cluster", (String)"val-key->uuid");
        const__12 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__13 = RT.var((String)"datomic.cluster", (String)"uuid->pod-key");
        const__15 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"uuid")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"UUID")}))))), RT.keyword(null, (String)"column"), 1});
        const__16 = RT.var((String)"datomic.cluster", (String)"pod-key->uuid");
        const__18 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__19 = RT.var((String)"datomic.cluster", (String)"new-val-key");
        const__21 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__22 = RT.var((String)"datomic.cluster", (String)"new-pod-key");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__25 = RT.var((String)"datomic.cluster", (String)"new-ref-key");
        const__27 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"name")))), RT.keyword(null, (String)"column"), 1});
        const__29 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__30 = RT.var((String)"datomic.cluster", (String)"path");
        const__34 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.lang.String"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__35 = RT.var((String)"datomic.cluster", (String)"PRIORITY_HIGH");
        const__37 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__38 = 2L;
        const__39 = RT.var((String)"datomic.cluster", (String)"PRIORITY_MID");
        const__40 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__41 = 3L;
        const__42 = RT.var((String)"datomic.cluster", (String)"PRIORITY_LOW");
        const__43 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__44 = 4L;
        const__45 = RT.classForName((String)"datomic.cluster.Dbid");
        const__46 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__47 = RT.var((String)"datomic.cluster", (String)"Dbid");
        const__48 = RT.var((String)"clojure.core", (String)"assoc");
        const__49 = RT.keyword(null, (String)"doc");
        const__50 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__51 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"dbId")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c"))))}))));
        const__52 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__53 = RT.var((String)"clojure.core", (String)"merge");
        const__57 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.cluster.Dbid"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.cluster.Dbid")});
        const__58 = RT.keyword(null, (String)"sigs");
        const__59 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"dbId"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"dbId")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"doc"), "Returns the db id of a cluster, or nil if a system cluster."})});
        const__60 = RT.keyword(null, (String)"var");
        const__61 = RT.keyword(null, (String)"method-map");
        const__63 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"dbId"), RT.keyword(null, (String)"dbId")});
        const__64 = RT.keyword(null, (String)"method-builders");
        const__65 = RT.var((String)"clojure.core", (String)"intern");
        const__66 = RT.var((String)"clojure.core", (String)"*ns*");
        const__67 = RT.var((String)"clojure.core", (String)"with-meta");
        const__68 = (AFn)((IObj)Symbol.intern(null, (String)"dbId")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c"))))}));
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"dbId")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"c")))), RT.keyword(null, (String)"doc"), "Returns the db id of a cluster, or nil if a system cluster."});
        const__70 = RT.keyword(null, (String)"protocol");
        const__71 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__72 = (AFn)Symbol.intern(null, (String)"Dbid");
        const__73 = RT.classForName((String)"datomic.cluster.ClusteredStore");
        const__74 = RT.var((String)"datomic.cluster", (String)"ClusteredStore");
        const__75 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"create-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))))})), ((IObj)Symbol.intern(null, (String)"get-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"delete")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"delete-reference")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"get-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"set-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"get-pod")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"get-pod-meta")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), ((IObj)Symbol.intern(null, (String)"update-pod*")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap"))))}))));
        const__77 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.cluster.ClusteredStore"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.cluster.ClusteredStore"), RT.keyword(null, (String)"doc"), "An interface to a clustered store. All fns might throw an exception on deref if no quorum is available."});
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"create-val"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"create-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"doc"), "Creates a new value in the store. Returns a reference to :created or nil"}), RT.keyword(null, (String)"get-val"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Gets the value at a key. Returns a reference to {:buf buf} or nil if not found"}), RT.keyword(null, (String)"delete"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"delete")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Soft delete. Returns a reference to :ok"}), RT.keyword(null, (String)"delete-reference"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"delete-reference")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Delete a reference (pod or ref).  Returns a reference to :ok"}), RT.keyword(null, (String)"get-ref"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Returns a reference to {:rev nnn, :key k} or nil if not found"}), RT.keyword(null, (String)"set-ref"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"set-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Makes vkey the new value of ref, iff rev is higher than existing\n   rev. You must have obtained rev from a prior read and incremented\n   it. Returns a reference to :ok or :conflict. set-ref with a rev of 0 can create a ref."}), RT.keyword(null, (String)"get-pod"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-pod")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Gets the value in a pod. Returns a reference to {:rev nnn, :etag xxx, :buf buf} and any metadata keys.\n   or nil if not found."}), RT.keyword(null, (String)"get-pod-meta"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-pod-meta")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Returns reference to pod-meta, without walking entire linked list a la get-pod."}), RT.keyword(null, (String)"update-pod*"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"update-pod*")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap")))), RT.keyword(null, (String)"doc"), "With nil etag, creates or resets pod to be supplied value. When\n   etag is non-nil, appends a non-nil buf to the current value of the\n   pod (a nil buf just 'touches' the pod, incrementing rev and leaving\n   the value intact), iff etag matches.  In all cases rev must be one\n   higher than existing rev. You must obtain rev and etag from a prior\n   get/update, and increment rev. Keys in metamap must be\n   namespaced. Returns a reference to {:rev nnn, :etag xxx, :buf buf}\n   or {:failed :conflict}."})});
        const__88 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"get-pod-meta"), RT.keyword(null, (String)"get-pod-meta"), RT.keyword(null, (String)"delete"), RT.keyword(null, (String)"delete"), RT.keyword(null, (String)"get-val"), RT.keyword(null, (String)"get-val"), RT.keyword(null, (String)"get-ref"), RT.keyword(null, (String)"get-ref"), RT.keyword(null, (String)"update-pod*"), RT.keyword(null, (String)"update-pod*"), RT.keyword(null, (String)"create-val"), RT.keyword(null, (String)"create-val"), RT.keyword(null, (String)"delete-reference"), RT.keyword(null, (String)"delete-reference"), RT.keyword(null, (String)"set-ref"), RT.keyword(null, (String)"set-ref"), RT.keyword(null, (String)"get-pod"), RT.keyword(null, (String)"get-pod")});
        const__89 = (AFn)((IObj)Symbol.intern(null, (String)"delete")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__90 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"delete")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Soft delete. Returns a reference to :ok"});
        const__91 = (AFn)((IObj)Symbol.intern(null, (String)"set-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"set-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"vkey")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Makes vkey the new value of ref, iff rev is higher than existing\n   rev. You must have obtained rev from a prior read and incremented\n   it. Returns a reference to :ok or :conflict. set-ref with a rev of 0 can create a ref."});
        const__93 = (AFn)((IObj)Symbol.intern(null, (String)"update-pod*")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap"))))}));
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"update-pod*")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap")))), RT.keyword(null, (String)"doc"), "With nil etag, creates or resets pod to be supplied value. When\n   etag is non-nil, appends a non-nil buf to the current value of the\n   pod (a nil buf just 'touches' the pod, incrementing rev and leaving\n   the value intact), iff etag matches.  In all cases rev must be one\n   higher than existing rev. You must obtain rev and etag from a prior\n   get/update, and increment rev. Keys in metamap must be\n   namespaced. Returns a reference to {:rev nnn, :etag xxx, :buf buf}\n   or {:failed :conflict}."});
        const__95 = (AFn)((IObj)Symbol.intern(null, (String)"delete-reference")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__96 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"delete-reference")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Delete a reference (pod or ref).  Returns a reference to :ok"});
        const__97 = (AFn)((IObj)Symbol.intern(null, (String)"get-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__98 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-ref")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"ref-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Returns a reference to {:rev nnn, :key k} or nil if not found"});
        const__99 = (AFn)((IObj)Symbol.intern(null, (String)"get-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Gets the value at a key. Returns a reference to {:buf buf} or nil if not found"});
        const__101 = (AFn)((IObj)Symbol.intern(null, (String)"create-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))))}));
        const__102 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"create-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"priority"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"doc"), "Creates a new value in the store. Returns a reference to :created or nil"});
        const__103 = (AFn)((IObj)Symbol.intern(null, (String)"get-pod-meta")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__104 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-pod-meta")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Returns reference to pod-meta, without walking entire linked list a la get-pod."});
        const__105 = (AFn)((IObj)Symbol.intern(null, (String)"get-pod")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))}));
        const__106 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-pod")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"doc"), "Gets the value in a pod. Returns a reference to {:rev nnn, :etag xxx, :buf buf} and any metadata keys.\n   or nil if not found."});
        const__107 = (AFn)Symbol.intern(null, (String)"ClusteredStore");
        const__108 = RT.classForName((String)"datomic.cluster.Get2");
        const__109 = RT.var((String)"datomic.cluster", (String)"Get2");
        const__110 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"get-val2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts"))))}))));
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.cluster.Get2"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.cluster.Get2"), RT.keyword(null, (String)"doc"), "Enhanced ClusteredStore/get-val that accepts opts map."});
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"get-val2"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-val2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts")))), RT.keyword(null, (String)"doc"), "Like ClusteredStore/get-val, but takes an opts map that flows to underlying implementations."})});
        const__115 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"get-val2"), RT.keyword(null, (String)"get-val2")});
        const__116 = (AFn)((IObj)Symbol.intern(null, (String)"get-val2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts"))))}));
        const__117 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-val2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"val-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"opts")))), RT.keyword(null, (String)"doc"), "Like ClusteredStore/get-val, but takes an opts map that flows to underlying implementations."});
        const__118 = (AFn)Symbol.intern(null, (String)"Get2");
        const__119 = RT.var((String)"datomic.cluster", (String)"update-pod");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)((IObj)Symbol.intern(null, (String)"pod-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)Symbol.intern(null, (String)"rev"), (Object)((IObj)Symbol.intern(null, (String)"etag")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"metamap")))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.cluster", (String)"reset-ref");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"v")))), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.cluster", (String)"touch-ref");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__128 = RT.var((String)"datomic.cluster", (String)"reset-pod");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"buf"), (Object)Symbol.intern(null, (String)"metamap")))), RT.keyword(null, (String)"column"), 1});
        const__131 = RT.var((String)"datomic.cluster", (String)"touch-pod");
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"pod-key"), (Object)Symbol.intern(null, (String)"pod")))), RT.keyword(null, (String)"column"), 1});
        const__134 = RT.var((String)"datomic.cluster", (String)"claim-pod");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"pod-key"), (Object)Symbol.intern(null, (String)"msec")))), RT.keyword(null, (String)"column"), 1});
        const__137 = RT.var((String)"datomic.cluster", (String)"clone-pod");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"from-key"), (Object)Symbol.intern(null, (String)"to-key")))), RT.keyword(null, (String)"column"), 1});
        const__140 = RT.var((String)"datomic.cluster", (String)"clone-ref");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"from-key"), (Object)Symbol.intern(null, (String)"to-key")))), RT.keyword(null, (String)"column"), 1});
        const__143 = RT.var((String)"datomic.cluster", (String)"uncached-val-lookup");
        const__145 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__146 = RT.var((String)"datomic.cluster", (String)"pacer");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.cluster", (String)"segment-writes");
        const__149 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__150 = RT.var((String)"clojure.core", (String)"atom");
        const__151 = 0L;
        const__152 = RT.var((String)"datomic.cluster", (String)"segment-pacing-msec");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.cluster", (String)"BOUNDING_TIMEOUT_MSEC");
        const__155 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__156 = 300000L;
        const__157 = RT.var((String)"datomic.cluster", (String)"write-vals*");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"source"), (Object)Symbol.intern(null, (String)"vmap")))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.cluster", (String)"write-vals");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"source"), (Object)Symbol.intern(null, (String)"vmap")))), RT.keyword(null, (String)"column"), 1});
        const__163 = RT.classForName((String)"datomic.cluster.AsyncWriter");
        const__164 = RT.var((String)"datomic.cluster", (String)"AsyncWriter");
        const__165 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"finish-writer")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), ((IObj)Symbol.intern(null, (String)"sync-writes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
        const__167 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.cluster.AsyncWriter"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.cluster.AsyncWriter")});
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"finish-writer"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"finish-writer")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Finish writer. Returns a future that will throw if any write failed."}), RT.keyword(null, (String)"sync-writes"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-writes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a promise that will be filled after all pending writes complete."})});
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"sync-writes"), RT.keyword(null, (String)"sync-writes"), RT.keyword(null, (String)"finish-writer"), RT.keyword(null, (String)"finish-writer")});
        const__172 = (AFn)((IObj)Symbol.intern(null, (String)"finish-writer")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__173 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"finish-writer")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Finish writer. Returns a future that will throw if any write failed."});
        const__174 = (AFn)((IObj)Symbol.intern(null, (String)"sync-writes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__175 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"sync-writes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a promise that will be filled after all pending writes complete."});
        const__176 = (AFn)Symbol.intern(null, (String)"AsyncWriter");
        const__177 = RT.var((String)"datomic.cluster", (String)"queueing-writer");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"par"), (Object)Symbol.intern(null, (String)"bounding-timeout-msec"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__180 = RT.classForName((String)"datomic.cluster.RefClusterStore");
        const__181 = RT.var((String)"datomic.cluster", (String)"RefClusterStore");
        const__182 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"-get-ref-store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"))))}))));
        const__184 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.cluster.RefClusterStore"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.cluster.RefClusterStore"), RT.keyword(null, (String)"doc"), "Helper for getting a ref store from a cluster"});
        const__185 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"-get-ref-store"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"-get-ref-store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"doc"), null})});
        const__187 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"-get-ref-store"), RT.keyword(null, (String)"-get-ref-store")});
        const__188 = (AFn)((IObj)Symbol.intern(null, (String)"-get-ref-store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"))))}));
        const__189 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"-get-ref-store")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"doc"), null});
        const__190 = (AFn)Symbol.intern(null, (String)"RefClusterStore");
        const__191 = RT.var((String)"datomic.cluster", (String)"get-ref-store");
        const__193 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__194 = RT.var((String)"datomic.cluster", (String)"close");
        const__196 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        cluster__init.__init0();
        cluster__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.cluster__init").getClassLoader());
        try {
            cluster__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

