/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.AReference
 *  clojure.lang.Compiler
 *  clojure.lang.Delay
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.Namespace
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.AReference;
import clojure.lang.Compiler;
import clojure.lang.Delay;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.Namespace;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.index$add_avet_indexes;
import datomic.index$aevt_attrs_datoms;
import datomic.index$attr_datoms;
import datomic.index$avet_sort_and_process_datoms;
import datomic.index$binary_search;
import datomic.index$bounded_count;
import datomic.index$btree_search;
import datomic.index$build_one_seg;
import datomic.index$build_psegs;
import datomic.index$build_segs;
import datomic.index$capture_last_ex;
import datomic.index$conjable_on_channel;
import datomic.index$create_pace_calculator;
import datomic.index$deref_or_throw;
import datomic.index$dir_node;
import datomic.index$dir_partition_size;
import datomic.index$disjoined_datoms;
import datomic.index$drop_avet;
import datomic.index$drop_avet_indexes;
import datomic.index$drop_avets;
import datomic.index$drop_dirnode_leaves;
import datomic.index$dropped_avet_aids;
import datomic.index$estimate_seg_offset;
import datomic.index$excise_ents;
import datomic.index$filter_nohist_pairs;
import datomic.index$find_index_root_id;
import datomic.index$floop;
import datomic.index$fn__14994;
import datomic.index$fn__14997;
import datomic.index$fn__14999;
import datomic.index$fn__15012;
import datomic.index$fn__15018;
import datomic.index$fn__15024;
import datomic.index$fn__15037;
import datomic.index$fn__15040;
import datomic.index$fn__15051;
import datomic.index$fn__15062;
import datomic.index$fn__15075;
import datomic.index$fn__15078;
import datomic.index$fn__15091;
import datomic.index$fn__15179;
import datomic.index$fn__15181;
import datomic.index$fn__15196;
import datomic.index$fn__15415;
import datomic.index$fred;
import datomic.index$fress;
import datomic.index$fully_partition_by;
import datomic.index$fully_take_while_delivering_tail;
import datomic.index$get_avet_sorted_datoms_mem;
import datomic.index$get_dir_node;
import datomic.index$ibinary_search;
import datomic.index$ibtree_search;
import datomic.index$idx_key;
import datomic.index$index_ref_key_name;
import datomic.index$indexed_binary_search;
import datomic.index$init_index;
import datomic.index$init_index_STAR_;
import datomic.index$least_pop_slice;
import datomic.index$load_index;
import datomic.index$loading__6434__auto____14344;
import datomic.index$lookup_index;
import datomic.index$make_sparse_lt;
import datomic.index$mem_index_bytes;
import datomic.index$merge_data;
import datomic.index$merge_db;
import datomic.index$merge_db_STAR_;
import datomic.index$merge_one_index;
import datomic.index$mindiff;
import datomic.index$needs_new_avet;
import datomic.index$paired_assertion_state;
import datomic.index$problem_assertion_state_QMARK_;
import datomic.index$reify__15183;
import datomic.index$reify__15185;
import datomic.index$reify__15187;
import datomic.index$reify__15189;
import datomic.index$reify__15232;
import datomic.index$reify__15234;
import datomic.index$reify__15236;
import datomic.index$reify__15238;
import datomic.index$reify__15240;
import datomic.index$reify__15242;
import datomic.index$repair_disjoined;
import datomic.index$retract_assert_pair_QMARK_;
import datomic.index$root_node;
import datomic.index$seg_last_datom;
import datomic.index$separating_retractions;
import datomic.index$serialize_dir;
import datomic.index$sparse_datom;
import datomic.index$sparse_e_xf;
import datomic.index$sparse_es;
import datomic.index$sparse_es_2;
import datomic.index$start_dirs_pipeline;
import datomic.index$stg_index_segs;
import datomic.index$stg_index_size;
import datomic.index$strdiff;
import datomic.index$transpose;
import datomic.index$transposed_data;
import datomic.index$use_array_cache_QMARK_;
import datomic.index$valid_version;
import datomic.index$vecdiff;
import datomic.index$version_root_key;
import datomic.index$with_log;
import datomic.index$write_dirs;
import datomic.index$write_object;
import datomic.index$write_vals;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class index__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final Keyword const__2;
    public static final AFn const__4;
    public static final AFn const__5;
    public static final Var const__6;
    public static final Var const__7;
    public static final Var const__8;
    public static final AFn const__14;
    public static final Var const__15;
    public static final AFn const__17;
    public static final Var const__18;
    public static final AFn const__20;
    public static final Var const__21;
    public static final AFn const__23;
    public static final Var const__24;
    public static final AFn const__25;
    public static final Var const__26;
    public static final AFn const__28;
    public static final Var const__29;
    public static final AFn const__31;
    public static final Object const__32;
    public static final Var const__33;
    public static final Var const__34;
    public static final Var const__35;
    public static final Var const__36;
    public static final ISeq const__37;
    public static final Var const__38;
    public static final Var const__39;
    public static final AFn const__43;
    public static final Keyword const__44;
    public static final AFn const__45;
    public static final Keyword const__46;
    public static final Keyword const__47;
    public static final AFn const__51;
    public static final Keyword const__52;
    public static final Var const__53;
    public static final Var const__54;
    public static final Var const__55;
    public static final AFn const__56;
    public static final AFn const__57;
    public static final Keyword const__58;
    public static final AFn const__59;
    public static final AFn const__60;
    public static final AFn const__61;
    public static final AFn const__62;
    public static final Var const__63;
    public static final AFn const__64;
    public static final Object const__65;
    public static final Var const__66;
    public static final ISeq const__67;
    public static final AFn const__69;
    public static final AFn const__70;
    public static final AFn const__72;
    public static final AFn const__73;
    public static final AFn const__74;
    public static final AFn const__75;
    public static final Var const__76;
    public static final AFn const__77;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__83;
    public static final AFn const__85;
    public static final Var const__86;
    public static final AFn const__87;
    public static final AFn const__89;
    public static final Var const__90;
    public static final AFn const__91;
    public static final AFn const__93;
    public static final Var const__94;
    public static final AFn const__96;
    public static final Var const__97;
    public static final AFn const__99;
    public static final Var const__100;
    public static final AFn const__102;
    public static final Var const__103;
    public static final AFn const__105;
    public static final Var const__106;
    public static final AFn const__108;
    public static final Var const__109;
    public static final AFn const__111;
    public static final Var const__112;
    public static final AFn const__113;
    public static final Var const__114;
    public static final Object const__115;
    public static final AFn const__118;
    public static final Object const__119;
    public static final AFn const__121;
    public static final Object const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__126;
    public static final Var const__127;
    public static final AFn const__130;
    public static final AFn const__132;
    public static final AFn const__134;
    public static final Var const__135;
    public static final AFn const__137;
    public static final Var const__138;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__145;
    public static final Var const__146;
    public static final AFn const__148;
    public static final Var const__149;
    public static final AFn const__151;
    public static final Object const__152;
    public static final Var const__153;
    public static final AFn const__155;
    public static final Var const__156;
    public static final AFn const__158;
    public static final Var const__159;
    public static final AFn const__161;
    public static final Var const__162;
    public static final AFn const__164;
    public static final Var const__165;
    public static final AFn const__167;
    public static final Var const__168;
    public static final AFn const__170;
    public static final Var const__171;
    public static final AFn const__172;
    public static final Object const__173;
    public static final Var const__174;
    public static final AFn const__175;
    public static final Object const__176;
    public static final Var const__177;
    public static final AFn const__179;
    public static final Var const__180;
    public static final AFn const__182;
    public static final Var const__183;
    public static final AFn const__185;
    public static final Var const__186;
    public static final AFn const__188;
    public static final Var const__189;
    public static final AFn const__191;
    public static final Var const__192;
    public static final AFn const__194;
    public static final Var const__195;
    public static final AFn const__197;
    public static final Var const__198;
    public static final AFn const__200;
    public static final Var const__201;
    public static final AFn const__203;
    public static final Var const__204;
    public static final AFn const__206;
    public static final Var const__207;
    public static final AFn const__209;
    public static final Var const__210;
    public static final AFn const__212;
    public static final Var const__213;
    public static final AFn const__215;
    public static final Var const__216;
    public static final AFn const__218;
    public static final Var const__219;
    public static final AFn const__220;
    public static final AFn const__229;
    public static final Var const__230;
    public static final AFn const__231;
    public static final Object const__232;
    public static final Var const__233;
    public static final AFn const__234;
    public static final Object const__235;
    public static final Var const__236;
    public static final AFn const__237;
    public static final Object const__238;
    public static final Var const__239;
    public static final AFn const__240;
    public static final Object const__241;
    public static final Var const__242;
    public static final AFn const__243;
    public static final Object const__244;
    public static final Var const__245;
    public static final AFn const__247;
    public static final Var const__248;
    public static final AFn const__250;
    public static final Var const__251;
    public static final AFn const__253;
    public static final Var const__254;
    public static final AFn const__256;
    public static final Var const__257;
    public static final AFn const__259;
    public static final AFn const__261;
    public static final Var const__262;
    public static final AFn const__264;
    public static final Var const__265;
    public static final AFn const__267;
    public static final Var const__268;
    public static final AFn const__270;
    public static final Var const__271;
    public static final AFn const__273;
    public static final Var const__274;
    public static final AFn const__276;
    public static final Var const__277;
    public static final AFn const__278;
    public static final Var const__279;
    public static final Keyword const__280;
    public static final Var const__281;
    public static final AFn const__283;
    public static final Var const__284;
    public static final AFn const__286;
    public static final Var const__287;
    public static final AFn const__289;
    public static final Var const__290;
    public static final AFn const__292;
    public static final Var const__293;
    public static final AFn const__295;
    public static final Var const__296;
    public static final AFn const__298;
    public static final Var const__299;
    public static final AFn const__301;
    public static final Var const__302;
    public static final AFn const__304;
    public static final Var const__305;
    public static final AFn const__307;
    public static final Var const__308;
    public static final AFn const__310;
    public static final Var const__311;
    public static final AFn const__313;
    public static final Var const__314;
    public static final AFn const__316;
    public static final Var const__317;
    public static final AFn const__319;
    public static final Var const__320;
    public static final AFn const__322;
    public static final Var const__323;
    public static final AFn const__325;
    public static final Var const__326;
    public static final AFn const__328;
    public static final Var const__329;
    public static final AFn const__331;
    public static final Var const__332;
    public static final AFn const__334;
    public static final Var const__335;
    public static final AFn const__337;
    public static final Var const__338;
    public static final AFn const__340;
    public static final Var const__341;
    public static final AFn const__343;
    public static final Var const__344;
    public static final AFn const__346;
    public static final Var const__347;
    public static final AFn const__349;
    public static final Var const__350;
    public static final AFn const__352;
    public static final Var const__353;
    public static final AFn const__355;
    public static final Var const__356;
    public static final AFn const__358;
    public static final Var const__359;
    public static final AFn const__361;
    public static final Var const__362;
    public static final AFn const__364;
    public static final Var const__365;
    public static final AFn const__367;
    public static final Var const__368;
    public static final AFn const__370;
    public static final Var const__371;
    public static final AFn const__373;
    public static final Var const__374;
    public static final AFn const__376;

    public static void load() {
        Object v3;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        IPersistentMap iPersistentMap = ((AReference)Namespace.find((Symbol)((Symbol)const__1))).resetMeta((IPersistentMap)const__4);
        Object object2 = ((IFn)new index$loading__6434__auto____14344()).invoke();
        if (((Symbol)const__1).equals((Object)const__5)) {
            v3 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new index$fn__14994())));
            v3 = null;
        }
        Object object3 = const__6.set((Object)Boolean.TRUE);
        Object object4 = const__7.set((Object)Boolean.TRUE);
        Var var = const__8;
        var.setMeta((IPersistentMap)const__14);
        Var var2 = var;
        var.bindRoot((Object)new index$deref_or_throw());
        Object object5 = ((IFn)new index$fn__14997()).invoke();
        Object object6 = ((IFn)new index$fn__14999()).invoke();
        Var var3 = const__15;
        var3.setMeta((IPersistentMap)const__17);
        Var var4 = var3;
        var3.bindRoot((Object)new index$transposed_data());
        Object object7 = ((IFn)new index$fn__15012()).invoke();
        Var var5 = const__18;
        var5.setMeta((IPersistentMap)const__20);
        Var var6 = var5;
        var5.bindRoot((Object)new index$root_node());
        Object object8 = ((IFn)new index$fn__15018()).invoke();
        Var var7 = const__21;
        var7.setMeta((IPersistentMap)const__23);
        Var var8 = var7;
        var7.bindRoot((Object)new index$dir_node());
        Var var9 = const__24;
        var9.setMeta((IPersistentMap)const__25);
        Var var10 = var9;
        var9.bindRoot((Object)new Delay((IFn)new index$fn__15024()));
        Var var11 = const__26;
        var11.setMeta((IPersistentMap)const__28);
        Var var12 = var11;
        var11.bindRoot((Object)new index$use_array_cache_QMARK_());
        Var var13 = const__29;
        var13.setMeta((IPersistentMap)const__31);
        Var var14 = var13;
        var13.bindRoot((Object)new index$get_dir_node());
        Object object9 = ((IFn)new index$fn__15037()).invoke();
        Object object10 = const__32;
        Object object11 = ((IFn)const__33.getRawRoot()).invoke((Object)const__34, const__35.getRawRoot(), (Object)const__2, null);
        Object object12 = ((IFn)const__36).invoke((Object)const__34, (Object)const__37);
        Object object13 = ((IFn)const__38.getRawRoot()).invoke((Object)const__34, const__39.getRawRoot(), ((IFn)const__35.getRawRoot()).invoke((Object)const__43, (Object)const__44, (Object)const__45, (Object)const__46, (Object)const__34, (Object)const__47, (Object)const__51, (Object)const__52, (Object)RT.map((Object[])new Object[]{((IFn)const__53.getRawRoot()).invoke(const__54.get(), ((IFn)const__55.getRawRoot()).invoke((Object)const__56, ((IFn)const__39.getRawRoot()).invoke((Object)const__57, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__58, const__34})))), new index$fn__15040(), ((IFn)const__53.getRawRoot()).invoke(const__54.get(), ((IFn)const__55.getRawRoot()).invoke((Object)const__59, ((IFn)const__39.getRawRoot()).invoke((Object)const__60, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__58, const__34})))), new index$fn__15051(), ((IFn)const__53.getRawRoot()).invoke(const__54.get(), ((IFn)const__55.getRawRoot()).invoke((Object)const__61, ((IFn)const__39.getRawRoot()).invoke((Object)const__62, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__58, const__34})))), new index$fn__15062()})));
        Object object14 = ((IFn)const__63.getRawRoot()).invoke(const__34.getRawRoot());
        AFn aFn = const__64;
        Object object15 = ((IFn)new index$fn__15075()).invoke();
        Object object16 = const__65;
        Object object17 = ((IFn)const__33.getRawRoot()).invoke((Object)const__66, const__35.getRawRoot(), (Object)const__2, null);
        Object object18 = ((IFn)const__36).invoke((Object)const__66, (Object)const__67);
        Object object19 = ((IFn)const__38.getRawRoot()).invoke((Object)const__66, const__39.getRawRoot(), ((IFn)const__35.getRawRoot()).invoke((Object)const__69, (Object)const__44, (Object)const__70, (Object)const__46, (Object)const__66, (Object)const__47, (Object)const__72, (Object)const__52, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__53.getRawRoot()).invoke(const__54.get(), ((IFn)const__55.getRawRoot()).invoke((Object)const__73, ((IFn)const__39.getRawRoot()).invoke((Object)const__74, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__58, const__66})))), new index$fn__15078()})));
        Object object20 = ((IFn)const__63.getRawRoot()).invoke(const__66.getRawRoot());
        AFn aFn2 = const__75;
        Object object21 = ((IFn)new index$fn__15091()).invoke();
        Object object22 = ((IFn)new index$fn__15179()).invoke();
        Object object23 = ((IFn)new index$fn__15181()).invoke();
        Var var15 = const__76;
        var15.setMeta((IPersistentMap)const__77);
        Var var16 = var15;
        var15.bindRoot((Object)((IObj)new index$reify__15183(null)).withMeta((IPersistentMap)const__81));
        Var var17 = const__82;
        var17.setMeta((IPersistentMap)const__83);
        Var var18 = var17;
        var17.bindRoot((Object)((IObj)new index$reify__15185(null)).withMeta((IPersistentMap)const__85));
        Var var19 = const__86;
        var19.setMeta((IPersistentMap)const__87);
        Var var20 = var19;
        var19.bindRoot((Object)((IObj)new index$reify__15187(null)).withMeta((IPersistentMap)const__89));
        Var var21 = const__90;
        var21.setMeta((IPersistentMap)const__91);
        Var var22 = var21;
        var21.bindRoot((Object)((IObj)new index$reify__15189(null)).withMeta((IPersistentMap)const__93));
        Var var23 = const__94;
        var23.setMeta((IPersistentMap)const__96);
        Var var24 = var23;
        var23.bindRoot((Object)new index$btree_search());
        Var var25 = const__97;
        var25.setMeta((IPersistentMap)const__99);
        Var var26 = var25;
        var25.bindRoot((Object)new index$binary_search());
        Var var27 = const__100;
        var27.setMeta((IPersistentMap)const__102);
        Var var28 = var27;
        var27.bindRoot((Object)new index$indexed_binary_search());
        Var var29 = const__103;
        var29.setMeta((IPersistentMap)const__105);
        Var var30 = var29;
        var29.bindRoot((Object)new index$ibtree_search());
        Var var31 = const__106;
        var31.setMeta((IPersistentMap)const__108);
        Var var32 = var31;
        var31.bindRoot((Object)new index$ibinary_search());
        Object object24 = ((IFn)new index$fn__15196()).invoke();
        Var var33 = const__109;
        var33.setMeta((IPersistentMap)const__111);
        Var var34 = var33;
        var33.bindRoot((Object)new index$lookup_index());
        Var var35 = const__112;
        var35.setMeta((IPersistentMap)const__113);
        Var var36 = var35;
        var35.bindRoot(((IFn)const__39.getRawRoot()).invoke(const__114.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__115, RT.mapUniqueKeys((Object[])new Object[]{"index-tdata", ((IObj)new index$reify__15232(null)).withMeta((IPersistentMap)const__118)}), const__119, RT.mapUniqueKeys((Object[])new Object[]{"index-root-node", ((IObj)new index$reify__15234(null)).withMeta((IPersistentMap)const__121)}), const__122, RT.mapUniqueKeys((Object[])new Object[]{"index-dir-node", ((IObj)new index$reify__15236(null)).withMeta((IPersistentMap)const__124)})})));
        Var var37 = const__125;
        var37.setMeta((IPersistentMap)const__126);
        Var var38 = var37;
        var37.bindRoot(((IFn)const__39.getRawRoot()).invoke(const__127.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{"index-tdata", ((IObj)new index$reify__15238(null)).withMeta((IPersistentMap)const__130), "index-root-node", ((IObj)new index$reify__15240(null)).withMeta((IPersistentMap)const__132), "index-dir-node", ((IObj)new index$reify__15242(null)).withMeta((IPersistentMap)const__134)})));
        Var var39 = const__135;
        var39.setMeta((IPersistentMap)const__137);
        Var var40 = var39;
        var39.bindRoot((Object)new index$index_ref_key_name());
        Var var41 = const__138;
        var41.setMeta((IPersistentMap)const__142);
        Var var42 = var41;
        var41.bindRoot((Object)new index$fress());
        Var var43 = const__143;
        var43.setMeta((IPersistentMap)const__145);
        Var var44 = var43;
        var43.bindRoot((Object)new index$transpose());
        Var var45 = const__146;
        var45.setMeta((IPersistentMap)const__148);
        Var var46 = var45;
        var45.bindRoot((Object)new index$write_vals());
        Var var47 = const__149;
        var47.setMeta((IPersistentMap)const__151);
        Var var48 = var47;
        var47.bindRoot(const__152);
        Var var49 = const__153;
        var49.setMeta((IPersistentMap)const__155);
        Var var50 = var49;
        var49.bindRoot((Object)new index$init_index_STAR_());
        Var var51 = const__156;
        var51.setMeta((IPersistentMap)const__158);
        Var var52 = var51;
        var51.bindRoot((Object)new index$init_index());
        Var var53 = const__159;
        var53.setMeta((IPersistentMap)const__161);
        Var var54 = var53;
        var53.bindRoot((Object)new index$find_index_root_id());
        Var var55 = const__162;
        var55.setMeta((IPersistentMap)const__164);
        Var var56 = var55;
        var55.bindRoot((Object)new index$valid_version());
        Var var57 = const__165;
        var57.setMeta((IPersistentMap)const__167);
        Var var58 = var57;
        var57.bindRoot((Object)new index$version_root_key());
        Var var59 = const__168;
        var59.setMeta((IPersistentMap)const__170);
        Var var60 = var59;
        var59.bindRoot((Object)new index$load_index());
        Var var61 = const__171;
        var61.setMeta((IPersistentMap)const__172);
        Var var62 = var61;
        var61.bindRoot(const__173);
        Var var63 = const__174;
        var63.setMeta((IPersistentMap)const__175);
        Var var64 = var63;
        var63.bindRoot(const__176);
        Var var65 = const__177;
        var65.setMeta((IPersistentMap)const__179);
        Var var66 = var65;
        var65.bindRoot((Object)new index$with_log());
        const__177.setMacro();
        Object v94 = null;
        Var var67 = const__177;
        Var var68 = const__180;
        var68.setMeta((IPersistentMap)const__182);
        Var var69 = var68;
        var68.bindRoot((Object)new index$floop());
        const__180.setMacro();
        Object v98 = null;
        Var var70 = const__180;
        Var var71 = const__183;
        var71.setMeta((IPersistentMap)const__185);
        Var var72 = var71;
        var71.bindRoot((Object)new index$create_pace_calculator());
        Var var73 = const__186.setDynamic(true);
        var73.setMeta((IPersistentMap)const__188);
        Var var74 = var73;
        var73.bindRoot(null);
        Var var75 = const__189;
        var75.setMeta((IPersistentMap)const__191);
        Var var76 = var75;
        var75.bindRoot((Object)new index$build_one_seg());
        Var var77 = const__192;
        var77.setMeta((IPersistentMap)const__194);
        Var var78 = var77;
        var77.bindRoot((Object)new index$bounded_count());
        Var var79 = const__195;
        var79.setMeta((IPersistentMap)const__197);
        Var var80 = var79;
        var79.bindRoot((Object)new index$build_psegs());
        Var var81 = const__198;
        var81.setMeta((IPersistentMap)const__200);
        Var var82 = var81;
        var81.bindRoot((Object)new index$filter_nohist_pairs());
        Var var83 = const__201;
        var83.setMeta((IPersistentMap)const__203);
        Var var84 = var83;
        var83.bindRoot((Object)new index$separating_retractions());
        Var var85 = const__204;
        var85.setMeta((IPersistentMap)const__206);
        Var var86 = var85;
        var85.bindRoot((Object)new index$fully_take_while_delivering_tail());
        Var var87 = const__207;
        var87.setMeta((IPersistentMap)const__209);
        Var var88 = var87;
        var87.bindRoot((Object)new index$fully_partition_by());
        Var var89 = const__210;
        var89.setMeta((IPersistentMap)const__212);
        Var var90 = var89;
        var89.bindRoot((Object)new index$fred());
        Var var91 = const__213;
        var91.setMeta((IPersistentMap)const__215);
        Var var92 = var91;
        var91.bindRoot((Object)new index$build_segs());
        Var var93 = const__216;
        var93.setMeta((IPersistentMap)const__218);
        Var var94 = var93;
        var93.bindRoot((Object)new index$merge_data());
        Var var95 = const__219;
        var95.setMeta((IPersistentMap)const__220);
        Var var96 = var95;
        var95.bindRoot((Object)const__229);
        Var var97 = const__230;
        var97.setMeta((IPersistentMap)const__231);
        Var var98 = var97;
        var97.bindRoot(const__232);
        Var var99 = const__233;
        var99.setMeta((IPersistentMap)const__234);
        Var var100 = var99;
        var99.bindRoot(const__235);
        Var var101 = const__236;
        var101.setMeta((IPersistentMap)const__237);
        Var var102 = var101;
        var101.bindRoot(const__238);
        Var var103 = const__239;
        var103.setMeta((IPersistentMap)const__240);
        Var var104 = var103;
        var103.bindRoot(const__241);
        Var var105 = const__242;
        var105.setMeta((IPersistentMap)const__243);
        Var var106 = var105;
        var105.bindRoot(const__244);
        Var var107 = const__245;
        var107.setMeta((IPersistentMap)const__247);
        Var var108 = var107;
        var107.bindRoot((Object)new index$dir_partition_size());
        Var var109 = const__248;
        var109.setMeta((IPersistentMap)const__250);
        Var var110 = var109;
        var109.bindRoot((Object)new index$make_sparse_lt());
        Var var111 = const__251;
        var111.setMeta((IPersistentMap)const__253);
        Var var112 = var111;
        var111.bindRoot((Object)new index$strdiff());
        Var var113 = const__254;
        Var var114 = var113;
        var113.setMeta((IPersistentMap)const__256);
        Var var115 = const__257;
        var115.setMeta((IPersistentMap)const__259);
        Var var116 = var115;
        var115.bindRoot((Object)new index$vecdiff());
        Var var117 = const__254;
        var117.setMeta((IPersistentMap)const__261);
        Var var118 = var117;
        var117.bindRoot((Object)new index$mindiff());
        Var var119 = const__262;
        var119.setMeta((IPersistentMap)const__264);
        Var var120 = var119;
        var119.bindRoot((Object)new index$sparse_datom());
        Var var121 = const__265;
        var121.setMeta((IPersistentMap)const__267);
        Var var122 = var121;
        var121.bindRoot((Object)new index$seg_last_datom());
        Var var123 = const__268;
        var123.setMeta((IPersistentMap)const__270);
        Var var124 = var123;
        var123.bindRoot((Object)new index$sparse_e_xf());
        Var var125 = const__271;
        var125.setMeta((IPersistentMap)const__273);
        Var var126 = var125;
        var125.bindRoot((Object)new index$sparse_es_2());
        Var var127 = const__274;
        var127.setMeta((IPersistentMap)const__276);
        Var var128 = var127;
        var127.bindRoot((Object)new index$sparse_es());
        Var var129 = const__277;
        var129.setMeta((IPersistentMap)const__278);
        Var var130 = var129;
        var129.bindRoot(((IFn)const__279.getRawRoot()).invoke(const__244, (Object)const__280, (Object)new index$fn__15415()));
        Var var131 = const__281;
        var131.setMeta((IPersistentMap)const__283);
        Var var132 = var131;
        var131.bindRoot((Object)new index$serialize_dir());
        Var var133 = const__284;
        var133.setMeta((IPersistentMap)const__286);
        Var var134 = var133;
        var133.bindRoot((Object)new index$write_dirs());
        Var var135 = const__287;
        var135.setMeta((IPersistentMap)const__289);
        Var var136 = var135;
        var135.bindRoot((Object)new index$conjable_on_channel());
        Var var137 = const__290;
        var137.setMeta((IPersistentMap)const__292);
        Var var138 = var137;
        var137.bindRoot((Object)new index$capture_last_ex());
        Var var139 = const__293;
        var139.setMeta((IPersistentMap)const__295);
        Var var140 = var139;
        var139.bindRoot((Object)new index$start_dirs_pipeline());
        Var var141 = const__296;
        var141.setMeta((IPersistentMap)const__298);
        Var var142 = var141;
        var141.bindRoot((Object)new index$merge_one_index());
        Var var143 = const__299;
        var143.setMeta((IPersistentMap)const__301);
        Var var144 = var143;
        var143.bindRoot((Object)new index$excise_ents());
        Var var145 = const__302;
        var145.setMeta((IPersistentMap)const__304);
        Var var146 = var145;
        var145.bindRoot((Object)new index$get_avet_sorted_datoms_mem());
        Var var147 = const__305;
        var147.setMeta((IPersistentMap)const__307);
        Var var148 = var147;
        var147.bindRoot((Object)new index$avet_sort_and_process_datoms());
        Var var149 = const__308;
        var149.setMeta((IPersistentMap)const__310);
        Var var150 = var149;
        var149.bindRoot((Object)new index$attr_datoms());
        Var var151 = const__311;
        var151.setMeta((IPersistentMap)const__313);
        Var var152 = var151;
        var151.bindRoot((Object)new index$aevt_attrs_datoms());
        Var var153 = const__314;
        var153.setMeta((IPersistentMap)const__316);
        Var var154 = var153;
        var153.bindRoot((Object)new index$idx_key());
        Var var155 = const__317;
        var155.setMeta((IPersistentMap)const__319);
        Var var156 = var155;
        var155.bindRoot((Object)new index$add_avet_indexes());
        Var var157 = const__320;
        var157.setMeta((IPersistentMap)const__322);
        Var var158 = var157;
        var157.bindRoot((Object)new index$needs_new_avet());
        Var var159 = const__323;
        var159.setMeta((IPersistentMap)const__325);
        Var var160 = var159;
        var159.bindRoot((Object)new index$dropped_avet_aids());
        Var var161 = const__326;
        var161.setMeta((IPersistentMap)const__328);
        Var var162 = var161;
        var161.bindRoot((Object)new index$write_object());
        Var var163 = const__329;
        var163.setMeta((IPersistentMap)const__331);
        Var var164 = var163;
        var163.bindRoot((Object)new index$drop_dirnode_leaves());
        Var var165 = const__332;
        var165.setMeta((IPersistentMap)const__334);
        Var var166 = var165;
        var165.bindRoot((Object)new index$drop_avet());
        Var var167 = const__335;
        var167.setMeta((IPersistentMap)const__337);
        Var var168 = var167;
        var167.bindRoot((Object)new index$drop_avets());
        Var var169 = const__338;
        var169.setMeta((IPersistentMap)const__340);
        Var var170 = var169;
        var169.bindRoot((Object)new index$drop_avet_indexes());
        Var var171 = const__341;
        var171.setMeta((IPersistentMap)const__343);
        Var var172 = var171;
        var171.bindRoot((Object)new index$mem_index_bytes());
        Var var173 = const__344;
        var173.setMeta((IPersistentMap)const__346);
        Var var174 = var173;
        var173.bindRoot((Object)new index$stg_index_segs());
        Var var175 = const__347;
        var175.setMeta((IPersistentMap)const__349);
        Var var176 = var175;
        var175.bindRoot((Object)new index$stg_index_size());
        Var var177 = const__350;
        var177.setMeta((IPersistentMap)const__352);
        Var var178 = var177;
        var177.bindRoot((Object)new index$estimate_seg_offset());
        Var var179 = const__353;
        var179.setMeta((IPersistentMap)const__355);
        Var var180 = var179;
        var179.bindRoot((Object)new index$least_pop_slice());
        Var var181 = const__356;
        var181.setMeta((IPersistentMap)const__358);
        Var var182 = var181;
        var181.bindRoot((Object)new index$retract_assert_pair_QMARK_());
        Var var183 = const__359;
        var183.setMeta((IPersistentMap)const__361);
        Var var184 = var183;
        var183.bindRoot((Object)new index$paired_assertion_state());
        Var var185 = const__362;
        var185.setMeta((IPersistentMap)const__364);
        Var var186 = var185;
        var185.bindRoot((Object)new index$problem_assertion_state_QMARK_());
        Var var187 = const__365;
        var187.setMeta((IPersistentMap)const__367);
        Var var188 = var187;
        var187.bindRoot((Object)new index$disjoined_datoms());
        Var var189 = const__368;
        var189.setMeta((IPersistentMap)const__370);
        Var var190 = var189;
        var189.bindRoot((Object)new index$repair_disjoined());
        Var var191 = const__371;
        var191.setMeta((IPersistentMap)const__373);
        Var var192 = var191;
        var191.bindRoot((Object)new index$merge_db_STAR_());
        Var var193 = const__374;
        var193.setMeta((IPersistentMap)const__376);
        Var var194 = var193;
        var193.bindRoot((Object)new index$merge_db());
        Object v224 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)((IObj)Symbol.intern(null, (String)"datomic.index")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"author"), "Rich Hickey"}));
        const__2 = RT.keyword(null, (String)"doc");
        const__4 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"doc"), "Index on cluster", RT.keyword(null, (String)"author"), "Rich Hickey"});
        const__5 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__6 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__7 = RT.var((String)"clojure.core", (String)"*unchecked-math*");
        const__8 = RT.var((String)"datomic.index", (String)"deref-or-throw");
        const__14 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ref")))), RT.keyword(null, (String)"column"), 1});
        const__15 = RT.var((String)"datomic.index", (String)"transposed-data");
        const__17 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"es")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"longs")})), (Object)((IObj)Symbol.intern(null, (String)"as")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ints")})), (Object)Symbol.intern(null, (String)"vs"), (Object)((IObj)Symbol.intern(null, (String)"ts")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"longs")})), (Object)((IObj)Symbol.intern(null, (String)"ops")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"booleans")}))))), RT.keyword(null, (String)"column"), 1});
        const__18 = RT.var((String)"datomic.index", (String)"root-node");
        const__20 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"keydata"), (Object)((IObj)Symbol.intern(null, (String)"dirids")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")}))))), RT.keyword(null, (String)"column"), 1});
        const__21 = RT.var((String)"datomic.index", (String)"dir-node");
        const__23 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"keydata"), (Object)((IObj)Symbol.intern(null, (String)"segids")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"objects")})), (Object)Symbol.intern(null, (String)"offsets"), (Object)Symbol.intern(null, (String)"counts"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.index.DirNode")})))), RT.keyword(null, (String)"column"), 1});
        const__24 = RT.var((String)"datomic.index", (String)"array-cache-ref");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__26 = RT.var((String)"datomic.index", (String)"use-array-cache?");
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__29 = RT.var((String)"datomic.index", (String)"get-dir-node");
        const__31 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"root")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"RootNode")})), (Object)Symbol.intern(null, (String)"ridx"), (Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"cache?"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.index.DirNode")})))), RT.keyword(null, (String)"column"), 1});
        const__32 = RT.classForName((String)"datomic.index.ITreeIter");
        const__33 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__34 = RT.var((String)"datomic.index", (String)"ITreeIter");
        const__35 = RT.var((String)"clojure.core", (String)"assoc");
        const__36 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__37 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"seg+item-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), ((IObj)Symbol.intern(null, (String)"seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), ((IObj)Symbol.intern(null, (String)"dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))}))));
        const__38 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__39 = RT.var((String)"clojure.core", (String)"merge");
        const__43 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.index.ITreeIter"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.index.ITreeIter")});
        const__44 = RT.keyword(null, (String)"sigs");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seg+item-seq"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seg+item-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of {:segid ... :item ...} for items in tree,\nand their seg ids.  Does not cache segs."}), RT.keyword(null, (String)"seg-seq"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of key data corresponding to each segment in the tree,\n                   starting at iter. Loads the segs as it goes."}), RT.keyword(null, (String)"dir-seq"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of {:key key-datum :seg seg-uuid :count count} corresponding to each segment in the tree,\n                   starting at iter."})});
        const__46 = RT.keyword(null, (String)"var");
        const__47 = RT.keyword(null, (String)"method-map");
        const__51 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seg+item-seq"), RT.keyword(null, (String)"seg+item-seq"), RT.keyword(null, (String)"dir-seq"), RT.keyword(null, (String)"dir-seq"), RT.keyword(null, (String)"seg-seq"), RT.keyword(null, (String)"seg-seq")});
        const__52 = RT.keyword(null, (String)"method-builders");
        const__53 = RT.var((String)"clojure.core", (String)"intern");
        const__54 = RT.var((String)"clojure.core", (String)"*ns*");
        const__55 = RT.var((String)"clojure.core", (String)"with-meta");
        const__56 = (AFn)((IObj)Symbol.intern(null, (String)"seg+item-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))}));
        const__57 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seg+item-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of {:segid ... :item ...} for items in tree,\nand their seg ids.  Does not cache segs."});
        const__58 = RT.keyword(null, (String)"protocol");
        const__59 = (AFn)((IObj)Symbol.intern(null, (String)"seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))}));
        const__60 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of key data corresponding to each segment in the tree,\n                   starting at iter. Loads the segs as it goes."});
        const__61 = (AFn)((IObj)Symbol.intern(null, (String)"dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))}));
        const__62 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"iter")))), RT.keyword(null, (String)"doc"), "Returns a seq of {:key key-datum :seg seg-uuid :count count} corresponding to each segment in the tree,\n                   starting at iter."});
        const__63 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__64 = (AFn)Symbol.intern(null, (String)"ITreeIter");
        const__65 = RT.classForName((String)"datomic.index.IIndex");
        const__66 = RT.var((String)"datomic.index", (String)"IIndex");
        const__67 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"seek-seg")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k"))))}))));
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.index.IIndex"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.index.IIndex")});
        const__70 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seek-seg"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-seg")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns the segid of seg that would contain k (but might not). Does not read seg."})});
        const__72 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seek-seg"), RT.keyword(null, (String)"seek-seg")});
        const__73 = (AFn)((IObj)Symbol.intern(null, (String)"seek-seg")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k"))))}));
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-seg")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"doc"), "Returns the segid of seg that would contain k (but might not). Does not read seg."});
        const__75 = (AFn)Symbol.intern(null, (String)"IIndex");
        const__76 = RT.var((String)"datomic.index", (String)"eavt-cmpi");
        const__77 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 315, RT.keyword(null, (String)"column"), 6});
        const__82 = RT.var((String)"datomic.index", (String)"avet-cmpi");
        const__83 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__85 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 354, RT.keyword(null, (String)"column"), 6});
        const__86 = RT.var((String)"datomic.index", (String)"aevt-cmpi");
        const__87 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 393, RT.keyword(null, (String)"column"), 6});
        const__90 = RT.var((String)"datomic.index", (String)"raet-cmpi");
        const__91 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__93 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 432, RT.keyword(null, (String)"column"), 6});
        const__94 = RT.var((String)"datomic.index", (String)"btree-search");
        const__96 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coll"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"cmp")))), RT.keyword(null, (String)"column"), 1});
        const__97 = RT.var((String)"datomic.index", (String)"binary-search");
        const__99 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coll"), (Object)Symbol.intern(null, (String)"k"), (Object)Symbol.intern(null, (String)"cmp")))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init1() {
        const__100 = RT.var((String)"datomic.index", (String)"indexed-binary-search");
        const__102 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"tdata")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"TransposedData")})), (Object)Symbol.intern(null, (String)"k"), (Object)((IObj)Symbol.intern(null, (String)"cmpi")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IndexedComparator")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__103 = RT.var((String)"datomic.index", (String)"ibtree-search");
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"coll"), (Object)Symbol.intern(null, (String)"k"), (Object)((IObj)Symbol.intern(null, (String)"cmp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IBinarySearch")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__106 = RT.var((String)"datomic.index", (String)"ibinary-search");
        const__108 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"coll")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.util.List")})), (Object)Symbol.intern(null, (String)"k"), (Object)((IObj)Symbol.intern(null, (String)"cmp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IBinarySearch")}))))), RT.keyword(null, (String)"column"), 1});
        const__109 = RT.var((String)"datomic.index", (String)"lookup-index");
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"cmpi"), (Object)Symbol.intern(null, (String)"rootid")))), RT.keyword(null, (String)"column"), 1});
        const__112 = RT.var((String)"datomic.index", (String)"common-write-handlers");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__114 = RT.var((String)"datomic.fressian", (String)"user-write-handlers");
        const__115 = RT.classForName((String)"datomic.index.TransposedData");
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 603, RT.keyword(null, (String)"column"), 12});
        const__119 = RT.classForName((String)"datomic.index.RootNode");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 614, RT.keyword(null, (String)"column"), 12});
        const__122 = RT.classForName((String)"datomic.index.DirNode");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 622, RT.keyword(null, (String)"column"), 12});
        const__125 = RT.var((String)"datomic.index", (String)"index-read-handlers");
        const__126 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__127 = RT.var((String)"datomic.fressian", (String)"user-read-handlers");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 634, RT.keyword(null, (String)"column"), 14});
        const__132 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 646, RT.keyword(null, (String)"column"), 14});
        const__134 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 649, RT.keyword(null, (String)"column"), 14});
        const__135 = RT.var((String)"datomic.index", (String)"index-ref-key-name");
        const__137 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__138 = RT.var((String)"datomic.index", (String)"fress");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"val"), (Object)Symbol.intern(null, (String)"handlers")))), RT.keyword(null, (String)"column"), 1});
        const__143 = RT.var((String)"datomic.index", (String)"transpose");
        const__145 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"datomic.index.TransposedData"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"data")))), RT.keyword(null, (String)"column"), 1});
        const__146 = RT.var((String)"datomic.index", (String)"write-vals");
        const__148 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"vmap")))), RT.keyword(null, (String)"column"), 1});
        const__149 = RT.var((String)"datomic.index", (String)"INDEX_VERSION");
        const__151 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__152 = 2L;
        const__153 = RT.var((String)"datomic.index", (String)"init-index*");
        const__155 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore")))), RT.keyword(null, (String)"column"), 1});
        const__156 = RT.var((String)"datomic.index", (String)"init-index");
        const__158 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore")))), RT.keyword(null, (String)"column"), 1});
        const__159 = RT.var((String)"datomic.index", (String)"find-index-root-id");
        const__161 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore")))), RT.keyword(null, (String)"column"), 1});
        const__162 = RT.var((String)"datomic.index", (String)"valid-version");
        const__164 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"root-map"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__165 = RT.var((String)"datomic.index", (String)"version-root-key");
        const__167 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"version")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__168 = RT.var((String)"datomic.index", (String)"load-index");
        const__170 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"index-root-id")))), RT.keyword(null, (String)"column"), 1});
        const__171 = RT.var((String)"datomic.index", (String)"SEG_BYTES_TARGET");
        const__172 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__173 = 16000L;
        const__174 = RT.var((String)"datomic.index", (String)"SEGS_PER_DIR");
        const__175 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__176 = 3000L;
        const__177 = RT.var((String)"datomic.index", (String)"with-log");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"name"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__180 = RT.var((String)"datomic.index", (String)"floop");
        const__182 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bindings"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__183 = RT.var((String)"datomic.index", (String)"create-pace-calculator");
        const__185 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"target-work"), (Object)Symbol.intern(null, (String)"window-msec")))), RT.keyword(null, (String)"column"), 1});
        const__186 = RT.var((String)"datomic.index", (String)"*pace-index-fn*");
        const__188 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"dynamic"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__189 = RT.var((String)"datomic.index", (String)"build-one-seg");
        const__191 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"data"), (Object)Symbol.intern(null, (String)"cnt"), (Object)Symbol.intern(null, (String)"write-handlers")))), RT.keyword(null, (String)"column"), 1});
        const__192 = RT.var((String)"datomic.index", (String)"bounded-count");
        const__194 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__195 = RT.var((String)"datomic.index", (String)"build-psegs");
        const__197 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"data"), (Object)Symbol.intern(null, (String)"es"), (Object)Symbol.intern(null, (String)"write-handlers"), (Object)Symbol.intern(null, (String)"segs-written-ref")))), RT.keyword(null, (String)"column"), 1});
        const__198 = RT.var((String)"datomic.index", (String)"filter-nohist-pairs");
    }

    public static void __init2() {
        const__200 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"data")))), RT.keyword(null, (String)"column"), 1});
        const__201 = RT.var((String)"datomic.index", (String)"separating-retractions");
        const__203 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"retref"), (Object)Symbol.intern(null, (String)"data")))), RT.keyword(null, (String)"column"), 1});
        const__204 = RT.var((String)"datomic.index", (String)"fully-take-while-delivering-tail");
        const__206 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"p"), (Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__207 = RT.var((String)"datomic.index", (String)"fully-partition-by");
        const__209 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__210 = RT.var((String)"datomic.index", (String)"fred");
        const__212 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"ret"), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__213 = RT.var((String)"datomic.index", (String)"build-segs");
        const__215 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"db"), Symbol.intern(null, (String)"cstore"), Symbol.intern(null, (String)"olookup"), Symbol.intern(null, (String)"data"), Symbol.intern(null, (String)"es"), Symbol.intern(null, (String)"retractions"), Symbol.intern(null, (String)"partfn"), Symbol.intern(null, (String)"write-handlers"), Symbol.intern(null, (String)"segs-written-ref")}))), RT.keyword(null, (String)"column"), 1});
        const__216 = RT.var((String)"datomic.index", (String)"merge-data");
        const__218 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cmp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Comparator")})), (Object)Symbol.intern(null, (String)"ds1"), (Object)Symbol.intern(null, (String)"ds2")))), RT.keyword(null, (String)"column"), 1});
        const__219 = RT.var((String)"datomic.index", (String)"DIR_PARTITION_SIZE");
        const__220 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__229 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"eavt"), 2400L, RT.keyword(null, (String)"aevt"), 2400L, RT.keyword(null, (String)"avet"), 1000L, RT.keyword(null, (String)"raet"), 2400L});
        const__230 = RT.var((String)"datomic.index", (String)"MEM_TO_STG_RATIO");
        const__231 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__232 = 0.07;
        const__233 = RT.var((String)"datomic.index", (String)"BYTES_PER_SEG");
        const__234 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__235 = 45000L;
        const__236 = RT.var((String)"datomic.index", (String)"MID_INDEX_THRESHOLD_FACTOR");
        const__237 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__238 = 10L;
        const__239 = RT.var((String)"datomic.index", (String)"MIN_MAIN_INDEX_THRESHOLD");
        const__240 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__241 = 20000000L;
        const__242 = RT.var((String)"datomic.index", (String)"SLICE_STEP");
        const__243 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__244 = 1L;
        const__245 = RT.var((String)"datomic.index", (String)"dir-partition-size");
        const__247 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx")))), RT.keyword(null, (String)"column"), 1});
        const__248 = RT.var((String)"datomic.index", (String)"make-sparse-lt");
        const__250 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cmp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Comparator")}))))), RT.keyword(null, (String)"column"), 1});
        const__251 = RT.var((String)"datomic.index", (String)"strdiff");
        const__253 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"mins")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")})), (Object)((IObj)Symbol.intern(null, (String)"maxs")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__254 = RT.var((String)"datomic.index", (String)"mindiff");
        const__256 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__257 = RT.var((String)"datomic.index", (String)"vecdiff");
        const__259 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"minv"), (Object)Symbol.intern(null, (String)"maxv")))), RT.keyword(null, (String)"column"), 1});
        const__261 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"minv"), (Object)Symbol.intern(null, (String)"maxv")))), RT.keyword(null, (String)"column"), 1});
        const__262 = RT.var((String)"datomic.index", (String)"sparse-datom");
        const__264 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"idx"), (Object)((IObj)Symbol.intern(null, (String)"prior")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDatum")})), (Object)((IObj)Symbol.intern(null, (String)"d")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDatum")}))))), RT.keyword(null, (String)"column"), 1});
        const__265 = RT.var((String)"datomic.index", (String)"seg-last-datom");
        const__267 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"segid")))), RT.keyword(null, (String)"column"), 1});
        const__268 = RT.var((String)"datomic.index", (String)"sparse-e-xf");
        const__270 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"idx")))), RT.keyword(null, (String)"column"), 1});
        const__271 = RT.var((String)"datomic.index", (String)"sparse-es-2");
        const__273 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"es")))), RT.keyword(null, (String)"column"), 1});
        const__274 = RT.var((String)"datomic.index", (String)"sparse-es");
        const__276 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"es")))), RT.keyword(null, (String)"column"), 1});
        const__277 = RT.var((String)"datomic.index", (String)"index-parallelism");
        const__278 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__279 = RT.var((String)"clojure.core", (String)"atom");
        const__280 = RT.keyword(null, (String)"validator");
        const__281 = RT.var((String)"datomic.index", (String)"serialize-dir");
        const__283 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"des")))), RT.keyword(null, (String)"column"), 1});
        const__284 = RT.var((String)"datomic.index", (String)"write-dirs");
        const__286 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"ch")))), RT.keyword(null, (String)"column"), 1});
        const__287 = RT.var((String)"datomic.index", (String)"conjable-on-channel");
        const__289 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ch")))), RT.keyword(null, (String)"column"), 1});
        const__290 = RT.var((String)"datomic.index", (String)"capture-last-ex");
        const__292 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__293 = RT.var((String)"datomic.index", (String)"start-dirs-pipeline");
        const__295 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cstore"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"idx"), (Object)Symbol.intern(null, (String)"dirnode-size"), (Object)Symbol.intern(null, (String)"dirs-ahead"), (Object)Symbol.intern(null, (String)"serialize-par"))})))), RT.keyword(null, (String)"column"), 1});
        const__296 = RT.var((String)"datomic.index", (String)"merge-one-index");
        const__298 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"db"), Symbol.intern(null, (String)"cstore"), Symbol.intern(null, (String)"olookup"), Symbol.intern(null, (String)"old-root-id"), Symbol.intern(null, (String)"data"), Symbol.intern(null, (String)"garbage-ids"), Symbol.intern(null, (String)"partfn"), Symbol.intern(null, (String)"cmp"), Symbol.intern(null, (String)"write-handlers"), Symbol.intern(null, (String)"filter-retractions?"), Symbol.intern(null, (String)"as-of-t"), Symbol.intern(null, (String)"idx"), Symbol.intern(null, (String)"xpreds"), Symbol.intern(null, (String)"filter-segids"), Symbol.intern(null, (String)"xcmp"), Symbol.intern(null, (String)"segs-written-ref"), Symbol.intern(null, (String)"dirs-written-ref")}))), RT.keyword(null, (String)"column"), 1});
        const__299 = RT.var((String)"datomic.index", (String)"excise-ents");
    }

    public static void __init3() {
        const__301 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__302 = RT.var((String)"datomic.index", (String)"get-avet-sorted-datoms-mem");
        const__304 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"attrids")))), RT.keyword(null, (String)"column"), 1});
        const__305 = RT.var((String)"datomic.index", (String)"avet-sort-and-process-datoms");
        const__307 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"datoms"), (Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__308 = RT.var((String)"datomic.index", (String)"attr-datoms");
        const__310 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"attrid")))), RT.keyword(null, (String)"column"), 1});
        const__311 = RT.var((String)"datomic.index", (String)"aevt-attrs-datoms");
        const__313 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), (Object)Symbol.intern(null, (String)"attrids")))), RT.keyword(null, (String)"column"), 1});
        const__314 = RT.var((String)"datomic.index", (String)"idx-key");
        const__316 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"ks")))), RT.keyword(null, (String)"column"), 1});
        const__317 = RT.var((String)"datomic.index", (String)"add-avet-indexes");
        const__319 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore"), (Object)Symbol.intern(null, (String)"olookup"), (Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), (Object)Symbol.intern(null, (String)"as-of-t"), (Object)Symbol.intern(null, (String)"root-map"), (Object)Symbol.intern(null, (String)"attrids")))), RT.keyword(null, (String)"column"), 1});
        const__320 = RT.var((String)"datomic.index", (String)"needs-new-avet");
        const__322 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")}))))), RT.keyword(null, (String)"column"), 1});
        const__323 = RT.var((String)"datomic.index", (String)"dropped-avet-aids");
        const__325 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")}))))), RT.keyword(null, (String)"column"), 1});
        const__326 = RT.var((String)"datomic.index", (String)"write-object");
        const__328 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"store"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"v")))), RT.keyword(null, (String)"column"), 1});
        const__329 = RT.var((String)"datomic.index", (String)"drop-dirnode-leaves");
        const__331 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"dirnode")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"DirNode")})), (Object)Symbol.intern(null, (String)"drop?")))), RT.keyword(null, (String)"column"), 1});
        const__332 = RT.var((String)"datomic.index", (String)"drop-avet");
        const__334 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"store"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"old-rootid"), (Object)Symbol.intern(null, (String)"aid"), (Object)Symbol.intern(null, (String)"old-garbage")))), RT.keyword(null, (String)"column"), 1});
        const__335 = RT.var((String)"datomic.index", (String)"drop-avets");
        const__337 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"store"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"attrids"), (Object)Symbol.intern(null, (String)"garbage")))), RT.keyword(null, (String)"column"), 1});
        const__338 = RT.var((String)"datomic.index", (String)"drop-avet-indexes");
        const__340 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"store"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"old-root-ids"), (Object)Symbol.intern(null, (String)"attrids"), (Object)Symbol.intern(null, (String)"as-of-t"), (Object)Symbol.intern(null, (String)"garbage"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"post"), Tuple.create((Object)((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"="), ((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"count"), Symbol.intern(null, (String)"old-root-ids")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 14})), ((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"count"), ((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"first"), Symbol.intern(null, (String)"%")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 42}))))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 35}))))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 11})))})))), RT.keyword(null, (String)"column"), 1});
        const__341 = RT.var((String)"datomic.index", (String)"mem-index-bytes");
        const__343 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"index")))), RT.keyword(null, (String)"column"), 1});
        const__344 = RT.var((String)"datomic.index", (String)"stg-index-segs");
        const__346 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)((IObj)Symbol.intern(null, (String)"index")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Index")})), (Object)Symbol.intern(null, (String)"part-size")))), RT.keyword(null, (String)"column"), 1});
        const__347 = RT.var((String)"datomic.index", (String)"stg-index-size");
        const__349 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"part-size")))), RT.keyword(null, (String)"column"), 1});
        const__350 = RT.var((String)"datomic.index", (String)"estimate-seg-offset");
        const__352 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)((IObj)Symbol.intern(null, (String)"index")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Index")})), (Object)Symbol.intern(null, (String)"dir-partition-size"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__353 = RT.var((String)"datomic.index", (String)"least-pop-slice");
        const__355 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"ks"), (Object)((IObj)Symbol.intern(null, (String)"index")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Index")})), (Object)Symbol.intern(null, (String)"dir-partition-size"), (Object)Symbol.intern(null, (String)"slice-size")))), RT.keyword(null, (String)"column"), 1});
        const__356 = RT.var((String)"datomic.index", (String)"retract-assert-pair?");
        const__358 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"d1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.Datum")})), (Object)((IObj)Symbol.intern(null, (String)"d2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.Datum")}))))), RT.keyword(null, (String)"column"), 1});
        const__359 = RT.var((String)"datomic.index", (String)"paired-assertion-state");
        const__361 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"sd1"), (Object)Tuple.create((Object)Symbol.intern(null, (String)"sd2"), (Object)RT.keyword(null, (String)"as"), (Object)Symbol.intern(null, (String)"more"))))), RT.keyword(null, (String)"column"), 1});
        const__362 = RT.var((String)"datomic.index", (String)"problem-assertion-state?");
        const__364 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"tier"), (Object)Symbol.intern(null, (String)"state")))), RT.keyword(null, (String)"column"), 1});
        const__365 = RT.var((String)"datomic.index", (String)"disjoined-datoms");
        const__367 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"tier"), (Object)Symbol.intern(null, (String)"sort")))), RT.keyword(null, (String)"column"), 1});
        const__368 = RT.var((String)"datomic.index", (String)"repair-disjoined");
        const__370 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"root-map")))), RT.keyword(null, (String)"column"), 1});
        const__371 = RT.var((String)"datomic.index", (String)"merge-db*");
        const__373 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"cstore"), Symbol.intern(null, (String)"olookup"), ((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), Symbol.intern(null, (String)"as-of-t"), Symbol.intern(null, (String)"old-root-id"), Symbol.intern(null, (String)"extra"), Symbol.intern(null, (String)"fulltext-enabled?"), Symbol.intern(null, (String)"excise-enabled?")}))), RT.keyword(null, (String)"column"), 1});
        const__374 = RT.var((String)"datomic.index", (String)"merge-db");
        const__376 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cstore"), (Object)Symbol.intern(null, (String)"olookup"), (Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), (Object)Symbol.intern(null, (String)"as-of-t")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        index__init.__init0();
        index__init.__init1();
        index__init.__init2();
        index__init.__init3();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.index__init").getClassLoader());
        try {
            index__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

