/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.integrity$_main;
import datomic.integrity$_main_STAR_;
import datomic.integrity$aevt_avet_stats;
import datomic.integrity$aevt_avet_stats_consistent_QMARK_;
import datomic.integrity$aevt_dquark_seq;
import datomic.integrity$attr_datoms;
import datomic.integrity$attr_id_set;
import datomic.integrity$avet_dquark_seq;
import datomic.integrity$cauterize;
import datomic.integrity$clusterfs_path_reachability;
import datomic.integrity$crosscheck_aevt_aevt;
import datomic.integrity$crosscheck_aevt_avet;
import datomic.integrity$crosscheck_aevt_eavt;
import datomic.integrity$crosscheck_aevt_raet;
import datomic.integrity$crosscheck_avet_aevt;
import datomic.integrity$crosscheck_avet_avet;
import datomic.integrity$crosscheck_avet_eavt;
import datomic.integrity$crosscheck_dir_segs;
import datomic.integrity$crosscheck_eavt_aevt;
import datomic.integrity$crosscheck_eavt_avet;
import datomic.integrity$crosscheck_eavt_eavt;
import datomic.integrity$crosscheck_eavt_raet;
import datomic.integrity$crosscheck_indexes;
import datomic.integrity$crosscheck_log;
import datomic.integrity$crosscheck_log_cli;
import datomic.integrity$crosscheck_log_representations;
import datomic.integrity$crosscheck_raet_aevt;
import datomic.integrity$crosscheck_raet_eavt;
import datomic.integrity$crosscheck_raet_raet;
import datomic.integrity$crosscheck_tx_range_with_tx_instant;
import datomic.integrity$datom_comparator;
import datomic.integrity$defcrosscheck;
import datomic.integrity$describe_segment;
import datomic.integrity$dir_seg_info_seq;
import datomic.integrity$dups;
import datomic.integrity$e_ts;
import datomic.integrity$eavt_dquark_seq;
import datomic.integrity$esafe;
import datomic.integrity$excisions;
import datomic.integrity$fn__21960;
import datomic.integrity$fn__21962;
import datomic.integrity$fn__21968;
import datomic.integrity$fn__21970;
import datomic.integrity$fulltext_path_reachability;
import datomic.integrity$fulltext_storage_seq;
import datomic.integrity$get_db;
import datomic.integrity$index_storage_seq;
import datomic.integrity$loading__6434__auto____20643;
import datomic.integrity$log_dir_entry_seq;
import datomic.integrity$log_seg_t_seq;
import datomic.integrity$log_storage_seq;
import datomic.integrity$make_tupler;
import datomic.integrity$merge_seqs;
import datomic.integrity$mk_attr_pred;
import datomic.integrity$mk_index_pred;
import datomic.integrity$nohistory_attrs;
import datomic.integrity$path_to_t;
import datomic.integrity$pod_storage_seq;
import datomic.integrity$progress_dot;
import datomic.integrity$progress_dot_fn;
import datomic.integrity$progress_reduce;
import datomic.integrity$report_aevt_avet_stats;
import datomic.integrity$restatement_QMARK_;
import datomic.integrity$selfcheck_index_cli;
import datomic.integrity$seq_diffs;
import datomic.integrity$stat_counts;
import datomic.integrity$tx_instant_ts;
import datomic.integrity$tx_range_ts;
import datomic.integrity$unfindable_datom_seq;
import datomic.integrity$unpaired_history_assertions;
import datomic.integrity$unpaired_history_retractions;
import datomic.integrity$unsorted_datoms;
import datomic.integrity$unsorted_dirs;
import datomic.integrity$validate_all;
import datomic.integrity$validate_dir_sorts;
import datomic.integrity$validate_excision;
import datomic.integrity$validate_fulltext;
import datomic.integrity$validate_garbage;
import datomic.integrity$validate_history_pairs;
import datomic.integrity$validate_index_sorts;
import datomic.integrity$validate_index_totals;
import datomic.integrity$validate_indexed_excisions;
import datomic.integrity$validate_log_cli;
import datomic.integrity$validate_memory_safe;
import datomic.integrity$validate_nohistory;
import datomic.integrity$validate_t_order;
import datomic.integrity$validate_t_order_STAR_;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class integrity__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final Keyword const__5;
    public static final Keyword const__6;
    public static final Var const__7;
    public static final AFn const__12;
    public static final Var const__13;
    public static final AFn const__15;
    public static final Var const__16;
    public static final AFn const__18;
    public static final Var const__19;
    public static final AFn const__21;
    public static final Var const__22;
    public static final AFn const__24;
    public static final Var const__25;
    public static final AFn const__27;
    public static final Var const__28;
    public static final AFn const__30;
    public static final Var const__31;
    public static final AFn const__33;
    public static final Var const__34;
    public static final AFn const__36;
    public static final Var const__37;
    public static final AFn const__39;
    public static final Var const__40;
    public static final AFn const__42;
    public static final Var const__43;
    public static final AFn const__45;
    public static final Var const__46;
    public static final AFn const__48;
    public static final Var const__49;
    public static final AFn const__51;
    public static final Var const__52;
    public static final AFn const__54;
    public static final Var const__55;
    public static final AFn const__57;
    public static final Var const__58;
    public static final AFn const__60;
    public static final Var const__61;
    public static final AFn const__63;
    public static final Var const__64;
    public static final AFn const__66;
    public static final Var const__67;
    public static final AFn const__69;
    public static final Var const__70;
    public static final AFn const__73;
    public static final Var const__74;
    public static final AFn const__76;
    public static final Var const__77;
    public static final AFn const__79;
    public static final Var const__80;
    public static final AFn const__82;
    public static final Var const__83;
    public static final AFn const__85;
    public static final Var const__86;
    public static final AFn const__88;
    public static final Var const__89;
    public static final AFn const__91;
    public static final Var const__92;
    public static final AFn const__94;
    public static final Var const__95;
    public static final AFn const__97;
    public static final Var const__98;
    public static final AFn const__100;
    public static final Var const__101;
    public static final AFn const__103;
    public static final Var const__104;
    public static final AFn const__106;
    public static final Var const__107;
    public static final AFn const__109;
    public static final Var const__110;
    public static final AFn const__112;
    public static final Var const__113;
    public static final AFn const__115;
    public static final Var const__116;
    public static final AFn const__118;
    public static final Var const__119;
    public static final AFn const__121;
    public static final Var const__122;
    public static final AFn const__124;
    public static final Var const__125;
    public static final AFn const__127;
    public static final Var const__128;
    public static final AFn const__130;
    public static final Var const__131;
    public static final AFn const__133;
    public static final Var const__134;
    public static final AFn const__136;
    public static final Var const__137;
    public static final AFn const__139;
    public static final Var const__140;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__145;
    public static final Var const__146;
    public static final AFn const__148;
    public static final Var const__149;
    public static final AFn const__151;
    public static final Var const__152;
    public static final AFn const__154;
    public static final Var const__155;
    public static final AFn const__157;
    public static final Var const__158;
    public static final AFn const__160;
    public static final Var const__161;
    public static final AFn const__163;
    public static final Var const__164;
    public static final AFn const__166;
    public static final Var const__167;
    public static final AFn const__169;
    public static final Var const__170;
    public static final AFn const__172;
    public static final Var const__173;
    public static final AFn const__175;
    public static final Var const__176;
    public static final AFn const__178;
    public static final Var const__179;
    public static final AFn const__181;
    public static final Var const__182;
    public static final AFn const__184;
    public static final Var const__185;
    public static final AFn const__187;
    public static final Var const__188;
    public static final AFn const__190;
    public static final Var const__191;
    public static final AFn const__193;
    public static final Var const__194;
    public static final AFn const__196;
    public static final Var const__197;
    public static final AFn const__199;
    public static final Var const__200;
    public static final AFn const__202;
    public static final Var const__203;
    public static final AFn const__205;
    public static final Var const__206;
    public static final AFn const__208;
    public static final Var const__209;
    public static final AFn const__211;
    public static final Var const__212;
    public static final AFn const__214;
    public static final Var const__215;
    public static final AFn const__217;
    public static final Var const__218;
    public static final AFn const__220;
    public static final Var const__221;
    public static final AFn const__223;
    public static final Var const__224;
    public static final AFn const__226;
    public static final Var const__227;
    public static final AFn const__229;
    public static final Var const__230;
    public static final AFn const__232;
    public static final Var const__233;
    public static final AFn const__234;
    public static final Var const__235;
    public static final Var const__236;
    public static final AFn const__238;
    public static final Var const__239;
    public static final AFn const__241;
    public static final Var const__242;
    public static final AFn const__244;
    public static final Var const__245;
    public static final AFn const__247;
    public static final Var const__248;
    public static final AFn const__250;
    public static final Var const__251;
    public static final AFn const__253;
    public static final Var const__254;
    public static final AFn const__255;
    public static final AFn const__272;
    public static final Var const__273;
    public static final AFn const__275;
    public static final Var const__276;
    public static final AFn const__278;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new integrity$loading__6434__auto____20643()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new integrity$fn__21960())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = ((IFn)new integrity$fn__21962()).invoke();
        MultiFn multiFn = ((MultiFn)const__4.getRawRoot()).addMethod((Object)const__5, (IFn)new integrity$fn__21968());
        MultiFn multiFn2 = ((MultiFn)const__4.getRawRoot()).addMethod((Object)const__6, (IFn)new integrity$fn__21970());
        Var var = const__7;
        var.setMeta((IPersistentMap)const__12);
        Var var2 = var;
        var.bindRoot((Object)new integrity$progress_reduce());
        Var var3 = const__13;
        var3.setMeta((IPersistentMap)const__15);
        Var var4 = var3;
        var3.bindRoot((Object)new integrity$progress_dot());
        Var var5 = const__16;
        var5.setMeta((IPersistentMap)const__18);
        Var var6 = var5;
        var5.bindRoot((Object)new integrity$cauterize());
        Var var7 = const__19;
        var7.setMeta((IPersistentMap)const__21);
        Var var8 = var7;
        var7.bindRoot((Object)new integrity$nohistory_attrs());
        Var var9 = const__22;
        var9.setMeta((IPersistentMap)const__24);
        Var var10 = var9;
        var9.bindRoot((Object)new integrity$attr_datoms());
        Var var11 = const__25;
        var11.setMeta((IPersistentMap)const__27);
        Var var12 = var11;
        var11.bindRoot((Object)new integrity$dups());
        Var var13 = const__28;
        var13.setMeta((IPersistentMap)const__30);
        Var var14 = var13;
        var13.bindRoot((Object)new integrity$restatement_QMARK_());
        Var var15 = const__31;
        var15.setMeta((IPersistentMap)const__33);
        Var var16 = var15;
        var15.bindRoot((Object)new integrity$attr_id_set());
        Var var17 = const__34;
        var17.setMeta((IPersistentMap)const__36);
        Var var18 = var17;
        var17.bindRoot((Object)new integrity$make_tupler());
        Var var19 = const__37;
        var19.setMeta((IPersistentMap)const__39);
        Var var20 = var19;
        var19.bindRoot((Object)new integrity$unfindable_datom_seq());
        Var var21 = const__40;
        var21.setMeta((IPersistentMap)const__42);
        Var var22 = var21;
        var21.bindRoot((Object)new integrity$progress_dot_fn());
        Var var23 = const__43;
        var23.setMeta((IPersistentMap)const__45);
        Var var24 = var23;
        var23.bindRoot((Object)new integrity$datom_comparator());
        Var var25 = const__46;
        var25.setMeta((IPersistentMap)const__48);
        Var var26 = var25;
        var25.bindRoot((Object)new integrity$unsorted_dirs());
        Var var27 = const__49;
        var27.setMeta((IPersistentMap)const__51);
        Var var28 = var27;
        var27.bindRoot((Object)new integrity$validate_dir_sorts());
        Var var29 = const__52;
        var29.setMeta((IPersistentMap)const__54);
        Var var30 = var29;
        var29.bindRoot((Object)new integrity$unsorted_datoms());
        Var var31 = const__55;
        var31.setMeta((IPersistentMap)const__57);
        Var var32 = var31;
        var31.bindRoot((Object)new integrity$validate_index_sorts());
        Var var33 = const__58;
        var33.setMeta((IPersistentMap)const__60);
        Var var34 = var33;
        var33.bindRoot((Object)new integrity$unpaired_history_assertions());
        Var var35 = const__61;
        var35.setMeta((IPersistentMap)const__63);
        Var var36 = var35;
        var35.bindRoot((Object)new integrity$unpaired_history_retractions());
        Var var37 = const__64;
        var37.setMeta((IPersistentMap)const__66);
        Var var38 = var37;
        var37.bindRoot((Object)new integrity$validate_history_pairs());
        Var var39 = const__67;
        var39.setMeta((IPersistentMap)const__69);
        Var var40 = var39;
        var39.bindRoot((Object)new integrity$selfcheck_index_cli());
        Var var41 = const__70;
        var41.setMeta((IPersistentMap)const__73);
        Var var42 = var41;
        var41.bindRoot((Object)new integrity$mk_attr_pred());
        Var var43 = const__74;
        var43.setMeta((IPersistentMap)const__76);
        Var var44 = var43;
        var43.bindRoot((Object)new integrity$mk_index_pred());
        Var var45 = const__77;
        var45.setMeta((IPersistentMap)const__79);
        Var var46 = var45;
        var45.bindRoot((Object)new integrity$crosscheck_log());
        Var var47 = const__80;
        var47.setMeta((IPersistentMap)const__82);
        Var var48 = var47;
        var47.bindRoot((Object)new integrity$crosscheck_log_representations());
        Var var49 = const__83;
        var49.setMeta((IPersistentMap)const__85);
        Var var50 = var49;
        var49.bindRoot((Object)new integrity$crosscheck_log_cli());
        Var var51 = const__86;
        var51.setMeta((IPersistentMap)const__88);
        Var var52 = var51;
        var51.bindRoot((Object)new integrity$defcrosscheck());
        const__86.setMacro();
        Object v59 = null;
        Var var53 = const__86;
        Var var54 = const__89;
        var54.setMeta((IPersistentMap)const__91);
        Var var55 = var54;
        var54.bindRoot((Object)new integrity$crosscheck_eavt_eavt());
        Var var56 = const__92;
        var56.setMeta((IPersistentMap)const__94);
        Var var57 = var56;
        var56.bindRoot((Object)new integrity$crosscheck_aevt_aevt());
        Var var58 = const__95;
        var58.setMeta((IPersistentMap)const__97);
        Var var59 = var58;
        var58.bindRoot((Object)new integrity$crosscheck_avet_avet());
        Var var60 = const__98;
        var60.setMeta((IPersistentMap)const__100);
        Var var61 = var60;
        var60.bindRoot((Object)new integrity$crosscheck_raet_raet());
        Var var62 = const__101;
        var62.setMeta((IPersistentMap)const__103);
        Var var63 = var62;
        var62.bindRoot((Object)new integrity$crosscheck_eavt_aevt());
        Var var64 = const__104;
        var64.setMeta((IPersistentMap)const__106);
        Var var65 = var64;
        var64.bindRoot((Object)new integrity$crosscheck_aevt_eavt());
        Var var66 = const__107;
        var66.setMeta((IPersistentMap)const__109);
        Var var67 = var66;
        var66.bindRoot((Object)new integrity$crosscheck_avet_eavt());
        Var var68 = const__110;
        var68.setMeta((IPersistentMap)const__112);
        Var var69 = var68;
        var68.bindRoot((Object)new integrity$crosscheck_avet_aevt());
        Var var70 = const__113;
        var70.setMeta((IPersistentMap)const__115);
        Var var71 = var70;
        var70.bindRoot((Object)new integrity$crosscheck_raet_aevt());
        Var var72 = const__116;
        var72.setMeta((IPersistentMap)const__118);
        Var var73 = var72;
        var72.bindRoot((Object)new integrity$crosscheck_raet_eavt());
        Var var74 = const__119;
        var74.setMeta((IPersistentMap)const__121);
        Var var75 = var74;
        var74.bindRoot((Object)new integrity$crosscheck_aevt_avet());
        Var var76 = const__122;
        var76.setMeta((IPersistentMap)const__124);
        Var var77 = var76;
        var76.bindRoot((Object)new integrity$crosscheck_eavt_avet());
        Var var78 = const__125;
        var78.setMeta((IPersistentMap)const__127);
        Var var79 = var78;
        var78.bindRoot((Object)new integrity$crosscheck_aevt_raet());
        Var var80 = const__128;
        var80.setMeta((IPersistentMap)const__130);
        Var var81 = var80;
        var80.bindRoot((Object)new integrity$crosscheck_eavt_raet());
        Var var82 = const__131;
        var82.setMeta((IPersistentMap)const__133);
        Var var83 = var82;
        var82.bindRoot((Object)new integrity$get_db());
        Var var84 = const__134;
        var84.setMeta((IPersistentMap)const__136);
        Var var85 = var84;
        var84.bindRoot((Object)new integrity$crosscheck_indexes());
        Var var86 = const__137;
        var86.setMeta((IPersistentMap)const__139);
        Var var87 = var86;
        var86.bindRoot((Object)new integrity$path_to_t());
        Var var88 = const__140;
        var88.setMeta((IPersistentMap)const__142);
        Var var89 = var88;
        var88.bindRoot((Object)new integrity$dir_seg_info_seq());
        Var var90 = const__143;
        var90.setMeta((IPersistentMap)const__145);
        Var var91 = var90;
        var90.bindRoot((Object)new integrity$validate_t_order_STAR_());
        Var var92 = const__146;
        var92.setMeta((IPersistentMap)const__148);
        Var var93 = var92;
        var92.bindRoot((Object)new integrity$validate_t_order());
        Var var94 = const__149;
        var94.setMeta((IPersistentMap)const__151);
        Var var95 = var94;
        var94.bindRoot((Object)new integrity$log_dir_entry_seq());
        Var var96 = const__152;
        var96.setMeta((IPersistentMap)const__154);
        Var var97 = var96;
        var96.bindRoot((Object)new integrity$log_seg_t_seq());
        Var var98 = const__155;
        var98.setMeta((IPersistentMap)const__157);
        Var var99 = var98;
        var98.bindRoot((Object)new integrity$crosscheck_dir_segs());
        Var var100 = const__158;
        var100.setMeta((IPersistentMap)const__160);
        Var var101 = var100;
        var100.bindRoot((Object)new integrity$merge_seqs());
        Var var102 = const__161;
        var102.setMeta((IPersistentMap)const__163);
        Var var103 = var102;
        var102.bindRoot((Object)new integrity$aevt_dquark_seq());
        Var var104 = const__164;
        var104.setMeta((IPersistentMap)const__166);
        Var var105 = var104;
        var104.bindRoot((Object)new integrity$eavt_dquark_seq());
        Var var106 = const__167;
        var106.setMeta((IPersistentMap)const__169);
        Var var107 = var106;
        var106.bindRoot((Object)new integrity$avet_dquark_seq());
        Var var108 = const__170;
        var108.setMeta((IPersistentMap)const__172);
        Var var109 = var108;
        var108.bindRoot((Object)new integrity$validate_log_cli());
        Var var110 = const__173;
        var110.setMeta((IPersistentMap)const__175);
        Var var111 = var110;
        var110.bindRoot((Object)new integrity$validate_memory_safe());
        Var var112 = const__176;
        var112.setMeta((IPersistentMap)const__178);
        Var var113 = var112;
        var112.bindRoot((Object)new integrity$excisions());
        Var var114 = const__179;
        var114.setMeta((IPersistentMap)const__181);
        Var var115 = var114;
        var114.bindRoot((Object)new integrity$e_ts());
        Var var116 = const__182;
        var116.setMeta((IPersistentMap)const__184);
        Var var117 = var116;
        var116.bindRoot((Object)new integrity$validate_excision());
        Var var118 = const__185;
        var118.setMeta((IPersistentMap)const__187);
        Var var119 = var118;
        var118.bindRoot((Object)new integrity$validate_indexed_excisions());
        Var var120 = const__188;
        var120.setMeta((IPersistentMap)const__190);
        Var var121 = var120;
        var120.bindRoot((Object)new integrity$clusterfs_path_reachability());
        Var var122 = const__191;
        var122.setMeta((IPersistentMap)const__193);
        Var var123 = var122;
        var122.bindRoot((Object)new integrity$fulltext_path_reachability());
        Var var124 = const__194;
        var124.setMeta((IPersistentMap)const__196);
        Var var125 = var124;
        var124.bindRoot((Object)new integrity$validate_fulltext());
        Var var126 = const__197;
        var126.setMeta((IPersistentMap)const__199);
        Var var127 = var126;
        var126.bindRoot((Object)new integrity$tx_range_ts());
        Var var128 = const__200;
        var128.setMeta((IPersistentMap)const__202);
        Var var129 = var128;
        var128.bindRoot((Object)new integrity$tx_instant_ts());
        Var var130 = const__203;
        var130.setMeta((IPersistentMap)const__205);
        Var var131 = var130;
        var130.bindRoot((Object)new integrity$seq_diffs());
        Var var132 = const__206;
        var132.setMeta((IPersistentMap)const__208);
        Var var133 = var132;
        var132.bindRoot((Object)new integrity$validate_garbage());
        Var var134 = const__209;
        var134.setMeta((IPersistentMap)const__211);
        Var var135 = var134;
        var134.bindRoot((Object)new integrity$crosscheck_tx_range_with_tx_instant());
        Var var136 = const__212;
        var136.setMeta((IPersistentMap)const__214);
        Var var137 = var136;
        var136.bindRoot((Object)new integrity$validate_nohistory());
        Var var138 = const__215;
        var138.setMeta((IPersistentMap)const__217);
        Var var139 = var138;
        var138.bindRoot((Object)new integrity$stat_counts());
        Var var140 = const__218;
        var140.setMeta((IPersistentMap)const__220);
        Var var141 = var140;
        var140.bindRoot((Object)new integrity$aevt_avet_stats());
        Object v149 = null;
        Var var142 = const__221;
        var142.setMeta((IPersistentMap)const__223);
        Var var143 = var142;
        var142.bindRoot((Object)new integrity$aevt_avet_stats_consistent_QMARK_());
        Var var144 = const__224;
        var144.setMeta((IPersistentMap)const__226);
        Var var145 = var144;
        var144.bindRoot((Object)new integrity$report_aevt_avet_stats());
        Var var146 = const__227;
        var146.setMeta((IPersistentMap)const__229);
        Var var147 = var146;
        var146.bindRoot((Object)new integrity$validate_index_totals());
        Var var148 = const__230;
        var148.setMeta((IPersistentMap)const__232);
        Var var149 = var148;
        var148.bindRoot((Object)new integrity$validate_all());
        Var var150 = const__233;
        var150.setMeta((IPersistentMap)const__234);
        Var var151 = var150;
        var150.bindRoot(const__235.getRawRoot());
        Var var152 = const__236;
        var152.setMeta((IPersistentMap)const__238);
        Var var153 = var152;
        var152.bindRoot((Object)new integrity$describe_segment());
        Var var154 = const__239;
        var154.setMeta((IPersistentMap)const__241);
        Var var155 = var154;
        var154.bindRoot((Object)new integrity$fulltext_storage_seq());
        Var var156 = const__242;
        var156.setMeta((IPersistentMap)const__244);
        Var var157 = var156;
        var156.bindRoot((Object)new integrity$log_storage_seq());
        Var var158 = const__245;
        var158.setMeta((IPersistentMap)const__247);
        Var var159 = var158;
        var158.bindRoot((Object)new integrity$index_storage_seq());
        Var var160 = const__248;
        var160.setMeta((IPersistentMap)const__250);
        Var var161 = var160;
        var160.bindRoot((Object)new integrity$pod_storage_seq());
        Var var162 = const__251;
        var162.setMeta((IPersistentMap)const__253);
        Var var163 = var162;
        var162.bindRoot((Object)new integrity$esafe());
        const__251.setMacro();
        Object v172 = null;
        Var var164 = const__251;
        Var var165 = const__254;
        var165.setMeta((IPersistentMap)const__255);
        Var var166 = var165;
        var165.bindRoot((Object)const__272);
        Var var167 = const__273;
        var167.setMeta((IPersistentMap)const__275);
        Var var168 = var167;
        var167.bindRoot((Object)new integrity$_main_STAR_());
        Var var169 = const__276;
        var169.setMeta((IPersistentMap)const__278);
        Var var170 = var169;
        var169.bindRoot((Object)new integrity$_main());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.integrity");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.integrity", (String)"enhance-uri");
        const__5 = RT.keyword(null, (String)"default");
        const__6 = RT.keyword(null, (String)"ddb+s3");
        const__7 = RT.var((String)"datomic.integrity", (String)"progress-reduce");
        const__12 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"val"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"n"))}), (Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__13 = RT.var((String)"datomic.integrity", (String)"progress-dot");
        const__15 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"column"), 1});
        const__16 = RT.var((String)"datomic.integrity", (String)"cauterize");
        const__18 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"ks")))), RT.keyword(null, (String)"column"), 1});
        const__19 = RT.var((String)"datomic.integrity", (String)"nohistory-attrs");
        const__21 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__22 = RT.var((String)"datomic.integrity", (String)"attr-datoms");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"attrs")))), RT.keyword(null, (String)"column"), 1});
        const__25 = RT.var((String)"datomic.integrity", (String)"dups");
        const__27 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"attr")))), RT.keyword(null, (String)"column"), 1});
        const__28 = RT.var((String)"datomic.integrity", (String)"restatement?");
        const__30 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"d1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Datom")})), (Object)((IObj)Symbol.intern(null, (String)"d2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Datom")})))))), RT.keyword(null, (String)"column"), 1});
        const__31 = RT.var((String)"datomic.integrity", (String)"attr-id-set");
        const__33 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"pred")))), RT.keyword(null, (String)"column"), 1});
        const__34 = RT.var((String)"datomic.integrity", (String)"make-tupler");
        const__36 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"index")))), RT.keyword(null, (String)"column"), 1});
        const__37 = RT.var((String)"datomic.integrity", (String)"unfindable-datom-seq");
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__40 = RT.var((String)"datomic.integrity", (String)"progress-dot-fn");
        const__42 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__43 = RT.var((String)"datomic.integrity", (String)"datom-comparator");
        const__45 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"sort"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.util.Comparator")})))), RT.keyword(null, (String)"column"), 1});
        const__46 = RT.var((String)"datomic.integrity", (String)"unsorted-dirs");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"tier"), (Object)Symbol.intern(null, (String)"sort"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__49 = RT.var((String)"datomic.integrity", (String)"validate-dir-sorts");
        const__51 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__52 = RT.var((String)"datomic.integrity", (String)"unsorted-datoms");
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"sort"), (Object)Symbol.intern(null, (String)"order"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__55 = RT.var((String)"datomic.integrity", (String)"validate-index-sorts");
        const__57 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")), Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"order")))), RT.keyword(null, (String)"column"), 1});
        const__58 = RT.var((String)"datomic.integrity", (String)"unpaired-history-assertions");
        const__60 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"sort"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__61 = RT.var((String)"datomic.integrity", (String)"unpaired-history-retractions");
        const__63 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"sort"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__64 = RT.var((String)"datomic.integrity", (String)"validate-history-pairs");
        const__66 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__67 = RT.var((String)"datomic.integrity", (String)"selfcheck-index-cli");
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"uri"))})))), RT.keyword(null, (String)"column"), 1});
        const__70 = RT.var((String)"datomic.integrity", (String)"mk-attr-pred");
        const__73 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__74 = RT.var((String)"datomic.integrity", (String)"mk-index-pred");
        const__76 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"index")))), RT.keyword(null, (String)"column"), 1});
        const__77 = RT.var((String)"datomic.integrity", (String)"crosscheck-log");
        const__79 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"index")), Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"index"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__80 = RT.var((String)"datomic.integrity", (String)"crosscheck-log-representations");
        const__82 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")), Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__83 = RT.var((String)"datomic.integrity", (String)"crosscheck-log-cli");
        const__85 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"uri"))})))), RT.keyword(null, (String)"column"), 1});
        const__86 = RT.var((String)"datomic.integrity", (String)"defcrosscheck");
        const__88 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"i1"), (Object)Symbol.intern(null, (String)"i2")))), RT.keyword(null, (String)"column"), 1});
        const__89 = RT.var((String)"datomic.integrity", (String)"crosscheck-eavt-eavt");
        const__91 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__92 = RT.var((String)"datomic.integrity", (String)"crosscheck-aevt-aevt");
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__95 = RT.var((String)"datomic.integrity", (String)"crosscheck-avet-avet");
        const__97 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__98 = RT.var((String)"datomic.integrity", (String)"crosscheck-raet-raet");
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__101 = RT.var((String)"datomic.integrity", (String)"crosscheck-eavt-aevt");
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__104 = RT.var((String)"datomic.integrity", (String)"crosscheck-aevt-eavt");
        const__106 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__107 = RT.var((String)"datomic.integrity", (String)"crosscheck-avet-eavt");
        const__109 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__110 = RT.var((String)"datomic.integrity", (String)"crosscheck-avet-aevt");
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__113 = RT.var((String)"datomic.integrity", (String)"crosscheck-raet-aevt");
        const__115 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__116 = RT.var((String)"datomic.integrity", (String)"crosscheck-raet-eavt");
        const__118 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__119 = RT.var((String)"datomic.integrity", (String)"crosscheck-aevt-avet");
        const__121 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__122 = RT.var((String)"datomic.integrity", (String)"crosscheck-eavt-avet");
        const__124 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__125 = RT.var((String)"datomic.integrity", (String)"crosscheck-aevt-raet");
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__128 = RT.var((String)"datomic.integrity", (String)"crosscheck-eavt-raet");
        const__130 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db1")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)((IObj)Symbol.intern(null, (String)"db2")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__131 = RT.var((String)"datomic.integrity", (String)"get-db");
        const__133 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"o"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.IDb")})))), RT.keyword(null, (String)"column"), 1});
        const__134 = RT.var((String)"datomic.integrity", (String)"crosscheck-indexes");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"column"), 1});
        const__137 = RT.var((String)"datomic.integrity", (String)"path-to-t");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__140 = RT.var((String)"datomic.integrity", (String)"dir-seg-info-seq");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"dir"), (Object)Symbol.intern(null, (String)"olookup")))), RT.keyword(null, (String)"column"), 1});
        const__143 = RT.var((String)"datomic.integrity", (String)"validate-t-order*");
        const__145 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__146 = RT.var((String)"datomic.integrity", (String)"validate-t-order");
        const__148 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"log-fn"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__149 = RT.var((String)"datomic.integrity", (String)"log-dir-entry-seq");
        const__151 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"))}), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__152 = RT.var((String)"datomic.integrity", (String)"log-seg-t-seq");
        const__154 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"))}), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__155 = RT.var((String)"datomic.integrity", (String)"crosscheck-dir-segs");
        const__157 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"))}), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__158 = RT.var((String)"datomic.integrity", (String)"merge-seqs");
        const__160 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"cmp")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.util.Comparator")})), (Object)Symbol.intern(null, (String)"s1"), (Object)Symbol.intern(null, (String)"s2")), Tuple.create((Object)Symbol.intern(null, (String)"cmp"), (Object)Symbol.intern(null, (String)"s1"), (Object)Symbol.intern(null, (String)"s2"), (Object)Symbol.intern(null, (String)"s3")), Tuple.create((Object)Symbol.intern(null, (String)"cmp"), (Object)Symbol.intern(null, (String)"s1"), (Object)Symbol.intern(null, (String)"s2"), (Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"s4")))), RT.keyword(null, (String)"column"), 1});
        const__161 = RT.var((String)"datomic.integrity", (String)"aevt-dquark-seq");
        const__163 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.Db")})), (Object)Symbol.intern(null, (String)"d")))), RT.keyword(null, (String)"column"), 1});
        const__164 = RT.var((String)"datomic.integrity", (String)"eavt-dquark-seq");
        const__166 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.Db")})), (Object)Symbol.intern(null, (String)"d")))), RT.keyword(null, (String)"column"), 1});
        const__167 = RT.var((String)"datomic.integrity", (String)"avet-dquark-seq");
        const__169 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.db.Db")})), (Object)Symbol.intern(null, (String)"d")))), RT.keyword(null, (String)"column"), 1});
        const__170 = RT.var((String)"datomic.integrity", (String)"validate-log-cli");
        const__172 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__173 = RT.var((String)"datomic.integrity", (String)"validate-memory-safe");
        const__175 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__176 = RT.var((String)"datomic.integrity", (String)"excisions");
        const__178 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__179 = RT.var((String)"datomic.integrity", (String)"e-ts");
        const__181 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"e")))), RT.keyword(null, (String)"column"), 1});
        const__182 = RT.var((String)"datomic.integrity", (String)"validate-excision");
        const__184 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"spec")))), RT.keyword(null, (String)"column"), 1});
        const__185 = RT.var((String)"datomic.integrity", (String)"validate-indexed-excisions");
        const__187 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__188 = RT.var((String)"datomic.integrity", (String)"clusterfs-path-reachability");
        const__190 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cfs"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__191 = RT.var((String)"datomic.integrity", (String)"fulltext-path-reachability");
        const__193 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"ft"), (Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__194 = RT.var((String)"datomic.integrity", (String)"validate-fulltext");
        const__196 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"olookup")))), RT.keyword(null, (String)"column"), 1});
        const__197 = RT.var((String)"datomic.integrity", (String)"tx-range-ts");
        const__199 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn")))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init2() {
        const__200 = RT.var((String)"datomic.integrity", (String)"tx-instant-ts");
        const__202 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__203 = RT.var((String)"datomic.integrity", (String)"seq-diffs");
        const__205 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"colla"), (Object)Symbol.intern(null, (String)"collb"), (Object)Symbol.intern(null, (String)"progress")), Tuple.create((Object)Symbol.intern(null, (String)"colla"), (Object)Symbol.intern(null, (String)"collb"), (Object)Symbol.intern(null, (String)"progress"), (Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__206 = RT.var((String)"datomic.integrity", (String)"validate-garbage");
        const__208 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cr"), (Object)Symbol.intern(null, (String)"progress")))), RT.keyword(null, (String)"column"), 1});
        const__209 = RT.var((String)"datomic.integrity", (String)"crosscheck-tx-range-with-tx-instant");
        const__211 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn")))), RT.keyword(null, (String)"column"), 1});
        const__212 = RT.var((String)"datomic.integrity", (String)"validate-nohistory");
        const__214 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__215 = RT.var((String)"datomic.integrity", (String)"stat-counts");
        const__217 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"a")))), RT.keyword(null, (String)"column"), 1});
        const__218 = RT.var((String)"datomic.integrity", (String)"aevt-avet-stats");
        const__220 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__221 = RT.var((String)"datomic.integrity", (String)"aevt-avet-stats-consistent?");
        const__223 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"aevt-total"), (Object)Symbol.intern(null, (String)"avet-total"))})))), RT.keyword(null, (String)"column"), 1});
        const__224 = RT.var((String)"datomic.integrity", (String)"report-aevt-avet-stats");
        const__226 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__227 = RT.var((String)"datomic.integrity", (String)"validate-index-totals");
        const__229 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__230 = RT.var((String)"datomic.integrity", (String)"validate-all");
        const__232 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__233 = RT.var((String)"datomic.integrity", (String)"diagnostics");
        const__234 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__235 = RT.var((String)"datomic.tools", (String)"diagnostics");
        const__236 = RT.var((String)"datomic.integrity", (String)"describe-segment");
        const__238 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"segment-id")))), RT.keyword(null, (String)"column"), 1});
        const__239 = RT.var((String)"datomic.integrity", (String)"fulltext-storage-seq");
        const__241 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__242 = RT.var((String)"datomic.integrity", (String)"log-storage-seq");
        const__244 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__245 = RT.var((String)"datomic.integrity", (String)"index-storage-seq");
        const__247 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__248 = RT.var((String)"datomic.integrity", (String)"pod-storage-seq");
        const__250 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__251 = RT.var((String)"datomic.integrity", (String)"esafe");
        const__253 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"body")))), RT.keyword(null, (String)"column"), 1});
        const__254 = RT.var((String)"datomic.integrity", (String)"index-sort-root-keys");
        const__255 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__272 = (AFn)RT.vector((Object[])new Object[]{RT.keyword(null, (String)"aevt-hist"), RT.keyword(null, (String)"aevt"), RT.keyword(null, (String)"aevt-mid"), RT.keyword(null, (String)"aevt-main"), RT.keyword(null, (String)"eavt-hist"), RT.keyword(null, (String)"eavt"), RT.keyword(null, (String)"eavt-mid"), RT.keyword(null, (String)"eavt-main"), RT.keyword(null, (String)"raet-hist"), RT.keyword(null, (String)"raet"), RT.keyword(null, (String)"raet-mid"), RT.keyword(null, (String)"raet-main"), RT.keyword(null, (String)"avet-hist"), RT.keyword(null, (String)"avet"), RT.keyword(null, (String)"avet-mid"), RT.keyword(null, (String)"avet-main")});
        const__273 = RT.var((String)"datomic.integrity", (String)"-main*");
        const__275 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"validate"))})))), RT.keyword(null, (String)"column"), 1});
        const__276 = RT.var((String)"datomic.integrity", (String)"-main");
        const__278 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        integrity__init.__init0();
        integrity__init.__init1();
        integrity__init.__init2();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.integrity__init").getClassLoader());
        try {
            integrity__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

