/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.io$alias_buf_bytes;
import datomic.io$allocate_buffer;
import datomic.io$append_buffer;
import datomic.io$base128__GT_bbuf;
import datomic.io$bbuf__GT_base128;
import datomic.io$bbuf__GT_clj;
import datomic.io$bbuf__GT_string;
import datomic.io$byte_buffer_seq;
import datomic.io$byte_source__GT_buffer;
import datomic.io$bytestream__GT_buf;
import datomic.io$chunk;
import datomic.io$clear_buffer;
import datomic.io$clj__GT_bbuf;
import datomic.io$context_resource;
import datomic.io$crc32;
import datomic.io$decode_base128;
import datomic.io$describe_bbuf;
import datomic.io$directify_buffer;
import datomic.io$encode_base128;
import datomic.io$expand_buffer;
import datomic.io$expand_byte_array;
import datomic.io$fill_array;
import datomic.io$fill_buffer;
import datomic.io$fn__9271;
import datomic.io$fn__9275;
import datomic.io$fn__9278;
import datomic.io$fn__9289;
import datomic.io$fn__9293;
import datomic.io$fn__9296;
import datomic.io$fn__9307;
import datomic.io$fn__9309;
import datomic.io$fn__9311;
import datomic.io$fn__9313;
import datomic.io$fn__9322;
import datomic.io$gunzip_buffer;
import datomic.io$gzip_buffer;
import datomic.io$limit;
import datomic.io$loading__6434__auto____9269;
import datomic.io$position;
import datomic.io$read_all;
import datomic.io$read_into_buffer;
import datomic.io$read_n_bytes;
import datomic.io$read_n_direct_bytes;
import datomic.io$remaining;
import datomic.io$seek;
import datomic.io$string__GT_bbuf;
import datomic.io$sub_buffer;
import datomic.io$unchunk;
import datomic.io$unflipped;
import datomic.io$valid_buf_limit_QMARK_;
import datomic.io$with_serialization_print_settings;
import datomic.io$write_buffer;
import datomic.io$write_bytes;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class io__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Object const__4;
    public static final Var const__5;
    public static final Var const__6;
    public static final Var const__7;
    public static final Keyword const__8;
    public static final Var const__9;
    public static final ISeq const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final AFn const__16;
    public static final Keyword const__17;
    public static final AFn const__18;
    public static final Keyword const__19;
    public static final Keyword const__20;
    public static final Keyword const__21;
    public static final AFn const__22;
    public static final Keyword const__23;
    public static final Var const__24;
    public static final Var const__25;
    public static final Var const__26;
    public static final AFn const__27;
    public static final AFn const__28;
    public static final Keyword const__29;
    public static final Var const__30;
    public static final AFn const__31;
    public static final Var const__32;
    public static final Object const__33;
    public static final Object const__34;
    public static final Var const__35;
    public static final ISeq const__36;
    public static final AFn const__38;
    public static final AFn const__39;
    public static final Keyword const__40;
    public static final AFn const__41;
    public static final AFn const__42;
    public static final AFn const__43;
    public static final AFn const__44;
    public static final Object const__45;
    public static final Object const__46;
    public static final Object const__47;
    public static final Var const__48;
    public static final AFn const__53;
    public static final Var const__54;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__59;
    public static final Var const__60;
    public static final AFn const__62;
    public static final Var const__63;
    public static final AFn const__65;
    public static final Var const__66;
    public static final AFn const__68;
    public static final Var const__69;
    public static final Var const__70;
    public static final Keyword const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final AFn const__78;
    public static final Var const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__84;
    public static final Var const__85;
    public static final AFn const__87;
    public static final Var const__88;
    public static final AFn const__90;
    public static final Var const__91;
    public static final AFn const__93;
    public static final Var const__94;
    public static final AFn const__96;
    public static final Var const__97;
    public static final AFn const__99;
    public static final Var const__100;
    public static final AFn const__102;
    public static final Var const__103;
    public static final AFn const__105;
    public static final Var const__106;
    public static final AFn const__108;
    public static final Var const__109;
    public static final AFn const__111;
    public static final Var const__112;
    public static final AFn const__114;
    public static final Var const__115;
    public static final AFn const__117;
    public static final Var const__118;
    public static final AFn const__120;
    public static final Var const__121;
    public static final AFn const__123;
    public static final Var const__124;
    public static final AFn const__126;
    public static final Var const__127;
    public static final AFn const__129;
    public static final Var const__130;
    public static final AFn const__132;
    public static final Var const__133;
    public static final AFn const__135;
    public static final Var const__136;
    public static final AFn const__138;
    public static final Var const__139;
    public static final AFn const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;
    public static final Var const__163;
    public static final AFn const__165;
    public static final Var const__166;
    public static final AFn const__168;
    public static final Var const__169;
    public static final AFn const__171;
    public static final Var const__172;
    public static final AFn const__174;
    public static final Var const__175;
    public static final AFn const__177;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new io$loading__6434__auto____9269()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new io$fn__9271())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = ((IFn)new io$fn__9275()).invoke();
        Object object5 = const__4;
        Object object6 = ((IFn)const__5.getRawRoot()).invoke((Object)const__6, const__7.getRawRoot(), (Object)const__8, null);
        Object object7 = ((IFn)const__9).invoke((Object)const__6, (Object)const__10);
        Object object8 = ((IFn)const__11.getRawRoot()).invoke((Object)const__6, const__12.getRawRoot(), ((IFn)const__7.getRawRoot()).invoke((Object)const__16, (Object)const__17, (Object)const__18, (Object)const__19, (Object)const__6, (Object)const__20, (Object)const__22, (Object)const__23, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__24.getRawRoot()).invoke(const__25.get(), ((IFn)const__26.getRawRoot()).invoke((Object)const__27, ((IFn)const__12.getRawRoot()).invoke((Object)const__28, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__29, const__6})))), new io$fn__9278()})));
        Object object9 = ((IFn)const__30.getRawRoot()).invoke(const__6.getRawRoot());
        AFn aFn = const__31;
        Object object10 = ((IFn)const__32.getRawRoot()).invoke(const__33, const__6.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__21, new io$fn__9289()}));
        Object object11 = ((IFn)new io$fn__9293()).invoke();
        Object object12 = const__34;
        Object object13 = ((IFn)const__5.getRawRoot()).invoke((Object)const__35, const__7.getRawRoot(), (Object)const__8, null);
        Object object14 = ((IFn)const__9).invoke((Object)const__35, (Object)const__36);
        Object object15 = ((IFn)const__11.getRawRoot()).invoke((Object)const__35, const__12.getRawRoot(), ((IFn)const__7.getRawRoot()).invoke((Object)const__38, (Object)const__17, (Object)const__39, (Object)const__19, (Object)const__35, (Object)const__20, (Object)const__41, (Object)const__23, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__24.getRawRoot()).invoke(const__25.get(), ((IFn)const__26.getRawRoot()).invoke((Object)const__42, ((IFn)const__12.getRawRoot()).invoke((Object)const__43, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__29, const__35})))), new io$fn__9296()})));
        Object object16 = ((IFn)const__30.getRawRoot()).invoke(const__35.getRawRoot());
        AFn aFn2 = const__44;
        Object object17 = ((IFn)const__32.getRawRoot()).invoke(null, const__35.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, new io$fn__9307()}));
        Object object18 = ((IFn)const__32.getRawRoot()).invoke(const__45, const__35.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, new io$fn__9309()}));
        Object object19 = ((IFn)const__32.getRawRoot()).invoke(const__46, const__35.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, new io$fn__9311()}));
        Object object20 = ((IFn)const__32.getRawRoot()).invoke(const__47, const__35.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__40, new io$fn__9313()}));
        Var var = const__48;
        var.setMeta((IPersistentMap)const__53);
        Var var2 = var;
        var.bindRoot((Object)new io$byte_source__GT_buffer());
        Var var3 = const__54;
        var3.setMeta((IPersistentMap)const__56);
        Var var4 = var3;
        var3.bindRoot((Object)new io$alias_buf_bytes());
        Var var5 = const__57;
        var5.setMeta((IPersistentMap)const__59);
        Var var6 = var5;
        var5.bindRoot((Object)new io$string__GT_bbuf());
        Var var7 = const__60;
        var7.setMeta((IPersistentMap)const__62);
        Var var8 = var7;
        var7.bindRoot((Object)new io$bbuf__GT_string());
        Var var9 = const__63;
        var9.setMeta((IPersistentMap)const__65);
        Var var10 = var9;
        var9.bindRoot((Object)new io$expand_byte_array());
        Var var11 = const__66;
        var11.setMeta((IPersistentMap)const__68);
        Var var12 = var11;
        var11.bindRoot((Object)new io$fill_array());
        Object object21 = ((IFn)const__32.getRawRoot()).invoke(const__33, const__69.getRawRoot(), ((IFn)const__7.getRawRoot()).invoke(const__70.getRawRoot(), (Object)const__71, (Object)new io$fn__9322()));
        Var var13 = const__72;
        var13.setMeta((IPersistentMap)const__74);
        Var var14 = var13;
        var13.bindRoot((Object)new io$fill_buffer());
        Var var15 = const__75;
        var15.setMeta((IPersistentMap)const__78);
        Var var16 = var15;
        var15.bindRoot((Object)new io$unflipped());
        Var var17 = const__79;
        var17.setMeta((IPersistentMap)const__81);
        Var var18 = var17;
        var17.bindRoot((Object)new io$clear_buffer());
        Var var19 = const__82;
        var19.setMeta((IPersistentMap)const__84);
        Var var20 = var19;
        var19.bindRoot((Object)new io$allocate_buffer());
        Var var21 = const__85;
        var21.setMeta((IPersistentMap)const__87);
        Var var22 = var21;
        var21.bindRoot((Object)new io$expand_buffer());
        Var var23 = const__88;
        var23.setMeta((IPersistentMap)const__90);
        Var var24 = var23;
        var23.bindRoot((Object)new io$append_buffer());
        Var var25 = const__91;
        var25.setMeta((IPersistentMap)const__93);
        Var var26 = var25;
        var25.bindRoot((Object)new io$directify_buffer());
        Var var27 = const__94;
        var27.setMeta((IPersistentMap)const__96);
        Var var28 = var27;
        var27.bindRoot((Object)new io$sub_buffer());
        Var var29 = const__97;
        var29.setMeta((IPersistentMap)const__99);
        Var var30 = var29;
        var29.bindRoot((Object)new io$bytestream__GT_buf());
        Var var31 = const__100;
        var31.setMeta((IPersistentMap)const__102);
        Var var32 = var31;
        var31.bindRoot((Object)new io$limit());
        Var var33 = const__103;
        var33.setMeta((IPersistentMap)const__105);
        Var var34 = var33;
        var33.bindRoot((Object)new io$remaining());
        Var var35 = const__106;
        var35.setMeta((IPersistentMap)const__108);
        Var var36 = var35;
        var35.bindRoot((Object)new io$position());
        Var var37 = const__109;
        var37.setMeta((IPersistentMap)const__111);
        Var var38 = var37;
        var37.bindRoot((Object)new io$seek());
        Var var39 = const__112;
        var39.setMeta((IPersistentMap)const__114);
        Var var40 = var39;
        var39.bindRoot((Object)new io$chunk());
        Var var41 = const__115;
        var41.setMeta((IPersistentMap)const__117);
        Var var42 = var41;
        var41.bindRoot((Object)new io$unchunk());
        Var var43 = const__118;
        var43.setMeta((IPersistentMap)const__120);
        Var var44 = var43;
        var43.bindRoot((Object)new io$gzip_buffer());
        Var var45 = const__121;
        var45.setMeta((IPersistentMap)const__123);
        Var var46 = var45;
        var45.bindRoot((Object)new io$gunzip_buffer());
        Var var47 = const__124;
        var47.setMeta((IPersistentMap)const__126);
        Var var48 = var47;
        var47.bindRoot((Object)new io$byte_buffer_seq());
        Var var49 = const__127;
        var49.setMeta((IPersistentMap)const__129);
        Var var50 = var49;
        var49.bindRoot((Object)new io$with_serialization_print_settings());
        const__127.setMacro();
        Object v74 = null;
        Var var51 = const__127;
        Var var52 = const__130;
        var52.setMeta((IPersistentMap)const__132);
        Var var53 = var52;
        var52.bindRoot((Object)new io$clj__GT_bbuf());
        Var var54 = const__133;
        var54.setMeta((IPersistentMap)const__135);
        Var var55 = var54;
        var54.bindRoot((Object)new io$bbuf__GT_clj());
        Var var56 = const__136;
        var56.setMeta((IPersistentMap)const__138);
        Var var57 = var56;
        var56.bindRoot((Object)new io$valid_buf_limit_QMARK_());
        Var var58 = const__139;
        var58.setMeta((IPersistentMap)const__141);
        Var var59 = var58;
        var58.bindRoot((Object)new io$encode_base128());
        Var var60 = const__142;
        var60.setMeta((IPersistentMap)const__144);
        Var var61 = var60;
        var60.bindRoot((Object)new io$decode_base128());
        Var var62 = const__145;
        var62.setMeta((IPersistentMap)const__147);
        Var var63 = var62;
        var62.bindRoot((Object)new io$bbuf__GT_base128());
        Var var64 = const__148;
        var64.setMeta((IPersistentMap)const__150);
        Var var65 = var64;
        var64.bindRoot((Object)new io$base128__GT_bbuf());
        Var var66 = const__151;
        var66.setMeta((IPersistentMap)const__153);
        Var var67 = var66;
        var66.bindRoot((Object)new io$read_all());
        Var var68 = const__154;
        var68.setMeta((IPersistentMap)const__156);
        Var var69 = var68;
        var68.bindRoot((Object)new io$context_resource());
        Var var70 = const__157;
        var70.setMeta((IPersistentMap)const__159);
        Var var71 = var70;
        var70.bindRoot((Object)new io$read_into_buffer());
        Var var72 = const__160;
        var72.setMeta((IPersistentMap)const__162);
        Var var73 = var72;
        var72.bindRoot((Object)new io$read_n_bytes());
        Var var74 = const__163;
        var74.setMeta((IPersistentMap)const__165);
        Var var75 = var74;
        var74.bindRoot((Object)new io$read_n_direct_bytes());
        Var var76 = const__166;
        var76.setMeta((IPersistentMap)const__168);
        Var var77 = var76;
        var76.bindRoot((Object)new io$write_buffer());
        Var var78 = const__169;
        var78.setMeta((IPersistentMap)const__171);
        Var var79 = var78;
        var78.bindRoot((Object)new io$write_bytes());
        Var var80 = const__172;
        var80.setMeta((IPersistentMap)const__174);
        Var var81 = var80;
        var80.bindRoot((Object)new io$crc32());
        Var var82 = const__175;
        var82.setMeta((IPersistentMap)const__177);
        Var var83 = var82;
        var82.bindRoot((Object)new io$describe_bbuf());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.io");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.classForName((String)"datomic.io.ByteSource");
        const__5 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__6 = RT.var((String)"datomic.io", (String)"ByteSource");
        const__7 = RT.var((String)"clojure.core", (String)"assoc");
        const__8 = RT.keyword(null, (String)"doc");
        const__9 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__10 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"slurp-bytes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
        const__11 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__12 = RT.var((String)"clojure.core", (String)"merge");
        const__16 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.io.ByteSource"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.io.ByteSource")});
        const__17 = RT.keyword(null, (String)"sigs");
        const__18 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"slurp-bytes"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"slurp-bytes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns copy unless owner always treats arrays as values. Does not consume owner."})});
        const__19 = RT.keyword(null, (String)"var");
        const__20 = RT.keyword(null, (String)"method-map");
        const__21 = RT.keyword(null, (String)"slurp-bytes");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"slurp-bytes"), RT.keyword(null, (String)"slurp-bytes")});
        const__23 = RT.keyword(null, (String)"method-builders");
        const__24 = RT.var((String)"clojure.core", (String)"intern");
        const__25 = RT.var((String)"clojure.core", (String)"*ns*");
        const__26 = RT.var((String)"clojure.core", (String)"with-meta");
        const__27 = (AFn)((IObj)Symbol.intern(null, (String)"slurp-bytes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"slurp-bytes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns copy unless owner always treats arrays as values. Does not consume owner."});
        const__29 = RT.keyword(null, (String)"protocol");
        const__30 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__31 = (AFn)Symbol.intern(null, (String)"ByteSource");
        const__32 = RT.var((String)"clojure.core", (String)"extend");
        const__33 = RT.classForName((String)"java.nio.ByteBuffer");
        const__34 = RT.classForName((String)"datomic.io.Coercions");
        const__35 = RT.var((String)"datomic.io", (String)"Coercions");
        const__36 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"as-uri")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}))));
        const__38 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.io.Coercions"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.io.Coercions")});
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as-uri"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"as-uri")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Coerce argument to a URI"})});
        const__40 = RT.keyword(null, (String)"as-uri");
        const__41 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"as-uri"), RT.keyword(null, (String)"as-uri")});
        const__42 = (AFn)((IObj)Symbol.intern(null, (String)"as-uri")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}));
        const__43 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"as-uri")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Coerce argument to a URI"});
        const__44 = (AFn)Symbol.intern(null, (String)"Coercions");
        const__45 = RT.classForName((String)"java.lang.String");
        const__46 = RT.classForName((String)"java.net.URI");
        const__47 = RT.classForName((String)"java.net.URL");
        const__48 = RT.var((String)"datomic.io", (String)"byte-source->buffer");
        const__53 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"b")))), RT.keyword(null, (String)"column"), 1});
        const__54 = RT.var((String)"datomic.io", (String)"alias-buf-bytes");
        const__56 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buff")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__57 = RT.var((String)"datomic.io", (String)"string->bbuf");
        const__59 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"s")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__60 = RT.var((String)"datomic.io", (String)"bbuf->string");
        const__62 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__63 = RT.var((String)"datomic.io", (String)"expand-byte-array");
        const__65 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"buf"), (Object)Symbol.intern(null, (String)"valid-bytes"), (Object)Symbol.intern(null, (String)"new-length")))), RT.keyword(null, (String)"column"), 1});
        const__66 = RT.var((String)"datomic.io", (String)"fill-array");
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"is")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"InputStream")})), (Object)((IObj)Symbol.intern(null, (String)"ba")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"bytes")}))))), RT.keyword(null, (String)"column"), 1});
        const__69 = RT.var((String)"clojure.java.io", (String)"IOFactory");
        const__70 = RT.var((String)"clojure.java.io", (String)"default-streams-impl");
        const__71 = RT.keyword(null, (String)"make-input-stream");
        const__72 = RT.var((String)"datomic.io", (String)"fill-buffer");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"is")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"InputStream")})), (Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.io", (String)"unflipped");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"b")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.var((String)"datomic.io", (String)"clear-buffer");
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__82 = RT.var((String)"datomic.io", (String)"allocate-buffer");
        const__84 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"size")))), RT.keyword(null, (String)"column"), 1});
        const__85 = RT.var((String)"datomic.io", (String)"expand-buffer");
        const__87 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)((IObj)Symbol.intern(null, (String)"extra")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")}))))), RT.keyword(null, (String)"column"), 1});
        const__88 = RT.var((String)"datomic.io", (String)"append-buffer");
        const__90 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"dest")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)((IObj)Symbol.intern(null, (String)"src")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__91 = RT.var((String)"datomic.io", (String)"directify-buffer");
        const__93 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__94 = RT.var((String)"datomic.io", (String)"sub-buffer");
        const__96 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"offset"), (Object)Symbol.intern(null, (String)"length")))), RT.keyword(null, (String)"column"), 1});
        const__97 = RT.var((String)"datomic.io", (String)"bytestream->buf");
        const__99 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"stream")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"BytesOutputStream")}))))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init1() {
        const__100 = RT.var((String)"datomic.io", (String)"limit");
        const__102 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)((IObj)Symbol.intern(null, (String)"limit")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.nio.ByteBuffer")})))), RT.keyword(null, (String)"column"), 1});
        const__103 = RT.var((String)"datomic.io", (String)"remaining");
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__106 = RT.var((String)"datomic.io", (String)"position");
        const__108 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))), RT.keyword(null, (String)"column"), 1});
        const__109 = RT.var((String)"datomic.io", (String)"seek");
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)((IObj)Symbol.intern(null, (String)"n")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")})))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.nio.ByteBuffer")})))), RT.keyword(null, (String)"column"), 1});
        const__112 = RT.var((String)"datomic.io", (String)"chunk");
        const__114 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"chunk-size"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"integer?"), Symbol.intern(null, (String)"chunk-size")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 10})), (Object)((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"pos?"), Symbol.intern(null, (String)"chunk-size")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 33})))})))), RT.keyword(null, (String)"column"), 1});
        const__115 = RT.var((String)"datomic.io", (String)"unchunk");
        const__117 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"bbufs"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"java.nio.ByteBuffer")})))), RT.keyword(null, (String)"column"), 1});
        const__118 = RT.var((String)"datomic.io", (String)"gzip-buffer");
        const__120 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buff")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__121 = RT.var((String)"datomic.io", (String)"gunzip-buffer");
        const__123 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"buff")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__124 = RT.var((String)"datomic.io", (String)"byte-buffer-seq");
        const__126 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__127 = RT.var((String)"datomic.io", (String)"with-serialization-print-settings");
        const__129 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"forms")))), RT.keyword(null, (String)"column"), 1});
        const__130 = RT.var((String)"datomic.io", (String)"clj->bbuf");
        const__132 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__133 = RT.var((String)"datomic.io", (String)"bbuf->clj");
        const__135 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bbuf")))), RT.keyword(null, (String)"column"), 1});
        const__136 = RT.var((String)"datomic.io", (String)"valid-buf-limit?");
        const__138 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bbuf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Buffer")})), (Object)Symbol.intern(null, (String)"limit")))), RT.keyword(null, (String)"column"), 1});
        const__139 = RT.var((String)"datomic.io", (String)"encode-base128");
        const__141 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"raw"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"bytes")})))), RT.keyword(null, (String)"column"), 1});
        const__142 = RT.var((String)"datomic.io", (String)"decode-base128");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coded")))), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.io", (String)"bbuf->base128");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bbuf")))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.io", (String)"base128->bbuf");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"s")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"String")}))))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.io", (String)"read-all");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"src")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Reader")}))))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.io", (String)"context-resource");
        const__156 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"r")))), RT.keyword(null, (String)"column"), 1});
        const__157 = RT.var((String)"datomic.io", (String)"read-into-buffer");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)Symbol.intern(null, (String)"n"), (Object)((IObj)Symbol.intern(null, (String)"rc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ReadableByteChannel")}))))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.io", (String)"read-n-bytes");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n"), (Object)((IObj)Symbol.intern(null, (String)"rc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ReadableByteChannel")}))))), RT.keyword(null, (String)"column"), 1});
        const__163 = RT.var((String)"datomic.io", (String)"read-n-direct-bytes");
        const__165 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), RT.classForName((String)"java.nio.ByteBuffer"), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n"), (Object)((IObj)Symbol.intern(null, (String)"rc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ReadableByteChannel")}))))), RT.keyword(null, (String)"column"), 1});
        const__166 = RT.var((String)"datomic.io", (String)"write-buffer");
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bb")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")})), (Object)((IObj)Symbol.intern(null, (String)"wc")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"WritableByteChannel")}))))), RT.keyword(null, (String)"column"), 1});
        const__169 = RT.var((String)"datomic.io", (String)"write-bytes");
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bytes"), (Object)Symbol.intern(null, (String)"wc")))), RT.keyword(null, (String)"column"), 1});
        const__172 = RT.var((String)"datomic.io", (String)"crc32");
        const__174 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"bbuf")))), RT.keyword(null, (String)"column"), 1});
        const__175 = RT.var((String)"datomic.io", (String)"describe-bbuf");
        const__177 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bbuf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        io__init.__init0();
        io__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.io__init").getClassLoader());
        try {
            io__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

