/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.MultiFn
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.MultiFn;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.query$apply_pf;
import datomic.query$cache;
import datomic.query$compile_construct;
import datomic.query$compile_construct_1;
import datomic.query$compile_construct_n;
import datomic.query$construct_fn;
import datomic.query$eav;
import datomic.query$emap;
import datomic.query$flatten_listy;
import datomic.query$fn__19130;
import datomic.query$fn__19171;
import datomic.query$fn__19174;
import datomic.query$fn__19214;
import datomic.query$fn__19218;
import datomic.query$fn__19221;
import datomic.query$fn__19232;
import datomic.query$fn__19234;
import datomic.query$fn__19236;
import datomic.query$fn__19244;
import datomic.query$fn__19246;
import datomic.query$gensym_padding;
import datomic.query$get_lazy_entity;
import datomic.query$group_fv;
import datomic.query$group_rel;
import datomic.query$has_self_unifications_QMARK_;
import datomic.query$listq__GT_mapq;
import datomic.query$load_query;
import datomic.query$loading__6434__auto____17823;
import datomic.query$mapify_query;
import datomic.query$move_sources_to_meta;
import datomic.query$normalize_pull;
import datomic.query$parse_query;
import datomic.query$pattern_QMARK_;
import datomic.query$process_aggregates;
import datomic.query$process_find_bindings;
import datomic.query$process_in_bindings;
import datomic.query$process_pulls;
import datomic.query$process_ranges;
import datomic.query$process_self_unifications;
import datomic.query$pull_fv;
import datomic.query$q;
import datomic.query$q_STAR_;
import datomic.query$qseq;
import datomic.query$query;
import datomic.query$query_STAR_;
import datomic.query$rae;
import datomic.query$ref_val;
import datomic.query$rename_self_unifications;
import datomic.query$resolve_qualified_fn;
import datomic.query$resolve_qualified_fns;
import datomic.query$sort_collection_by_indexed;
import datomic.query$sort_for_pull;
import datomic.query$touch;
import datomic.query$validate_query;
import datomic.query$variables_in_clause;
import datomic.query$xf_tuple;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class query__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__8;
    public static final Var const__9;
    public static final AFn const__12;
    public static final Var const__13;
    public static final AFn const__16;
    public static final Var const__17;
    public static final AFn const__19;
    public static final Var const__20;
    public static final AFn const__22;
    public static final Var const__23;
    public static final AFn const__25;
    public static final AFn const__27;
    public static final Var const__28;
    public static final Object const__29;
    public static final Object const__30;
    public static final Var const__31;
    public static final Var const__32;
    public static final Var const__33;
    public static final Keyword const__34;
    public static final Var const__35;
    public static final ISeq const__36;
    public static final Var const__37;
    public static final Var const__38;
    public static final AFn const__42;
    public static final Keyword const__43;
    public static final AFn const__44;
    public static final Keyword const__45;
    public static final Keyword const__46;
    public static final Keyword const__47;
    public static final AFn const__48;
    public static final Keyword const__49;
    public static final Var const__50;
    public static final Var const__51;
    public static final Var const__52;
    public static final AFn const__53;
    public static final AFn const__54;
    public static final Keyword const__55;
    public static final Var const__56;
    public static final AFn const__57;
    public static final Var const__58;
    public static final Object const__59;
    public static final Object const__60;
    public static final Object const__61;
    public static final Object const__62;
    public static final Var const__63;
    public static final AFn const__65;
    public static final Var const__66;
    public static final AFn const__68;
    public static final Var const__69;
    public static final AFn const__71;
    public static final Var const__72;
    public static final AFn const__74;
    public static final Var const__75;
    public static final AFn const__77;
    public static final Var const__78;
    public static final AFn const__80;
    public static final Var const__81;
    public static final AFn const__83;
    public static final Var const__84;
    public static final AFn const__86;
    public static final Var const__87;
    public static final AFn const__89;
    public static final Var const__90;
    public static final AFn const__92;
    public static final Var const__93;
    public static final AFn const__95;
    public static final Var const__96;
    public static final AFn const__98;
    public static final Var const__99;
    public static final AFn const__101;
    public static final Var const__102;
    public static final AFn const__104;
    public static final Var const__105;
    public static final AFn const__107;
    public static final Var const__108;
    public static final AFn const__110;
    public static final Var const__111;
    public static final AFn const__113;
    public static final Var const__114;
    public static final AFn const__116;
    public static final Var const__117;
    public static final AFn const__119;
    public static final Var const__120;
    public static final AFn const__122;
    public static final Var const__123;
    public static final AFn const__125;
    public static final Var const__126;
    public static final AFn const__128;
    public static final Var const__129;
    public static final AFn const__131;
    public static final Var const__132;
    public static final AFn const__134;
    public static final Var const__135;
    public static final AFn const__137;
    public static final Var const__138;
    public static final AFn const__139;
    public static final Var const__140;
    public static final Object const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;
    public static final Var const__163;
    public static final AFn const__165;
    public static final Var const__166;
    public static final AFn const__168;
    public static final Var const__169;
    public static final AFn const__171;
    public static final Var const__172;
    public static final AFn const__174;
    public static final Var const__175;
    public static final AFn const__177;
    public static final Var const__178;
    public static final AFn const__180;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new query$loading__6434__auto____17823()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new query$fn__19130())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        Var var2 = var;
        var.setMeta((IPersistentMap)const__8);
        Var var3 = const__9;
        var3.setMeta((IPersistentMap)const__12);
        Var var4 = var3;
        var3.bindRoot((Object)new query$rae());
        Var var5 = const__13;
        var5.setMeta((IPersistentMap)const__16);
        Var var6 = var5;
        var5.bindRoot((Object)new query$ref_val());
        Var var7 = const__17;
        var7.setMeta((IPersistentMap)const__19);
        Var var8 = var7;
        var7.bindRoot((Object)new query$eav());
        Var var9 = const__20;
        var9.setMeta((IPersistentMap)const__22);
        Var var10 = var9;
        var9.bindRoot((Object)new query$get_lazy_entity());
        Object object4 = ((IFn)new query$fn__19171()).invoke();
        Var var11 = const__23;
        var11.setMeta((IPersistentMap)const__25);
        Var var12 = var11;
        var11.bindRoot((Object)new query$touch());
        Object object5 = ((IFn)new query$fn__19174()).invoke();
        Var var13 = const__4;
        var13.setMeta((IPersistentMap)const__27);
        Var var14 = var13;
        var13.bindRoot((Object)new query$emap());
        MultiFn multiFn = ((MultiFn)const__28.getRawRoot()).addMethod(const__29, (IFn)new query$fn__19214());
        Object object6 = ((IFn)new query$fn__19218()).invoke();
        Object object7 = const__30;
        Object object8 = ((IFn)const__31.getRawRoot()).invoke((Object)const__32, const__33.getRawRoot(), (Object)const__34, null);
        Object object9 = ((IFn)const__35).invoke((Object)const__32, (Object)const__36);
        Object object10 = ((IFn)const__37.getRawRoot()).invoke((Object)const__32, const__38.getRawRoot(), ((IFn)const__33.getRawRoot()).invoke((Object)const__42, (Object)const__43, (Object)const__44, (Object)const__45, (Object)const__32, (Object)const__46, (Object)const__48, (Object)const__49, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__50.getRawRoot()).invoke(const__51.get(), ((IFn)const__52.getRawRoot()).invoke((Object)const__53, ((IFn)const__38.getRawRoot()).invoke((Object)const__54, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__55, const__32})))), new query$fn__19221()})));
        Object object11 = ((IFn)const__56.getRawRoot()).invoke(const__32.getRawRoot());
        AFn aFn = const__57;
        Object object12 = ((IFn)const__58.getRawRoot()).invoke(null, const__32.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__47, new query$fn__19232()}));
        Object object13 = ((IFn)const__58.getRawRoot()).invoke(const__59, const__32.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__47, new query$fn__19234()}));
        Object object14 = ((IFn)const__58.getRawRoot()).invoke(const__60, const__32.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__47, new query$fn__19236()}));
        Object object15 = ((IFn)const__58.getRawRoot()).invoke(const__61, const__32.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__47, new query$fn__19244()}));
        Object object16 = ((IFn)const__58.getRawRoot()).invoke(const__62, const__32.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__47, new query$fn__19246()}));
        Var var15 = const__63;
        var15.setMeta((IPersistentMap)const__65);
        Var var16 = var15;
        var15.bindRoot((Object)new query$listq__GT_mapq());
        Var var17 = const__66;
        var17.setMeta((IPersistentMap)const__68);
        Var var18 = var17;
        var17.bindRoot((Object)new query$move_sources_to_meta());
        Var var19 = const__69;
        var19.setMeta((IPersistentMap)const__71);
        Var var20 = var19;
        var19.bindRoot((Object)new query$flatten_listy());
        Var var21 = const__72;
        var21.setMeta((IPersistentMap)const__74);
        Var var22 = var21;
        var21.bindRoot((Object)new query$variables_in_clause());
        Var var23 = const__75;
        var23.setMeta((IPersistentMap)const__77);
        Var var24 = var23;
        var23.bindRoot((Object)new query$validate_query());
        Var var25 = const__78;
        var25.setMeta((IPersistentMap)const__80);
        Var var26 = var25;
        var25.bindRoot((Object)new query$process_in_bindings());
        Var var27 = const__81;
        var27.setMeta((IPersistentMap)const__83);
        Var var28 = var27;
        var27.bindRoot((Object)new query$process_ranges());
        Var var29 = const__84;
        var29.setMeta((IPersistentMap)const__86);
        Var var30 = var29;
        var29.bindRoot((Object)new query$process_aggregates());
        Var var31 = const__87;
        var31.setMeta((IPersistentMap)const__89);
        Var var32 = var31;
        var31.bindRoot((Object)new query$process_find_bindings());
        Var var33 = const__90;
        var33.setMeta((IPersistentMap)const__92);
        Var var34 = var33;
        var33.bindRoot((Object)new query$pattern_QMARK_());
        Var var35 = const__93;
        var35.setMeta((IPersistentMap)const__95);
        Var var36 = var35;
        var35.bindRoot((Object)new query$normalize_pull());
        Var var37 = const__96;
        var37.setMeta((IPersistentMap)const__98);
        Var var38 = var37;
        var37.bindRoot((Object)new query$process_pulls());
        Var var39 = const__99;
        var39.setMeta((IPersistentMap)const__101);
        Var var40 = var39;
        var39.bindRoot((Object)new query$mapify_query());
        Var var41 = const__102;
        var41.setMeta((IPersistentMap)const__104);
        Var var42 = var41;
        var41.bindRoot((Object)new query$rename_self_unifications());
        Var var43 = const__105;
        var43.setMeta((IPersistentMap)const__107);
        Var var44 = var43;
        var43.bindRoot((Object)new query$gensym_padding());
        Var var45 = const__108;
        var45.setMeta((IPersistentMap)const__110);
        Var var46 = var45;
        var45.bindRoot((Object)new query$has_self_unifications_QMARK_());
        Var var47 = const__111;
        var47.setMeta((IPersistentMap)const__113);
        Var var48 = var47;
        var47.bindRoot((Object)new query$process_self_unifications());
        Var var49 = const__114;
        var49.setMeta((IPersistentMap)const__116);
        Var var50 = var49;
        var49.bindRoot((Object)new query$compile_construct_1());
        Var var51 = const__117;
        var51.setMeta((IPersistentMap)const__119);
        Var var52 = var51;
        var51.bindRoot((Object)new query$compile_construct_n());
        Var var53 = const__120;
        var53.setMeta((IPersistentMap)const__122);
        Var var54 = var53;
        var53.bindRoot((Object)new query$compile_construct());
        Var var55 = const__123;
        var55.setMeta((IPersistentMap)const__125);
        Var var56 = var55;
        var55.bindRoot((Object)new query$resolve_qualified_fn());
        Var var57 = const__126;
        var57.setMeta((IPersistentMap)const__128);
        Var var58 = var57;
        var57.bindRoot((Object)new query$resolve_qualified_fns());
        Var var59 = const__129;
        var59.setMeta((IPersistentMap)const__131);
        Var var60 = var59;
        var59.bindRoot((Object)new query$parse_query());
        Var var61 = const__132;
        var61.setMeta((IPersistentMap)const__134);
        Var var62 = var61;
        var61.bindRoot((Object)new query$load_query());
        Var var63 = const__135;
        var63.setMeta((IPersistentMap)const__137);
        Var var64 = var63;
        var63.bindRoot((Object)new query$group_rel());
        Var var65 = const__138;
        var65.setMeta((IPersistentMap)const__139);
        Var var66 = var65;
        var65.bindRoot(((IFn)const__140.getRawRoot()).invoke(const__132.getRawRoot(), const__141));
        Var var67 = const__142;
        var67.setMeta((IPersistentMap)const__144);
        Var var68 = var67;
        var67.bindRoot((Object)new query$group_fv());
        Var var69 = const__145;
        var69.setMeta((IPersistentMap)const__147);
        Var var70 = var69;
        var69.bindRoot((Object)new query$xf_tuple());
        Var var71 = const__148;
        var71.setMeta((IPersistentMap)const__150);
        Var var72 = var71;
        var71.bindRoot((Object)new query$pull_fv());
        Var var73 = const__151;
        var73.setMeta((IPersistentMap)const__153);
        Var var74 = var73;
        var73.bindRoot((Object)new query$sort_collection_by_indexed());
        Var var75 = const__154;
        var75.setMeta((IPersistentMap)const__156);
        Var var76 = var75;
        var75.bindRoot((Object)new query$sort_for_pull());
        Var var77 = const__157;
        var77.setMeta((IPersistentMap)const__159);
        Var var78 = var77;
        var77.bindRoot((Object)new query$q_STAR_());
        Var var79 = const__160;
        var79.setMeta((IPersistentMap)const__162);
        Var var80 = var79;
        var79.bindRoot((Object)new query$query_STAR_());
        Var var81 = const__163;
        var81.setMeta((IPersistentMap)const__165);
        Var var82 = var81;
        var81.bindRoot((Object)new query$apply_pf());
        Var var83 = const__166;
        var83.setMeta((IPersistentMap)const__168);
        Var var84 = var83;
        var83.bindRoot((Object)new query$q());
        Var var85 = const__169;
        var85.setMeta((IPersistentMap)const__171);
        Var var86 = var85;
        var85.bindRoot((Object)new query$query());
        Var var87 = const__172;
        var87.setMeta((IPersistentMap)const__174);
        Var var88 = var87;
        var87.bindRoot((Object)new query$qseq());
        Var var89 = const__175;
        var89.setMeta((IPersistentMap)const__177);
        Var var90 = var89;
        var89.bindRoot((Object)new query$cache());
        Var var91 = const__178;
        var91.setMeta((IPersistentMap)const__180);
        Var var92 = var91;
        var91.bindRoot((Object)new query$construct_fn());
        Object v111 = null;
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.query");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.query", (String)"emap");
        const__8 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__9 = RT.var((String)"datomic.query", (String)"rae");
        const__12 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"r"), (Object)Symbol.intern(null, (String)"a")))), RT.keyword(null, (String)"column"), 1});
        const__13 = RT.var((String)"datomic.query", (String)"ref-val");
        const__16 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"ref?"), (Object)Symbol.intern(null, (String)"v")))), RT.keyword(null, (String)"column"), 1});
        const__17 = RT.var((String)"datomic.query", (String)"eav");
        const__19 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Db")})), (Object)Symbol.intern(null, (String)"e"), (Object)Symbol.intern(null, (String)"a")))), RT.keyword(null, (String)"column"), 1});
        const__20 = RT.var((String)"datomic.query", (String)"get-lazy-entity");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"ent")))), RT.keyword(null, (String)"column"), 1});
        const__23 = RT.var((String)"datomic.query", (String)"touch");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"e")))), RT.keyword(null, (String)"column"), 1});
        const__27 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"eid")))), RT.keyword(null, (String)"column"), 1});
        const__28 = RT.var((String)"clojure.core", (String)"print-method");
        const__29 = RT.classForName((String)"datomic.query.EntityMap");
        const__30 = RT.classForName((String)"datomic.query.Immutify");
        const__31 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__32 = RT.var((String)"datomic.query", (String)"Immutify");
        const__33 = RT.var((String)"clojure.core", (String)"assoc");
        const__34 = RT.keyword(null, (String)"doc");
        const__35 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__36 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"immutify")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}))));
        const__37 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__38 = RT.var((String)"clojure.core", (String)"merge");
        const__42 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.query.Immutify"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.query.Immutify")});
        const__43 = RT.keyword(null, (String)"sigs");
        const__44 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"immutify"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"immutify")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Return immutable form of x. Presumes that if top of a data structure\nis immutable, rest is too."})});
        const__45 = RT.keyword(null, (String)"var");
        const__46 = RT.keyword(null, (String)"method-map");
        const__47 = RT.keyword(null, (String)"immutify");
        const__48 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"immutify"), RT.keyword(null, (String)"immutify")});
        const__49 = RT.keyword(null, (String)"method-builders");
        const__50 = RT.var((String)"clojure.core", (String)"intern");
        const__51 = RT.var((String)"clojure.core", (String)"*ns*");
        const__52 = RT.var((String)"clojure.core", (String)"with-meta");
        const__53 = (AFn)((IObj)Symbol.intern(null, (String)"immutify")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}));
        const__54 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"immutify")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Return immutable form of x. Presumes that if top of a data structure\nis immutable, rest is too."});
        const__55 = RT.keyword(null, (String)"protocol");
        const__56 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__57 = (AFn)Symbol.intern(null, (String)"Immutify");
        const__58 = RT.var((String)"clojure.core", (String)"extend");
        const__59 = RT.classForName((String)"java.lang.Object");
        const__60 = RT.classForName((String)"java.util.Map");
        const__61 = RT.classForName((String)"java.util.Set");
        const__62 = RT.classForName((String)"java.util.List");
        const__63 = RT.var((String)"datomic.query", (String)"listq->mapq");
        const__65 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"lq")))), RT.keyword(null, (String)"column"), 1});
        const__66 = RT.var((String)"datomic.query", (String)"move-sources-to-meta");
        const__68 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{Symbol.intern(null, (String)"srcs"), RT.keyword(null, (String)"in"), Symbol.intern(null, (String)"clauses"), RT.keyword(null, (String)"where"), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"q")})))), RT.keyword(null, (String)"column"), 1});
        const__69 = RT.var((String)"datomic.query", (String)"flatten-listy");
        const__71 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__72 = RT.var((String)"datomic.query", (String)"variables-in-clause");
        const__74 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"clause")))), RT.keyword(null, (String)"column"), 1});
        const__75 = RT.var((String)"datomic.query", (String)"validate-query");
        const__77 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__78 = RT.var((String)"datomic.query", (String)"process-in-bindings");
        const__80 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap"), (Object)Symbol.intern(null, (String)"prefix")))), RT.keyword(null, (String)"column"), 1});
        const__81 = RT.var((String)"datomic.query", (String)"process-ranges");
        const__83 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__84 = RT.var((String)"datomic.query", (String)"process-aggregates");
        const__86 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__87 = RT.var((String)"datomic.query", (String)"process-find-bindings");
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"find")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"qmap")})))), RT.keyword(null, (String)"column"), 1});
        const__90 = RT.var((String)"datomic.query", (String)"pattern?");
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__93 = RT.var((String)"datomic.query", (String)"normalize-pull");
        const__95 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"expr")))), RT.keyword(null, (String)"column"), 1});
        const__96 = RT.var((String)"datomic.query", (String)"process-pulls");
        const__98 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"find"), (Object)Symbol.intern(null, (String)"in")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"qmap")})))), RT.keyword(null, (String)"column"), 1});
        const__99 = RT.var((String)"datomic.query", (String)"mapify-query");
    }

    public static void __init1() {
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__102 = RT.var((String)"datomic.query", (String)"rename-self-unifications");
        const__104 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap"), (Object)Symbol.intern(null, (String)"padding")))), RT.keyword(null, (String)"column"), 1});
        const__105 = RT.var((String)"datomic.query", (String)"gensym-padding");
        const__107 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__108 = RT.var((String)"datomic.query", (String)"has-self-unifications?");
        const__110 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__111 = RT.var((String)"datomic.query", (String)"process-self-unifications");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qmap")))), RT.keyword(null, (String)"column"), 1});
        const__114 = RT.var((String)"datomic.query", (String)"compile-construct-1");
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"smap"), (Object)Symbol.intern(null, (String)"clause")))), RT.keyword(null, (String)"column"), 1});
        const__117 = RT.var((String)"datomic.query", (String)"compile-construct-n");
        const__119 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"find-clause"), (Object)Symbol.intern(null, (String)"construct-clause")))), RT.keyword(null, (String)"column"), 1});
        const__120 = RT.var((String)"datomic.query", (String)"compile-construct");
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__123 = RT.var((String)"datomic.query", (String)"resolve-qualified-fn");
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__126 = RT.var((String)"datomic.query", (String)"resolve-qualified-fns");
        const__128 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"where"), (Object)Symbol.intern(null, (String)"group"))})))), RT.keyword(null, (String)"column"), 1});
        const__129 = RT.var((String)"datomic.query", (String)"parse-query");
        const__131 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__132 = RT.var((String)"datomic.query", (String)"load-query");
        const__134 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query")))), RT.keyword(null, (String)"column"), 1});
        const__135 = RT.var((String)"datomic.query", (String)"group-rel");
        const__137 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"fv"), (Object)Symbol.intern(null, (String)"rel")))), RT.keyword(null, (String)"column"), 1});
        const__138 = RT.var((String)"datomic.query", (String)"query-cache");
        const__139 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__140 = RT.var((String)"datomic.cache", (String)"create-computing");
        const__141 = 1000L;
        const__142 = RT.var((String)"datomic.query", (String)"group-fv");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"find-clause"), (Object)Symbol.intern(null, (String)"group-clause")))), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.query", (String)"xf-tuple");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"fv"), (Object)Symbol.intern(null, (String)"tuple")))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.query", (String)"pull-fv");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"find"), (Object)Symbol.intern(null, (String)"pull"), (Object)Symbol.intern(null, (String)"with"), (Object)Symbol.intern(null, (String)"in")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"qmap")}), (Object)Symbol.intern(null, (String)"srcs")))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.query", (String)"sort-collection-by-indexed");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"coll")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Collection")})), (Object)((IObj)Symbol.intern(null, (String)"idx")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"long")}))))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.query", (String)"sort-for-pull");
        const__156 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"result")))), RT.keyword(null, (String)"column"), 1});
        const__157 = RT.var((String)"datomic.query", (String)"q*");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"srcs")))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.query", (String)"query*");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query-map")))), RT.keyword(null, (String)"column"), 1});
        const__163 = RT.var((String)"datomic.query", (String)"apply-pf");
        const__165 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"result"), (Object)Symbol.intern(null, (String)"pf"))))), RT.keyword(null, (String)"column"), 1});
        const__166 = RT.var((String)"datomic.query", (String)"q");
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"query"), (Object)Symbol.intern(null, (String)"srcs")))), RT.keyword(null, (String)"column"), 1});
        const__169 = RT.var((String)"datomic.query", (String)"query");
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"io-context"), (Object)Symbol.intern(null, (String)"query-stats")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"query-map")})))), RT.keyword(null, (String)"column"), 1});
        const__172 = RT.var((String)"datomic.query", (String)"qseq");
        const__174 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"offset"), (Object)Symbol.intern(null, (String)"limit"), (Object)Symbol.intern(null, (String)"io-context")), RT.keyword(null, (String)"or"), RT.map((Object[])new Object[]{Symbol.intern(null, (String)"offset"), 0L, Symbol.intern(null, (String)"limit"), Symbol.intern((String)"Long", (String)"MAX_VALUE")}), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"query-map")})), Tuple.create((Object)Symbol.intern(null, (String)"query-map"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__175 = RT.var((String)"datomic.query", (String)"cache");
        const__177 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"q")))), RT.keyword(null, (String)"column"), 1});
        const__178 = RT.var((String)"datomic.query", (String)"construct-fn");
        const__180 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"qform")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        query__init.__init0();
        query__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.query__init").getClassLoader());
        try {
            query__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

