/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 *  com.amazonaws.services.s3.model.CannedAccessControlList
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import com.amazonaws.services.s3.model.CannedAccessControlList;
import datomic.s3$_list_objects_seq;
import datomic.s3$create_bucket;
import datomic.s3$debug;
import datomic.s3$delete_all_objects;
import datomic.s3$delete_bucket;
import datomic.s3$delete_object;
import datomic.s3$delete_objects;
import datomic.s3$destroy_bucket;
import datomic.s3$ensure_bucket;
import datomic.s3$fn__23252;
import datomic.s3$fn__23257;
import datomic.s3$fn__23260;
import datomic.s3$fn__23271;
import datomic.s3$fn__23273;
import datomic.s3$get_bucket;
import datomic.s3$get_bucket_policy;
import datomic.s3$get_bytes;
import datomic.s3$get_direct_buffer;
import datomic.s3$get_file;
import datomic.s3$get_non_direct_buffer;
import datomic.s3$get_object;
import datomic.s3$list_buckets;
import datomic.s3$list_objects;
import datomic.s3$loading__6434__auto____22955;
import datomic.s3$new_bucket;
import datomic.s3$object_exists_QMARK_;
import datomic.s3$put_clj;
import datomic.s3$put_file_as;
import datomic.s3$put_object;
import datomic.s3$s3_service;
import datomic.s3$set_bucket_policy;
import datomic.s3$signed_get_clj;
import datomic.s3$signed_get_file;
import datomic.s3$signed_put_clj;
import datomic.s3$signed_put_file;
import datomic.s3$signed_url;
import datomic.s3$years_from_now;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class s3__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__9;
    public static final Object const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final Var const__13;
    public static final Keyword const__14;
    public static final Var const__15;
    public static final ISeq const__16;
    public static final Var const__17;
    public static final Var const__18;
    public static final AFn const__22;
    public static final Keyword const__23;
    public static final AFn const__24;
    public static final Keyword const__25;
    public static final Keyword const__26;
    public static final Keyword const__27;
    public static final AFn const__28;
    public static final Keyword const__29;
    public static final Var const__30;
    public static final Var const__31;
    public static final Var const__32;
    public static final AFn const__33;
    public static final AFn const__34;
    public static final Keyword const__35;
    public static final Var const__36;
    public static final AFn const__37;
    public static final Var const__38;
    public static final Object const__39;
    public static final Object const__40;
    public static final Var const__41;
    public static final AFn const__43;
    public static final Var const__44;
    public static final AFn const__46;
    public static final Var const__47;
    public static final AFn const__49;
    public static final Var const__50;
    public static final AFn const__52;
    public static final Var const__53;
    public static final AFn const__55;
    public static final Var const__56;
    public static final AFn const__58;
    public static final Var const__59;
    public static final AFn const__61;
    public static final Var const__62;
    public static final AFn const__64;
    public static final Var const__65;
    public static final AFn const__67;
    public static final AFn const__69;
    public static final Var const__70;
    public static final AFn const__72;
    public static final Var const__73;
    public static final AFn const__75;
    public static final Var const__76;
    public static final AFn const__78;
    public static final Var const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__84;
    public static final Var const__85;
    public static final AFn const__86;
    public static final Var const__87;
    public static final AFn const__89;
    public static final Var const__90;
    public static final AFn const__92;
    public static final Var const__93;
    public static final AFn const__95;
    public static final Var const__96;
    public static final AFn const__98;
    public static final Var const__99;
    public static final AFn const__101;
    public static final Var const__102;
    public static final AFn const__104;
    public static final Var const__105;
    public static final AFn const__107;
    public static final Var const__108;
    public static final AFn const__110;
    public static final Var const__111;
    public static final AFn const__113;
    public static final Var const__114;
    public static final AFn const__116;
    public static final Var const__117;
    public static final AFn const__119;
    public static final Var const__120;
    public static final AFn const__122;
    public static final Var const__123;
    public static final AFn const__125;
    public static final Var const__126;
    public static final AFn const__128;
    public static final Var const__129;
    public static final AFn const__131;
    public static final Var const__132;
    public static final AFn const__134;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new s3$loading__6434__auto____22955()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new s3$fn__23252())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Var var = const__4;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot((Object)new s3$s3_service());
        Object object4 = ((IFn)new s3$fn__23257()).invoke();
        Object object5 = const__10;
        Object object6 = ((IFn)const__11.getRawRoot()).invoke((Object)const__12, const__13.getRawRoot(), (Object)const__14, null);
        Object object7 = ((IFn)const__15).invoke((Object)const__12, (Object)const__16);
        Object object8 = ((IFn)const__17.getRawRoot()).invoke((Object)const__12, const__18.getRawRoot(), ((IFn)const__13.getRawRoot()).invoke((Object)const__22, (Object)const__23, (Object)const__24, (Object)const__25, (Object)const__12, (Object)const__26, (Object)const__28, (Object)const__29, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__30.getRawRoot()).invoke(const__31.get(), ((IFn)const__32.getRawRoot()).invoke((Object)const__33, ((IFn)const__18.getRawRoot()).invoke((Object)const__34, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__35, const__12})))), new s3$fn__23260()})));
        Object object9 = ((IFn)const__36.getRawRoot()).invoke(const__12.getRawRoot());
        AFn aFn = const__37;
        Object object10 = ((IFn)const__38.getRawRoot()).invoke(const__39, const__12.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__27, new s3$fn__23271()}));
        Object object11 = ((IFn)const__38.getRawRoot()).invoke(const__40, const__12.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__27, new s3$fn__23273()}));
        Var var3 = const__41;
        var3.setMeta((IPersistentMap)const__43);
        Var var4 = var3;
        var3.bindRoot((Object)new s3$years_from_now());
        Var var5 = const__44;
        var5.setMeta((IPersistentMap)const__46);
        Var var6 = var5;
        var5.bindRoot((Object)new s3$create_bucket());
        Var var7 = const__47;
        Var var8 = var7;
        var7.setMeta((IPersistentMap)const__49);
        Var var9 = const__50;
        var9.setMeta((IPersistentMap)const__52);
        Var var10 = var9;
        var9.bindRoot((Object)new s3$ensure_bucket());
        Var var11 = const__53;
        var11.setMeta((IPersistentMap)const__55);
        Var var12 = var11;
        var11.bindRoot((Object)new s3$new_bucket());
        Var var13 = const__56;
        var13.setMeta((IPersistentMap)const__58);
        Var var14 = var13;
        var13.bindRoot((Object)new s3$debug());
        Var var15 = const__59;
        var15.setMeta((IPersistentMap)const__61);
        Var var16 = var15;
        var15.bindRoot((Object)new s3$signed_url());
        Var var17 = const__62;
        var17.setMeta((IPersistentMap)const__64);
        Var var18 = var17;
        var17.bindRoot((Object)new s3$_list_objects_seq());
        Var var19 = const__65;
        var19.setMeta((IPersistentMap)const__67);
        Var var20 = var19;
        var19.bindRoot((Object)new s3$list_objects());
        Var var21 = const__47;
        var21.setMeta((IPersistentMap)const__69);
        Var var22 = var21;
        var21.bindRoot((Object)new s3$get_bucket());
        Var var23 = const__70;
        var23.setMeta((IPersistentMap)const__72);
        Var var24 = var23;
        var23.bindRoot((Object)new s3$list_buckets());
        Var var25 = const__73;
        var25.setMeta((IPersistentMap)const__75);
        Var var26 = var25;
        var25.bindRoot((Object)new s3$delete_object());
        Var var27 = const__76;
        var27.setMeta((IPersistentMap)const__78);
        Var var28 = var27;
        var27.bindRoot((Object)new s3$delete_objects());
        Var var29 = const__79;
        var29.setMeta((IPersistentMap)const__81);
        Var var30 = var29;
        var29.bindRoot((Object)new s3$delete_all_objects());
        Var var31 = const__82;
        var31.setMeta((IPersistentMap)const__84);
        Var var32 = var31;
        var31.bindRoot((Object)new s3$object_exists_QMARK_());
        Var var33 = const__85;
        var33.setMeta((IPersistentMap)const__86);
        Var var34 = var33;
        var33.bindRoot((Object)CannedAccessControlList.BucketOwnerFullControl);
        Var var35 = const__87;
        var35.setMeta((IPersistentMap)const__89);
        Var var36 = var35;
        var35.bindRoot((Object)new s3$put_file_as());
        Var var37 = const__90;
        var37.setMeta((IPersistentMap)const__92);
        Var var38 = var37;
        var37.bindRoot((Object)new s3$put_object());
        Var var39 = const__93;
        var39.setMeta((IPersistentMap)const__95);
        Var var40 = var39;
        var39.bindRoot((Object)new s3$get_object());
        Var var41 = const__96;
        var41.setMeta((IPersistentMap)const__98);
        Var var42 = var41;
        var41.bindRoot((Object)new s3$get_direct_buffer());
        Var var43 = const__99;
        var43.setMeta((IPersistentMap)const__101);
        Var var44 = var43;
        var43.bindRoot((Object)new s3$get_bytes());
        Var var45 = const__102;
        var45.setMeta((IPersistentMap)const__104);
        Var var46 = var45;
        var45.bindRoot((Object)new s3$get_non_direct_buffer());
        Var var47 = const__105;
        var47.setMeta((IPersistentMap)const__107);
        Var var48 = var47;
        var47.bindRoot((Object)new s3$delete_bucket());
        Var var49 = const__108;
        var49.setMeta((IPersistentMap)const__110);
        Var var50 = var49;
        var49.bindRoot((Object)new s3$destroy_bucket());
        Var var51 = const__111;
        var51.setMeta((IPersistentMap)const__113);
        Var var52 = var51;
        var51.bindRoot((Object)new s3$signed_get_clj());
        Var var53 = const__114;
        var53.setMeta((IPersistentMap)const__116);
        Var var54 = var53;
        var53.bindRoot((Object)new s3$signed_get_file());
        Var var55 = const__117;
        var55.setMeta((IPersistentMap)const__119);
        Var var56 = var55;
        var55.bindRoot((Object)new s3$get_file());
        Var var57 = const__120;
        var57.setMeta((IPersistentMap)const__122);
        Var var58 = var57;
        var57.bindRoot((Object)new s3$signed_put_file());
        Var var59 = const__123;
        var59.setMeta((IPersistentMap)const__125);
        Var var60 = var59;
        var59.bindRoot((Object)new s3$signed_put_clj());
        Var var61 = const__126;
        var61.setMeta((IPersistentMap)const__128);
        Var var62 = var61;
        var61.bindRoot((Object)new s3$put_clj());
        Var var63 = const__129;
        var63.setMeta((IPersistentMap)const__131);
        Var var64 = var63;
        var63.bindRoot((Object)new s3$set_bucket_policy());
        Var var65 = const__132;
        var65.setMeta((IPersistentMap)const__134);
        Var var66 = var65;
        var65.bindRoot((Object)new s3$get_bucket_policy());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.s3");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.s3", (String)"s3-service");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"&"), (Object)Symbol.intern(null, (String)"args")))), RT.keyword(null, (String)"column"), 1});
        const__10 = RT.classForName((String)"datomic.s3.Name");
        const__11 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__12 = RT.var((String)"datomic.s3", (String)"Name");
        const__13 = RT.var((String)"clojure.core", (String)"assoc");
        const__14 = RT.keyword(null, (String)"doc");
        const__15 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__16 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"s3-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}))));
        const__17 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__18 = RT.var((String)"clojure.core", (String)"merge");
        const__22 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.s3.Name"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.s3.Name")});
        const__23 = RT.keyword(null, (String)"sigs");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"s3-name"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"s3-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Get the string name from an object that can be used as\n    a name in an S3 context."})});
        const__25 = RT.keyword(null, (String)"var");
        const__26 = RT.keyword(null, (String)"method-map");
        const__27 = RT.keyword(null, (String)"s3-name");
        const__28 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"s3-name"), RT.keyword(null, (String)"s3-name")});
        const__29 = RT.keyword(null, (String)"method-builders");
        const__30 = RT.var((String)"clojure.core", (String)"intern");
        const__31 = RT.var((String)"clojure.core", (String)"*ns*");
        const__32 = RT.var((String)"clojure.core", (String)"with-meta");
        const__33 = (AFn)((IObj)Symbol.intern(null, (String)"s3-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))}));
        const__34 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"s3-name")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"doc"), "Get the string name from an object that can be used as\n    a name in an S3 context."});
        const__35 = RT.keyword(null, (String)"protocol");
        const__36 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__37 = (AFn)Symbol.intern(null, (String)"Name");
        const__38 = RT.var((String)"clojure.core", (String)"extend");
        const__39 = RT.classForName((String)"java.lang.String");
        const__40 = RT.classForName((String)"clojure.lang.APersistentMap");
        const__41 = RT.var((String)"datomic.s3", (String)"years-from-now");
        const__43 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"n")))), RT.keyword(null, (String)"column"), 1});
        const__44 = RT.var((String)"datomic.s3", (String)"create-bucket");
        const__46 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")), Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"region")))), RT.keyword(null, (String)"column"), 1});
        const__47 = RT.var((String)"datomic.s3", (String)"get-bucket");
        const__49 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__50 = RT.var((String)"datomic.s3", (String)"ensure-bucket");
        const__52 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")), Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"region")))), RT.keyword(null, (String)"column"), 1});
        const__53 = RT.var((String)"datomic.s3", (String)"new-bucket");
        const__55 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"basename")))), RT.keyword(null, (String)"column"), 1});
        const__56 = RT.var((String)"datomic.s3", (String)"debug");
        const__58 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__59 = RT.var((String)"datomic.s3", (String)"signed-url");
        const__61 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"method"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"key"), (Object)Symbol.intern(null, (String)"expiry")), RT.vector((Object[])new Object[]{Symbol.intern(null, (String)"s3"), Symbol.intern(null, (String)"method"), Symbol.intern(null, (String)"bucket"), Symbol.intern(null, (String)"key"), Symbol.intern(null, (String)"expiry"), Symbol.intern(null, (String)"headers"), Symbol.intern(null, (String)"virtual-host?")}))), RT.keyword(null, (String)"column"), 1});
        const__62 = RT.var((String)"datomic.s3", (String)"-list-objects-seq");
        const__64 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"results")))), RT.keyword(null, (String)"column"), 1});
        const__65 = RT.var((String)"datomic.s3", (String)"list-objects");
        const__67 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")), Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"prefix"), (Object)Symbol.intern(null, (String)"delimiter")))), RT.keyword(null, (String)"column"), 1});
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket-name")))), RT.keyword(null, (String)"column"), 1});
        const__70 = RT.var((String)"datomic.s3", (String)"list-buckets");
        const__72 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3")))), RT.keyword(null, (String)"column"), 1});
        const__73 = RT.var((String)"datomic.s3", (String)"delete-object");
        const__75 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"key")))), RT.keyword(null, (String)"column"), 1});
        const__76 = RT.var((String)"datomic.s3", (String)"delete-objects");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"keys")))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.var((String)"datomic.s3", (String)"delete-all-objects");
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")))), RT.keyword(null, (String)"column"), 1});
        const__82 = RT.var((String)"datomic.s3", (String)"object-exists?");
        const__84 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__85 = RT.var((String)"datomic.s3", (String)"BUCKET_OWNER_FULL_ACCESS_CANNED_ACL");
        const__86 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__87 = RT.var((String)"datomic.s3", (String)"put-file-as");
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"path")), Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"metadata")), Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"metadata"), (Object)Symbol.intern(null, (String)"canned-acl")))), RT.keyword(null, (String)"column"), 1});
        const__90 = RT.var((String)"datomic.s3", (String)"put-object");
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"stream"), (Object)Symbol.intern(null, (String)"metadata")))), RT.keyword(null, (String)"column"), 1});
        const__93 = RT.var((String)"datomic.s3", (String)"get-object");
        const__95 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path")))), RT.keyword(null, (String)"column"), 1});
        const__96 = RT.var((String)"datomic.s3", (String)"get-direct-buffer");
        const__98 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path")))), RT.keyword(null, (String)"column"), 1});
        const__99 = RT.var((String)"datomic.s3", (String)"get-bytes");
    }

    public static void __init1() {
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path")))), RT.keyword(null, (String)"column"), 1});
        const__102 = RT.var((String)"datomic.s3", (String)"get-non-direct-buffer");
        const__104 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path")))), RT.keyword(null, (String)"column"), 1});
        const__105 = RT.var((String)"datomic.s3", (String)"delete-bucket");
        const__107 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")))), RT.keyword(null, (String)"column"), 1});
        const__108 = RT.var((String)"datomic.s3", (String)"destroy-bucket");
        const__110 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")))), RT.keyword(null, (String)"column"), 1});
        const__111 = RT.var((String)"datomic.s3", (String)"signed-get-clj");
        const__113 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"url")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"URL")}))))), RT.keyword(null, (String)"column"), 1});
        const__114 = RT.var((String)"datomic.s3", (String)"signed-get-file");
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"url")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"URL")})), (Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__117 = RT.var((String)"datomic.s3", (String)"get-file");
        const__119 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"path"), (Object)Symbol.intern(null, (String)"dest")))), RT.keyword(null, (String)"column"), 1});
        const__120 = RT.var((String)"datomic.s3", (String)"signed-put-file");
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"url")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"URL")})), (Object)Symbol.intern(null, (String)"f")))), RT.keyword(null, (String)"column"), 1});
        const__123 = RT.var((String)"datomic.s3", (String)"signed-put-clj");
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"url")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"URL")})), (Object)Symbol.intern(null, (String)"obj")))), RT.keyword(null, (String)"column"), 1});
        const__126 = RT.var((String)"datomic.s3", (String)"put-clj");
        const__128 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"key"), (Object)Symbol.intern(null, (String)"obj")))), RT.keyword(null, (String)"column"), 1});
        const__129 = RT.var((String)"datomic.s3", (String)"set-bucket-policy");
        const__131 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket"), (Object)Symbol.intern(null, (String)"policy")))), RT.keyword(null, (String)"column"), 1});
        const__132 = RT.var((String)"datomic.s3", (String)"get-bucket-policy");
        const__134 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"s3"), (Object)Symbol.intern(null, (String)"bucket")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        s3__init.__init0();
        s3__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.s3__init").getClassLoader());
        try {
            s3__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

