/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.AReference
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.ISeq
 *  clojure.lang.Keyword
 *  clojure.lang.LockingTransaction
 *  clojure.lang.Namespace
 *  clojure.lang.Numbers
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 *  org.fressian.impl.Codes
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.AReference;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.ISeq;
import clojure.lang.Keyword;
import clojure.lang.LockingTransaction;
import clojure.lang.Namespace;
import clojure.lang.Numbers;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.log$catchup;
import datomic.log$catchup_tx;
import datomic.log$claim_log;
import datomic.log$combine_last_if;
import datomic.log$convert_log_version;
import datomic.log$create_entry;
import datomic.log$create_leaves;
import datomic.log$create_leaves_STAR_;
import datomic.log$create_log_impl;
import datomic.log$create_log_val;
import datomic.log$create_new_log;
import datomic.log$create_tail;
import datomic.log$empty_tail;
import datomic.log$ensure_index_and_log;
import datomic.log$excise;
import datomic.log$excise_dir_map;
import datomic.log$excise_root;
import datomic.log$excise_ts;
import datomic.log$extend_tail;
import datomic.log$extend_tree;
import datomic.log$find_log;
import datomic.log$fn__15938;
import datomic.log$fn__15945;
import datomic.log$fn__15948;
import datomic.log$fn__15961;
import datomic.log$fn__15990;
import datomic.log$fn__15993;
import datomic.log$fn__16008;
import datomic.log$fn__16019;
import datomic.log$fn__16030;
import datomic.log$fn__16047;
import datomic.log$fn__16058;
import datomic.log$fn__16073;
import datomic.log$fn__16076;
import datomic.log$fn__16089;
import datomic.log$fn__16092;
import datomic.log$fn__16105;
import datomic.log$fn__16108;
import datomic.log$fn__16121;
import datomic.log$fn__16124;
import datomic.log$fn__16138;
import datomic.log$fn__16140;
import datomic.log$fn__16143;
import datomic.log$fn__16194;
import datomic.log$fn__16200;
import datomic.log$fn__16251;
import datomic.log$fn__16296;
import datomic.log$fn__16456;
import datomic.log$fn__16476;
import datomic.log$fn__16485;
import datomic.log$fressianed_dir;
import datomic.log$fressianed_leaf;
import datomic.log$fressianed_tx;
import datomic.log$fressianed_txes_length;
import datomic.log$inc_rev;
import datomic.log$last_by_nth;
import datomic.log$last_tree_tx;
import datomic.log$legacy_root_ref_key;
import datomic.log$load_tail;
import datomic.log$loading__6434__auto____14342;
import datomic.log$log_tree;
import datomic.log$max_eidx;
import datomic.log$max_t;
import datomic.log$normalize_desc;
import datomic.log$partition_by_weight;
import datomic.log$pod_update_succeeded_QMARK_;
import datomic.log$read_tail_descriptor;
import datomic.log$reify__16166;
import datomic.log$reify__16168;
import datomic.log$resets_caches_QMARK_;
import datomic.log$root_id;
import datomic.log$seek_seg_id;
import datomic.log$seek_tx;
import datomic.log$segment;
import datomic.log$segmented_basis_t;
import datomic.log$since;
import datomic.log$tail_byte_count;
import datomic.log$tail_descriptor_QMARK_;
import datomic.log$tail_empty_QMARK_;
import datomic.log$tail_pod_key;
import datomic.log$tail_ts;
import datomic.log$tx_range;
import datomic.log$write_excise_val;
import datomic.log$write_excised_log;
import datomic.log$write_new_log;
import datomic.log$write_tail_descriptor;
import datomic.log$zip_and_create;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.concurrent.Callable;
import org.fressian.impl.Codes;

public class log__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final Keyword const__2;
    public static final AFn const__3;
    public static final AFn const__4;
    public static final Var const__5;
    public static final Var const__6;
    public static final AFn const__9;
    public static final Var const__10;
    public static final Var const__11;
    public static final Var const__12;
    public static final AFn const__13;
    public static final Var const__14;
    public static final Var const__15;
    public static final AFn const__16;
    public static final Object const__17;
    public static final Var const__18;
    public static final AFn const__19;
    public static final Object const__20;
    public static final Var const__21;
    public static final AFn const__25;
    public static final Object const__26;
    public static final Var const__27;
    public static final Var const__28;
    public static final Var const__29;
    public static final Var const__30;
    public static final ISeq const__31;
    public static final Var const__32;
    public static final Var const__33;
    public static final AFn const__37;
    public static final Keyword const__38;
    public static final AFn const__39;
    public static final Keyword const__40;
    public static final Keyword const__41;
    public static final Keyword const__42;
    public static final AFn const__44;
    public static final Keyword const__45;
    public static final Var const__46;
    public static final Var const__47;
    public static final Var const__48;
    public static final AFn const__49;
    public static final AFn const__50;
    public static final Keyword const__51;
    public static final AFn const__52;
    public static final AFn const__53;
    public static final Var const__54;
    public static final AFn const__55;
    public static final Var const__56;
    public static final AFn const__58;
    public static final Object const__59;
    public static final Var const__60;
    public static final ISeq const__61;
    public static final AFn const__63;
    public static final AFn const__64;
    public static final AFn const__71;
    public static final AFn const__72;
    public static final AFn const__73;
    public static final AFn const__74;
    public static final AFn const__75;
    public static final AFn const__76;
    public static final AFn const__77;
    public static final AFn const__78;
    public static final AFn const__79;
    public static final AFn const__80;
    public static final AFn const__81;
    public static final AFn const__82;
    public static final AFn const__83;
    public static final AFn const__84;
    public static final Object const__85;
    public static final Var const__86;
    public static final ISeq const__87;
    public static final AFn const__89;
    public static final AFn const__90;
    public static final AFn const__92;
    public static final AFn const__93;
    public static final AFn const__94;
    public static final AFn const__95;
    public static final Object const__96;
    public static final Var const__97;
    public static final ISeq const__98;
    public static final AFn const__100;
    public static final AFn const__101;
    public static final Keyword const__102;
    public static final AFn const__103;
    public static final AFn const__104;
    public static final AFn const__105;
    public static final AFn const__106;
    public static final Object const__107;
    public static final Var const__108;
    public static final ISeq const__109;
    public static final AFn const__111;
    public static final AFn const__112;
    public static final AFn const__114;
    public static final AFn const__115;
    public static final AFn const__116;
    public static final AFn const__117;
    public static final Object const__118;
    public static final Var const__119;
    public static final ISeq const__120;
    public static final AFn const__122;
    public static final AFn const__123;
    public static final AFn const__125;
    public static final AFn const__126;
    public static final AFn const__127;
    public static final AFn const__128;
    public static final Var const__129;
    public static final AFn const__131;
    public static final Var const__132;
    public static final Object const__133;
    public static final Object const__134;
    public static final Var const__135;
    public static final AFn const__136;
    public static final Var const__137;
    public static final Object const__138;
    public static final AFn const__142;
    public static final Var const__143;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__148;
    public static final Var const__149;
    public static final AFn const__151;
    public static final Var const__152;
    public static final AFn const__154;
    public static final Var const__155;
    public static final AFn const__157;
    public static final Var const__158;
    public static final AFn const__160;
    public static final Var const__161;
    public static final AFn const__163;
    public static final Var const__164;
    public static final AFn const__166;
    public static final Var const__167;
    public static final AFn const__169;
    public static final Object const__170;
    public static final Var const__171;
    public static final AFn const__173;
    public static final Var const__174;
    public static final AFn const__176;
    public static final Var const__177;
    public static final AFn const__179;
    public static final Var const__180;
    public static final AFn const__182;
    public static final Var const__183;
    public static final AFn const__185;
    public static final Var const__186;
    public static final AFn const__188;
    public static final Var const__189;
    public static final AFn const__191;
    public static final Var const__192;
    public static final AFn const__194;
    public static final Var const__195;
    public static final AFn const__196;
    public static final Var const__199;
    public static final AFn const__200;
    public static final Var const__201;
    public static final AFn const__202;
    public static final Var const__203;
    public static final AFn const__205;
    public static final Var const__206;
    public static final AFn const__207;
    public static final Var const__208;
    public static final AFn const__210;
    public static final Var const__211;
    public static final AFn const__213;
    public static final Var const__214;
    public static final AFn const__216;
    public static final Var const__217;
    public static final AFn const__219;
    public static final Var const__220;
    public static final AFn const__222;
    public static final Var const__223;
    public static final AFn const__225;
    public static final AFn const__227;
    public static final AFn const__229;
    public static final Var const__230;
    public static final AFn const__232;
    public static final Var const__233;
    public static final AFn const__235;
    public static final Var const__236;
    public static final AFn const__238;
    public static final Var const__239;
    public static final AFn const__241;
    public static final Var const__242;
    public static final AFn const__244;
    public static final Var const__245;
    public static final AFn const__247;
    public static final Var const__248;
    public static final AFn const__250;
    public static final Var const__251;
    public static final AFn const__253;
    public static final Var const__254;
    public static final AFn const__256;
    public static final Var const__257;
    public static final AFn const__259;
    public static final Var const__260;
    public static final AFn const__262;
    public static final Var const__263;
    public static final AFn const__265;
    public static final Var const__266;
    public static final AFn const__268;
    public static final Var const__269;
    public static final AFn const__271;
    public static final Var const__272;
    public static final AFn const__274;
    public static final Var const__275;
    public static final AFn const__277;
    public static final Var const__278;
    public static final AFn const__280;
    public static final Object const__281;
    public static final Var const__282;
    public static final AFn const__284;
    public static final Var const__285;
    public static final AFn const__287;
    public static final Var const__288;
    public static final AFn const__290;
    public static final Var const__291;
    public static final AFn const__293;
    public static final Var const__294;
    public static final AFn const__296;
    public static final Var const__297;
    public static final AFn const__299;
    public static final Var const__300;
    public static final AFn const__302;
    public static final Var const__303;
    public static final AFn const__305;
    public static final Var const__306;
    public static final AFn const__308;
    public static final Var const__309;
    public static final AFn const__311;
    public static final Var const__312;
    public static final AFn const__314;
    public static final Var const__315;
    public static final AFn const__317;
    public static final Var const__318;
    public static final AFn const__320;

    public static void load() {
        Object v3;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        IPersistentMap iPersistentMap = ((AReference)Namespace.find((Symbol)((Symbol)const__1))).resetMeta((IPersistentMap)const__3);
        Object object2 = ((IFn)new log$loading__6434__auto____14342()).invoke();
        if (((Symbol)const__1).equals((Object)const__4)) {
            v3 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new log$fn__15938())));
            v3 = null;
        }
        Object object3 = const__5.set((Object)Boolean.TRUE);
        Var var = const__6;
        var.setMeta((IPersistentMap)const__9);
        Var var2 = var;
        var.bindRoot(((IFn)const__10.getRawRoot()).invoke((Object)const__11));
        Var var3 = const__12;
        var3.setMeta((IPersistentMap)const__13);
        Var var4 = var3;
        var3.bindRoot(((IFn)const__10.getRawRoot()).invoke((Object)const__14));
        Var var5 = const__15;
        var5.setMeta((IPersistentMap)const__16);
        Var var6 = var5;
        var5.bindRoot(const__17);
        Var var7 = const__18;
        var7.setMeta((IPersistentMap)const__19);
        Var var8 = var7;
        var7.bindRoot(const__20);
        Var var9 = const__21;
        var9.setMeta((IPersistentMap)const__25);
        Var var10 = var9;
        var9.bindRoot((Object)new log$last_by_nth());
        Object object4 = ((IFn)new log$fn__15945()).invoke();
        Object object5 = const__26;
        Object object6 = ((IFn)const__27.getRawRoot()).invoke((Object)const__28, const__29.getRawRoot(), (Object)const__2, null);
        Object object7 = ((IFn)const__30).invoke((Object)const__28, (Object)const__31);
        Object object8 = ((IFn)const__32.getRawRoot()).invoke((Object)const__28, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__37, (Object)const__38, (Object)const__39, (Object)const__40, (Object)const__28, (Object)const__41, (Object)const__44, (Object)const__45, (Object)RT.map((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__49, ((IFn)const__33.getRawRoot()).invoke((Object)const__50, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__28})))), new log$fn__15948(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__52, ((IFn)const__33.getRawRoot()).invoke((Object)const__53, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__28})))), new log$fn__15961()})));
        Object object9 = ((IFn)const__54.getRawRoot()).invoke(const__28.getRawRoot());
        AFn aFn = const__55;
        Var var11 = const__56;
        var11.setMeta((IPersistentMap)const__58);
        Var var12 = var11;
        var11.bindRoot((Object)new log$seek_seg_id());
        Object object10 = ((IFn)new log$fn__15990()).invoke();
        Object object11 = const__59;
        Object object12 = ((IFn)const__27.getRawRoot()).invoke((Object)const__60, const__29.getRawRoot(), (Object)const__2, null);
        Object object13 = ((IFn)const__30).invoke((Object)const__60, (Object)const__61);
        Object object14 = ((IFn)const__32.getRawRoot()).invoke((Object)const__60, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__63, (Object)const__38, (Object)const__64, (Object)const__40, (Object)const__60, (Object)const__41, (Object)const__71, (Object)const__45, (Object)RT.map((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__72, ((IFn)const__33.getRawRoot()).invoke((Object)const__73, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__15993(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__74, ((IFn)const__33.getRawRoot()).invoke((Object)const__75, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__16008(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__76, ((IFn)const__33.getRawRoot()).invoke((Object)const__77, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__16019(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__78, ((IFn)const__33.getRawRoot()).invoke((Object)const__79, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__16030(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__80, ((IFn)const__33.getRawRoot()).invoke((Object)const__81, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__16047(), ((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__82, ((IFn)const__33.getRawRoot()).invoke((Object)const__83, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__60})))), new log$fn__16058()})));
        Object object15 = ((IFn)const__54.getRawRoot()).invoke(const__60.getRawRoot());
        AFn aFn2 = const__84;
        Object object16 = ((IFn)new log$fn__16073()).invoke();
        Object object17 = const__85;
        Object object18 = ((IFn)const__27.getRawRoot()).invoke((Object)const__86, const__29.getRawRoot(), (Object)const__2, null);
        Object object19 = ((IFn)const__30).invoke((Object)const__86, (Object)const__87);
        Object object20 = ((IFn)const__32.getRawRoot()).invoke((Object)const__86, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__89, (Object)const__38, (Object)const__90, (Object)const__40, (Object)const__86, (Object)const__41, (Object)const__92, (Object)const__45, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__93, ((IFn)const__33.getRawRoot()).invoke((Object)const__94, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__86})))), new log$fn__16076()})));
        Object object21 = ((IFn)const__54.getRawRoot()).invoke(const__86.getRawRoot());
        AFn aFn3 = const__95;
        Object object22 = ((IFn)new log$fn__16089()).invoke();
        Object object23 = const__96;
        Object object24 = ((IFn)const__27.getRawRoot()).invoke((Object)const__97, const__29.getRawRoot(), (Object)const__2, null);
        Object object25 = ((IFn)const__30).invoke((Object)const__97, (Object)const__98);
        Object object26 = ((IFn)const__32.getRawRoot()).invoke((Object)const__97, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__100, (Object)const__38, (Object)const__101, (Object)const__40, (Object)const__97, (Object)const__41, (Object)const__103, (Object)const__45, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__104, ((IFn)const__33.getRawRoot()).invoke((Object)const__105, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__97})))), new log$fn__16092()})));
        Object object27 = ((IFn)const__54.getRawRoot()).invoke(const__97.getRawRoot());
        AFn aFn4 = const__106;
        Object object28 = ((IFn)new log$fn__16105()).invoke();
        Object object29 = const__107;
        Object object30 = ((IFn)const__27.getRawRoot()).invoke((Object)const__108, const__29.getRawRoot(), (Object)const__2, null);
        Object object31 = ((IFn)const__30).invoke((Object)const__108, (Object)const__109);
        Object object32 = ((IFn)const__32.getRawRoot()).invoke((Object)const__108, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__111, (Object)const__38, (Object)const__112, (Object)const__40, (Object)const__108, (Object)const__41, (Object)const__114, (Object)const__45, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__115, ((IFn)const__33.getRawRoot()).invoke((Object)const__116, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__108})))), new log$fn__16108()})));
        Object object33 = ((IFn)const__54.getRawRoot()).invoke(const__108.getRawRoot());
        AFn aFn5 = const__117;
        Object object34 = ((IFn)new log$fn__16121()).invoke();
        Object object35 = const__118;
        Object object36 = ((IFn)const__27.getRawRoot()).invoke((Object)const__119, const__29.getRawRoot(), (Object)const__2, null);
        Object object37 = ((IFn)const__30).invoke((Object)const__119, (Object)const__120);
        Object object38 = ((IFn)const__32.getRawRoot()).invoke((Object)const__119, const__33.getRawRoot(), ((IFn)const__29.getRawRoot()).invoke((Object)const__122, (Object)const__38, (Object)const__123, (Object)const__40, (Object)const__119, (Object)const__41, (Object)const__125, (Object)const__45, (Object)RT.mapUniqueKeys((Object[])new Object[]{((IFn)const__46.getRawRoot()).invoke(const__47.get(), ((IFn)const__48.getRawRoot()).invoke((Object)const__126, ((IFn)const__33.getRawRoot()).invoke((Object)const__127, (Object)RT.mapUniqueKeys((Object[])new Object[]{const__51, const__119})))), new log$fn__16124()})));
        Object object39 = ((IFn)const__54.getRawRoot()).invoke(const__119.getRawRoot());
        AFn aFn6 = const__128;
        Var var13 = const__129;
        var13.setMeta((IPersistentMap)const__131);
        Var var14 = var13;
        var13.bindRoot((Object)new log$fressianed_txes_length());
        Object object40 = ((IFn)const__132.getRawRoot()).invoke(const__133, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new log$fn__16138()}));
        Object object41 = ((IFn)const__132.getRawRoot()).invoke(const__134, const__97.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__102, new log$fn__16140()}));
        Object object42 = ((IFn)new log$fn__16143()).invoke();
        Var var15 = const__135;
        var15.setMeta((IPersistentMap)const__136);
        Var var16 = var15;
        var15.bindRoot(((IFn)const__33.getRawRoot()).invoke(((IFn)const__137.getRawRoot()).invoke((Object)Boolean.TRUE), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__138, RT.mapUniqueKeys((Object[])new Object[]{"log-dir", ((IObj)new log$reify__16166(null)).withMeta((IPersistentMap)const__142)})})));
        Var var17 = const__143;
        var17.setMeta((IPersistentMap)const__144);
        Var var18 = var17;
        var17.bindRoot(((IFn)const__33.getRawRoot()).invoke(const__145.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{"log-dir", ((IObj)new log$reify__16168(null)).withMeta((IPersistentMap)const__148)})));
        Var var19 = const__149;
        var19.setMeta((IPersistentMap)const__151);
        Var var20 = var19;
        var19.bindRoot((Object)new log$fressianed_tx());
        Var var21 = const__152;
        var21.setMeta((IPersistentMap)const__154);
        Var var22 = var21;
        var21.bindRoot((Object)new log$create_entry());
        Var var23 = const__155;
        var23.setMeta((IPersistentMap)const__157);
        Var var24 = var23;
        var23.bindRoot((Object)new log$tail_pod_key());
        Var var25 = const__158;
        var25.setMeta((IPersistentMap)const__160);
        Var var26 = var25;
        var25.bindRoot((Object)new log$tail_descriptor_QMARK_());
        Var var27 = const__161;
        var27.setMeta((IPersistentMap)const__163);
        Var var28 = var27;
        var27.bindRoot((Object)new log$inc_rev());
        Var var29 = const__164;
        var29.setMeta((IPersistentMap)const__166);
        Var var30 = var29;
        var29.bindRoot((Object)new log$legacy_root_ref_key());
        Var var31 = const__167;
        var31.setMeta((IPersistentMap)const__169);
        Var var32 = var31;
        var31.bindRoot(const__170);
        Var var33 = const__171;
        var33.setMeta((IPersistentMap)const__173);
        Var var34 = var33;
        var33.bindRoot((Object)new log$normalize_desc());
        Var var35 = const__174;
        var35.setMeta((IPersistentMap)const__176);
        Var var36 = var35;
        var35.bindRoot((Object)new log$read_tail_descriptor());
        Var var37 = const__177;
        var37.setMeta((IPersistentMap)const__179);
        Var var38 = var37;
        var37.bindRoot((Object)new log$pod_update_succeeded_QMARK_());
        Var var39 = const__180;
        var39.setMeta((IPersistentMap)const__182);
        Var var40 = var39;
        var39.bindRoot((Object)new log$write_tail_descriptor());
        Var var41 = const__183;
        var41.setMeta((IPersistentMap)const__185);
        Var var42 = var41;
        var41.bindRoot((Object)new log$claim_log());
        Var var43 = const__186;
        var43.setMeta((IPersistentMap)const__188);
        Var var44 = var43;
        var43.bindRoot((Object)new log$convert_log_version());
        Var var45 = const__189;
        var45.setMeta((IPersistentMap)const__191);
        Var var46 = var45;
        var45.bindRoot((Object)new log$zip_and_create());
        Var var47 = const__192;
        var47.setMeta((IPersistentMap)const__194);
        Var var48 = var47;
        var47.bindRoot((Object)new log$write_excise_val());
        Object object43 = ((IFn)new log$fn__16194()).invoke();
        Var var49 = const__195;
        var49.setMeta((IPersistentMap)const__196);
        Var var50 = var49;
        var49.bindRoot((Object)ByteBuffer.wrap(Numbers.byte_array((Object)Tuple.create((Object)RT.uncheckedByteCast((int)Codes.BEGIN_OPEN_LIST)))));
        Var var51 = const__199;
        var51.setMeta((IPersistentMap)const__200);
        Var var52 = var51;
        var51.bindRoot((Object)ByteBuffer.wrap(Numbers.byte_array((Object)Tuple.create((Object)RT.uncheckedByteCast((int)Codes.BEGIN_CLOSED_LIST)))));
        Var var53 = const__201;
        var53.setMeta((IPersistentMap)const__202);
        Var var54 = var53;
        var53.bindRoot((Object)ByteBuffer.wrap(Numbers.byte_array((Object)Tuple.create((Object)RT.uncheckedByteCast((int)Codes.END_COLLECTION)))));
        Var var55 = const__203;
        Var var56 = var55;
        var55.setMeta((IPersistentMap)const__205);
        Var var57 = const__206;
        Var var58 = var57;
        var57.setMeta((IPersistentMap)const__207);
        Object object44 = ((IFn)new log$fn__16200()).invoke();
        Var var59 = const__208;
        var59.setMeta((IPersistentMap)const__210);
        Var var60 = var59;
        var59.bindRoot((Object)new log$tail_byte_count());
        Var var61 = const__211;
        var61.setMeta((IPersistentMap)const__213);
        Var var62 = var61;
        var61.bindRoot((Object)new log$tail_ts());
        Var var63 = const__214;
        var63.setMeta((IPersistentMap)const__216);
        Var var64 = var63;
        var63.bindRoot((Object)new log$tail_empty_QMARK_());
        Var var65 = const__217;
        var65.setMeta((IPersistentMap)const__219);
        Var var66 = var65;
        var65.bindRoot((Object)new log$extend_tail());
        Var var67 = const__220;
        var67.setMeta((IPersistentMap)const__222);
        Var var68 = var67;
        var67.bindRoot((Object)new log$since());
        Var var69 = const__223;
        var69.setMeta((IPersistentMap)const__225);
        Var var70 = var69;
        var69.bindRoot((Object)new log$resets_caches_QMARK_());
        Var var71 = const__203;
        var71.setMeta((IPersistentMap)const__227);
        Var var72 = var71;
        var71.bindRoot((Object)new log$create_tail());
        Var var73 = const__206;
        var73.setMeta((IPersistentMap)const__229);
        Var var74 = var73;
        var73.bindRoot((Object)new log$empty_tail());
        Var var75 = const__230;
        var75.setMeta((IPersistentMap)const__232);
        Var var76 = var75;
        var75.bindRoot((Object)new log$load_tail());
        Var var77 = const__233;
        var77.setMeta((IPersistentMap)const__235);
        Var var78 = var77;
        var77.bindRoot((Object)new log$fressianed_dir());
        Var var79 = const__236;
        var79.setMeta((IPersistentMap)const__238);
        Var var80 = var79;
        var79.bindRoot((Object)new log$fressianed_leaf());
        Object object45 = ((IFn)new log$fn__16251()).invoke();
        Object object46 = ((IFn)new log$fn__16296()).invoke();
        Var var81 = const__239;
        var81.setMeta((IPersistentMap)const__241);
        Var var82 = var81;
        var81.bindRoot((Object)new log$create_log_impl());
        Var var83 = const__242;
        var83.setMeta((IPersistentMap)const__244);
        Var var84 = var83;
        var83.bindRoot((Object)new log$write_new_log());
        Var var85 = const__245;
        var85.setMeta((IPersistentMap)const__247);
        Var var86 = var85;
        var85.bindRoot((Object)new log$create_new_log());
        Var var87 = const__248;
        var87.setMeta((IPersistentMap)const__250);
        Var var88 = var87;
        var87.bindRoot((Object)new log$seek_tx());
        Var var89 = const__251;
        var89.setMeta((IPersistentMap)const__253);
        Var var90 = var89;
        var89.bindRoot((Object)new log$find_log());
        Var var91 = const__254;
        var91.setMeta((IPersistentMap)const__256);
        Var var92 = var91;
        var91.bindRoot((Object)new log$log_tree());
        Var var93 = const__257;
        var93.setMeta((IPersistentMap)const__259);
        Var var94 = var93;
        var93.bindRoot((Object)new log$catchup_tx());
        Var var95 = const__260;
        var95.setMeta((IPersistentMap)const__262);
        Var var96 = var95;
        var95.bindRoot((Object)new log$catchup());
        Var var97 = const__263;
        var97.setMeta((IPersistentMap)const__265);
        Var var98 = var97;
        var97.bindRoot((Object)new log$ensure_index_and_log());
        Var var99 = const__266;
        var99.setMeta((IPersistentMap)const__268);
        Var var100 = var99;
        var99.bindRoot((Object)new log$excise_ts());
        Var var101 = const__269;
        var101.setMeta((IPersistentMap)const__271);
        Var var102 = var101;
        var101.bindRoot((Object)new log$excise_dir_map());
        Var var103 = const__272;
        var103.setMeta((IPersistentMap)const__274);
        Var var104 = var103;
        var103.bindRoot((Object)new log$write_excised_log());
        Var var105 = const__275;
        var105.setMeta((IPersistentMap)const__277);
        Var var106 = var105;
        var105.bindRoot((Object)new log$excise());
        Var var107 = const__278;
        var107.setMeta((IPersistentMap)const__280);
        Var var108 = var107;
        var107.bindRoot((Object)new log$excise_root());
        Object object47 = ((IFn)new log$fn__16456()).invoke();
        Object object48 = ((IFn)const__132.getRawRoot()).invoke(const__281, const__28.getRawRoot(), (Object)RT.mapUniqueKeys((Object[])new Object[]{const__42, new log$fn__16476()}));
        Var var109 = const__282;
        var109.setMeta((IPersistentMap)const__284);
        Var var110 = var109;
        var109.bindRoot((Object)new log$tx_range());
        Object object49 = ((IFn)new log$fn__16485()).invoke();
        Var var111 = const__285;
        var111.setMeta((IPersistentMap)const__287);
        Var var112 = var111;
        var111.bindRoot((Object)new log$segmented_basis_t());
        Var var113 = const__288;
        var113.setMeta((IPersistentMap)const__290);
        Var var114 = var113;
        var113.bindRoot((Object)new log$create_log_val());
        Var var115 = const__291;
        var115.setMeta((IPersistentMap)const__293);
        Var var116 = var115;
        var115.bindRoot((Object)new log$max_t());
        Var var117 = const__294;
        var117.setMeta((IPersistentMap)const__296);
        Var var118 = var117;
        var117.bindRoot((Object)new log$max_eidx());
        Var var119 = const__297;
        var119.setMeta((IPersistentMap)const__299);
        Var var120 = var119;
        var119.bindRoot((Object)new log$last_tree_tx());
        Var var121 = const__300;
        var121.setMeta((IPersistentMap)const__302);
        Var var122 = var121;
        var121.bindRoot((Object)new log$root_id());
        Var var123 = const__303;
        var123.setMeta((IPersistentMap)const__305);
        Var var124 = var123;
        var123.bindRoot((Object)new log$partition_by_weight());
        Var var125 = const__306;
        var125.setMeta((IPersistentMap)const__308);
        Var var126 = var125;
        var125.bindRoot((Object)new log$combine_last_if());
        Var var127 = const__309;
        var127.setMeta((IPersistentMap)const__311);
        Var var128 = var127;
        var127.bindRoot((Object)new log$create_leaves_STAR_());
        Var var129 = const__312;
        var129.setMeta((IPersistentMap)const__314);
        Var var130 = var129;
        var129.bindRoot((Object)new log$create_leaves());
        Var var131 = const__315;
        var131.setMeta((IPersistentMap)const__317);
        Var var132 = var131;
        var131.bindRoot((Object)new log$extend_tree());
        Var var133 = const__318;
        var133.setMeta((IPersistentMap)const__320);
        Var var134 = var133;
        var133.bindRoot((Object)new log$segment());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)((IObj)Symbol.intern(null, (String)"datomic.log")).withMeta(RT.map((Object[])new Object[0]));
        const__2 = RT.keyword(null, (String)"doc");
        const__3 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"doc"), "Database log.\n\nLog comprises a tree, plus a tail pod that does three jobs:\n\n- points to the log tree, via the :d/r key in pod-meta\n- holds the tail of data not in the tree yet, in the pod \"value\"\n- coordinates who is allowed to write transactions\n\nThat sounds complected, and it is. The pod code is subtle and does not\nrepresent our ideas on best practice. It works the way it does for\ncompatibility with existing databases.\n\nAll pod writes increment the revision, which is a CAS guard that\nensures serialization of all activity on the pod. There are several\nkinds of calls to cluster/update-pod:\n\n- Claim the pod by passing a nil buf and the etag from the previous\n  value. This leaves the pod value and metadata unchanged, while\n  causing other writers to encounter a conflict on their next write.\n\n- Append transaction data by passing the previous etag and a buf which\n  gets appended to the buf already in the pod.\n\n- Adopt a new root by setting :d/r in the pod metadata, passing a\n  buf with whatever data is not yet in the root, and setting the\n  etag to nil to reset the pod value to the buf passed in.\n\n- Create a new database log by setting etag to nil, :d/r to point to a\n  new, empty tree, and setting the pod value to an empty list of\n  transactions.\n\nTransactions in the tail pod or in a leaf segment each are their own\ncaching context, and therefore must be preceded by a Fressian\nRESET_CACHES code.\n\nAn empty list of transactions in the pod buffer is the only place\nwhere Datomic uses Fressian's BEGIN_OPEN_LIST bytecode."});
        const__4 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__5 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__6 = RT.var((String)"datomic.log", (String)"btree-search");
        const__9 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__10 = RT.var((String)"clojure.core", (String)"deref");
        const__11 = RT.var((String)"datomic.index", (String)"btree-search");
        const__12 = RT.var((String)"datomic.log", (String)"binary-search");
        const__13 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__14 = RT.var((String)"datomic.index", (String)"binary-search");
        const__15 = RT.var((String)"datomic.log", (String)"segment-threshold");
        const__16 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__17 = 54000L;
        const__18 = RT.var((String)"datomic.log", (String)"dir-threshold");
        const__19 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__20 = 1000L;
        const__21 = RT.var((String)"datomic.log", (String)"last-by-nth");
        const__25 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"coll")))), RT.keyword(null, (String)"column"), 1});
        const__26 = RT.classForName((String)"datomic.log.LogSeek");
        const__27 = RT.var((String)"clojure.core", (String)"alter-meta!");
        const__28 = RT.var((String)"datomic.log", (String)"LogSeek");
        const__29 = RT.var((String)"clojure.core", (String)"assoc");
        const__30 = RT.var((String)"clojure.core", (String)"assert-same-protocol");
        const__31 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"seek-tx-impl")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))})), ((IObj)Symbol.intern(null, (String)"seek-seg-path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))}))));
        const__32 = RT.var((String)"clojure.core", (String)"alter-var-root");
        const__33 = RT.var((String)"clojure.core", (String)"merge");
        const__37 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.LogSeek"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.LogSeek")});
        const__38 = RT.keyword(null, (String)"sigs");
        const__39 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seek-tx-impl"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-tx-impl")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns iterator over log transactions at t"}), RT.keyword(null, (String)"seek-seg-path"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-seg-path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns the [dirid segid] that contains/would contain t."})});
        const__40 = RT.keyword(null, (String)"var");
        const__41 = RT.keyword(null, (String)"method-map");
        const__42 = RT.keyword(null, (String)"seek-tx-impl");
        const__44 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"seek-tx-impl"), RT.keyword(null, (String)"seek-tx-impl"), RT.keyword(null, (String)"seek-seg-path"), RT.keyword(null, (String)"seek-seg-path")});
        const__45 = RT.keyword(null, (String)"method-builders");
        const__46 = RT.var((String)"clojure.core", (String)"intern");
        const__47 = RT.var((String)"clojure.core", (String)"*ns*");
        const__48 = RT.var((String)"clojure.core", (String)"with-meta");
        const__49 = (AFn)((IObj)Symbol.intern(null, (String)"seek-tx-impl")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__50 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-tx-impl")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns iterator over log transactions at t"});
        const__51 = RT.keyword(null, (String)"protocol");
        const__52 = (AFn)((IObj)Symbol.intern(null, (String)"seek-seg-path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__53 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"seek-seg-path")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Returns the [dirid segid] that contains/would contain t."});
        const__54 = RT.var((String)"clojure.core", (String)"-reset-methods");
        const__55 = (AFn)Symbol.intern(null, (String)"LogSeek");
        const__56 = RT.var((String)"datomic.log", (String)"seek-seg-id");
        const__58 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__59 = RT.classForName((String)"datomic.log.Log");
        const__60 = RT.var((String)"datomic.log", (String)"Log");
        const__61 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"claim")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"))))})), ((IObj)Symbol.intern(null, (String)"get-root-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), ((IObj)Symbol.intern(null, (String)"get-root-id")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), ((IObj)Symbol.intern(null, (String)"adopt-root")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t"))))})), ((IObj)Symbol.intern(null, (String)"append")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs"))))})), ((IObj)Symbol.intern(null, (String)"val-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))}))));
        const__63 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.Log"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.Log")});
        const__64 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"claim"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"claim")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"doc"), "Touch the tail pod and root rev. Returns updated log or nil"}), RT.keyword(null, (String)"get-root-val"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-root-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns the root"}), RT.keyword(null, (String)"get-root-id"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-root-id")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns the root id"}), RT.keyword(null, (String)"adopt-root"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"adopt-root")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Adopt a new root. Updates pod. If t is not nil,\ntruncates tail to txes since t. Returns the updated log."}), RT.keyword(null, (String)"append"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"append")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs")))), RT.keyword(null, (String)"doc"), "Appends tx msgs, segments if necessary, updates pod, returns log"}), RT.keyword(null, (String)"val-keys"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"val-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns inorder traversal of keys (strings)"})});
        const__71 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"adopt-root"), RT.keyword(null, (String)"adopt-root"), RT.keyword(null, (String)"append"), RT.keyword(null, (String)"append"), RT.keyword(null, (String)"val-keys"), RT.keyword(null, (String)"val-keys"), RT.keyword(null, (String)"get-root-val"), RT.keyword(null, (String)"get-root-val"), RT.keyword(null, (String)"get-root-id"), RT.keyword(null, (String)"get-root-id"), RT.keyword(null, (String)"claim"), RT.keyword(null, (String)"claim")});
        const__72 = (AFn)((IObj)Symbol.intern(null, (String)"append")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs"))))}));
        const__73 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"append")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"msgs")))), RT.keyword(null, (String)"doc"), "Appends tx msgs, segments if necessary, updates pod, returns log"});
        const__74 = (AFn)((IObj)Symbol.intern(null, (String)"get-root-id")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))}));
        const__75 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-root-id")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns the root id"});
        const__76 = (AFn)((IObj)Symbol.intern(null, (String)"val-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))}));
        const__77 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"val-keys")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns inorder traversal of keys (strings)"});
        const__78 = (AFn)((IObj)Symbol.intern(null, (String)"adopt-root")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t"))))}));
        const__79 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"adopt-root")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"doc"), "Adopt a new root. Updates pod. If t is not nil,\ntruncates tail to txes since t. Returns the updated log."});
        const__80 = (AFn)((IObj)Symbol.intern(null, (String)"get-root-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))}));
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"get-root-val")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log")))), RT.keyword(null, (String)"doc"), "Returns the root"});
        const__82 = (AFn)((IObj)Symbol.intern(null, (String)"claim")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"))))}));
        const__83 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"claim")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"doc"), "Touch the tail pod and root rev. Returns updated log or nil"});
        const__84 = (AFn)Symbol.intern(null, (String)"Log");
        const__85 = RT.classForName((String)"datomic.log.TailTxes");
        const__86 = RT.var((String)"datomic.log", (String)"TailTxes");
        const__87 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"tail-txes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
        const__89 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.TailTxes"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.TailTxes")});
        const__90 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tail-txes"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"tail-txes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns the tail txes"})});
        const__92 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"tail-txes"), RT.keyword(null, (String)"tail-txes")});
        const__93 = (AFn)((IObj)Symbol.intern(null, (String)"tail-txes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__94 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"tail-txes")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns the tail txes"});
        const__95 = (AFn)Symbol.intern(null, (String)"TailTxes");
        const__96 = RT.classForName((String)"datomic.log.LogKey");
        const__97 = RT.var((String)"datomic.log", (String)"LogKey");
        const__98 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"log-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
    }

    public static void __init1() {
        const__100 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.LogKey"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.LogKey")});
        const__101 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-key"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Key for navigating log structures on disk."})});
        const__102 = RT.keyword(null, (String)"log-key");
        const__103 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-key"), RT.keyword(null, (String)"log-key")});
        const__104 = (AFn)((IObj)Symbol.intern(null, (String)"log-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-key")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Key for navigating log structures on disk."});
        const__106 = (AFn)Symbol.intern(null, (String)"LogKey");
        const__107 = RT.classForName((String)"datomic.log.LogSegSeq");
        const__108 = RT.var((String)"datomic.log", (String)"LogSegSeq");
        const__109 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"log-seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.LogSegSeq"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.LogSegSeq")});
        const__112 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-seg-seq"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a seq of log segments starting at iter.\n                       Loads the segs as it goes."})});
        const__114 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-seg-seq"), RT.keyword(null, (String)"log-seg-seq")});
        const__115 = (AFn)((IObj)Symbol.intern(null, (String)"log-seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__116 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-seg-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a seq of log segments starting at iter.\n                       Loads the segs as it goes."});
        const__117 = (AFn)Symbol.intern(null, (String)"LogSegSeq");
        const__118 = RT.classForName((String)"datomic.log.LogDirSeq");
        const__119 = RT.var((String)"datomic.log", (String)"LogDirSeq");
        const__120 = (ISeq)PersistentList.create(Arrays.asList(((IObj)Symbol.intern(null, (String)"log-dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}))));
        const__122 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"on"), Symbol.intern(null, (String)"datomic.log.LogDirSeq"), RT.keyword(null, (String)"on-interface"), RT.classForName((String)"datomic.log.LogDirSeq")});
        const__123 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-dir-seq"), RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a seq of log dir segments starting at iter.\n                       Loads the segs as it goes."})});
        const__125 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"log-dir-seq"), RT.keyword(null, (String)"log-dir-seq")});
        const__126 = (AFn)((IObj)Symbol.intern(null, (String)"log-dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))}));
        const__127 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"name"), ((IObj)Symbol.intern(null, (String)"log-dir-seq")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_"))))})), RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"_")))), RT.keyword(null, (String)"doc"), "Returns a seq of log dir segments starting at iter.\n                       Loads the segs as it goes."});
        const__128 = (AFn)Symbol.intern(null, (String)"LogDirSeq");
        const__129 = RT.var((String)"datomic.log", (String)"fressianed-txes-length");
        const__131 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"fressianed-txes")))), RT.keyword(null, (String)"column"), 1});
        const__132 = RT.var((String)"clojure.core", (String)"extend");
        const__133 = RT.classForName((String)"java.util.Map");
        const__134 = RT.classForName((String)"java.lang.Long");
        const__135 = RT.var((String)"datomic.log", (String)"write-handlers");
        const__136 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__137 = RT.var((String)"datomic.transaction", (String)"write-handlers");
        const__138 = RT.classForName((String)"datomic.log.LogDir");
        const__142 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 143, RT.keyword(null, (String)"column"), 6});
        const__143 = RT.var((String)"datomic.log", (String)"read-handlers");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.transaction", (String)"read-handlers");
        const__148 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"line"), 154, RT.keyword(null, (String)"column"), 5});
        const__149 = RT.var((String)"datomic.log", (String)"fressianed-tx");
        const__151 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"tx")))), RT.keyword(null, (String)"column"), 1});
        const__152 = RT.var((String)"datomic.log", (String)"create-entry");
        const__154 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"t")), Tuple.create((Object)Symbol.intern(null, (String)"t"), (Object)Symbol.intern(null, (String)"uuid")))), RT.keyword(null, (String)"column"), 1});
        const__155 = RT.var((String)"datomic.log", (String)"tail-pod-key");
        const__157 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__158 = RT.var((String)"datomic.log", (String)"tail-descriptor?");
        const__160 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"desc")))), RT.keyword(null, (String)"column"), 1});
        const__161 = RT.var((String)"datomic.log", (String)"inc-rev");
        const__163 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"m")))), RT.keyword(null, (String)"column"), 1});
        const__164 = RT.var((String)"datomic.log", (String)"legacy-root-ref-key");
        const__166 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__167 = RT.var((String)"datomic.log", (String)"LOG_VERSION");
        const__169 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__170 = 3L;
        const__171 = RT.var((String)"datomic.log", (String)"normalize-desc");
        const__173 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"desc"), (Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__174 = RT.var((String)"datomic.log", (String)"read-tail-descriptor");
        const__176 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__177 = RT.var((String)"datomic.log", (String)"pod-update-succeeded?");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"response")))), RT.keyword(null, (String)"column"), 1});
        const__180 = RT.var((String)"datomic.log", (String)"write-tail-descriptor");
        const__182 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"desc"), (Object)Symbol.intern(null, (String)"buf")))), RT.keyword(null, (String)"column"), 1});
        const__183 = RT.var((String)"datomic.log", (String)"claim-log");
        const__185 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"desc")))), RT.keyword(null, (String)"column"), 1});
        const__186 = RT.var((String)"datomic.log", (String)"convert-log-version");
        const__188 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"to-version")))), RT.keyword(null, (String)"column"), 1});
        const__189 = RT.var((String)"datomic.log", (String)"zip-and-create");
        const__191 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"uuid"), (Object)Symbol.intern(null, (String)"buf")))), RT.keyword(null, (String)"column"), 1});
        const__192 = RT.var((String)"datomic.log", (String)"write-excise-val");
        const__194 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"uuid"), (Object)Symbol.intern(null, (String)"fressianed-buf")))), RT.keyword(null, (String)"column"), 1});
        const__195 = RT.var((String)"datomic.log", (String)"BEGIN_OPEN_LIST");
        const__196 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__199 = RT.var((String)"datomic.log", (String)"BEGIN_CLOSED_LIST");
    }

    public static void __init2() {
        const__200 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__201 = RT.var((String)"datomic.log", (String)"END_COLLECTION");
        const__202 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__203 = RT.var((String)"datomic.log", (String)"create-tail");
        const__205 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__206 = RT.var((String)"datomic.log", (String)"empty-tail");
        const__207 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"declared"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__208 = RT.var((String)"datomic.log", (String)"tail-byte-count");
        const__210 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"bufs"))})))), RT.keyword(null, (String)"column"), 1});
        const__211 = RT.var((String)"datomic.log", (String)"tail-ts");
        const__213 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"txes"))})))), RT.keyword(null, (String)"column"), 1});
        const__214 = RT.var((String)"datomic.log", (String)"tail-empty?");
        const__216 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"txes"))})))), RT.keyword(null, (String)"column"), 1});
        const__217 = RT.var((String)"datomic.log", (String)"extend-tail");
        const__219 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"txes"), (Object)Symbol.intern(null, (String)"bufs"))}), (Object)Symbol.intern(null, (String)"new-txes"), (Object)Symbol.intern(null, (String)"new-bufs")))), RT.keyword(null, (String)"column"), 1});
        const__220 = RT.var((String)"datomic.log", (String)"since");
        const__222 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"txes"), (Object)Symbol.intern(null, (String)"bufs")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"tail")}), (Object)Symbol.intern(null, (String)"since-t")))), RT.keyword(null, (String)"column"), 1});
        const__223 = RT.var((String)"datomic.log", (String)"resets-caches?");
        const__225 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bbuf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__227 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"txes"), (Object)Symbol.intern(null, (String)"bufs")))), RT.keyword(null, (String)"column"), 1});
        const__229 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__230 = RT.var((String)"datomic.log", (String)"load-tail");
        const__232 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"bbuf")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"ByteBuffer")}))))), RT.keyword(null, (String)"column"), 1});
        const__233 = RT.var((String)"datomic.log", (String)"fressianed-dir");
        const__235 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"val")))), RT.keyword(null, (String)"column"), 1});
        const__236 = RT.var((String)"datomic.log", (String)"fressianed-leaf");
        const__238 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"val")))), RT.keyword(null, (String)"column"), 1});
        const__239 = RT.var((String)"datomic.log", (String)"create-log-impl");
        const__241 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"desc"), (Object)Symbol.intern(null, (String)"tail")))), RT.keyword(null, (String)"column"), 1});
        const__242 = RT.var((String)"datomic.log", (String)"write-new-log");
        const__244 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__245 = RT.var((String)"datomic.log", (String)"create-new-log");
        const__247 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup")))), RT.keyword(null, (String)"column"), 1});
        const__248 = RT.var((String)"datomic.log", (String)"seek-tx");
        const__250 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"provider"), (Object)Symbol.intern(null, (String)"t"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"datomic.iter.Iter")})))), RT.keyword(null, (String)"column"), 1});
        const__251 = RT.var((String)"datomic.log", (String)"find-log");
        const__253 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup")))), RT.keyword(null, (String)"column"), 1});
        const__254 = RT.var((String)"datomic.log", (String)"log-tree");
        const__256 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"root-id")))), RT.keyword(null, (String)"column"), 1});
        const__257 = RT.var((String)"datomic.log", (String)"catchup-tx");
        const__259 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDbImpl")})), (Object)Symbol.intern(null, (String)"size"))}), (Object)Symbol.intern(null, (String)"tx")))), RT.keyword(null, (String)"column"), 1});
        const__260 = RT.var((String)"datomic.log", (String)"catchup");
        const__262 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"log")), Tuple.create((Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Database")})), (Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"catchup-ft")))), RT.keyword(null, (String)"column"), 1});
        const__263 = RT.var((String)"datomic.log", (String)"ensure-index-and-log");
        const__265 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"db-id")))), RT.keyword(null, (String)"column"), 1});
        const__266 = RT.var((String)"datomic.log", (String)"excise-ts");
        const__268 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"xpreds")))), RT.keyword(null, (String)"column"), 1});
        const__269 = RT.var((String)"datomic.log", (String)"excise-dir-map");
        const__271 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"ts")))), RT.keyword(null, (String)"column"), 1});
        const__272 = RT.var((String)"datomic.log", (String)"write-excised-log");
        const__274 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"xpreds"), (Object)Symbol.intern(null, (String)"ts"), (Object)Symbol.intern(null, (String)"dir-map")))), RT.keyword(null, (String)"column"), 1});
        const__275 = RT.var((String)"datomic.log", (String)"excise");
        const__277 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"xpreds")))), RT.keyword(null, (String)"column"), 1});
        const__278 = RT.var((String)"datomic.log", (String)"excise-root");
        const__280 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"lookup"), (Object)Symbol.intern(null, (String)"current-root-id"), (Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"dir-map"), (Object)Symbol.intern(null, (String)"replacements"))})))), RT.keyword(null, (String)"column"), 1});
        const__281 = RT.classForName((String)"datomic.db.MemLog");
        const__282 = RT.var((String)"datomic.log", (String)"tx-range");
        const__284 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)((IObj)Symbol.intern(null, (String)"db")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"IDb")})), (Object)Symbol.intern(null, (String)"start"), (Object)Symbol.intern(null, (String)"end")))), RT.keyword(null, (String)"column"), 1});
        const__285 = RT.var((String)"datomic.log", (String)"segmented-basis-t");
        const__287 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log-value")))), RT.keyword(null, (String)"column"), 1});
        const__288 = RT.var((String)"datomic.log", (String)"create-log-val");
        const__290 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"db"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"db"))})))), RT.keyword(null, (String)"column"), 1});
        const__291 = RT.var((String)"datomic.log", (String)"max-t");
        const__293 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"datoms")))), RT.keyword(null, (String)"column"), 1});
        const__294 = RT.var((String)"datomic.log", (String)"max-eidx");
        const__296 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"datoms")))), RT.keyword(null, (String)"column"), 1});
        const__297 = RT.var((String)"datomic.log", (String)"last-tree-tx");
        const__299 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"olookup")), RT.keyword(null, (String)"as"), Symbol.intern(null, (String)"log")})), Tuple.create((Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"root-id")))), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init3() {
        const__300 = RT.var((String)"datomic.log", (String)"root-id");
        const__302 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs")))), RT.keyword(null, (String)"column"), 1});
        const__303 = RT.var((String)"datomic.log", (String)"partition-by-weight");
        const__305 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"weigh"), (Object)Symbol.intern(null, (String)"target")))), RT.keyword(null, (String)"column"), 1});
        const__306 = RT.var((String)"datomic.log", (String)"combine-last-if");
        const__308 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"combine")))), RT.keyword(null, (String)"column"), 1});
        const__309 = RT.var((String)"datomic.log", (String)"create-leaves*");
        const__311 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"target-size"), (Object)Symbol.intern(null, (String)"ftxes")))), RT.keyword(null, (String)"column"), 1});
        const__312 = RT.var((String)"datomic.log", (String)"create-leaves");
        const__314 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"target-size"), (Object)Symbol.intern(null, (String)"tail")))), RT.keyword(null, (String)"column"), 1});
        const__315 = RT.var((String)"datomic.log", (String)"extend-tree");
        const__317 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cs"), (Object)Symbol.intern(null, (String)"olookup"), (Object)Symbol.intern(null, (String)"root-id"), (Object)Symbol.intern(null, (String)"target-dir-count"), (Object)Symbol.intern(null, (String)"leaf-segs")))), RT.keyword(null, (String)"column"), 1});
        const__318 = RT.var((String)"datomic.log", (String)"segment");
        const__320 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup")))), RT.keyword(null, (String)"column"), 1});
    }

    static {
        log__init.__init0();
        log__init.__init1();
        log__init.__init2();
        log__init.__init3();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.log__init").getClassLoader());
        try {
            log__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

