/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  clojure.lang.AFn
 *  clojure.lang.Compiler
 *  clojure.lang.IFn
 *  clojure.lang.IObj
 *  clojure.lang.IPersistentMap
 *  clojure.lang.LockingTransaction
 *  clojure.lang.PersistentList
 *  clojure.lang.RT
 *  clojure.lang.Symbol
 *  clojure.lang.Tuple
 *  clojure.lang.Var
 */
package datomic;

import clojure.lang.AFn;
import clojure.lang.Compiler;
import clojure.lang.IFn;
import clojure.lang.IObj;
import clojure.lang.IPersistentMap;
import clojure.lang.LockingTransaction;
import clojure.lang.PersistentList;
import clojure.lang.RT;
import clojure.lang.Symbol;
import clojure.lang.Tuple;
import clojure.lang.Var;
import datomic.tools$avof_map;
import datomic.tools$card_ones;
import datomic.tools$catalog;
import datomic.tools$cause_chain;
import datomic.tools$class_sym;
import datomic.tools$count_log_segs;
import datomic.tools$cr_QMARK_;
import datomic.tools$datom_read_handler;
import datomic.tools$db_diagnostics;
import datomic.tools$diagnostics;
import datomic.tools$ever_nohistory_attrs;
import datomic.tools$flush_progress;
import datomic.tools$fn__21723;
import datomic.tools$fn__21739;
import datomic.tools$fulltexts;
import datomic.tools$get_index;
import datomic.tools$get_index_ref;
import datomic.tools$get_val;
import datomic.tools$identities_in_ts;
import datomic.tools$index_has_t_QMARK_;
import datomic.tools$loading__6434__auto____21721;
import datomic.tools$log_entry__GT_next_t;
import datomic.tools$log_size;
import datomic.tools$log_size_STAR_;
import datomic.tools$nohistory_checker;
import datomic.tools$pace_fn;
import datomic.tools$pace_msec_per_seg;
import datomic.tools$peer_diagnostics;
import datomic.tools$pretty_datom;
import datomic.tools$println_err;
import datomic.tools$prn_err;
import datomic.tools$read_capacity_units;
import datomic.tools$rehome;
import datomic.tools$replace_index;
import datomic.tools$reset_index_ref;
import datomic.tools$retarget;
import datomic.tools$retract;
import datomic.tools$retract_entity;
import datomic.tools$segment_log;
import datomic.tools$serialized;
import datomic.tools$set_index_basis;
import datomic.tools$storage_diagnostics;
import datomic.tools$system_cluster;
import datomic.tools$tools_fault;
import datomic.tools$touch_heartbeat;
import datomic.tools$touch_index_ref;
import datomic.tools$tx_range_from_log;
import datomic.tools$unique_identities;
import datomic.tools$unique_values;
import datomic.tools$uniques_in_ts;
import datomic.tools$unsorted_seq;
import datomic.tools$values_in_ts;
import java.util.Arrays;
import java.util.concurrent.Callable;

public class tools__init {
    public static final Var const__0;
    public static final AFn const__1;
    public static final AFn const__2;
    public static final Var const__3;
    public static final Var const__4;
    public static final AFn const__5;
    public static final Var const__6;
    public static final AFn const__10;
    public static final Object const__11;
    public static final Var const__12;
    public static final AFn const__15;
    public static final Var const__16;
    public static final AFn const__17;
    public static final Var const__18;
    public static final Var const__19;
    public static final AFn const__21;
    public static final Var const__22;
    public static final AFn const__24;
    public static final Var const__25;
    public static final AFn const__27;
    public static final Var const__28;
    public static final AFn const__29;
    public static final Var const__30;
    public static final AFn const__32;
    public static final Var const__33;
    public static final AFn const__34;
    public static final Var const__35;
    public static final Var const__36;
    public static final AFn const__37;
    public static final Var const__38;
    public static final Var const__39;
    public static final AFn const__40;
    public static final Var const__41;
    public static final Var const__42;
    public static final AFn const__43;
    public static final Var const__44;
    public static final Var const__45;
    public static final AFn const__47;
    public static final Var const__48;
    public static final AFn const__50;
    public static final Var const__51;
    public static final AFn const__53;
    public static final Var const__54;
    public static final AFn const__56;
    public static final Var const__57;
    public static final AFn const__59;
    public static final Var const__60;
    public static final AFn const__63;
    public static final Var const__64;
    public static final AFn const__66;
    public static final Var const__67;
    public static final AFn const__69;
    public static final Var const__70;
    public static final AFn const__72;
    public static final Var const__73;
    public static final AFn const__75;
    public static final Var const__76;
    public static final AFn const__78;
    public static final Var const__79;
    public static final AFn const__81;
    public static final Var const__82;
    public static final AFn const__84;
    public static final Var const__85;
    public static final AFn const__87;
    public static final Var const__88;
    public static final AFn const__90;
    public static final Var const__91;
    public static final AFn const__93;
    public static final Var const__94;
    public static final AFn const__96;
    public static final Var const__97;
    public static final AFn const__99;
    public static final Var const__100;
    public static final AFn const__102;
    public static final Var const__103;
    public static final AFn const__105;
    public static final Var const__106;
    public static final AFn const__108;
    public static final Var const__109;
    public static final AFn const__111;
    public static final Var const__112;
    public static final AFn const__114;
    public static final Var const__115;
    public static final AFn const__117;
    public static final Var const__118;
    public static final AFn const__120;
    public static final Var const__121;
    public static final AFn const__123;
    public static final Var const__124;
    public static final AFn const__126;
    public static final Var const__127;
    public static final AFn const__129;
    public static final Var const__130;
    public static final AFn const__132;
    public static final Var const__133;
    public static final AFn const__135;
    public static final Var const__136;
    public static final AFn const__138;
    public static final Var const__139;
    public static final AFn const__141;
    public static final Var const__142;
    public static final AFn const__144;
    public static final Var const__145;
    public static final AFn const__147;
    public static final Var const__148;
    public static final AFn const__150;
    public static final Var const__151;
    public static final AFn const__153;
    public static final Var const__154;
    public static final AFn const__156;
    public static final Var const__157;
    public static final AFn const__159;
    public static final Var const__160;
    public static final AFn const__162;
    public static final Var const__163;
    public static final AFn const__165;
    public static final Var const__166;
    public static final AFn const__168;
    public static final Var const__169;
    public static final AFn const__171;
    public static final Var const__172;
    public static final AFn const__174;
    public static final Var const__175;
    public static final AFn const__177;
    public static final Var const__178;
    public static final AFn const__179;
    public static final Var const__180;
    public static final Var const__181;
    public static final AFn const__182;
    public static final Var const__183;

    public static void load() {
        Object v2;
        Object object = ((IFn)const__0.getRawRoot()).invoke((Object)const__1);
        Object object2 = ((IFn)new tools$loading__6434__auto____21721()).invoke();
        if (((Symbol)const__1).equals((Object)const__2)) {
            v2 = null;
        } else {
            LockingTransaction.runInTransaction((Callable)((Callable)((Object)new tools$fn__21723())));
            v2 = null;
        }
        Object object3 = const__3.set((Object)Boolean.TRUE);
        Object object4 = ((IFn)const__4.getRawRoot()).invoke((Object)const__5);
        Var var = const__6;
        var.setMeta((IPersistentMap)const__10);
        Var var2 = var;
        var.bindRoot(const__11);
        Var var3 = const__12;
        var3.setMeta((IPersistentMap)const__15);
        Var var4 = var3;
        var3.bindRoot((Object)new tools$datom_read_handler());
        Var var5 = const__16;
        var5.setMeta((IPersistentMap)const__17);
        Var var6 = var5;
        var5.bindRoot(((IFn)const__18.getRawRoot()).invoke(null));
        Var var7 = const__19;
        var7.setMeta((IPersistentMap)const__21);
        Var var8 = var7;
        var7.bindRoot((Object)new tools$serialized());
        Var var9 = const__22;
        var9.setMeta((IPersistentMap)const__24);
        Var var10 = var9;
        var9.bindRoot((Object)new tools$prn_err());
        Var var11 = const__25;
        var11.setMeta((IPersistentMap)const__27);
        Var var12 = var11;
        var11.bindRoot((Object)new tools$println_err());
        Var var13 = const__28;
        var13.setMeta((IPersistentMap)const__29);
        Var var14 = var13;
        var13.bindRoot(((IFn)const__19.getRawRoot()).invoke((Object)new tools$fn__21739()));
        Var var15 = const__30;
        var15.setMeta((IPersistentMap)const__32);
        Var var16 = var15;
        var15.bindRoot((Object)new tools$flush_progress());
        Var var17 = const__33;
        var17.setMeta((IPersistentMap)const__34);
        Var var18 = var17;
        var17.bindRoot(const__35.getRawRoot());
        Var var19 = const__36;
        var19.setMeta((IPersistentMap)const__37);
        Var var20 = var19;
        var19.bindRoot(const__38.getRawRoot());
        Var var21 = const__39;
        var21.setMeta((IPersistentMap)const__40);
        Var var22 = var21;
        var21.bindRoot(const__41.getRawRoot());
        Var var23 = const__42;
        var23.setMeta((IPersistentMap)const__43);
        Var var24 = var23;
        var23.bindRoot(const__44.getRawRoot());
        Var var25 = const__45;
        var25.setMeta((IPersistentMap)const__47);
        Var var26 = var25;
        var25.bindRoot((Object)new tools$log_entry__GT_next_t());
        Var var27 = const__48;
        var27.setMeta((IPersistentMap)const__50);
        Var var28 = var27;
        var27.bindRoot((Object)new tools$index_has_t_QMARK_());
        Var var29 = const__51;
        var29.setMeta((IPersistentMap)const__53);
        Var var30 = var29;
        var29.bindRoot((Object)new tools$set_index_basis());
        Var var31 = const__54;
        var31.setMeta((IPersistentMap)const__56);
        Var var32 = var31;
        var31.bindRoot((Object)new tools$get_val());
        Var var33 = const__57;
        var33.setMeta((IPersistentMap)const__59);
        Var var34 = var33;
        var33.bindRoot((Object)new tools$get_index_ref());
        Var var35 = const__60;
        var35.setMeta((IPersistentMap)const__63);
        Var var36 = var35;
        var35.bindRoot((Object)new tools$reset_index_ref());
        Var var37 = const__64;
        var37.setMeta((IPersistentMap)const__66);
        Var var38 = var37;
        var37.bindRoot((Object)new tools$replace_index());
        Var var39 = const__67;
        var39.setMeta((IPersistentMap)const__69);
        Var var40 = var39;
        var39.bindRoot((Object)new tools$touch_index_ref());
        Var var41 = const__70;
        var41.setMeta((IPersistentMap)const__72);
        Var var42 = var41;
        var41.bindRoot((Object)new tools$log_size_STAR_());
        Var var43 = const__73;
        var43.setMeta((IPersistentMap)const__75);
        Var var44 = var43;
        var43.bindRoot((Object)new tools$log_size());
        Var var45 = const__76;
        var45.setMeta((IPersistentMap)const__78);
        Var var46 = var45;
        var45.bindRoot((Object)new tools$get_index());
        Var var47 = const__79;
        var47.setMeta((IPersistentMap)const__81);
        Var var48 = var47;
        var47.bindRoot((Object)new tools$cr_QMARK_());
        Var var49 = const__82;
        var49.setMeta((IPersistentMap)const__84);
        Var var50 = var49;
        var49.bindRoot((Object)new tools$tx_range_from_log());
        Var var51 = const__85;
        var51.setMeta((IPersistentMap)const__87);
        Var var52 = var51;
        var51.bindRoot((Object)new tools$unique_identities());
        Var var53 = const__88;
        var53.setMeta((IPersistentMap)const__90);
        Var var54 = var53;
        var53.bindRoot((Object)new tools$read_capacity_units());
        Var var55 = const__91;
        var55.setMeta((IPersistentMap)const__93);
        Var var56 = var55;
        var55.bindRoot((Object)new tools$pace_msec_per_seg());
        Var var57 = const__94;
        var57.setMeta((IPersistentMap)const__96);
        Var var58 = var57;
        var57.bindRoot((Object)new tools$pace_fn());
        Var var59 = const__97;
        var59.setMeta((IPersistentMap)const__99);
        Var var60 = var59;
        var59.bindRoot((Object)new tools$peer_diagnostics());
        Var var61 = const__100;
        var61.setMeta((IPersistentMap)const__102);
        Var var62 = var61;
        var61.bindRoot((Object)new tools$count_log_segs());
        Var var63 = const__103;
        var63.setMeta((IPersistentMap)const__105);
        Var var64 = var63;
        var63.bindRoot((Object)new tools$storage_diagnostics());
        Var var65 = const__106;
        var65.setMeta((IPersistentMap)const__108);
        Var var66 = var65;
        var65.bindRoot((Object)new tools$db_diagnostics());
        Var var67 = const__109;
        var67.setMeta((IPersistentMap)const__111);
        Var var68 = var67;
        var67.bindRoot((Object)new tools$system_cluster());
        Var var69 = const__112;
        var69.setMeta((IPersistentMap)const__114);
        Var var70 = var69;
        var69.bindRoot((Object)new tools$cause_chain());
        Var var71 = const__115;
        var71.setMeta((IPersistentMap)const__117);
        Var var72 = var71;
        var71.bindRoot((Object)new tools$class_sym());
        Var var73 = const__118;
        var73.setMeta((IPersistentMap)const__120);
        Var var74 = var73;
        var73.bindRoot((Object)new tools$tools_fault());
        Var var75 = const__121;
        var75.setMeta((IPersistentMap)const__123);
        Var var76 = var75;
        var75.bindRoot((Object)new tools$catalog());
        Var var77 = const__124;
        var77.setMeta((IPersistentMap)const__126);
        Var var78 = var77;
        var77.bindRoot((Object)new tools$diagnostics());
        Var var79 = const__127;
        var79.setMeta((IPersistentMap)const__129);
        Var var80 = var79;
        var79.bindRoot((Object)new tools$unique_values());
        Var var81 = const__130;
        var81.setMeta((IPersistentMap)const__132);
        Var var82 = var81;
        var81.bindRoot((Object)new tools$card_ones());
        Var var83 = const__133;
        var83.setMeta((IPersistentMap)const__135);
        Var var84 = var83;
        var83.bindRoot((Object)new tools$fulltexts());
        Var var85 = const__136;
        var85.setMeta((IPersistentMap)const__138);
        Var var86 = var85;
        var85.bindRoot((Object)new tools$pretty_datom());
        Var var87 = const__139;
        var87.setMeta((IPersistentMap)const__141);
        Var var88 = var87;
        var87.bindRoot((Object)new tools$touch_heartbeat());
        Var var89 = const__142;
        var89.setMeta((IPersistentMap)const__144);
        Var var90 = var89;
        var89.bindRoot((Object)new tools$segment_log());
        Var var91 = const__145;
        var91.setMeta((IPersistentMap)const__147);
        Var var92 = var91;
        var91.bindRoot((Object)new tools$retract());
        Var var93 = const__148;
        var93.setMeta((IPersistentMap)const__150);
        Var var94 = var93;
        var93.bindRoot((Object)new tools$retract_entity());
        Var var95 = const__151;
        var95.setMeta((IPersistentMap)const__153);
        Var var96 = var95;
        var95.bindRoot((Object)new tools$rehome());
        Var var97 = const__154;
        var97.setMeta((IPersistentMap)const__156);
        Var var98 = var97;
        var97.bindRoot((Object)new tools$retarget());
        Var var99 = const__157;
        var99.setMeta((IPersistentMap)const__159);
        Var var100 = var99;
        var99.bindRoot((Object)new tools$avof_map());
        Var var101 = const__160;
        var101.setMeta((IPersistentMap)const__162);
        Var var102 = var101;
        var101.bindRoot((Object)new tools$uniques_in_ts());
        Var var103 = const__163;
        var103.setMeta((IPersistentMap)const__165);
        Var var104 = var103;
        var103.bindRoot((Object)new tools$identities_in_ts());
        Var var105 = const__166;
        var105.setMeta((IPersistentMap)const__168);
        Var var106 = var105;
        var105.bindRoot((Object)new tools$values_in_ts());
        Var var107 = const__169;
        var107.setMeta((IPersistentMap)const__171);
        Var var108 = var107;
        var107.bindRoot((Object)new tools$unsorted_seq());
        Var var109 = const__172;
        var109.setMeta((IPersistentMap)const__174);
        Var var110 = var109;
        var109.bindRoot((Object)new tools$ever_nohistory_attrs());
        Var var111 = const__175;
        var111.setMeta((IPersistentMap)const__177);
        Var var112 = var111;
        var111.bindRoot((Object)new tools$nohistory_checker());
        Var var113 = const__178;
        var113.setMeta((IPersistentMap)const__179);
        Var var114 = var113;
        var113.bindRoot(const__180.getRawRoot());
        Var var115 = const__181;
        var115.setMeta((IPersistentMap)const__182);
        Var var116 = var115;
        var115.bindRoot(const__183.getRawRoot());
    }

    public static void __init0() {
        const__0 = RT.var((String)"clojure.core", (String)"in-ns");
        const__1 = (AFn)Symbol.intern(null, (String)"datomic.tools");
        const__2 = (AFn)Symbol.intern(null, (String)"clojure.core");
        const__3 = RT.var((String)"clojure.core", (String)"*warn-on-reflection*");
        const__4 = RT.var((String)"datomic.require", (String)"maybe-require");
        const__5 = (AFn)Symbol.intern(null, (String)"datomic.ddb");
        const__6 = RT.var((String)"datomic.tools", (String)"TOOLS_VERSION");
        const__10 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"const"), Boolean.TRUE, RT.keyword(null, (String)"column"), 1});
        const__11 = 1L;
        const__12 = RT.var((String)"datomic.tools", (String)"datom-read-handler");
        const__15 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Tuple.create((Object)Symbol.intern(null, (String)"e"), (Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"v"), (Object)Symbol.intern(null, (String)"tx"), (Object)Symbol.intern(null, (String)"op"))))), RT.keyword(null, (String)"column"), 1});
        const__16 = RT.var((String)"datomic.tools", (String)"serializer");
        const__17 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__18 = RT.var((String)"clojure.core", (String)"agent");
        const__19 = RT.var((String)"datomic.tools", (String)"serialized");
        const__21 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"f")), Tuple.create((Object)Symbol.intern(null, (String)"f"), (Object)Symbol.intern(null, (String)"agt")))), RT.keyword(null, (String)"column"), 1});
        const__22 = RT.var((String)"datomic.tools", (String)"prn-err");
        const__24 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__25 = RT.var((String)"datomic.tools", (String)"println-err");
        const__27 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"x")))), RT.keyword(null, (String)"column"), 1});
        const__28 = RT.var((String)"datomic.tools", (String)"progress");
        const__29 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__30 = RT.var((String)"datomic.tools", (String)"flush-progress");
        const__32 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
        const__33 = RT.var((String)"datomic.tools", (String)"connection-resources");
        const__34 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__35 = RT.var((String)"datomic.db-io", (String)"storage-resources");
        const__36 = RT.var((String)"datomic.tools", (String)"index-db");
        const__37 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__38 = RT.var((String)"datomic.db-io", (String)"index-db");
        const__39 = RT.var((String)"datomic.tools", (String)"log");
        const__40 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__41 = RT.var((String)"datomic.db-io", (String)"log");
        const__42 = RT.var((String)"datomic.tools", (String)"db-resources");
        const__43 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__44 = RT.var((String)"datomic.db-io", (String)"db-resources");
        const__45 = RT.var((String)"datomic.tools", (String)"log-entry->next-t");
        const__47 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log-entry")))), RT.keyword(null, (String)"column"), 1});
        const__48 = RT.var((String)"datomic.tools", (String)"index-has-t?");
        const__50 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__51 = RT.var((String)"datomic.tools", (String)"set-index-basis");
        const__53 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"basisT")))), RT.keyword(null, (String)"column"), 1});
        const__54 = RT.var((String)"datomic.tools", (String)"get-val");
        const__56 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn"), (Object)Symbol.intern(null, (String)"k")))), RT.keyword(null, (String)"column"), 1});
        const__57 = RT.var((String)"datomic.tools", (String)"get-index-ref");
        const__59 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster")))), RT.keyword(null, (String)"column"), 1});
        const__60 = RT.var((String)"datomic.tools", (String)"reset-index-ref");
        const__63 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"root-id")))), RT.keyword(null, (String)"column"), 1});
        const__64 = RT.var((String)"datomic.tools", (String)"replace-index");
        const__66 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"index-id"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"string?"), Symbol.intern(null, (String)"index-id")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 10})))})))), RT.keyword(null, (String)"column"), 1});
        const__67 = RT.var((String)"datomic.tools", (String)"touch-index-ref");
        const__69 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"cluster")))), RT.keyword(null, (String)"column"), 1});
        const__70 = RT.var((String)"datomic.tools", (String)"log-size*");
        const__72 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"conn"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__73 = RT.var((String)"datomic.tools", (String)"log-size");
        const__75 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri"), (Object)Symbol.intern(null, (String)"t")))), RT.keyword(null, (String)"column"), 1});
        const__76 = RT.var((String)"datomic.tools", (String)"get-index");
        const__78 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"))})))), RT.keyword(null, (String)"column"), 1});
        const__79 = RT.var((String)"datomic.tools", (String)"cr?");
        const__81 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"o")))), RT.keyword(null, (String)"column"), 1});
        const__82 = RT.var((String)"datomic.tools", (String)"tx-range-from-log");
        const__84 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(((IObj)Tuple.create((Object)Symbol.intern(null, (String)"cr"), (Object)Symbol.intern(null, (String)"start"), (Object)Symbol.intern(null, (String)"end"))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"pre"), Tuple.create((Object)((IObj)PersistentList.create(Arrays.asList(Symbol.intern(null, (String)"cr?"), Symbol.intern(null, (String)"cr")))).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 10})))})))), RT.keyword(null, (String)"column"), 1});
        const__85 = RT.var((String)"datomic.tools", (String)"unique-identities");
        const__87 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__88 = RT.var((String)"datomic.tools", (String)"read-capacity-units");
        const__90 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__91 = RT.var((String)"datomic.tools", (String)"pace-msec-per-seg");
        const__93 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"provisioned-kbs")))), RT.keyword(null, (String)"column"), 1});
        const__94 = RT.var((String)"datomic.tools", (String)"pace-fn");
        const__96 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"pace-msec")))), RT.keyword(null, (String)"column"), 1});
        const__97 = RT.var((String)"datomic.tools", (String)"peer-diagnostics");
        const__99 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create())), RT.keyword(null, (String)"column"), 1});
    }

    public static void __init1() {
        const__100 = RT.var((String)"datomic.tools", (String)"count-log-segs");
        const__102 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"cluster"), (Object)Symbol.intern(null, (String)"olookup"))})))), RT.keyword(null, (String)"column"), 1});
        const__103 = RT.var((String)"datomic.tools", (String)"storage-diagnostics");
        const__105 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__106 = RT.var((String)"datomic.tools", (String)"db-diagnostics");
        const__108 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__109 = RT.var((String)"datomic.tools", (String)"system-cluster");
        const__111 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__112 = RT.var((String)"datomic.tools", (String)"cause-chain");
        const__114 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Throwable")}))))), RT.keyword(null, (String)"column"), 1});
        const__115 = RT.var((String)"datomic.tools", (String)"class-sym");
        const__117 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"obj")))), RT.keyword(null, (String)"column"), 1});
        const__118 = RT.var((String)"datomic.tools", (String)"tools-fault");
        const__120 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)((IObj)Symbol.intern(null, (String)"t")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Throwable")}))))), RT.keyword(null, (String)"column"), 1});
        const__121 = RT.var((String)"datomic.tools", (String)"catalog");
        const__123 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__124 = RT.var((String)"datomic.tools", (String)"diagnostics");
        const__126 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__127 = RT.var((String)"datomic.tools", (String)"unique-values");
        const__129 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__130 = RT.var((String)"datomic.tools", (String)"card-ones");
        const__132 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__133 = RT.var((String)"datomic.tools", (String)"fulltexts");
        const__135 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__136 = RT.var((String)"datomic.tools", (String)"pretty-datom");
        const__138 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)((IObj)Symbol.intern(null, (String)"datom")).withMeta(RT.map((Object[])new Object[]{RT.keyword(null, (String)"tag"), Symbol.intern(null, (String)"Datom")}))))), RT.keyword(null, (String)"column"), 1});
        const__139 = RT.var((String)"datomic.tools", (String)"touch-heartbeat");
        const__141 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__142 = RT.var((String)"datomic.tools", (String)"segment-log");
        const__144 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"uri")))), RT.keyword(null, (String)"column"), 1});
        const__145 = RT.var((String)"datomic.tools", (String)"retract");
        const__147 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"d")))), RT.keyword(null, (String)"column"), 1});
        const__148 = RT.var((String)"datomic.tools", (String)"retract-entity");
        const__150 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"d")))), RT.keyword(null, (String)"column"), 1});
        const__151 = RT.var((String)"datomic.tools", (String)"rehome");
        const__153 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"e"), (Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"v"))}), (Object)Symbol.intern(null, (String)"to")))), RT.keyword(null, (String)"column"), 1});
        const__154 = RT.var((String)"datomic.tools", (String)"retarget");
        const__156 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)RT.map((Object[])new Object[]{RT.keyword(null, (String)"keys"), Tuple.create((Object)Symbol.intern(null, (String)"e"), (Object)Symbol.intern(null, (String)"a"), (Object)Symbol.intern(null, (String)"v"))}), (Object)Symbol.intern(null, (String)"to")))), RT.keyword(null, (String)"column"), 1});
        const__157 = RT.var((String)"datomic.tools", (String)"avof-map");
        const__159 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"datoms")))), RT.keyword(null, (String)"column"), 1});
        const__160 = RT.var((String)"datomic.tools", (String)"uniques-in-ts");
        const__162 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"private"), Boolean.TRUE, RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"ts"), (Object)Symbol.intern(null, (String)"ids")))), RT.keyword(null, (String)"column"), 1});
        const__163 = RT.var((String)"datomic.tools", (String)"identities-in-ts");
        const__165 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"ts")))), RT.keyword(null, (String)"column"), 1});
        const__166 = RT.var((String)"datomic.tools", (String)"values-in-ts");
        const__168 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db"), (Object)Symbol.intern(null, (String)"log"), (Object)Symbol.intern(null, (String)"ts")))), RT.keyword(null, (String)"column"), 1});
        const__169 = RT.var((String)"datomic.tools", (String)"unsorted-seq");
        const__171 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"pred"), (Object)Symbol.intern(null, (String)"s")))), RT.keyword(null, (String)"column"), 1});
        const__172 = RT.var((String)"datomic.tools", (String)"ever-nohistory-attrs");
        const__174 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__175 = RT.var((String)"datomic.tools", (String)"nohistory-checker");
        const__177 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"arglists"), PersistentList.create(Arrays.asList(Tuple.create((Object)Symbol.intern(null, (String)"db")))), RT.keyword(null, (String)"column"), 1});
        const__178 = RT.var((String)"datomic.tools", (String)"uuid->val-key");
        const__179 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__180 = RT.var((String)"datomic.cluster", (String)"uuid->val-key");
        const__181 = RT.var((String)"datomic.tools", (String)"val-key->uuid");
        const__182 = (AFn)RT.map((Object[])new Object[]{RT.keyword(null, (String)"column"), 1});
        const__183 = RT.var((String)"datomic.cluster", (String)"val-key->uuid");
    }

    static {
        tools__init.__init0();
        tools__init.__init1();
        Compiler.pushNSandLoader((ClassLoader)RT.classForName((String)"datomic.tools__init").getClassLoader());
        try {
            tools__init.load();
        }
        catch (Throwable throwable) {
            Var.popThreadBindings();
            throw throwable;
        }
        Var.popThreadBindings();
    }
}

